### ISSUE TITLE
Waypoints Requests

### ISSUE THREAD

**Issue by jeefo** [yapb/yapb#139]
Waypoints requests should only placed  in this issue.

If you're requesting waypoints file, please provide working link for map.

**Comment by stambeto2006** [comment]
Can you make waypoints for these maps?

1. zm_battle_ground2   -----> https://www.17buddies.rocks/17b2/View/Map/19187/zm_battle_ground2.html
2. zm_crossfire10   -----> https://www.17buddies.rocks/17b2/View/Map/54144/zm_crossfire10.html
3. zm_dust_jasionka   -----> https://www.17buddies.rocks/17b2/View/Map/55464/zm_dust_jasionka.html
4. zm_dust2_final   -----> https://www.17buddies.rocks/17b2/View/Map/24967/zm_dust2_final.html
5. zm_firezone   -----> https://www.17buddies.rocks/17b2/View/Map/70325/zm_firezone.html
6. zm_heal_dust2   -----> https://www.17buddies.rocks/17b2/View/Map/24527/zm_heal_dust2.html
7. zm_hell_house_v4   -----> https://www.17buddies.rocks/17b2/View/Map/28219/zm_hell_house_v4.html
8. zm_infantry   -----> https://www.17buddies.rocks/17b2/View/Map/19773/zm_infantry.html
9. zm_laf   -----> https://www.17buddies.rocks/17b2/View/Map/75393/zm_laf.html
10. zm_lan_house   -----> https://www.17buddies.rocks/17b2/View/Map/93844/zm_lan_house.html
11. zm_militia   -----> https://www.17buddies.rocks/17b2/View/Map/54147/zm_militia.html
12. zm_mystic   -----> https://www.17buddies.rocks/17b2/View/Map/28227/zm_mystic.html
13. zm_neris2   -----> https://www.17buddies.rocks/17b2/View/Map/108802/zm_neris2.html
14. zm_toxic_house_vk   -----> https://www.17buddies.rocks/17b2/View/Map/40414/zm_toxic_house_vk.html

**Comment by Overitab** [comment]
hi, I'll do it when I have time

**Comment by ForeskinJohn** [comment]
If someone needs some waypoints done, I can get on it as well.

**Comment by jeefo** [comment]
New waypoint for map: [de_test](https://yapb.ru/graph/de_test.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you @test for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [de_dust2.graph](https://yapb.ru/graph/de_dust2.graph.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you  for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [de_dust2.graph](https://yapb.ru/graph/de_dust2.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you  for sharing!

**Comment by Overitab** [comment]
[zm_firezone.zip](https://github.com/jeefo/yapb/files/4943903/zm_firezone.zip)

**Comment by jeefo** [comment]
New waypoint for map: [zm_firezone.graph](https://yapb.ru/graph/zm_firezone.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you Overitab for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [zm_battle_ground2.graph](https://yapb.ru/graph/zm_battle_ground2.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you Overitab for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [zm_crossfire10.graph](https://yapb.ru/graph/zm_crossfire10.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you Overitab for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [de_dust2.graph](https://yapb.ru/graph/de_dust2.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you пердак for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [zm_dust_jasionka.graph](https://yapb.ru/graph/zm_dust_jasionka.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you Overitab for sharing!

**Comment by ForeskinJohn** [comment]
Im going to put some work into the graph for de_prodigy and cs_office, prodigy especially needs fixing

**Comment by jeefo** [comment]
New waypoint for map: [zm_dust2_final.graph](https://yapb.ru/graph/zm_dust2_final.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you Overitab for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [zm_heal_dust2.graph](https://yapb.ru/graph/zm_heal_dust2.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you Overitab for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [zm_hell_house_v4.graph](https://yapb.ru/graph/zm_hell_house_v4.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you Overitab for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [zm_infantry.graph](https://yapb.ru/graph/zm_infantry.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you Overitab for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [zm_laf.graph](https://yapb.ru/graph/zm_laf.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you Overitab for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [zm_lan_house.graph](https://yapb.ru/graph/zm_lan_house.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you Overitab for sharing!

**Comment by Overitab** [comment]
on lan_house I didn't find a way to get on the roof, any secret teleport or no way?

**Comment by jeefo** [comment]
New waypoint for map: [zm_militia.graph](https://yapb.ru/graph/zm_militia.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you Overitab for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [zm_mystic.graph](https://yapb.ru/graph/zm_mystic.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you Overitab for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [zm_neris2.graph](https://yapb.ru/graph/zm_neris2.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you Overitab for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [zm_toxic_house_vk.graph](https://yapb.ru/graph/zm_toxic_house_vk.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you Overitab for sharing!

**Comment by kYov0** [comment]
T bots only goes to site 2 and sometimes they just stand there with c4 holding in their hands instead of planting it.(de_tuscan)
T bots always goes to mid at the beginning of a round and there is no more routes for them.(de_mirage)
Steam latest cs without amxx or metamod.

**Comment by jeefo** [comment]
New waypoint for map: [de_mirage.graph](https://yapb.ru/graph/de_mirage.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you Overitab for sharing!

**Comment by Overitab** [comment]
Increased the number of nodes to 1000 on mirage, almost made ways from scratch. Last time I missed this map, probably because there were many versions of css and csgo dimakes

**Comment by jeefo** [comment]
New waypoint for map: [de_tuscan.graph](https://yapb.ru/graph/de_tuscan.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you Overitab for sharing!

**Comment by kYov0** [comment]
Both T and CT bots stuck at spawn points all the time in de_aztec.

**Comment by Overitab** [comment]
as I know this map has 2 versions 
maybe need try 1.5 version
https://yapb.ru/files/graph/de_aztec%28cs%201.5%29.graph

**Comment by jeefo** [comment]
New waypoint for map: [de_piranesi.graph](https://yapb.ru/graph/de_piranesi.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you Overitab for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [de_aztec.graph](https://yapb.ru/graph/de_aztec.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you Overitab for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [cs_office.graph](https://yapb.ru/graph/cs_office.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you Overitab for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [aim_map_hlo.graph](https://yapb.ru/graph/aim_map_hlo.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you [PRince4] for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [aim_map_mp5.graph](https://yapb.ru/graph/aim_map_mp5.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you [PRince4] for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [de_blackbush_b0.graph](https://yapb.ru/graph/de_blackbush_b0.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you [PRince4] for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [aim_3xd.graph](https://yapb.ru/graph/aim_3xd.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you [PRince4] for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [de_dust2_2020_b1.graph](https://yapb.ru/graph/de_dust2_2020_b1.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you Overitab for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [csg_militia.graph](https://yapb.ru/graph/csg_militia.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you Overitab for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [csg_dust2.graph](https://yapb.ru/graph/csg_dust2.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you Overitab for sharing!

**Comment by stambeto2006** [comment]
1. de_rats_1337_32  -----> https://www.17buddies.rocks/17b2/View/Map/61084/de_rats_1337_32.html
2. de_westwood  ----->  https://www.17buddies.rocks/17b2/View/Map/5852/de_westwood.html
3. de_inferno_final  ----->  https://www.17buddies.rocks/17b2/View/Map/54535/de_inferno_final.html
4. cs_assault_hotel  ----->  https://www.17buddies.rocks/17b2/View/Map/17493/cs_assault_hotel.html
5. de_winterdust2_fragarena  ----->  https://www.17buddies.rocks/17b2/View/Map/105502/de_winterdust2_fragarena.html
6. cs_deathmatch_final  ----->  https://www.17buddies.rocks/17b2/View/Map/106317/cs_deathmatch_final.html

**Comment by jeefo** [comment]
New waypoint for map: [de_bank_csgo.graph](https://yapb.ru/graph/de_bank_csgo.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you $_Vladislav for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [cs_assault_hotel.graph](https://yapb.ru/graph/cs_assault_hotel.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you Overitab for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [de_winterdust2_fragarena.graph](https://yapb.ru/graph/de_winterdust2_fragarena.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you Overitab for sharing!

**Comment by Overitab** [comment]
quickly create a quality graph file with 1000 nodes in 20 minutes on a dust2 size map, 
without test gameplay but in my experience everything should work, bots will learn if play more
rename graph from original dust2 not work for this map, another coordinates

https://www.youtube.com/watch?v=L35Ko5IbVgk

before save graph enter command yb wp clean all , this delete all unnecessary connections

my config for fast create graph
yapb.cfg
bind "MOUSE1" "yapb menu; menuselect 2; menuselect 2; menuselect 5; menuselect 1"  // standart waypoint
bind "MOUSE2" "yapb menu; menuselect 2; menuselect 2; menuselect 4"                        //delete connection
bind "MOUSE5" "yapb menu; menuselect 2; menuselect 2; menuselect 6"                        //delete waypoint
bind "MOUSE4" "yapb menu; menuselect 2; menuselect 2; menuselect 3; menuselect 1"   //make connection
bind "MOUSE3" "yapb menu; menuselect 2; menuselect 2; menuselect 5; menuselect 9"  //jump waypoint
bind "6" "yapb menu; menuselect 2; menuselect 2; menuselect 5; menuselect 6"             //camp waypoint
bind "7" "yapb menu; menuselect 2; menuselect 2; menuselect 5; menuselect 7"            //end camp waypoint
bind "z" "yapb menu; menuselect 2; menuselect 2; menuselect 1"                                  // open graph menu 

bind "c" "exec userconfig.cfg"  //this make standart config , when need shoot window for example

in userconfig.cfg
bind "c" "exec yapb.cfg"

**Comment by jeefo** [comment]
New waypoint for map: [cs_deathmatch_final.graph](https://yapb.ru/graph/cs_deathmatch_final.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you Overitab for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [awp_crazy.graph](https://yapb.ru/graph/awp_crazy.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you Overitab for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [de_cocaine.graph](https://yapb.ru/graph/de_cocaine.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you [PRince4] for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [glassfloor2019_v85.graph](https://yapb.ru/graph/glassfloor2019_v85.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you [PRince4] for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [de_bretonia.graph](https://yapb.ru/graph/de_bretonia.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you $_Vladislav for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [cs_mansion_BM.graph](https://yapb.ru/graph/cs_mansion_BM.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you $_Vladislav for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [es_dbridge_a2.graph](https://yapb.ru/graph/es_dbridge_a2.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you $_Vladislav for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [de_dust2_2020_b3.graph](https://yapb.ru/graph/de_dust2_2020_b3.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you Overitab and $_Vladislav for sharing!

**Comment by Vladislav4KZ** [comment]
@jeefo replace graph file for map es_endustrial with this
[es_industrial.graph.zip](https://github.com/jeefo/yapb/files/5212638/es_industrial.graph.zip)

I added nodes on T Spawn. I can't add it to the graph database myself due to the error: "Path broken from 0 to 684". I do not know why this error appeared, I seem to have done everything right.

**Comment by jeefo** [comment]
Thank you.

https://git.stx.su/yapb/graph/commit/043120e0307b1c4ce12298e04abcb659952f3def

**Comment by jeefo** [comment]
New waypoint for map: [de_mirage.graph](https://yapb.ru/graph/de_mirage.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you @V$- for sharing!

**Comment by PRinceBhai** [comment]
@Vladislav4KZ The error happens when a waypoint is either not connected to another or have no outgoing path. I Hope this helps.

**Comment by Vladislav4KZ** [comment]
> @Vladislav4KZ The error happens when a waypoint is either not connected to another or have no outgoing path. I Hope this helps.

But this waypoint had two-ways path connection to other waypoints. When I remove it, a similar error appears on another waypoint. And it is on the terrorists spawn. Elsewhere there is no such error.

**Comment by jeefo** [comment]
New waypoint for map: [de_dust2_2x2.graph](https://yapb.ru/graph/de_dust2_2x2.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you $_Vladislav for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [de_train32.graph](https://yapb.ru/graph/de_train32.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you [RWL]Deni$OK and $_Vladislav for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [fy_snowrock.graph](https://yapb.ru/graph/fy_snowrock.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you $_Vladislav for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [as_fortress.graph](https://yapb.ru/graph/as_fortress.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you $_Vladislav for sharing!

**Comment by regener** [comment]
Hey guys!
Can someone make a tutorial video how to properly make waypoints for YaPB? 😀

I want to try it myself (and of course share them if I made any).

**Comment by jeefo** [comment]
New waypoint for map: [$2000$.graph](https://yapb.ru/graph/$2000$.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you Player for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [$2000$.graph](https://yapb.ru/graph/$2000$.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you Player for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [$2000$.graph](https://yapb.ru/graph/$2000$.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you S3B`` for sharing!

**Comment by Vladislav4KZ** [comment]
> Hey guys!
> Can someone make a tutorial video how to properly make waypoints for YaPB? 😀
> 
> I want to try it myself (and of course share them if I made any).

Above, Overitab gave a link to a video on YouTube for creating waypoints.

> quickly create a quality graph file with 1000 nodes in 20 minutes on a dust2 size map, 
> without test gameplay but in my experience everything should work, bots will learn if play more
> rename graph from original dust2 not work for this map, another coordinates
> 
> https://www.youtube.com/watch?v=L35Ko5IbVgk
>

**Comment by jeefo** [comment]
New waypoint for map: [35hp_2_lite.graph](https://yapb.ru/graph/35hp_2_lite.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you $_Vladislav for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [35hp_reborn.graph](https://yapb.ru/graph/35hp_reborn.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you $_Vladislav for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [35hp_lava.graph](https://yapb.ru/graph/35hp_lava.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you $_Vladislav for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [fy_spqr2020_pool_b2.graph](https://yapb.ru/graph/fy_spqr2020_pool_b2.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you $_Vladislav for sharing!

**Comment by vladislav980** [comment]
На даст 2на2 там Goal точки неправильно расположены, боты не могут бомбу поставить.

**Comment by Vladislav4KZ** [comment]
> На даст 2на2 там Goal точки неправильно расположены, боты не могут бомбу поставить.
> 
> 

Ок, исправлю если смогу загрузить graph в базу. Раньше там был вэйпоинт от S3B в котором тоже были неверно расположены целевые точки. Да и не вся карта была покрыта вэйпоинтами.

Текущий graph файл это отредактированный из de_dust2 от LLIHULLEJIb. И как оказалось координаты места закладки бомбы немного смещены и из-за этого боты не могут ставить бомбу.

**Comment by jeefo** [comment]
New waypoint for map: [vlhcs_blast.graph](https://yapb.ru/graph/vlhcs_blast.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you $_Vladislav for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [100hp.graph](https://yapb.ru/graph/100hp.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you $_Vladislav for sharing!

**Comment by Vladislav4KZ** [comment]
@jeefo can you please replace graph file for de_piranesi map with this 
[de_piranesi.zip](https://github.com/jeefo/yapb/files/5397192/de_piranesi.zip)

I noticed that the paths there are not correct, probably the waypoint was made for a map from CS 1.5
![ezgif-7-22b180c248bb](https://user-images.githubusercontent.com/22411953/96361879-312a3080-114b-11eb-9a60-04382a9774e0.png)
![ezgif-7-1f2ab1fd7cd3](https://user-images.githubusercontent.com/22411953/96361884-3a1b0200-114b-11eb-9ffa-cf98aa842a5c.png)
![ezgif-7-974bd1c8f595](https://user-images.githubusercontent.com/22411953/96361887-3be4c580-114b-11eb-8ec7-b6fc20331a11.png)

And graph for de_dust2_2x2 with fixed goal nodes 
[de_dust2_2x2.zip](https://github.com/jeefo/yapb/files/5397196/de_dust2_2x2.zip)

**Comment by jeefo** [comment]
New waypoint for map: [de_dust2_night.graph](https://yapb.ru/graph/de_dust2_night.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you epresmoha for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [de_dust2_fundo2.graph](https://yapb.ru/graph/de_dust2_fundo2.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you epresmoha for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [aim_bloody-mp5.graph](https://yapb.ru/graph/aim_bloody-mp5.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you epresmoha for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [aim_tankers.graph](https://yapb.ru/graph/aim_tankers.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you epresmoha for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [awp_eb@_aztec.graph](https://yapb.ru/graph/awp_eb@_aztec.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you epresmoha for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [go_vertigo_classic.graph](https://yapb.ru/graph/go_vertigo_classic.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you $_Vladislav for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [go_vertigo_classic_pub.graph](https://yapb.ru/graph/go_vertigo_classic_pub.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you $_Vladislav for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [de_vertigo_classic.graph](https://yapb.ru/graph/de_vertigo_classic.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you $_Vladislav for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [awp_white.graph](https://yapb.ru/graph/awp_white.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you epresmoha for sharing!

**Comment by regener** [comment]
I have remade the graph file for cs_max, since it was buggy.
In this version the bots doesn't get stuck in CT doors, instead they use the window to get out and jump to other side of the bridge too.
https://www.youtube.com/watch?v=27Ea7gjfwuY

Can you replace it please?
[cs_max.zip](https://github.com/jeefo/yapb/files/5429181/cs_max.zip)

**Comment by jeefo** [comment]
New waypoint for map: [1hp_just.graph](https://yapb.ru/graph/1hp_just.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you $_Vladislav for sharing!

**Comment by Vladislav4KZ** [comment]
@jeefo you forgot to replace graph file for de_piranesi.
I also made a fixed graph for the de_cbble map. Previous graph had paths going through crates

[cbble&piranesi_fixed.zip](https://github.com/jeefo/yapb/files/5432692/cbble.piranesi_fixed.zip)

**Comment by jeefo** [comment]
New waypoint for map: [ka_risingsun.graph](https://yapb.ru/graph/ka_risingsun.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you $_Vladislav for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [fy_new_pool_day2.graph](https://yapb.ru/graph/fy_new_pool_day2.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you epresmoha for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [fy_md.graph](https://yapb.ru/graph/fy_md.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you epresmoha for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [fy_snow_dew.graph](https://yapb.ru/graph/fy_snow_dew.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you epresmoha for sharing!

**Comment by stambeto2006** [comment]
**1. zm_defense_xld  -----> https://amxx-bg.info/viewtopic.php?f=65&t=9829**

**Comment by jeefo** [comment]
New waypoint for map: [fy_alcool.graph](https://yapb.ru/graph/fy_alcool.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you epresmoha for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [fy_constanta.graph](https://yapb.ru/graph/fy_constanta.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you epresmoha for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [fy_flake.graph](https://yapb.ru/graph/fy_flake.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you epresmoha for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [fy_monster.graph](https://yapb.ru/graph/fy_monster.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you epresmoha for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [fy_reunited.graph](https://yapb.ru/graph/fy_reunited.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you epresmoha for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [fy_snow_war.graph](https://yapb.ru/graph/fy_snow_war.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you epresmoha for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [fy_sudcs.graph](https://yapb.ru/graph/fy_sudcs.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you epresmoha for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [fy_snow_xgm.graph](https://yapb.ru/graph/fy_snow_xgm.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you epresmoha for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [ka_cobble.graph](https://yapb.ru/graph/ka_cobble.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you epresmoha for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [scout_dust2012.graph](https://yapb.ru/graph/scout_dust2012.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you epresmoha for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [ka_sillo.graph](https://yapb.ru/graph/ka_sillo.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you epresmoha for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [ka_sudzone.graph](https://yapb.ru/graph/ka_sudzone.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you epresmoha for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [scout_xxx.graph](https://yapb.ru/graph/scout_xxx.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you epresmoha for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [de_tuscan_2x2.graph](https://yapb.ru/graph/de_tuscan_2x2.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you $_Vladislav for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [de_mirage_2x2.graph](https://yapb.ru/graph/de_mirage_2x2.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you $_Vladislav for sharing!

**Comment by jeefo** [comment]
New waypoint for map: [de_aztec2x2.graph](https://yapb.ru/graph/de_aztec2x2.graph) was uploaded to YaPB database.

It's now available to download for every YaPB user.

Thank you $_Vladislav for sharing!

**Comment by jeefo** [comment]
Continue: https://github.com/yapb/graph/issues/1
