### ISSUE TITLE
Transfer C4 to Human Players

### ISSUE THREAD

**Issue by yuusuke09** [yapb/yapb#144]
hi, 
Is it possible that force the C4 to be randomly given to human players when playing with the bots on de_ maps?
Thanks.
Cstrike + AMXX 1.10.0.5405 + Metamod-P39

**Comment by jeefo** [comment]
Hello. You mean the bot should not receive a c4 If some players on Ts is alive?

If yes, than it's better job for some amx plugin.

**Comment by yuusuke09** [comment]
Thanks for replying. 
Yes, that's exactly what I need because bots sometimes may not plant bomb if they are confused and stuck on somewhere.
