### ISSUE TITLE
Missing letters in cvar descriptions/Пропадание букв в описаниях кваров

### ISSUE THREAD

**Issue by Vladislav4KZ** [yapb/yapb#177]
YaPB v4.0.500 commit: fba3837

Line breaks found in some descriptions, see screenshot

![Снимок экрана (109)](https://user-images.githubusercontent.com/22411953/95958970-b3e97d80-0e23-11eb-9927-90722014d000.png)

**Comment by jeefo** [comment]
Oh...

https://github.com/jeefo/yapb/commit/2bef810ce66fc10dbf6db1b6875cdc72142bfe5e  ?

**Comment by Vladislav4KZ** [comment]
Looks nice in English, but in Russian I noticed some letters missing.

By the way, why did you turn off the translation of game.print in hlds? In my opinion it was better to leave it as it is, tk. the translation worked well both on hlds and rehlds (listen server too). Even with rapid output

**Comment by Vladislav4KZ** [comment]
Listen server
--------------------
YaPB v4.0.501 commit: 2bef810
![Снимок экрана (110)](https://user-images.githubusercontent.com/22411953/96236206-8b958680-0fbd-11eb-8a57-717a3408315d.png)

YaPB v.4.0.501 Custom build
![Снимок экрана (112)](https://user-images.githubusercontent.com/22411953/96236550-0363b100-0fbe-11eb-8c7e-082341481922.png)

Dedicated server
------------------------------
YaPB v4.0.501 commit: 2bef810
![Снимок экрана (114)](https://user-images.githubusercontent.com/22411953/96237022-98ff4080-0fbe-11eb-9642-089f24849e1c.png)

YaPB v4.0.501 Custom build
![Снимок экрана (113)](https://user-images.githubusercontent.com/22411953/96237106-b502e200-0fbe-11eb-905a-50840dc723db.png)

**Translation of cvar descriptions works fine only on a dedicated server**
![Снимок экрана (115)](https://user-images.githubusercontent.com/22411953/96237482-2e9ad000-0fbf-11eb-9cf6-80d52f90827d.png)

**Comment by jeefo** [comment]
> Looks nice in English, but in Russian I noticed some letters missing.
> 
> By the way, why did you turn off the translation of game.print in hlds? In my opinion it was better to leave it as it is, because the translation worked well both on hlds and rehlds (listen server too). Even with rapid output

It's nice to have game.print() but these messages then aren't displayed from to client, when using yapb commands remotely on hlds. (using yb_password[_key])

**Comment by jeefo** [comment]
about missing letters, eah, i will add multibyte support for splitting messages.

**Comment by Vladislav4KZ** [comment]
@jeefo баг с пропаданием букв в описаниях кваров на русском языке всё ещё актуален на последнем Continuous build (v4.5.1159)
