### ISSUE TITLE
BOTs Unusal actions

### ISSUE THREAD

**Issue by jaythomas77** [yapb/yapb#185]
Bots are still camping and shift walking.
When there cvars has the below value
BOTs were camping, and playing like the difficulty was 1 or 2.
Sometimes the bot used to just see the walls and peep in them. When you used to run behind they couldn't hear you and attack you.

My Current cfg
yb_autokill_delay "0"
yb_autovacate "0"
yb_bind_menu_key "="
yb_botbuy "1"
yb_botskin_t "0"
yb_botskin_ct "0"
yb_camping_allowed "0"
yb_chat "0"
yb_check_enemy_rendering "1"
yb_csdm_mode "2"
yb_chatter_path "sound/radio/bot"
yb_communication_type "0"
yb_debug "1"
yb_debug_goal "-1"
yb_debug_heuristic_type "0"
yb_destroy_breakables_around "1"
yb_difficulty "4"
yb_difficulty_min "-1"
yb_difficulty_max "-1"
yb_difficulty_auto "0"
yb_display_welcome_text "0"
yb_display_menu_text "1"
yb_economics_rounds "0"
yb_enable_query_hook "1"
yb_freeze_bots "0"
yb_graph_fixcamp "0"
yb_graph_url ""
yb_ignore_cvars_on_changelevel "yb_quota,yb_autovacate"
yb_ignore_enemies "0"
yb_jasonmode "0"
yb_join_after_player "0"
yb_join_team any
yb_join_delay "0.0"
yb_language "en"
yb_latency_display "2"
yb_name_prefix ""
yb_password_key "_yrekt"
yb_password "foceswiss"
yb_ping_base_min "10"
yb_ping_base_max "70"
yb_quota "15"
yb_quota_mode "normal"
yb_quota_match "0"
yb_restricted_weapons "usp;glock;p228;elite;fn57;m3;xm1014;mp5;tmp;p90;mac10;ump45;galil;famas;sg552;aug;scout;g3sg1;sg550;m249;flash;sgren;defuser;shield"
yb_shoots_thru_walls "2"
yb_show_avatars "0"
yb_spraypaints "1"
yb_stab_close_enemies "1"
yb_think_fps "30.0"
yb_tkpunish "0"
yb_user_follow_percent "0"
yb_user_max_followers "0"
yb_walking_allowed "0"
yb_whose_your_daddy "1"

**Comment by regener** [comment]
What map and mode are you playing at?

**Comment by jeefo** [comment]
Actual question above...
