### ISSUE TITLE
Assign Valve/Nonsteam ID to bots

### ISSUE THREAD

**Issue by jaythomas77** [yapb/yapb#186]
I had seen one earlier issue & you commented there that it would require to patch rehlds.
You had posted a link and told to compile it from there.
https://git.stx.su/ds/rehlds-fbs/commit/75c055267c7d5c0ac49bd2ced82922251249d6be

I compiled this and was using but it didnt worked :(

**Comment by jeefo** [comment]
You're need to set ``sv_rehlds_show_bots_as_players`` to ``1`` to get it working.

Anyway, it's not the place to discuss this modification. It's doesn't directly connects to YaPB.
