### ISSUE TITLE
Linux vs Windows dedicated server differences

### ISSUE THREAD

**Issue by regener** [yapb/yapb#189]
Bots fly away on linux server at spawn and they can't use the ladders easily as they do on a windows server.

[![](http://img.youtube.com/vi/cS-_CjmK2pY/0.jpg)](http://www.youtube.com/watch?v=cS-_CjmK2pY "YaPB dedicated server behaviour: linux vs windows")

**Comment by jeefo** [comment]
It's fun)

Is it only on that map ?

**Comment by regener** [comment]
Until they die they enjoy it too, I guess :D

No, it happens ony every map, even default (like dust2) ones.
I'm using latest YaPB build with lastest AMXX 1.10 build 5406, with ReHLDS and ReGameDLL (those are 1-2 month old).
I have tried without AMXX plugins, but it didn't help.

**Comment by jeefo** [comment]
Is it custom-compiled bot .so ? or official build?

**Comment by regener** [comment]
Official from Releases / 4.0.532
I have tried 4.0.478 too (random picked one), but same results. Should I try some older too?

**Comment by jeefo** [comment]
That's pretty odd, actually. 

Try:
https://yapb.ru/files/binaries/4.0.532/release/yapb.gcc.so
And:
https://yapb.ru/files/binaries/4.0.532/release/yapb.clang.so

**Comment by regener** [comment]
It seems that the GCC version did fix it. Thanks.
Any idea what causes that?

**Comment by jeefo** [comment]
Idk currently. And can you verify clang?

**Comment by regener** [comment]
Clang works too.
