### ISSUE TITLE
[REQUEST] Getters for AMXX

### ISSUE THREAD

**Issue by hellmoss** [yapb/yapb#191]
Hello, @jeefo 
Would it be possible to add just a few lines of code so amxx can communicate with yapb?
I'm talking about just simple getters for indeces of points and a function to tell bots to go to the point specified and follow the specified route through amxx. I'm trying to make the bots a little smarter in my zombie plague mod and I've thought of a good method (in theory).

I don't know if you would have to add code so that the bot needs to calculate a new route all the way to the point if its far from him; if so I will do that through amxx, you don't have to put in a lot of effort.

Thanks.

P. S. A curious question: would it be a lot of work to record movements as a human player and then implement them to be used by bot exactly as recorded (analogous to demo recording)?

**Comment by jeefo** [comment]
hello.

I was thinking about AMXX api for bots. But currently i'm out of time, probably later.

**Comment by hellmoss** [comment]
> hello.
> 
> I was thinking about AMXX api for bots. But currently i'm out of time, probably a little later.

I'm looking forward to it! Thanks!

**Comment by jeefo** [comment]
Ok. I've added basic API for AMXX in bot, i believe i'll be ready to release AMXX module itself next week.

**Comment by hellmoss** [comment]
I'm available for testing if needed. Thanks!

**Comment by hellmoss** [comment]
Also instructions for looking for a new random enemy would be good, like forcing the bot to look for a new enemy. 

As well as setting their new target to a specific player id.

**Comment by jeefo** [comment]
Sorry for the delay. Out of time completely.

Will push amxx module next week.
