### ISSUE TITLE
Can't hear bot steps

### ISSUE THREAD

**Issue by ThePhoenixd** [yapb/yapb#195]
По какой-то причине у ботов пропадает звук шагов, если не звуки стрельбы, урона и по нему и всё, что связано с ним.

Происходит на разных картах. Видео: https://dropmefiles.com/v0mrZ

Инфа по серверу:

> amxx 1.9.0.5271
> rehlds 5.18.0.474-dev
> regamedll 5.18.0.474-dev
> Metamod-r v1.3.0.128

```
Currently loaded plugins:
      description      stat pend  file                        vers             src  load  unload
 [ 1] Reunion          RUN   -    reunion_mm_i386.so          v0.1.0.92c       ini  Start Never
 [ 2] Rechecker        RUN   -    rechecker_mm_i386.so        v2.5             ini  Chlvl ANY  
 [ 3] VoiceTranscoder  RUN   -    VoiceTranscoder.so          v2017RC5         ini  ANY   ANY  
 [ 4] SafeNameAndChat  RUN   -    SafeNameAndChat.so          v1.1             ini  ANY   ANY  
 [ 5] AMX Mod X        RUN   -    amxmodx_mm_i386.so          v1.9.0.5271      ini  Start ANY  
 [ 6] WHBlocker        RUN   -    whblocker_mm_i386.so        v1.5.696         ini  Chlvl ANY  
 [ 7] ReSemiclip       RUN   -    resemiclip_mm_i386.so       v2.3.9           ini  Chlvl ANY  
 [ 8] YaPB             RUN   -    yapb.so                     v4.0.499         ini  Chlvl ANY  
 [ 9] MySQL            RUN   -    mysql_amxx_i386.so          v1.9.0.5271      pl5  ANY   ANY  
 [10] ReAPI            RUN   -    reapi_amxx_i386.so          v5.15.0.197-dev  pl5  ANY   Never
 [11] ReAimDetector    RUN   -    reaimdetector_amxx_i386.so  v0.2.2           pl5  ANY   Never
 [12] Admins Kit       RUN   -    adminskit_amxx_i386.so      v1.0.2           pl5  ANY   Never
 [13] GeoIP            RUN   -    geoip_amxx_i386.so          v1.9.0.5271      pl5  ANY   ANY  
 [14] FakeMeta         RUN   -    fakemeta_amxx_i386.so       v1.9.0.5271      pl5  ANY   ANY  
 [15] Ham Sandwich     RUN   -    hamsandwich_amxx_i386.so    v1.9.0.5271      pl5  ANY   ANY  
 [16] CStrike          RUN   -    cstrike_amxx_i386.so        v1.9.0.5271      pl5  ANY   ANY  
 [17] Engine           RUN   -    engine_amxx_i386.so         v1.9.0.5271      pl5  ANY   ANY  
 [18] Fun              RUN   -    fun_amxx_i386.so            v1.9.0.5271      pl5  ANY   ANY  
18 plugins, 18 running
```

```
amxx list
Currently loaded plugins:
       name                    version     author            file             status   
 [  1] Admin Loader            3.5         neygomon          admin_loader.am  running  
 [  2] Lite Bans               2.2         neygomon          lite_bans_off.a  running  
 [  3] ScreenMaker             1.1         neygomon          screen_maker.am  running  
 [  4] Aliases checker         1.0.6       kanagava          alias_detector_  running  
 [  5] ReAimDetector API       0.2.2       ReHLDS Team       reaimdetector.a  running  
 [  6] Ultimate Chats Control  5.2(c)      neygomon          ucc.amxx         running  
 [  7] Admin Commands          1.9.0.5271  AMXX Dev Team     admincmd.amxx    running  
 [  8] Admin Chat              1.9.0.5271  AMXX Dev Team     adminchat.amxx   running  
 [  9] Admin Votes             1.9.0.5271  AMXX Dev Team     adminvote.amxx   running  
 [ 10] New Kick Menu           1.0         s13cs.ru          newkickmenu.amx  running  
 [ 11] Menus Front-End         1.4         neugomon          menufront_end.a  running  
 [ 12] Commands Menu           1.9.0.5271  AMXX Dev Team     cmdmenu.amxx     running  
 [ 13] Players Menu            1.7         neugomon          players_menu.am  running  
 [ 14] Maps Menu               1.9.0.5271  AMXX Dev Team     mapsmenu.amxx    running  
 [ 15] CSStatsX SQL            0.7.4+2     serfreeman1337    csstatsx_sql.am  running  
 [ 16] AES: StatsX             0.5+1       serfreeman1337    aes_statsx_cstr  running  
 [ 17] StatsX                  1.9.0.5271  AMXX Dev Team     statsx.amxx      running  
 [ 18] Stats Configuration     1.9.0.5271  AMXX Dev Team     statscfg.amxx    running  
 [ 19] CS Stats Logging        1.9.0.5271  AMXX Dev Team     stats_logging.a  running  
 [ 20] ReChecker Logging       1.0         custom            rc_logging.amxx  running  
 [ 21] Chat Manager            1.1.2-16    Mistrick          chatmanager.amx  running  
 [ 22] Chat Manager: Addon     0.0.4-70    Mistrick          chatmanager_add  running  
 [ 23] Advert Messages         1.2.2       neygomon          adverts.amxx     running  
 [ 24] Welcome Message         1.0         ThePhoenix        welcome.amxx     running  
 [ 25] Lite Recoder            1.0.1       neygomon          amx_demorec.amx  running  
 [ 26] [ReAPI] Reset Score     0.1         pUzzlik           re_reset_score.  running  
 [ 27] AFK Control ReNew       1.2(a)      neygomon          afk_control.amx  running  
 [ 28] Lite Balance            1.1         ThePhoenix        lite_balance.am  running  
 [ 29] Use for Flags           0.0.1       ThePhoenix        use_for_flags.a  running  
 [ 30] [ReAPI] Hint blocker    0.1.0       F@tn0M            reapi_hint_bloc  running  
 [ 31] Custom Smoke            1.09        bionext           custom_smoke.am  running  
 [ 32] AntiFlood Change Name   28.11.2018  sergrib           block_change_sp  running  
 [ 33] [Reapi] Block Advert    1.4         neygomon          block_all_avder  running  
 [ 34] unknown                 unknown     unknown           protection.amxx  running  
 [ 35] Team Select             1.6.0       F@nt0M            teamselect.amxx  running  
 [ 36] WeaponState Remember    0.0.4       Vaqtincha         weaponstate_rem  running  
 [ 37] Ping Checker            RC2         h1k3              ping_checker.am  running  
 [ 38] Menu + RUBs             1.1         ThePhoenix        menu_plus_rubs.  running  
 [ 39] AMX MODES               2.0.0.20    ThePhoenix        amx_modes.amxx   debug    
 [ 40] Classic Mode            0.65        ThePhoenix        amx_classic.amx  debug    
 [ 41] Lite VIP                0.999       ThePhoenix        lite_vip.amxx    debug    
 [ 42] Weapon Use Pickup       1.0         PurposeLess       weaponusepickup  debug    
 [ 43] Punish System           1.0.0.0     ThePhoenix        tk_punish_syste  debug    
 [ 44] GameRules Info          1.2         shadow            GameRulesInfo.a  debug    
 [ 45] GunGame Mode            1.1.1.60    ThePhoenix        amx_gungame.amx  stopped  
 [ 46] Knife DM Mode           1.0.0.15    ThePhoenix        amx_knife_dm.am  stopped  
 [ 47] Classes KNIFE DM        1.4         ThePhoenix        amx_characters.  stopped  
 [ 48] DM FFA Mode             2.0.0.17    ThePhoenix        amx_dm_ffa.amxx  stopped  
 [ 49] DM FFA BONUSES          2.0.0.15    ThePhoenix        amx_dm_ffa_bonu  stopped  
 [ 50] FFA Enemy Models        0.1         Vaqtincha         ffa_enemy_model  stopped  
 [ 51] DeathMatch Spawn Manag  0.1.4       Vaqtincha         csdm_spawn_mana  stopped  
 [ 52] Combo On Kill           0.2         Vaqtincha         combo_on_kill.a  stopped  
 [ 53] Fun Mode                1.0.0.0     ThePhoenix        amx_fun.amxx     stopped  
 [ 54] Alternate Hostage Resc  0.2         Vaqtincha         Alternate_Hosta  running  
54 plugins, 45 running
```

Ни в одном плагине нет установки звука шагов.

**Comment by vladislav980** [comment]
mp_footsteps 1 в server.cfg есть такое?

**Comment by ThePhoenixd** [comment]
ещё бы, иначе других не было бы слышно.

**Comment by jeefo** [comment]
Попробуй metamod-p, чисто для интереса?

**Comment by ThePhoenixd** [comment]
Есть принципиальная разница в использовании metamod с ботами?

**Comment by jeefo** [comment]
Нет, но самы боты не генерируют шаги. Поэтому как вариант.

**Comment by PRinceBhai** [comment]
Могу я узнать, где вы взяли некоторые плагины. Я не могу найти его на https://www.amxmodx.org/compiler.php

**Comment by ThePhoenixd** [comment]
О чём именно идёт речь?

**Comment by PRinceBhai** [comment]
> О чём именно идёт речь?

Я извиняюсь за поздний ответ. Я говорил о плагинах amxx на ваших скриншотах.

**Comment by ThePhoenixd** [comment]
Смотря какие плагины. Почему нельзя спросить более конкретно то?
Часть плагинов с разных форумов, часть моих.

**Comment by jeefo** [comment]
Is it working with podbot?

**Comment by ThePhoenixd** [comment]
Если ты про плагины - то они все работают с ботами нормально. Если ты про проблему, то я так и ничего не проверил, т.к заграницей и без ПК :)

**Comment by jeefo** [comment]
Я имею в виду, подботы, издают звуки?

**Comment by ThePhoenixd** [comment]
"Если ты про проблему, то я так и ничего не проверил, т.к заграницей и без ПК :)"
Хотел успеть до отъезда, но не получилось

**Comment by PRinceBhai** [comment]
Друг, я имею в виду следующие модули:

 [ 1] Reunion          RUN   -    reunion_mm_i386.so          v0.1.0.92c       ini  Start Never
 [ 2] Rechecker        RUN   -    rechecker_mm_i386.so        v2.5             ini  Chlvl ANY  
 [ 3] VoiceTranscoder  RUN   -    VoiceTranscoder.so          v2017RC5         ini  ANY   ANY  
 [ 4] SafeNameAndChat  RUN   -    SafeNameAndChat.so          v1.1             ini  ANY   ANY  
 [ 5] AMX Mod X        RUN   -    amxmodx_mm_i386.so          v1.9.0.5271      ini  Start ANY  
 [ 6] WHBlocker        RUN   -    whblocker_mm_i386.so        v1.5.696         ini  Chlvl ANY  
 [ 7] ReSemiclip       RUN   -    resemiclip_mm_i386.so       v2.3.9           ini  Chlvl ANY  
 [10] ReAPI            RUN   -    reapi_amxx_i386.so          v5.15.0.197-dev  pl5  ANY   Never
 [11] ReAimDetector    RUN   -    reaimdetector_amxx_i386.so  v0.2.2           pl5  ANY   Never
 [12] Admins Kit       RUN   -    adminskit_amxx_i386.so      v1.0.2           pl5  ANY   Never

и плагины :

 [  1] Admin Loader            3.5         neygomon          admin_loader.am  running  
 [  2] Lite Bans               2.2         neygomon          lite_bans_off.a  running  
 [  3] ScreenMaker             1.1         neygomon          screen_maker.am  running  
 [  4] Aliases checker         1.0.6       kanagava          alias_detector_  running  
 [  5] ReAimDetector API       0.2.2       ReHLDS Team       reaimdetector.a  running  
 [  6] Ultimate Chats Control  5.2(c)      neygomon          ucc.amxx         running  
 [ 10] New Kick Menu           1.0         s13cs.ru          newkickmenu.amx  running  
 [ 11] Menus Front-End         1.4         neugomon          menufront_end.a  running  
 [ 12] Commands Menu           1.9.0.5271  AMXX Dev Team     cmdmenu.amxx     running  
 [ 13] Players Menu            1.7         neugomon          players_menu.am  running  
 [ 14] Maps Menu               1.9.0.5271  AMXX Dev Team     mapsmenu.amxx    running  
 [ 15] CSStatsX SQL            0.7.4+2     serfreeman1337    csstatsx_sql.am  running  
 [ 16] AES: StatsX             0.5+1       serfreeman1337    aes_statsx_cstr  running  
 [ 20] ReChecker Logging       1.0         custom            rc_logging.amxx  running  
 [ 21] Chat Manager            1.1.2-16    Mistrick          chatmanager.amx  running  
 [ 22] Chat Manager: Addon     0.0.4-70    Mistrick          chatmanager_add  running  
 [ 23] Advert Messages         1.2.2       neygomon          adverts.amxx     running  
 [ 24] Welcome Message         1.0         ThePhoenix        welcome.amxx     running  
 [ 25] Lite Recoder            1.0.1       neygomon          amx_demorec.amx  running  
 [ 26] [ReAPI] Reset Score     0.1         pUzzlik           re_reset_score.  running  
 [ 27] AFK Control ReNew       1.2(a)      neygomon          afk_control.amx  running  
 [ 28] Lite Balance            1.1         ThePhoenix        lite_balance.am  running  
 [ 29] Use for Flags           0.0.1       ThePhoenix        use_for_flags.a  running  
 [ 30] [ReAPI] Hint blocker    0.1.0       F@tn0M            reapi_hint_bloc  running  
 [ 31] Custom Smoke            1.09        bionext           custom_smoke.am  running  
 [ 32] AntiFlood Change Name   28.11.2018  sergrib           block_change_sp  running  
 [ 33] [Reapi] Block Advert    1.4         neygomon          block_all_avder  running  
 [ 34] unknown                 unknown     unknown           protection.amxx  running  
 [ 35] Team Select             1.6.0       F@nt0M            teamselect.amxx  running  
 [ 36] WeaponState Remember    0.0.4       Vaqtincha         weaponstate_rem  running  
 [ 37] Ping Checker            RC2         h1k3              ping_checker.am  running  
 [ 38] Menu + RUBs             1.1         ThePhoenix        menu_plus_rubs.  running  
 [ 39] AMX MODES               2.0.0.20    ThePhoenix        amx_modes.amxx   debug    
 [ 40] Classic Mode            0.65        ThePhoenix        amx_classic.amx  debug    
 [ 41] Lite VIP                0.999       ThePhoenix        lite_vip.amxx    debug    
 [ 42] Weapon Use Pickup       1.0         PurposeLess       weaponusepickup  debug    
 [ 43] Punish System           1.0.0.0     ThePhoenix        tk_punish_syste  debug    
 [ 44] GameRules Info          1.2         shadow            GameRulesInfo.a  debug    
 [ 45] GunGame Mode            1.1.1.60    ThePhoenix        amx_gungame.amx  stopped  
 [ 46] Knife DM Mode           1.0.0.15    ThePhoenix        amx_knife_dm.am  stopped  
 [ 47] Classes KNIFE DM        1.4         ThePhoenix        amx_characters.  stopped  
 [ 48] DM FFA Mode             2.0.0.17    ThePhoenix        amx_dm_ffa.amxx  stopped  
 [ 49] DM FFA BONUSES          2.0.0.15    ThePhoenix        amx_dm_ffa_bonu  stopped  
 [ 50] FFA Enemy Models        0.1         Vaqtincha         ffa_enemy_model  stopped  
 [ 51] DeathMatch Spawn Manag  0.1.4       Vaqtincha         csdm_spawn_mana  stopped  
 [ 52] Combo On Kill           0.2         Vaqtincha         combo_on_kill.a  stopped  
 [ 53] Fun Mode                1.0.0.0     ThePhoenix        amx_fun.amxx     stopped  
 [ 54] Alternate Hostage Resc  0.2         Vaqtincha         Alternate_Hosta  running  

Я выбрал практически все плагины, извините  :P
Спасибо

**Comment by jeefo** [comment]
closing as stale, and no feedback
