### ISSUE TITLE
Movement and targeting issues 

### ISSUE THREAD

**Issue by Hedgefog** [yapb/yapb#205]
## ❓ What I'm talking about?
Bots are constantly "derailing" (leaving their waypoints), falling, stuck, and shooting walls.
Sometimes they focus on the enemy prevents them from moving normally and looks unnatural.

## 🛠 Fixes:
I've made the first fix for bots, but it's still in progress: https://github.com/yapb/yapb/pull/204
I'm not sure I know the way to fix all of these issues, but I'll continue to research.

## 📃 Checklist:
- [x] Fix deadly move check
- [ ] Fix reluctant forward movement
- [ ] Fix obstacle ignoring
- [ ] Fix excessive accuracy
- [ ] Fix Pixel hunting (Trying to shoot a hidden enemy)
- [ ] Fix ignoring enemies with specific movetype/solidtype
- [ ] Smoother aim
 
### PodBot bots + Halloween Mod:

[![Watch](https://img.youtube.com/vi/UThGLnfS8j4/0.jpg)](https://www.youtube.com/watch?v=UThGLnfS8j4)

https://www.youtube.com/watch?v=UThGLnfS8j4

### YaPB bots  + Halloween Mod:

[![Watch](https://img.youtube.com/vi/k5__KDPayKE/0.jpg)](https://www.youtube.com/watch?v=k5__KDPayKE)

https://www.youtube.com/watch?v=k5__KDPayKE

**Comment by jeefo** [comment]
Probably isDeadlyDrop() isn't doing it's work very well. I'm currently out
of time, but will try to look into it next week.

**Comment by Hedgefog** [comment]
@jeefo
isDeadlyMove fix: https://github.com/yapb/yapb/pull/206/files
