### ISSUE TITLE
Specific weapon modes crash

### ISSUE THREAD

**Issue by qq578023708** [yapb/yapb#207]
When my server adds some restrictions on office weapons, for example, only knives are allowed in the first round, and the robot plug-in will crash and exit. Even if there is no crash, the robot will not work normally. For example, only weapons and knives are allowed to be used. However, the robot only squats in the original place and slides continuously, and will not approach the attack. I don't know how to solve this problem.

The plug-in code looks like this
`public plugin_init()
{
	register_plugin("Restrict Weapons Fight", "1.2", "Rulzy")
	register_menucmd(register_menuid("#Buy", 1), 511, "menuBuy")
	register_menucmd(register_menuid("BuyItem", 1), 511, "menuItem")
	register_event("TextMsg", "Game_Commencing", "ac", "2&#Game_Commencing")
	register_concmd("amx_clear_restwpns", "cmdClearRestrictWeapons", ADMIN_LEVEL_A, "<n> <flags> - set restrict weapons")
	register_concmd("amx_add_restwpns", "cmdAddRestrictWeapons", ADMIN_LEVEL_A, "<flags> - set restrict weapons")
	register_cvar("amx_delaygivegrenade", "0.1")
	register_event("CurWeapon","eWeaponChange","be")
	register_event("HLTV", "eNewRound", "a", "1=0", "2=0")
	//register_clcmd("fullupdate", "cmd_fullupdate")
	register_event("ResetHUD", "eResetHUD", "be")
	register_event("TextMsg", "eRestart", "a", "2=#Game_will_restart_in")
	register_event("AmmoX", "eAmmoX", "be")
	g_RestrictCount = 0
	for(new i=0;i<MAX_REST_ROUND_COUNT;i++)
		g_weaponflags[i] = FLAG_Z
}`

**Comment by jeefo** [comment]
Please, use issue template. the plugin_init code you're posted says nothing to me. Please re-open with correct description.
