### ISSUE TITLE
engclient command causes crash

### ISSUE THREAD

**Issue by qq578023708** [yapb/yapb#211]
**Describe the bug**
If the command engclient_cmd(id, "weapon_knife") is sent to the robot ,
Force robot to switch weapon to knife,
It will cause game server to crash and exit.
At the moment, my approach is to skip the robot player.

**Expected behavior**

**Video**
If it's problem with AI behaviour, add video to help explain your problem.

**Environment details:**
 - OS: [windows server 2012]
 - Engine: [rehlds 3.8.0.702]
 - GameDLL: [no]
 - Metamod: [metamod]
 - Bot Version: [4.1.566]
 - Game mode: [ public]

Additionally, please provide list of AMX Mod X plugins: ``amxx plugins`` and list of Metamod plugins: ``meta plugins``.

**Additional context**

**Comment by jeefo** [comment]
I cant reproduce. Nothing interesting happens with engclient_cmd(id, "weapon_knife") .
