### ISSUE TITLE
if enable yb_jasonmode,T bot and CT bot are often stuck on both sides of a box

### ISSUE THREAD

**Issue by qq578023708** [yapb/yapb#215]
**Describe the bug**

if enable yb_jasonmode 1
bot are often stuck on both sides of a box
Fall into the pit and don't jump out
A bunch of robots blocking the door
Do not move
CT cannot defused C4

There's also the problem of picking up weapons. If weapons fall out of reach, robots will move all the way to the weapon point, but they can't get there

Can we add a delay detection mechanism, when we want to do some action, start timing. According to the distance, if it is not completed within the specified time, it is judged that it can not be completed and give up the action. This can solve some problems caused by the dead cycle

**Expected behavior**

**Video**
If it's problem with AI behaviour, add video to help explain your problem.

**Environment details:**
 - OS: [e.g. windows 10 / linux debian 10.4]
 - Engine: [e.g. rehlds 3.8.0.702 / vanilla 8684]
 - GameDLL: [e.g. regamedll 5.18.0.479 / vanilla]
 - Metamod: [e.g. metamod-r / metamod-p / metamod]
 - Bot Version: [e.g. 4.1.566]
 - Game mode: [e.g. csdm / public / zombie]

Additionally, please provide list of AMX Mod X plugins: ``amxx plugins`` and list of Metamod plugins: ``meta plugins``.

**Additional context**

**Comment by Vladislav4KZ** [comment]
You didn't even write the name of the map where this happens. How to check it? This issue has been going on for 2 years now, and there is still no detailed information.

**Comment by Vladislav4KZ** [comment]
Otherwise, I will close this issue as stale.

You did not specify how to reproduce bugs, and the name of the map.
