### ISSUE TITLE
The shooting at the very beginning of the round

### ISSUE THREAD

**Issue by stambeto2006** [yapb/yapb#217]
**Describe the bug**
@jeefo Is it expected that the shooting at the very beginning of the round will be fixed soon, when the bots are shot at each other, as they are in the same team, because this thing leads to a slight lag.

**Environment details:**
 - OS: [windows 10]
 - Engine: [rehlds-dist-3.8.0.702 / Exe build: 18:22:55 Nov  8 2020 (2402)]
 - GameDLL: [regamedll 5.19.0.486]
 - Metamod: [metamod-r]
 - Bot Version: [v 4.2.597]
 - Game mode: [zombie plague]

**Comment by jeefo** [comment]
Can you provide video?

Thanks.

**Comment by stambeto2006** [comment]
View the .dem file ->  https://dox.abv.bg/download?id=82cf0c9cce

@jeefo There is another problem that when humans have dropped their weapons on the ground and when zombies have to kill humans, they always do. Well, they just stand by the weapons on the ground until the round is over.

**Comment by stambeto2006** [comment]
Maybe with this plugin it makes things a little easier before the round and the countdown has started.
https://forums.alliedmods.net/showthread.php?t=158255

**Comment by stambeto2006** [comment]
@jeefo See in this demo how bots at a certain time as if they are not active and frozen, do not take any action!
https://dox.abv.bg/download?id=ce6c03f000
