### ISSUE TITLE
Not compatible with sxe anti cheating

### ISSUE THREAD

**Issue by qq578023708** [yapb/yapb#222]
**Describe the bug**
server opens sxe anti cheating, This robot doesn't install bombs
The robot has reached the target point on the map, but C4 will not be installed

**Expected behavior**

**Video**
If it's problem with AI behaviour, add video to help explain your problem.

**Environment details:**
 - OS: [server2008R2]
 - Engine: [rehlds 3.8.0.702]
 - GameDLL: [regamedll 5.18.0.479]
 - Metamod: [metamod-p]
 - Bot Version: [e.g. 4.2.598]
 - Game mode: [ public]

Additionally, please provide list of AMX Mod X plugins: ``amxx plugins`` and list of Metamod plugins: ``meta plugins``.
amxmodx 1.9
sxe inject 17.1
aguard 1.6

**Additional context**

**Comment by jeefo** [comment]
Not related to bot.
