### ISSUE TITLE
[Request] Add a command line option to yapb.cfg

### ISSUE THREAD

**Issue by regener** [yapb/yapb#228]
Add an optional command line function to the yapb.cfg.
This would allow us to put cvars there to auto execute them.

Example:
yb_auto_commands "mp_timelimit 30; mp_roundtime 30; mp_maxrounds 0"

This would allow enough time to waypoint a map without the round or the map ending.

**Comment by jeefo** [comment]
Well these are automatically set, when graph edit is on.
