### ISSUE TITLE
Bots have the ability to break and pick up objects from the ground

### ISSUE THREAD

**Issue by stambeto2006** [yapb/yapb#230]
Can you make the bots of zombie mods have the skills to be able to break objects on the ground and then be able to pick them up?

**Comment by Hedgefog** [comment]
Set `yb_pickup_custom_items` to `1` and bots will pickup any items with "item_" in the entity name

**Comment by stambeto2006** [comment]
I tried and it doesn't help!

**Comment by stambeto2006** [comment]
@jeefo Can bots be made to break doors or windows during a game?

**Comment by stambeto2006** [comment]
@jeefo Is there a solution because the bots are constantly standing near fallen weapons until the round is over?

**Comment by jeefo** [comment]
I believe issues should be fixed in current master.
