### ISSUE TITLE
Bots not able to use nades and bot count won't show up in Search Servers Window

### ISSUE THREAD

**Issue by shubhambanekar** [yapb/yapb#232]
Hi, I just used YaPb and found it interesting on my Condition Zero (Linux) Server, but I'm having few problems. I have GunGame(CSDM Type) mod installed and when there is a nade round the bots don't use the nade and instead use a knife. When at night there are sometimes no real players on the server, the map isn't changed because after the nade round there is a knife round, after which the map has to be changed automatically, but it doesn't happen as bots don't use the grenade.
Secondly, when I search for my server in the Server Browser Window and If I have 6 bots, when there are no players, it should show 6/32 players playing, but it shows zero, even after turning on the yb_enable_query_hook 1, I'm using the latest YAPB version.

**Environment details:**
 - OS: [linux ununtu 20.04.2 LTS]
 - Engine: [rehlds 3.8.0.715]
 - GameDLL: [regamedll 5.20.0.492]
 - Metamod: [Metamod v1.21.1-am]
 - Bot Version: [4.2.598]
 - Game mode: [gungame 213c]
 - AMX Version: [AMX Mod X 1.9.0.5271]

Meta Mod Plugins
Currently loaded plugins:
      description      stat pend  file              vers      src  load  unlod
 [ 1] Reunion          RUN   -    reunion_mm_i386.  v0.1.92d  ini  Start Never
 [ 2] ReSemiclip       RUN   -    resemiclip_mm_i3  v2.3.9    ini  Chlvl ANY
 [ 3] AMX Mod X        RUN   -    amxmodx_mm_i386.  v1.9.0.5  ini  Start ANY
 [ 4] YaPB             RUN   -    yapb.so           v4.2.598  ini  Chlvl ANY
 [ 5] Fun              RUN   -    fun_amxx_i386.so  v1.9.0.5  pl3  ANY   ANY
 [ 6] FakeMeta         RUN   -    fakemeta_amxx_i3  v1.9.0.5  pl3  ANY   ANY
 [ 7] GeoIP            RUN   -    geoip_amxx_i386.  v1.9.0.5  pl3  ANY   ANY
 [ 8] CStrike          RUN   -    cstrike_amxx_i38  v1.9.0.5  pl3  ANY   ANY
 [ 9] CSX              RUN   -    csx_amxx_i386.so  v1.9.0.5  pl3  ANY   ANY
 [10] Ham Sandwich     RUN   -    hamsandwich_amxx  v1.9.0.5  pl3  ANY   ANY
 [11] ReAPI            RUN   -    reapi_amxx_i386.  v5.19.0.  pl3  ANY   Never
 [12] MySQL            RUN   -    mysql_amxx_i386.  v1.9.0.5  pl3  ANY   ANY
 [13] Engine           RUN   -    engine_amxx_i386  v1.9.0.5  pl3  ANY   ANY
13 plugins, 13 running

AMX Mod Plugins
gungame.amxx
abd.amxx
admin_spec_esp.amxx
amx_gore_ultimate.amxx
adminhierarchy.amxx
colored_round_money.amxx
cs_war.amxx
afk_manager_1-8-3.amxx
KnifeKill.amxx
crx_gospec.amxx
crx_chatmanager.amxx
crx_resetscore.amxx
AmxxTag.amxx
vampire.amxx
gamenamechanger.amxx
kill_assist.amxx
hlstatsx_commands_cstrike.amxx
reconnect_features.amxx
crx_advmute.amxx
ad_manager.amxx
multijump.amxx

**Comment by jeefo** [comment]
yb_enable_query_hook  is not working with steam now. only for some sites like game tracker, sadly.
