### ISSUE TITLE
Bot Spawn Bug YaPB 4.2.598 Linux 

### ISSUE THREAD

**Issue by Infamous2017** [yapb/yapb#234]
If a round starts and the bot dies then it respawns immediately. That shouldn't really be the case. My zombie server is set up so that bots and players spawn after 31 and 47 seconds. So if the bot spawns straight away and then dies again. THEN it will only spawn again after 47 seconds. So this is a definite bug for me. Please fix it. Last version Linux. 

YaPB 4.2.598

**Comment by jeefo** [comment]
Bots doesn't control it's spawn/respawn process.
