### ISSUE TITLE
YaPB causes Linux CS couldn't exit correctly

### ISSUE THREAD

**Issue by KilobY73** [yapb/yapb#241]
**Describe the bug**
When I use YaPB 4.2.598, I can never exit the game normally. Everytime I type "quit" in console or click "exit" in main menu, the game ends but doesn't exit, leaving a black window with my mouse cursor captured. What I can only do is to change a tty and kill the process.

**Expected behavior**
The game exits normally like what it does under Windows, without any problems.

**Environment details:**
 - OS: Arch Linux/Linux Debian 10.9
 - Engine: vanilla 8684
 - GameDLL: yapb.so
 - Metamod: without metamod
 - Bot Version: 4.2.598
 - Game mode: public

**Additional context**
I've changed several distros and they all have the same problem.

**Comment by jeefo** [comment]
Verify in 4.2.601
