### ISSUE TITLE
Можно ли исправить 3 поведения?

### ISSUE THREAD

**Issue by ZGBarmaleyPetrovich** [yapb/yapb#242]
Привет.

Можно ли исправить три поведения ботов:
 - на сервере используется resemiclip и боты стоят в очереди на подъем на лестницу. Можно ли сделать, чтобы они не ждали друг друга а все сразу поднимались (к примеру параметром yb_semiclip)
 - если у бота имеется только нож, то он бывает двигается хаотично, даже убегая от цели. Можно ли сделать, чтобы они всегда бежал на игрока и не убегал от него?
 - Боты в 95% случаев используют короткий маршрут до цели (случай когда все противники в одном месте сидят) , идут почти всегда одним и тем же путем, хотя до места противников есть малость длиннее путь. Можно ли немного скорректировать поиск пути до цели?

Если потребуется, могу снять видео с примерами.
Был бы очень признателен за эти исправления. 
Заранее спасибо.

**Comment by ForeskinJohn** [comment]
Just played a game on de_mirage, and another on de_cpl_strike and bots on T went apartments route to B site, they did this for 4 different rounds too, waypoints must be fixed now.

**Comment by ZGBarmaleyPetrovich** [comment]
> Just played a game on de_mirage, and another on de_cpl_strike and bots on T went apartments route to B site, they did this for 4 different rounds too, waypoints must be fixed now.

It's non standard gameplay (without hostages / bomb), all players in one place, bots try kill them. I think that bots react to shooting and run to the action on a short path. Waypoints not broken

**Comment by ZGBarmaleyPetrovich** [comment]
Вот бы было здорово еще научить ботов кидать гранаты / слеповые почаще (к примеру пока одни отстреливаются, другие кидали бы гранаты).

**Comment by ZGBarmaleyPetrovich** [comment]
Jeefo, 
Не знаю куда писать, сервер с версией 4.2.610 не запускается на WIN. 
С предыдущей версией 4.2.602 проблем с запуском нет.

**Comment by jeefo** [comment]
Привет, обновить на 622, я в основном на линуксе тестирую сейчас. Мой косяк)

**Comment by ZGBarmaleyPetrovich** [comment]
> Привет, обновить на 622, я в основном на линуксе тестирую сейчас. Мой косяк)

На этой версии завелось) Спасибо)
Боты все равно ходят по одному пути :( В игре использую personality = rusher, но попробовал personality = random, результат тот же :(
Вот пример https://youtu.be/Qt0j9H2CmF8
Можешь подсказать, почему они все идут на шум стрельбы? Почему не идут через другой вход.

**Comment by jeefo** [comment]
Это cs_italy_cz?

**Comment by ZGBarmaleyPetrovich** [comment]
Да, но waypoint'ы сам делаю

**Comment by jeefo** [comment]
Со штатным также?

**Comment by jeefo** [comment]
> > Привет, обновить на 622, я в основном на линуксе тестирую сейчас. Мой косяк)
> 
> На этой версии завелось) Спасибо)
> Боты все равно ходят по одному пути :( В игре использую personality = rusher, но попробовал personality = random, результат тот же :(
> Вот пример https://youtu.be/Qt0j9H2CmF8
> Можешь подсказать, почему они все идут на шум стрельбы? Почему не идут через другой вход.

https://github.com/yapb/yapb/actions/runs/1249000545

С этим билдом стало лучше?

**Comment by ZGBarmaleyPetrovich** [comment]
> > > Привет, обновить на 622, я в основном на линуксе тестирую сейчас. Мой косяк)
> > 
> > 
> > На этой версии завелось) Спасибо)
> > Боты все равно ходят по одному пути :( В игре использую personality = rusher, но попробовал personality = random, результат тот же :(
> > Вот пример https://youtu.be/Qt0j9H2CmF8
> > Можешь подсказать, почему они все идут на шум стрельбы? Почему не идут через другой вход.
> 
> https://github.com/yapb/yapb/actions/runs/1249000545
> 
> С этим билдом стало лучше?

Поставил 622, ситуация почти такая же - когда боты в начале все бегут, из 30 ~ 2 бота забегают в резервный вход. Но как только начинается стрельба, все боты бегут через основной вход. 
Попробовал вейпоинты от cs_italy_cz ситуация такая же :(
personality = random

**Comment by jeefo** [comment]
понял, буду смотреть

**Comment by ZGBarmaleyPetrovich** [comment]
Спасибо)

**Comment by ZGBarmaleyPetrovich** [comment]
Привет. Расскажи пож-та про параметр yb_danger_factor[min/max]. В исходниках не нашел про него упоминания. И на вызовы не отображаются текущие значения.

**Comment by Vladislav4KZ** [comment]
Интересно, вроде issue создан в 2021 году а в видео заметно что используется старая версия YaPB. Это заметно по старому русскому переводу. Ты точно пользовался последней версией YaPB? Потому-что обновление перевода было аж в 2019 году.

**Comment by jeefo** [comment]
The problem should be resolved in latest revisions. If not, please open a new issue.
