### ISSUE TITLE
GUNGAME  Mode Avalance. Боты очень редко используют HE гранату.

### ISSUE THREAD

**Issue by wood-grouse** [yapb/yapb#243]
Здравствуйте.
На уровне граната (Гангейм мод) боты ооооочень редко используют гранаты. Прям приходится минут по 10 ждать, когда кто-то из них ее кинет))
Есть ли возможность добавить приоритет по гранатам?
Те сейчас на уровне, когда нужно подорвать с гранаты, ботам выдается в придачу с хе-шкой глок+нож.
Так они предпочитают использовать глок, а если глок стрипнуть, то нож, но никак не хе-гранату))
Нож скипнуть не могу, тк на последнем уровне нужно с ножа зарезать. (кфг прикрепил)
С Pod ботами таких проблем не наблюдалось.

[yapb.txt](https://github.com/yapb/yapb/files/7026169/yapb.txt)

**Comment by Vladislav4KZ** [comment]
Закрываю, в связи с дублированием этой issue: https://github.com/yapb/yapb/issues/414

Я оставляю новую issue вместо этой, так как там шло обсуждение этой проблемы.
