### ISSUE TITLE
Windows XP bots not loading with metamod (using files from .zip) and .exe installer won't even start.

### ISSUE THREAD

**Issue by idchlife** [yapb/yapb#244]
**Describe the bug**

CS 1.6 v19 Windows XP not working. Metamod says status BADF (I don't know how to see the full description) for .dll file.
.exe installer does not start.

**Expected behavior**
Bots to work.

**Video**
If it's problem with AI behaviour, add video to help explain your problem.

**Environment details:**
 - OS: Windows XP SP3 (I installed it specifically to play old games, I have modern systems :D )
 - Engine: [e.g. rehlds 3.8.0.702 / vanilla 8684]
 - GameDLL: [e.g. regamedll 5.18.0.479 / vanilla]
 - Metamod: [e.g. metamod-r / metamod-p / metamod]
 - Bot Version: latest
 - Game mode: classic

Additionally, please provide list of AMX Mod X plugins: ``amxx plugins`` and list of Metamod plugins: ``meta plugins``.

**Additional context**

Hey... I wonder if it's even possible now to install bots in Windows XP? I know they are modern, but it would be cool to play with them on Windows XP machine :D

**Comment by jeefo** [comment]
Hi. I will make changes to be loadable at windows xp.

**Comment by jeefo** [comment]
@idchlife can you verify if this binary works: https://fsync.jeefo.net/f/e421b0cff5a04e4b9c72/

has no XP installation anywhere...

**Comment by jeefo** [comment]
Verify in 4.2.601

**Comment by idchlife** [comment]
@jeefo it works. Thanks! <3

**Comment by dimaspaf14** [comment]
Hi @jeefo, does the new version still works on win xp?

**Comment by jeefo** [comment]
yes
