### ISSUE TITLE
HLDS Crash with NO ERRORS

### ISSUE THREAD

**Issue by feren02** [yapb/yapb#250]
**Describe the bug**
I use YapB in my server, however it makes hlds stop like "hang".
No errors or logs, just that HLDS stops. I can Exit it and Start smoothly again.

**Expected behavior**
Smooth 24/7 not crashing HLDS.

**Video**
N/A

**Environment details:**
 - OS: windows 10
 - Engine: HLDS
 - GameDLL: hl.dll
 - Metamod: metamod
 - Bot Version: YapB 4.2.623
 - Game mode: PUB

Additionally, please provide list of AMX Mod X plugins: ``amxx plugins`` and list of Metamod plugins: ``meta plugins``.

Currently loaded plugins:
       name                    version     author            file             status
 [  1] Admin Base              1.8.2       AMXX Dev Team     admin.amxx       running
 [  2] Admin Commands          1.8.2       AMXX Dev Team     admincmd.amxx    running
 [  3] Slots Reservation       1.8.2       AMXX Dev Team     adminslots.amxx  running
 [  4] Menus Front-End         1.8.2       AMXX Dev Team     menufront.amxx   running
 [  5] Commands Menu           1.8.2       AMXX Dev Team     cmdmenu.amxx     running
 [  6] Players Menu            1.8.2       AMXX Dev Team     plmenu.amxx      running
 [  7] Maps Menu               1.8.2       AMXX Dev Team     mapsmenu.amxx    running
 [  8] Plugin Menu             1.8.2       AMXX Dev Team     pluginmenu.amxx  running
 [  9] Admin Chat              1.8.2       AMXX Dev Team     adminchat.amxx   running
 [ 10] Anti Flood              1.8.2       AMXX Dev Team     antiflood.amxx   running
 [ 11] Admin Votes             1.8.2       AMXX Dev Team     adminvote.amxx   running
 [ 12] NextMap                 1.8.2       AMXX Dev Team     nextmap.amxx     running
 [ 13] TimeLeft                1.8.2       AMXX Dev Team     timeleft.amxx    running
 [ 14] Pause Plugins           1.8.2       AMXX Dev Team     pausecfg.amxx    running
 [ 15] Stats Configuration     1.8.2       AMXX Dev Team     statscfg.amxx    running
 [ 16] Restrict Weapons        1.8.2       AMXX Dev Team     restmenu.amxx    running
 [ 17] StatsX                  1.8.2       AMXX Dev Team     statsx.amxx      running
 [ 18] Ultimate Sounds         1.7         Dizzy / Bmann_42  ultimate_sounds  running
 [ 19] Vote Ban                1.0         Alka              voteban.amxx     running
 [ 20] Admin Check             1.51        OneEyed           admin_check.amx  running
 [ 21] GHW Connect Messages    1.1         GHW_Chronic       GHW_connect.amx  running
 [ 22] unknown                 unknown     unknown           tunnel.amxx      running
 [ 23] Autoresponder/Advertis  0.5         MaximusBrood      ad_manager.amxx  running
 [ 24] Admin Model Menu        1.0         Dimision          admodelsCT.amxx  running
 [ 25] Admin Model Menu        1.0         Dimision          admodelsT.amxx   running
 [ 26] Admin Check             1.51        OneEyed           vip_check.amxx   running
 [ 27] Auto Round Restart      1.6         SubStream         autorr.amxx      running
 [ 28] Ping Faker              1.5a        MeRcyLeZZ         pingfaker.amxx   running
 [ 29] Server Models           1.0         feruchio          finalweapon.amx  running
 [ 30] Show Players            1.0         NapoleoN#         dailyrestart.amxx  running
 [ 31] ANTI Change Name        0.1beta     F.E.A.R.&Many     nochangename.amxx  running
 [ 32] botespectador           1.0         _|Polimpo4|_      PMN_BOT_SPEC.amxx running
 
 ----------
 
 Currently loaded plugins:
      description      stat pend  file              vers      src  load  unlod
 [ 1] AMX Mod X        RUN   -    amxmodx_mm.dll    v1.8.2    ini  Start ANY
 [ 2] STATSME          RUN   -    statsme_mm.dll    v2.8.3    ini  Chlvl Chlvl
 [ 3] Booster          RUN   -    booster_mm.dll    v2.40     ini  Chlvl Pause
 [ 4] HLGuard          RUN   -    hlguard_mm.dll    v1.9.n10  ini  Chlvl Chlvl
 [ 5] YaPB             RUN   -    yapb.dll          v4.2.623  ini  Chlvl ANY
 [ 6] CStrike          RUN   -    cstrike_amxx.dll  v1.8.2     pl1  ANY   ANY
 [ 7] CSX              RUN   -    csx_amxx.dll      v1.8.2    pl1  ANY   ANY
 [ 8] FakeMeta         RUN   -    fakemeta_amxx.dl  v1.8.2    pl1  ANY   ANY
 [ 9] Ham Sandwich     RUN   -    hamsandwich_amxx  v1.8.2    pl1  ANY   ANY
 [10] Fun              RUN   -    fun_amxx.dll      v1.8.2    pl1  ANY   ANY
 [11] Engine           RUN   -    engine_amxx.dll   v1.8.2    pl1  ANY   ANY

**Additional context**
Happening with PLAYERS connected or even WHEN NO PLAYERS are connected.
HLDS just stops with no error.

Looking forward!

**Comment by yuusuke09** [comment]
Which version of metamod do you use?
I think using Metamod v1.21.1-am could be more stable than metamod-p.

**Comment by jeefo** [comment]
https://sync.jeefo.net/u/d/7e42de8188874631b290/

you can upload here. it will be private.
