### ISSUE TITLE
Can't strafe as well as podbots

### ISSUE THREAD

**Issue by commandcobra7** [yapb/yapb#253]
Bots can't dodge well in combat mode they stay in place all the time attackMovement() doesn't work well

**Comment by commandcobra7** [comment]
Movement and targeting issues #205

**Comment by commandcobra7** [comment]
Movement and targeting issues #205
6 more issues in progress only 1 issue fixed

**Comment by commandcobra7** [comment]
Movement and targeting issues #205
6 more issues in progress only 1 issue fixed

**Comment by jeefo** [comment]
I believe it's would be nice to provide PR for this)

**Comment by commandcobra7** [comment]
make sure the bots are working fine to avoid getting hit like podbot_mm


jeefo ***@***.***>, 16 Kas 2021 Sal, 15:35 tarihinde şunu
yazdı:
