### ISSUE TITLE
Add zombie plague compatibility like sypb bots

### ISSUE THREAD

**Issue by commandcobra7** [yapb/yapb#254]
**Describe the bug**

**Expected behavior**

**Video**
If it's problem with AI behaviour, add video to help explain your problem.

**Environment details:**
 - OS: [e.g. windows 10 / linux debian 10.4]
 - Engine: [e.g. rehlds 3.8.0.702 / vanilla 8684]
 - GameDLL: [e.g. regamedll 5.18.0.479 / vanilla]
 - Metamod: [e.g. metamod-r / metamod-p / metamod]
 - Bot Version: [e.g. 4.1.566]
 - Game mode: [e.g. csdm / public / zombie]

Additionally, please provide list of AMX Mod X plugins: ``amxx plugins`` and list of Metamod plugins: ``meta plugins``.

**Additional context**

**Comment by jeefo** [comment]
You'd better to use sypb for such mods. Basic support is there, but i don't ever player ZM, so i cant' help here.

**Comment by commandcobra7** [comment]
Actually, I don't want much from you, I just want them to not shoot each other at the beginning of the round and add functionality like avoiding zombies, that's all.
