### ISSUE TITLE
Add ''yb_aimbot'' function as in sypb bots

### ISSUE THREAD

**Issue by commandcobra7** [yapb/yapb#257]
**Describe the bug**

**Expected behavior**

**Video**
If it's problem with AI behaviour, add video to help explain your problem.

**Environment details:**
 - OS: [e.g. windows 10 / linux debian 10.4]
 - Engine: [e.g. rehlds 3.8.0.702 / vanilla 8684]
 - GameDLL: [e.g. regamedll 5.18.0.479 / vanilla]
 - Metamod: [e.g. metamod-r / metamod-p / metamod]
 - Bot Version: [e.g. 4.1.566]
 - Game mode: [e.g. csdm / public / zombie]

Additionally, please provide list of AMX Mod X plugins: ``amxx plugins`` and list of Metamod plugins: ``meta plugins``.

**Additional context**

**Comment by jeefo** [comment]
yb_whose_your_daddy 1

**Comment by commandcobra7** [comment]
thank you anyway
