### ISSUE TITLE
Bots aim and shoot the sniper very fast

### ISSUE THREAD

**Issue by commandcobra7** [yapb/yapb#258]
**Describe the bug**

**Expected behavior**

**Video**
If it's problem with AI behaviour, add video to help explain your problem.

**Environment details:**
 - OS: [e.g. windows 10 / linux debian 10.4]
 - Engine: [e.g. rehlds 3.8.0.702 / vanilla 8684]
 - GameDLL: [e.g. regamedll 5.18.0.479 / vanilla]
 - Metamod: [e.g. metamod-r / metamod-p / metamod]
 - Bot Version: [e.g. 4.1.566]
 - Game mode: [e.g. csdm / public / zombie]

Additionally, please provide list of AMX Mod X plugins: ``amxx plugins`` and list of Metamod plugins: ``meta plugins``.

**Additional context**

**Comment by ForeskinJohn** [comment]
Im not sure if i consider this a bug, some bots are faster than others with scoped rifles, it really simulates the flick reflex some people use to play the AWP or Scout, this is a feature in my book

**Comment by commandcobra7** [comment]
I think this is the problem. They use the sniper fast and they don't hit. The firing seconds should be increased. @ForeskinJohn @
