### ISSUE TITLE
Bots do not use parachutes when falling from a height that's why they die when they fall

### ISSUE THREAD

**Issue by commandcobra7** [yapb/yapb#265]
**Describe the bug**

**Expected behavior**

**Video**
If it's problem with AI behaviour, add video to help explain your problem.

**Environment details:**
 - OS: [e.g. windows 10 / linux debian 10.4]
 - Engine: [e.g. rehlds 3.8.0.702 / vanilla 8684]
 - GameDLL: [e.g. regamedll 5.18.0.479 / vanilla]
 - Metamod: [e.g. metamod-r / metamod-p / metamod]
 - Bot Version: [e.g. 4.1.566]
 - Game mode: [e.g. csdm / public / zombie]

Additionally, please provide list of AMX Mod X plugins: ``amxx plugins`` and list of Metamod plugins: ``meta plugins``.

**Additional context**

**Comment by yuusuke09** [comment]
addons\yapb\conf\custom.cfg
=======================
; Custon cvar name for parachute handling, there are all the different plugins that
; handles parachute (AMX Parachute, AMX Parachute Lite, etc..), you can specify needed
; cvar here.
;
AMXParachuteCvar = xxxxxxxxxxxxxxx
