### ISSUE TITLE
Вызываются радиосообщения когда переходишь по пунктам в меню YaPB

### ISSUE THREAD

**Issue by Vladislav4KZ** [yapb/yapb#271]
Когда я использовал радиокоманды "кнопки Z, X или C и цифра для выбора радиокоманды", то после этого при выборе любого пункта меню ботов YaPB проигрывается радиокоманда

https://www.youtube.com/watch?v=owuJcvy6e_4

**Детали окружения:**
 - OС: Windows 10 Pro x64 21H2
 - Движок: оригинальный 8684 билд
 - GameDLL: Везде, и с обычной и с ReGameDLL
 - Metamod: не используется
 - Версия бота: 4.2.627 (ручная сборка с Visual Studio)
 - Режим игры: любой

**Comment by jeefo** [comment]
, случаем не при пересечении buyzone?

**Comment by Vladislav4KZ** [comment]
> , случаем не при пересечении buyzone?

Нет, зона покупки тут не причём

**Comment by PRinceBhai** [comment]
Also happens with me. I thought this happened when you have a Radio Menu open but then you press a key to open the YaPB menu and then if you press any numerical key you get radio commands.
