### ISSUE TITLE
yb_radio_mode 0 is not disable radio commands

### ISSUE THREAD

**Issue by stambeto2006** [yapb/yapb#272]
**Describe the bug**
Given that I have blocked the bots from using radio commands and chat, when starting a new round, the sound is heard every time that they use radio commands without writing anything in the chat on their part.
yb_radio_mode 0

**Environment details:**
 - OS: [e.g. windows 10]
 - Engine: [e.g. rehlds 3.11.0.767 ]
 - AMX Mod X [1.10.0.5460 ]
 - GameDLL: [e.g. ReGameDLL version: 5.21.0.547-dev]
 - Metamod: [e.g. Metamod-r v1.3.0.128]
 - Bot Version: [e.g. v4.2.623]
 - Game mode: [e.g. zombie]

**Comment by jeefo** [comment]
Sorry, can't reproduce. Can you record a video?

**Comment by stambeto2006** [comment]
@jeefo The demo shows how they use radio commands at the beginning of each round, a green exclamation mark can be seen above the person and the sound can be heard without captions in the chat!

- Demo 1 ---- https://www.mediafire.com/file/klypxunubg68kpq/radio.dem/file
- Demo 2 ---- https://www.mediafire.com/file/lvbutl1uabjs9jp/radio3.dem/file

Given that you have banned all variants of bots to use the radio for sound and messages, but the demo shows how they get a radio command for each round at the beginning.
//  If '0', radio and chatter is disabled.

**Comment by jeefo** [comment]
Sorry, i c an't play demos. Too much resources missing. Video ? or server IP to get the resources.

**Comment by stambeto2006** [comment]
@jeefo Try now?
Video ----> https://www.mediafire.com/file/br5f1qeueg4y9is/radio2.avi/file

**Comment by jeefo** [comment]
yup, this has nothing with bots. this ratio messages a played by gamedll on player automatically.

**Comment by stambeto2006** [comment]
Without them, how can this thing not exist, only when bots are running and they use commands and this comes out!

**Comment by jeefo** [comment]
It's gamedll feature. Bots can't control that.

Refer:
https://github.com/s1lentq/ReGameDLL_CS/blob/a54abba88f3d8b9cdf5b87769af24b699b00e677/regamedll/dlls/multiplay_gamerules.cpp#L2746

https://github.com/s1lentq/ReGameDLL_CS/blob/a54abba88f3d8b9cdf5b87769af24b699b00e677/regamedll/dlls/multiplay_gamerules.cpp#L2799
