### ISSUE TITLE
[Feature Request] Possibility of Bot2Player Function in YAPB?

### ISSUE THREAD

**Issue by PRinceBhai** [yapb/yapb#275]
Just Like CS:GO has this functionality.

There is a [SourceMod plugin](https://forums.alliedmods.net/showthread.php?p=1950871) for CS:S, that actually works even with the Current Version.

But CS 1.6 doesn't even have bots and CZ isn't much popular so I wanted to ask If it would be possible to include this feature in YAPB, for a Bot to be Replaced or Controlled by a Real Player (preferably an Admin, Server Owner or whitelisted Players that can control these bots after they die).

Thanks.

**Comment by jeefo** [comment]
hello. I was thinking about this some time ago, but this will require
memory hacking with gamedll (we're targeting vanilla gamedll not regamedll
by default). so it's not possible for bots as we're supporting ancient game
engines and CS versions from beta 7.0 on multiple platforms.

you can try to use attached amxx plugin(requires a dozen of re* products)
from @Vaqtincha.

**Comment by PRinceBhai** [comment]
Thank you so much for sharing that jeefo, it works like a Charm even with silentq's reGameDll. YApB also works fine on it.

BTW, I wanted to ask this graph related question, I'm trying to make some Graphs for aim_, fy_ and gg_ maps but how should I add a Goal Waypoint as there are no objectives in these maps and thus I can't upload. Please let me know what's the workaround. Thank you so much for your work. :D

**Comment by jeefo** [comment]
you should put the goal on the center of such maps.

**Comment by Drevny13** [comment]
hi can you upload compiled plugin here?

**Comment by PRinceBhai** [comment]
> hi can you upload compiled plugin here?

Just copy the sma to "scripting" folder and then drag & drop that file on compile.exe and you'll get the plugin in the "Compiled" folder.

My compiled plugin might not work for you because of difference in AmX versions.

**Comment by Drevny13** [comment]
to play as bot need press N ?

**Comment by PRinceBhai** [comment]
> to play as bot need press N ?

Yes.

**Comment by Drevny13** [comment]
found this version also, latest with fixes, but not work for me, can you look code?
[BotFeatures.zip](https://github.com/yapb/yapb/files/7859903/BotFeatures.zip)

**Comment by PRinceBhai** [comment]
> found this version also, latest with fixes, but not work for me, can you look code? [BotFeatures.zip](https://github.com/yapb/yapb/files/7859903/BotFeatures.zip)

I just compiled it and it worked, it's even better than the previous one jeefo linked but this seems to have an older version specified in the code?

The one jeefo linked was 0.0.5 and this one is 0.0.3fix2 ?

IDK that's confusing but it works, what problem are you encountering? Does it not load or does it not work, be a bit specific. Also where did you find this? This is not on available Vaqtincha's Repository.

**Comment by Vaqtincha** [comment]
Hi, last version https://goldsrc.ru/resources/262/

**Comment by PRinceBhai** [comment]
> Hi, last version 0.9 https://goldsrc.ru/resources/262/

Thank you so much, Vaqtincha! You rock!

**Comment by Vaqtincha** [comment]
@PRinceBhai Found a small bug that can crash the server. I will fix it.

**Comment by PRinceBhai** [comment]
@Vaqtincha Have you fixed it? Also can you please Post this Script on Dev-CS.ru or another forum? Because I can't seem to register on goldsrc.ru, I've registered my Account but I never got the Confirmation E-Mail in my Mail, I've also checked the Spam folder, but it's not there. I even contacted support but also no reply from their either.

So whenever you get some free time please attach the plugin here or post it on another forum.  Thanks.

**Comment by Vaqtincha** [comment]
@PRinceBhai Okay. About the bug reported only one person (who had Yapb). Although I have had this plugin working for years (I only have csbot).

**Comment by PRinceBhai** [comment]
@Vaqtincha That's not a problem, even the old version still works without any flaws but can you please post the script here? I can't download it from goldsrc.ru
Thanks :)

**Comment by Drevny13** [comment]
> @PRinceBhai Okay. About the bug reported only one person (who had Yapb). Although I have had this plugin working for years (I only have csbot).

i try with this server windows with yapb also crash

[BotFeatures.zip](https://github.com/yapb/yapb/files/7892336/BotFeatures.zip)
