### ISSUE TITLE
[BUG?] YApB not generating graph from pwf or loading pwf.

### ISSUE THREAD

**Issue by PRinceBhai** [yapb/yapb#276]
I have a `pwf `of a map in the `yapb/data` folder but yapb doesn't detect it. I've tried using commands `yb graph check`,` yb graph load` but no avail I tried pasting that` pwf` in `yapb/data/graph` folder even renaming it to graph but of course that didn't work either it can't read the "magic" of that graph( pwf).

**Comment by jeefo** [comment]
it should be in yapb/data/pwf folder.

**Comment by PRinceBhai** [comment]
> it should be in yapb/data/pwf folder.

Damn, I don't know how I missed that folder lol. Thanks.
