### ISSUE TITLE
Боты пишут сообщения в чат связанные с установкой бомбы, даже на тех картах где её нет

### ISSUE THREAD

**Issue by Vladislav4KZ** [yapb/yapb#281]
Старый баг, по моему тянется ещё с версии 4.0 наверно.

Когда бот достигает целевой точки на любой карте, они пишут а чат что-то типа "Defuse kit у меня", и т.д. как будто кто-то поставил бомбу. Также ещё могут всплывать фразы у ботов в голосовом чате, что они собираются ставить бомбу или идут кемперить на месте закладки бомбы.

Это всё проявляется на всех картах, даже там где нет сценария закладки бомбы.

**Comment by jeefo** [comment]
Saychat именно? странно, посмотрю.

**Comment by Vladislav4KZ** [comment]
> Saychat именно? странно, посмотрю.

Не только он, я же написал что боты ещё говорят голосом что собираются ставить бомбу/охранять место закладки

**Comment by Vladislav4KZ** [comment]
Теперь понятно почему появлялись такие сообщения в текстовом чате.

Вот только не пойму почему в голосовом чате они говорят про бомбу когда её нет.
