### ISSUE TITLE
Квар yb_debug 1 не работает

### ISSUE THREAD

**Issue by Vladislav4KZ** [yapb/yapb#282]
У квара yb_debug есть 4 значения как сообщает консоль.
При вводе квара yb_debug 1 или yb_debug 2 отладочная информация не появляется. Появляется только при вводе yb_debug 3 и yb_debug 4. В чём разница значений 3 и 4? Я не заметил отличия

**Детали окружения:**
 - ОС: Windows 10 Pro x64 21H2
 - Движок: Оригинальный 8684
 - GameDLL: Оригинальный
 - Metamod: нет
 - Версия бота: 4.2.647 (с GitHub Actions)
 - Режим игры: Обычный

**Comment by jeefo** [comment]
1,2 под текстовые сообщения, их нет в коде) было когда-то но все вырезано.

минимальный сейчас 3,4 (что выше 3, то debug-overlay).
