### ISSUE TITLE
Можно сделать так чтобы пути вэйпоинтов не прокладывались через CLIP браши?

### ISSUE THREAD

**Issue by Vladislav4KZ** [yapb/yapb#285]
Допустим на карте есть какая-то модель, чтобы не проходить сквозь неё, её покрыли брашем с текстурой CLIP (невидимая стена, через которую невозможно пройти, но можно кидать гранаты)

Если был поставлен вэйпоинт за этой "стеной" и перед ней, то оба вэйпоинта соединятся между собой.

**Comment by jeefo** [comment]
Честно говоря хз, есть пример карты ? что говорит движковый Traceline по поводу таких объектов ?

**Comment by Vladislav4KZ** [comment]
> Честно говоря хз, есть пример карты ?

Карта de_expulsion_final, на крыше где место закладки бомбы, стоят ящики с радиоактивными веществами.

Когда ставил целевые точки, они соединялись с другими точками за этими ящиками

**Comment by Vladislav4KZ** [comment]
Вот это место:
![de_expulsion_final0000.png](https://user-images.githubusercontent.com/22411953/150631250-ebc6dcd1-be9f-4f61-be3f-32e19b17987f.png)

**Comment by PRinceBhai** [comment]
Just delete the path that you don't need. If there's a path that goes through the model then deleting it would be sufficient.

**Comment by jeefo** [comment]
So, i can't do much on that one, it'll require manual parsing bsp-tree, which is not good idea for a bot...
