### ISSUE TITLE
Боты стреляют по окнам на карте cs_backalley

### ISSUE THREAD

**Issue by Vladislav4KZ** [yapb/yapb#288]
**Описание бага**
На карте cs_backalley боты пытаются сломать стёкла и деревяшки на окнах, но у них получается только сломать стёкла.

И так они стреляют до тех пор пока не кончатся патроны.

Если патроны кончились, боты просто стоят на месте и ничего не делают весь раунд.

**Видео**
https://youtu.be/Rs7Rz9GLYVM

**Детали окружения:**
 - ОС: Windows 10 Pro x64 21H2
 - Движок: Оригинальный 8684
 - GameDLL: Оригинальный
 - Metamod: нет
 - Версия бота: 4.2.648 (с GitHub Actions)
 - Режим игры: Обычный

**Comment by commandcobra7** [comment]
I do not have such a problem, try to set yb_destroy_breakables_around "0", then the problem will be solved.
