### ISSUE TITLE
Как собрать новую версию ботов?

### ISSUE THREAD

**Issue by vladislav980** [yapb/yapb#294]
При сборке пишет что нет файла vector.h
../ext/hlsdk/extdll.h:27:10: fatal error: 'crlib/vector.h' file not found

**Comment by vladislav980** [comment]
Скачал отдельно crlib @ 9375af6
Теперь новые ошибки.
meson compile
[1/14] Compiling C++ object yapb.so.p/src_chatlib.cpp.o
FAILED: yapb.so.p/src_chatlib.cpp.o 
clang++ -Iyapb.so.p -I. -I.. -fvisibility=hidden -flto -fcolor-diagnostics -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -Werror -std=c++14 -fno-exceptions -O3 -DVERSION_GENERATED -fno-threadsafe-statics -fno-exceptions -fno-rtti -m32 -pedantic -fdata-sections -ffunction-sections -mtune=generic -fno-builtin -funroll-loops -fomit-frame-pointer -fno-stack-protector -fvisibility=hidden -fvisibility-inlines-hidden -msse2 -mfpmath=sse -fPIC -isystem../ext/crlib -isystem../ext -isystem../inc -isystem.. -isystem. -MD -MQ yapb.so.p/src_chatlib.cpp.o -MF yapb.so.p/src_chatlib.cpp.o.d -o yapb.so.p/src_chatlib.cpp.o -c ../src/chatlib.cpp
In file included from ../src/chatlib.cpp:8:
In file included from ../inc/yapb.h:10:
In file included from ../ext/hlsdk/extdll.h:27:
In file included from ../ext/crlib/vector.h:10:
In file included from ../ext/crlib/math.h:10:
In file included from ../ext/crlib/basic.h:125:
In file included from ../ext/crlib/platform.h:144:
In file included from ../ext/crlib/string.h:14:
../ext/crlib/memory.h:32:10: error: use of undeclared identifier 'plat'
         plat.abort ();
         ^
In file included from ../src/chatlib.cpp:8:
In file included from ../inc/yapb.h:10:
In file included from ../ext/hlsdk/extdll.h:27:
In file included from ../ext/crlib/vector.h:10:
In file included from ../ext/crlib/math.h:10:
In file included from ../ext/crlib/basic.h:125:
In file included from ../ext/crlib/platform.h:144:
In file included from ../ext/crlib/string.h:17:
In file included from ../ext/crlib/array.h:13:
../ext/crlib/random.h:18:42: error: use of undeclared identifier 'time'
   uint64 state_ { static_cast <uint64> (time (nullptr)) };
                                         ^
In file included from ../src/chatlib.cpp:8:                                  
In file included from ../inc/yapb.h:10:
In file included from ../ext/hlsdk/extdll.h:27:
In file included from ../ext/crlib/vector.h:10:
In file included from ../ext/crlib/math.h:10:
In file included from ../ext/crlib/basic.h:125:
In file included from ../ext/crlib/platform.h:144:
../ext/crlib/string.h:99:40: error: use of undeclared identifier 'memcmp'
      return length_ == rhs.length_ && memcmp (chars_, rhs.chars_, length_) == 0;
                                       ^
../ext/crlib/string.h:141:45: error: use of undeclared identifier 'strncmp'  
      return prefix.length () <= length_ && strncmp (chars (), prefix.chars (), prefix.length ()) == 0;
                                            ^
../ext/crlib/string.h:145:45: error: use of undeclared identifier 'strncmp'  
      return suffix.length () <= length_ && strncmp (chars () + length_ - suffix.length (), suffix.chars (), suffix.length ()) == 0;
                                            ^
../ext/crlib/string.h:364:43: error: use of undeclared identifier 'strlen'   
      return length > 0 ? length : (str ? strlen (str) : 0);
                                          ^
../ext/crlib/string.h:408:10: error: use of undeclared identifier 'memcpy'   
         memcpy (&transfer[0], &chars_[0], length_);
         ^
../ext/crlib/string.h:425:10: error: use of undeclared identifier 'memcpy'   
         memcpy (&chars_[0], str, length);
         ^
../ext/crlib/string.h:448:7: error: use of undeclared identifier 'memcpy'    
      memcpy (chars_.get () + length_, str, length);
      ^
In file included from ../src/chatlib.cpp:8:                                  
In file included from ../inc/yapb.h:10:
In file included from ../ext/hlsdk/extdll.h:27:
In file included from ../ext/crlib/vector.h:10:
In file included from ../ext/crlib/math.h:10:
In file included from ../ext/crlib/basic.h:125:
../ext/crlib/platform.h:279:7: error: use of undeclared identifier 'memset'
      memset (reinterpret_cast <void *> (ptr), 0, len);
      ^
../ext/crlib/platform.h:306:10: error: use of undeclared identifier 'strncpy'
         strncpy (result, data, cr::bufsize (result));
         ^
In file included from ../src/chatlib.cpp:8:                                  
In file included from ../inc/yapb.h:10:
In file included from ../ext/hlsdk/extdll.h:27:
In file included from ../ext/crlib/vector.h:10:
In file included from ../ext/crlib/math.h:26:
In file included from ../ext/crlib/simd.h:21:
../ext/crlib/ssemath/ssemath.h:196:32: error: use of undeclared identifier 'M_E'
DECLARE_SSEMATH_PS (E, (float) M_E);
                               ^
../ext/crlib/ssemath/ssemath.h:196:32: error: use of undeclared identifier 'M_E'
../ext/crlib/ssemath/ssemath.h:196:32: error: use of undeclared identifier 'M_E'
../ext/crlib/ssemath/ssemath.h:196:32: error: use of undeclared identifier 'M_E'
../ext/crlib/ssemath/ssemath.h:197:36: error: use of undeclared identifier 'M_LOG2E'
DECLARE_SSEMATH_PS (LOG2E, (float) M_LOG2E);
                                   ^
../ext/crlib/ssemath/ssemath.h:197:36: error: use of undeclared identifier 'M_LOG2E'
../ext/crlib/ssemath/ssemath.h:197:36: error: use of undeclared identifier 'M_LOG2E'
../ext/crlib/ssemath/ssemath.h:197:36: error: use of undeclared identifier 'M_LOG2E'
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
[2/14] Compiling C++ object yapb.so.p/src_combat.cpp.o
FAILED: yapb.so.p/src_combat.cpp.o 
clang++ -Iyapb.so.p -I. -I.. -fvisibility=hidden -flto -fcolor-diagnostics -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -Werror -std=c++14 -fno-exceptions -O3 -DVERSION_GENERATED -fno-threadsafe-statics -fno-exceptions -fno-rtti -m32 -pedantic -fdata-sections -ffunction-sections -mtune=generic -fno-builtin -funroll-loops -fomit-frame-pointer -fno-stack-protector -fvisibility=hidden -fvisibility-inlines-hidden -msse2 -mfpmath=sse -fPIC -isystem../ext/crlib -isystem../ext -isystem../inc -isystem.. -isystem. -MD -MQ yapb.so.p/src_combat.cpp.o -MF yapb.so.p/src_combat.cpp.o.d -o yapb.so.p/src_combat.cpp.o -c ../src/combat.cpp
In file included from ../src/combat.cpp:8:
In file included from ../inc/yapb.h:10:
In file included from ../ext/hlsdk/extdll.h:27:
In file included from ../ext/crlib/vector.h:10:
In file included from ../ext/crlib/math.h:10:
In file included from ../ext/crlib/basic.h:125:
In file included from ../ext/crlib/platform.h:144:
In file included from ../ext/crlib/string.h:14:
../ext/crlib/memory.h:32:10: error: use of undeclared identifier 'plat'
         plat.abort ();
         ^
In file included from ../src/combat.cpp:8:                                   
In file included from ../inc/yapb.h:10:
In file included from ../ext/hlsdk/extdll.h:27:
In file included from ../ext/crlib/vector.h:10:
In file included from ../ext/crlib/math.h:10:
In file included from ../ext/crlib/basic.h:125:
In file included from ../ext/crlib/platform.h:144:
In file included from ../ext/crlib/string.h:17:
In file included from ../ext/crlib/array.h:13:
../ext/crlib/random.h:18:42: error: use of undeclared identifier 'time'
   uint64 state_ { static_cast <uint64> (time (nullptr)) };
                                         ^
In file included from ../src/combat.cpp:8:                                   
In file included from ../inc/yapb.h:10:
In file included from ../ext/hlsdk/extdll.h:27:
In file included from ../ext/crlib/vector.h:10:
In file included from ../ext/crlib/math.h:10:
In file included from ../ext/crlib/basic.h:125:
In file included from ../ext/crlib/platform.h:144:
../ext/crlib/string.h:99:40: error: use of undeclared identifier 'memcmp'
      return length_ == rhs.length_ && memcmp (chars_, rhs.chars_, length_) == 0;
                                       ^
../ext/crlib/string.h:141:45: error: use of undeclared identifier 'strncmp'  
      return prefix.length () <= length_ && strncmp (chars (), prefix.chars (), prefix.length ()) == 0;
                                            ^
../ext/crlib/string.h:145:45: error: use of undeclared identifier 'strncmp'  
      return suffix.length () <= length_ && strncmp (chars () + length_ - suffix.length (), suffix.chars (), suffix.length ()) == 0;
                                            ^
../ext/crlib/string.h:364:43: error: use of undeclared identifier 'strlen'   
      return length > 0 ? length : (str ? strlen (str) : 0);
                                          ^
../ext/crlib/string.h:408:10: error: use of undeclared identifier 'memcpy'   
         memcpy (&transfer[0], &chars_[0], length_);
         ^
../ext/crlib/string.h:425:10: error: use of undeclared identifier 'memcpy'   
         memcpy (&chars_[0], str, length);
         ^
../ext/crlib/string.h:448:7: error: use of undeclared identifier 'memcpy'    
      memcpy (chars_.get () + length_, str, length);
      ^
In file included from ../src/combat.cpp:8:                                   
In file included from ../inc/yapb.h:10:
In file included from ../ext/hlsdk/extdll.h:27:
In file included from ../ext/crlib/vector.h:10:
In file included from ../ext/crlib/math.h:10:
In file included from ../ext/crlib/basic.h:125:
../ext/crlib/platform.h:279:7: error: use of undeclared identifier 'memset'
      memset (reinterpret_cast <void *> (ptr), 0, len);
      ^
../ext/crlib/platform.h:306:10: error: use of undeclared identifier 'strncpy'
         strncpy (result, data, cr::bufsize (result));
         ^
In file included from ../src/combat.cpp:8:                                   
In file included from ../inc/yapb.h:10:
In file included from ../ext/hlsdk/extdll.h:27:
In file included from ../ext/crlib/vector.h:10:
In file included from ../ext/crlib/math.h:26:
In file included from ../ext/crlib/simd.h:21:
../ext/crlib/ssemath/ssemath.h:196:32: error: use of undeclared identifier 'M_E'
DECLARE_SSEMATH_PS (E, (float) M_E);
                               ^
../ext/crlib/ssemath/ssemath.h:196:32: error: use of undeclared identifier 'M_E'
../ext/crlib/ssemath/ssemath.h:196:32: error: use of undeclared identifier 'M_E'
../ext/crlib/ssemath/ssemath.h:196:32: error: use of undeclared identifier 'M_E'
../ext/crlib/ssemath/ssemath.h:197:36: error: use of undeclared identifier 'M_LOG2E'
DECLARE_SSEMATH_PS (LOG2E, (float) M_LOG2E);
                                   ^
../ext/crlib/ssemath/ssemath.h:197:36: error: use of undeclared identifier 'M_LOG2E'
../ext/crlib/ssemath/ssemath.h:197:36: error: use of undeclared identifier 'M_LOG2E'
../ext/crlib/ssemath/ssemath.h:197:36: error: use of undeclared identifier 'M_LOG2E'
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
[3/14] Compiling C++ object yapb.so.p/src_botlib.cpp.o
FAILED: yapb.so.p/src_botlib.cpp.o 
clang++ -Iyapb.so.p -I. -I.. -fvisibility=hidden -flto -fcolor-diagnostics -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -Werror -std=c++14 -fno-exceptions -O3 -DVERSION_GENERATED -fno-threadsafe-statics -fno-exceptions -fno-rtti -m32 -pedantic -fdata-sections -ffunction-sections -mtune=generic -fno-builtin -funroll-loops -fomit-frame-pointer -fno-stack-protector -fvisibility=hidden -fvisibility-inlines-hidden -msse2 -mfpmath=sse -fPIC -isystem../ext/crlib -isystem../ext -isystem../inc -isystem.. -isystem. -MD -MQ yapb.so.p/src_botlib.cpp.o -MF yapb.so.p/src_botlib.cpp.o.d -o yapb.so.p/src_botlib.cpp.o -c ../src/botlib.cpp
In file included from ../src/botlib.cpp:8:
In file included from ../inc/yapb.h:10:
In file included from ../ext/hlsdk/extdll.h:27:
In file included from ../ext/crlib/vector.h:10:
In file included from ../ext/crlib/math.h:10:
In file included from ../ext/crlib/basic.h:125:
In file included from ../ext/crlib/platform.h:144:
In file included from ../ext/crlib/string.h:14:
../ext/crlib/memory.h:32:10: error: use of undeclared identifier 'plat'
         plat.abort ();
         ^
In file included from ../src/botlib.cpp:8:                                   
In file included from ../inc/yapb.h:10:
In file included from ../ext/hlsdk/extdll.h:27:
In file included from ../ext/crlib/vector.h:10:
In file included from ../ext/crlib/math.h:10:
In file included from ../ext/crlib/basic.h:125:
In file included from ../ext/crlib/platform.h:144:
In file included from ../ext/crlib/string.h:17:
In file included from ../ext/crlib/array.h:13:
../ext/crlib/random.h:18:42: error: use of undeclared identifier 'time'
   uint64 state_ { static_cast <uint64> (time (nullptr)) };
                                         ^
In file included from ../src/botlib.cpp:8:                                   
In file included from ../inc/yapb.h:10:
In file included from ../ext/hlsdk/extdll.h:27:
In file included from ../ext/crlib/vector.h:10:
In file included from ../ext/crlib/math.h:10:
In file included from ../ext/crlib/basic.h:125:
In file included from ../ext/crlib/platform.h:144:
../ext/crlib/string.h:99:40: error: use of undeclared identifier 'memcmp'
      return length_ == rhs.length_ && memcmp (chars_, rhs.chars_, length_) == 0;
                                       ^
../ext/crlib/string.h:141:45: error: use of undeclared identifier 'strncmp'  
      return prefix.length () <= length_ && strncmp (chars (), prefix.chars (), prefix.length ()) == 0;
                                            ^
../ext/crlib/string.h:145:45: error: use of undeclared identifier 'strncmp'  
      return suffix.length () <= length_ && strncmp (chars () + length_ - suffix.length (), suffix.chars (), suffix.length ()) == 0;
                                            ^
../ext/crlib/string.h:364:43: error: use of undeclared identifier 'strlen'   
      return length > 0 ? length : (str ? strlen (str) : 0);
                                          ^
../ext/crlib/string.h:408:10: error: use of undeclared identifier 'memcpy'   
         memcpy (&transfer[0], &chars_[0], length_);
         ^
../ext/crlib/string.h:425:10: error: use of undeclared identifier 'memcpy'   
         memcpy (&chars_[0], str, length);
         ^
../ext/crlib/string.h:448:7: error: use of undeclared identifier 'memcpy'    
      memcpy (chars_.get () + length_, str, length);
      ^
In file included from ../src/botlib.cpp:8:                                   
In file included from ../inc/yapb.h:10:
In file included from ../ext/hlsdk/extdll.h:27:
In file included from ../ext/crlib/vector.h:10:
In file included from ../ext/crlib/math.h:10:
In file included from ../ext/crlib/basic.h:125:
../ext/crlib/platform.h:279:7: error: use of undeclared identifier 'memset'
      memset (reinterpret_cast <void *> (ptr), 0, len);
      ^
../ext/crlib/platform.h:306:10: error: use of undeclared identifier 'strncpy'
         strncpy (result, data, cr::bufsize (result));
         ^
In file included from ../src/botlib.cpp:8:                                   
In file included from ../inc/yapb.h:10:
In file included from ../ext/hlsdk/extdll.h:27:
In file included from ../ext/crlib/vector.h:10:
In file included from ../ext/crlib/math.h:26:
In file included from ../ext/crlib/simd.h:21:
../ext/crlib/ssemath/ssemath.h:196:32: error: use of undeclared identifier 'M_E'
DECLARE_SSEMATH_PS (E, (float) M_E);
                               ^
../ext/crlib/ssemath/ssemath.h:196:32: error: use of undeclared identifier 'M_E'
../ext/crlib/ssemath/ssemath.h:196:32: error: use of undeclared identifier 'M_E'
../ext/crlib/ssemath/ssemath.h:196:32: error: use of undeclared identifier 'M_E'
../ext/crlib/ssemath/ssemath.h:197:36: error: use of undeclared identifier 'M_LOG2E'
DECLARE_SSEMATH_PS (LOG2E, (float) M_LOG2E);
                                   ^
../ext/crlib/ssemath/ssemath.h:197:36: error: use of undeclared identifier 'M_LOG2E'
../ext/crlib/ssemath/ssemath.h:197:36: error: use of undeclared identifier 'M_LOG2E'
../ext/crlib/ssemath/ssemath.h:197:36: error: use of undeclared identifier 'M_LOG2E'
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
ninja: build stopped: subcommand failed.

**Comment by jeefo** [comment]
Какой шланг? Какой Linux?

**Comment by vladislav980** [comment]
> Какой шланг? Какой Linux?

Virtualbox kalilinux. Даже в visualstudio не собирается. На счет шланга не понял)

**Comment by vladislav980** [comment]
[ошибки.txt](https://github.com/yapb/yapb/files/7963109/default.txt)
это в visual

**Comment by jeefo** [comment]
> > Какой шланг? Какой Linux?
> 
> Virtualbox kalilinux. Даже в visualstudio не собирается. На счет шланга не понял)

версия clang

**Comment by jeefo** [comment]
> 

судя по ошибкам, нужна студия посвежее

**Comment by vladislav980** [comment]
2022 студия

**Comment by vladislav980** [comment]
Версия шланга
Debian clang version 11.1.0-4
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64

**Comment by vladislav980** [comment]
После этой версии 4.2.598 больше не собирается у меня.

**Comment by MurLemur** [comment]
2022 студия, clang 12.0.0 
Ошибки такого вида :  templates must have C++ linkage	yapb	D:\TMP\yapb-master\ext\crlib\movable.h	15

Подскажите какая версия clang нужна ?

**Comment by jeefo** [comment]
любая поддерживающая c++14

странно, у меня собирается из коробки

**Comment by jeefo** [comment]
> templates must have C++ linkage

нужен gcc-multilib, не знаю как его поставить в Kali

**Comment by jeefo** [comment]
@[vladislav980](https://github.com/vladislav980)

нужен GCC-multilib, где-его взять в Kali, не нзаю

**Comment by vladislav980** [comment]
sudo apt-get install gcc-multilib ?

**Comment by vladislav980** [comment]
может даже так sudo apt-get install gcc-multilib g++-multilib

**Comment by jeefo** [comment]
мне то без надобности, я сижу на арче сейчас.Sent from my Galaxy
-------- Original message --------From: vladislav980 ***@***.***> Date: 2/22/22  01:13  (GMT+03:00) To: yapb/yapb ***@***.***> Cc: jeefo ***@***.***>, Comment ***@***.***> Subject: Re: [yapb/yapb] Как собрать новую версию ботов? (Issue #294) 

может даже так sudo apt-get install gcc-multilib g++-multilib

**Comment by vladislav980** [comment]
> мне то без надобности, я сижу на арче сейчас.Sent from my Galaxy -------- Original message --------From: vladislav980 ***@***.***> Date: 2/22/22 01:13 (GMT+03:00) To: yapb/yapb ***@***.***> Cc: jeefo ***@***.***>, Comment ***@***.***> Subject: Re: [yapb/yapb] Как собрать новую версию ботов? (Issue #294) может даже так sudo apt-get install gcc-multilib g++-multilib —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

Можешь дать ссылку на него я себе поставлю проверю на на нем будет ли собирать.

**Comment by vladislav980** [comment]
Под ArchLinux компилируется, теперь понять бы как в визуал скомпилировать.

**Comment by vladislav980** [comment]
Так теперь и в Kali linux компилирует. После того как я клонировал crlib а не закидывал через drandrop

**Comment by vladislav980** [comment]
Короче проблемно собрать стало как только crlib переехал в отдельную репозиторию)

**Comment by vladislav980** [comment]
Скинул с kali linux crlib который скачал через git clone, теперь и визуалка собирает. 
а если скачивать https://github.com/yapb/crlib/tree/9375af6e408b5fcd195c2bce5f2565bc3fbd3160 или
https://github.com/yapb/crlib/tree/master
 то начинаются ошибки.

**Comment by vladislav980** [comment]
Ну в общем как-то так) Теперь все собирается и компилируется)

**Comment by jeefo** [comment]
надо было просто сделать git submodule upfate

**Comment by vladislav980** [comment]
> Ошибки при компилировании были из за того что по отдельности crlib подкидывали и промазали со структурой - то есть было ext/crlib/* а надо ext/crlib/crlib/* , можно закрывать.

Да не, у меня ext/crlib/ и там файлы
