### ISSUE TITLE
Боты слишком часто раскидывают оружие

### ISSUE THREAD

**Issue by Vladislav4KZ** [yapb/yapb#301]
Такое поведение хорошо заметно на всяких картах где оружие лежит на земле. Например, на карте cs_pf_dust на земле лежит по несколько штук одного и того же оружия в одном и том же месте.

И происходит что боты очень быстро раскидывают оружие по всей карте

**Видео**
https://youtu.be/5EehW28vlEA

**Детали окружения:**
 - ОС: Windows 10 Pro x64 21H2
 - Движок: Оригинальный 8684
 - GameDLL: Оригинальный
 - Metamod: нет
 - Версия бота: 4.2.660 (с GitHub Actions)
 - Режим игры: Обычный

**Comment by jeefo** [comment]
выглядит забавно

какая это карта?)

**Comment by jeefo** [comment]
Можешь проверить ?

**Comment by Vladislav4KZ** [comment]
> Можешь проверить ? нет возможности сейчас запускать listenserver.

Теперь всё нормально, боты не раскидывают оружие.
