### ISSUE TITLE
Бот использует неверные направления кемперских точек

### ISSUE THREAD

**Issue by Vladislav4KZ** [yapb/yapb#303]
Например на карте cs_pf_dust, есть кемперские точки находящиеся рядом друг с другом.
И необязательно они должны быть соединены путями.

Даже если одна кемперская точка находится выше другой то всё равно, если направления у кемперских точек поблизости разные, бот использует направления не от той кемперской точки на которой он сидит, а от другой ближней.

И получается что, когда бот находится на кемперской точке, то он смотрит в стену.

**Детали окружения:**
 - ОС: Windows 10 Pro x64 21H2
 - Движок: Оригинальный 8684
 - GameDLL: Оригинальный
 - Metamod: нет
 - Версия бота: 4.2.660 (с GitHub Actions)
 - Режим игры: Обычный

**Comment by PRinceBhai** [comment]
How are you running YAPB without MetaMod?

**Comment by Vladislav4KZ** [comment]
> How are you running YAPB without MetaMod?

YaPB doesn't require metamod.

**Comment by jeefo** [comment]
Можно видос с включенной yb_debug 3 ? Не могу увидеть проблему.

**Comment by Vladislav4KZ** [comment]
> Можно видос с включенной yb_debug 3 ? Не могу увидеть проблему.

Хорошо, как словлю баг, так скину.

**Comment by Vladislav4KZ** [comment]
И да, походу это случается когда бот увидел врага.

**Comment by Vladislav4KZ** [comment]
Вот видос
https://youtu.be/JQgXDQdlfbg

**Comment by jeefo** [comment]
когда доберусь до листена, поправлю predict - трекинг ласт врага, не должен он так сквозь стену смотреть конечно

**Comment by commandcobra7** [comment]
I think I know the solution for this error. Probably some of the camp desire must be broken. Some of the PodBot source codes should be looked at. If you look at the codes between 7265 and 7396 in the bot.cpp file, maybe the problem will be completely resolved if you take inspiration from there.

**Comment by commandcobra7** [comment]
I solved this problem but I'm not so sure. I got this code from @EfeDursun125 repository from CS-EBOT. I don't know if it will solve the problem.

I copied and pasted the code below.
----------------------------------------------------------------------------------------------------------------------
      else {
         int lastEnemyNearestIndex = graph.getNearest (m_lastEnemy->v.origin);

         if (!game.isNullEntity (m_lastEnemy) && util.isAlive (m_lastEnemy) && rg.get (1, 3) == 1 && graph.isVisible (m_currentNodeIndex, lastEnemyNearestIndex)) {
            m_camp = graph[lastEnemyNearestIndex].origin;
         }
         else {
            m_camp = graph[findCampingDirection ()].origin;
         }
      }

**Comment by Vladislav4KZ** [comment]
Скачал билд с фиксом этого бага, а на самом деле он не исчез. Боты всё также могут смотреть в стены когда кемперят (смотрят в абсолютно противоположном направлении, чем указано на кемперской точке).

**Comment by Vladislav4KZ** [comment]
На последней версии баг не совсем пропал
![Безымянный.png](https://user-images.githubusercontent.com/22411953/197216473-1ec2d98b-8079-4664-aa36-9cf3e574f382.png)

Но всё же, он стал проявляться намного реже. Боты теперь стали чаще смотреть по направлениям от кемперской точки.

**Comment by commandcobra7** [comment]
Vladislav4KZ dude, I made a correction again, now see if the problem is solved, I did my best

https://github.com/yapb/yapb/actions/runs/3302643876

**Comment by commandcobra7** [comment]
> [Vladislav4KZ](https://github.com/Vladislav4KZ) dude, I made a correction again, now see if the problem is solved, I did my best
> 
> https://github.com/yapb/yapb/actions/runs/3302643876

**Comment by Vladislav4KZ** [comment]
> dude, I made a correction again, now see if the problem is solved, I did my best
> 
> https://github.com/yapb/yapb/actions/runs/3302643876

@commandcobra7 I said that the problem began to manifest itself less often, that's good. But I tried the latest build of the YaPB with your fix, but apparently this problem cannot be completely eliminated.

**Comment by commandcobra7** [comment]
@Vladislav4KZ I don't understand how to solve this problem, probably there must be a problem with "findCampingDirection ()"

**Comment by commandcobra7** [comment]
@Vladislav4KZ I solved this problem The problem is in the transition points. Bots do not use the visibility of the camp point. uses the visibility of normal waypoints connected to the camp point. Delete nodes between waypoints and camp points, add a point near the camp points, then they can't face the wall.

**Comment by commandcobra7** [comment]
@Vladislav4KZ this issue has been resolved with the latest edit.

https://github.com/yapb/yapb/actions/runs/4637872475

**Comment by Vladislav4KZ** [comment]
> this issue has been resolved with the latest edit.
> 
> https://github.com/yapb/yapb/actions/runs/4637872475

Yes, now this bug is actually fixed.
