### ISSUE TITLE
Возможность выбора пятого класса игрока в Condition Zero

### ISSUE THREAD

**Issue by Vladislav4KZ** [yapb/yapb#310]
На данный момент, при добавлении бота на выбор даётся 4 класса игрока. А в Condition Zero есть дополнительный 5 класс игрока.

У террористов это "Midwest Militia" (Ополчение среднего запада), а у контр-террористов "Russian Spetsnaz" (Русский Спецназ).

**Comment by jeefo** [comment]
через меню?

**Comment by Vladislav4KZ** [comment]
> через меню?

Да, я говорю про меню

**Comment by Vladislav4KZ** [comment]
В Condition Zero кстати, когда выбираешь пятый пункт "5. Случайный выбор" при добавлении бота через меню, то добавляется именно "Спецназ" за Контр-Террористов или "Ополчение среднего запада" за Террористов. Сам случайный выбор не работает, выбирается только один конкретный класс.

В Condition Zero в самом меню где выбирается класс, пункт "Случайный выбор" находится на шестом месте.

**Comment by jeefo** [comment]
а стоит ли? динамические меню используются только для кика ботов, их сложнее переводить)

ф
