### ISSUE TITLE
Hosting wanted

### ISSUE THREAD

**Issue by jeefo** [yapb/yapb#316]
Do to sanctions applied to Russia, i believe Oracle Free Tier that hosts YaPB websites will terminate accounts associated with Russian persons.

Moving to Russia is not an option, cause our brain damaged government likely cut the access to global internet in near future.

So, if anyone could donate a small VPS (not in RU/UA) for YaPB (graph upload feature require VPS, not virtual hosting), i would be happy to transfer everything to it.

Maybe it's nice to move to new domain, since i believe registrars will terminate *.jeefo.net zone, where bot is currently hosted.

**Comment by weimzh** [comment]
Hi,

Sorry for everything happened recently :( it's totally unbelievable and I hope you stay fine.

I check the original yapb.bots-united.com however it seems neglected and uploading/downloading html/php is not currently working. 

I've got a small VPS at AWS (US Region, 1 CPU / 512M RAM / 30GB SSD).  Not sure if it's sufficient, I can create a larger one if not.

-Whistler

**Comment by jeefo** [comment]
Hi, Whistler. Yes, it's very bad situation for regular people.

Thanks, it would be more than enough for bots needs. Can you contact me via dmitry@jeefo.net?

(i believe it's not a problem, i have just can't pay anything with my cards outside of Russia, and can't register any account anywhere, AWS/Azure/DO.. so here is what this issue here).

Again, thank you.

**Comment by jeefo** [comment]
Transferred, thanks @weimzh
