### ISSUE TITLE
Бот не может забраться на лестницу

### ISSUE THREAD

**Issue by Vladislav4KZ** [yapb/yapb#319]
https://youtu.be/cWkFMkjny18

**Детали окружения:**
 - ОС: Windows 10 Pro x64 21H2
 - Движок: Оригинальный 8684
 - GameDLL: Оригинальный
 - Metamod: Metamod-P 1.21p38
 - Версия бота: 4.2.671
 - Режим игры: Обычный

**Comment by Drevny13** [comment]
лестница под углом к стене ?

**Comment by Vladislav4KZ** [comment]
> лестница под углом к стене ?
Карта: cs_arabstreets_csm
![Screenshot_20220316-193812.png](https://user-images.githubusercontent.com/22411953/158602791-b6861110-65f3-4a62-a725-9ede24d4b2af.png)![Screenshot_20220316-193821.png](https://user-images.githubusercontent.com/22411953/158602853-c855381e-da02-402d-ac01-f52a29c08102.png)

Такое происходит не всегда, бот иногда может забраться на лестницу.

Это может происходить на любых картах.

**Comment by commandcobra7** [comment]
@Vladislav4KZ whatever I did in the code edits didn't work. It jumps when going up, there is no problem when going down, but when going down, they stay stuck on the bottom ladder for a while and then continue on their way. Even the codes I got from Podbot didn't work, I tested it. I don't know where this problem comes from.

**Comment by commandcobra7** [comment]
@Vladislav4KZ this problem was solved before with the new version, check the bots on the ladder again in the new version

**Comment by Vladislav4KZ** [comment]
@commandcobra7 I checked on the same map, and no, the issue is not solved.

**Comment by commandcobra7** [comment]
@Vladislav4KZ I have not seen this problem much, I rarely have this problem

**Comment by Vladislav4KZ** [comment]
@commandcobra7 yeah, this bug doesn't always show up, but it does exist.

I just tested the latest version of the bots from GitHub Actions again, and I saw that when you specify a ladder node in the debug goal menu, the bot climbs the ladder the first time.

But with the radio command "Follow me" when there are 9 bots in the game, the bot cannot climb the ladder the first time.

It climbs the ladder only from the third or fourth time.

**Comment by jeefo** [comment]
на последних ревизиях это воспроизводится?

**Comment by Vladislav4KZ** [comment]
> на последних ревизиях это воспроизводится?

Да, проверил только что на версии 4.4.904

**Comment by jeefo** [comment]
а сейчас?

**Comment by jeefo** [comment]
Перелопатил часть когда по айму и навигации по лестницам, до кучи починив лифты. Должно работать более или менее.

**Comment by Vladislav4KZ** [comment]
> Перелопатил часть когда по айму и навигации по лестницам, до кучи починив лифты. Должно работать более или менее.

Да, сейчас в большинстве случаев боты без проблем забираются на лестницу. Проверил на этой же карте (cs_arabstreets_csm), на которой изначально заметил этот баг.
