### ISSUE TITLE
Когда мёртв, при открытии командного меню на экран не выводится сообщение о невозможности его открытия когда стоит русский язык

### ISSUE THREAD

**Issue by Vladislav4KZ** [yapb/yapb#322]
Проверял на английском и немецком языке, там сообщение выводится, а на русском почему-то нет. Оно выводится только в консоль, в то время как на других языках появляется на экране.

**Детали окружения:**
 - ОС: Windows 10 Pro x64 21H2
 - Движок: Оригинальный 8684
 - GameDLL: Оригинальный
 - Metamod: Metamod-P 1.21p38
 - Версия бота: 4.2.675 (с GitHub Actions)
 - Режим игры: Обычный

**Comment by jeefo** [comment]
Просьба проверить, дос их пор доступ только к HLDS :(

**Comment by Vladislav4KZ** [comment]
> Просьба проверить, дос их пор доступ только к HLDS :(

Проверил, все нормально работает. Текст выводится на экран как и положено. 👍
