### ISSUE TITLE
Проблемы ботов на карте es_industrial

### ISSUE THREAD

**Issue by Vladislav4KZ** [yapb/yapb#323]
Боты не стреляют друг в друга.
Сначала думал это из-за ошибки
```
A* Search for bot "bot nickname" has failed. Falling back to shortest-path algorithm. Seems to be graph is broken.
```
Она появлялась из-за того что пути точек на базе террористов указывали на прыжок на ящик, а обратного пути с ящика на базу террористов нет. Но я соединил точки с ящика к точкам на базе террористов двухсторонними путями. Ошибка исчезла, но проблема оказалась в другом. Боты все ещё создают толпу и ничего не делают.

Иногда они всё таки перестреливаются, но потом опять все ломается.

Также бот пытается заложить бомбу на место побега террористов.

Бот контр-террорист не может обезвредить заложенную бомбу.

Вот на этой нестандартной карте такие проблемы. Она имеет зону закупки оружия на базе террористов, имеет место закладки бомбы и место побега террористов.

Также на этой карте в запертой комнате находится один заложник.

**Детали окружения:**
 - ОС: Windows 10 Pro x64 21H2
 - Движок: Оригинальный 8684
 - GameDLL: Оригинальный
 - Metamod: Metamod-P 1.21p38
 - Версия бота: 4.2.677 (с GitHub Actions)
 - Режим игры: Обычный

**Comment by jeefo** [comment]
@Vladislav4KZ если будет время,  проверь карту.

**Comment by Vladislav4KZ** [comment]
Хорошо, проверю.

**Comment by Vladislav4KZ** [comment]
Все вышеперечисленные баги больше не появляются в последней сборке бота.
