### ISSUE TITLE
Боты не используют фонарик и прибор ночного видения

### ISSUE THREAD

**Issue by Vladislav4KZ** [yapb/yapb#326]
Боты не используют фонарик или прибор ночного видения в тёмных местах.

Для примера, есть карта, de_transsibirian которая тёмная снаружи, ночное время суток. Боты PODBot 3.0 когда поднимались на крыши вагонов, они включали фонарик, а YaPB нет.

И ещё в редакторе графов, где находится информация о точке, для чего-то же отображается уровень освещённости. Разве не для того, что при каком-то уровне освещённости бот включает фонарик?

Про этот баг ещё кто-то писал, но он закрыл issue

Когда игрок включает прибор ночного видения, слышен звук. Но YaPB боты его тоже не включали.

**Детали окружения:**
 - ОС: Windows 10 Pro x64 21H2
 - Движок: Оригинальный 8684
 - GameDLL: Оригинальный
 - Metamod: Metamod-P 1.21p38
 - Версия бота: 4.2.680 (с GitHub Actions)
 - Режим игры: Обычный

**Comment by jeefo** [comment]
Посмотри в этом билде:

https://github.com/yapb/yapb/actions/runs/2166410743

**Comment by Vladislav4KZ** [comment]
> Посмотри в этом билде:
> 
> https://github.com/yapb/yapb/actions/runs/2166410743

Проверил, теперь боты включают фонарик. 👍

**Comment by Vladislav4KZ** [comment]
Хотя, через время они почему-то перестали его включать.

**Comment by Vladislav4KZ** [comment]
Получилось так, бот один раз включил фонарик, и больше не включает. После перезапуска сервера или игры, бот всё равно не включает фонарик.

**Comment by Vladislav4KZ** [comment]
Забудь, это я другой билд поставил
