### ISSUE TITLE
Боты не воспроизводят звуковые файлы чаттера с папки cstrike_russian

### ISSUE THREAD

**Issue by Vladislav4KZ** [yapb/yapb#327]
Если файлы радиопереговоров ботов положить в папку локализации, например cstrike_russian, то боты не видят их, и используют обычные радиокоманды.
Когда эти файлы лежат в папке cstrike, то боты воспроизводят их.

zBot например, может воспроизводить звуки с той папки

**Детали окружения:**
 - ОС: Windows 10 Pro x64 21H2
 - Движок: Оригинальный 8684
 - GameDLL: Оригинальный
 - Metamod: Metamod-P 1.21p38
 - Версия бота: 4.2.680 (с GitHub Actions)
 - Режим игры: Обычный

**Comment by Vladislav4KZ** [comment]
То же самое и с папкой cstrike_addon

**Comment by jeefo** [comment]
Привет.

https://github.com/yapb/yapb/actions/runs/2166214660

**Comment by Vladislav4KZ** [comment]
Проверил, звуки с папки cstrike_russian работают
