### ISSUE TITLE
Suicidal CT in as_oilrig

### ISSUE THREAD

**Issue by A-Randomized-Dude** [yapb/yapb#331]
CT tries to use elevator but they get bonked on the head until every one of them is dead.

I use amx mod x 1.8.3 dev git 5201 base
I use amx mod x 1.8.3 dev git 5201 cstrike

Latest version of yapb on cs condition zero.

![20220417132203_1](https://user-images.githubusercontent.com/66621511/163711240-6d17a558-1fa4-4cc0-969e-c6aaf46b09ba.jpg)

**Comment by Vladislav4KZ** [comment]
Need graph fix for this map, because I looked and saw that the paths leading to the elevator button do not have a return path, and only lead to a node located above (which the bot must reach when taking the elevator)

Maybe I'll fix it a little bit later.

**Comment by Vladislav4KZ** [comment]
It will not be possible to completely fix CT suicide if the bots use the elevator. This can be fixed only by removing the node next to the elevator button, then the bots will not use it and, accordingly, the elevator will not kill them.
