### ISSUE TITLE
Боты идут только к одной точке спасения заложников

### ISSUE THREAD

**Issue by Vladislav4KZ** [yapb/yapb#335]
Есть карты, на которых расположено несколько зон спасения заложников, такие как cs_KVARTAL2 (3 зоны), cs_747 (2 зоны), cs_747_b65 (5-6 зон) cs_mansion (2 зоны, у канализации и возле мониторов)

Боты идут только к той точке спасения, которая была поставлена в первую очередь во время создания вэйпоинта для карты, все остальные точки они игнорируют. Идут только к одной и той же.

**Детали окружения:**
 - ОС: Windows 10 Pro x64 21H2
 - Движок: Оригинальный 8684
 - GameDLL: Оригинальный
 - Metamod: нет
 - Версия бота: 4.2.685 (с GitHub Actions)
 - Режим игры: Обычный

**Comment by jeefo** [comment]
Они идут к ближайшей...

**Comment by Vladislav4KZ** [comment]
> Они идут к ближайшей...

Хз, я поставил заложника рядом с зоной спасения, бот взял и отвёл его вообще в другую, дальнюю зону спасения. Хотя заложник стоял в паре шагов от зоны спасения

Проверял на карте: cs_747

**Comment by jeefo** [comment]
Сейчас проблема актуальна?
