### ISSUE TITLE
Когда бот находится в воде, на экране появляется эффект подводного тумана

### ISSUE THREAD

**Issue by Vladislav4KZ** [yapb/yapb#336]
Этот туман ещё может мерцать
![fy_poolparty0003.png](https://user-images.githubusercontent.com/22411953/163988349-292f7ec1-c514-4e0b-84ed-593a263f0754.png)

**Детали окружения:**
 - ОС: Windows 10 Pro x64 21H2
 - Движок: Оригинальный 8684
 - GameDLL: Оригинальный
 - Metamod: нет
 - Версия бота: 4.2.685 (с GitHub Actions)
 - Режим игры: Обычный

**Comment by Vladislav4KZ** [comment]
Скрин сделал в режиме наблюдателя, и в yb_debug_goal указал номер точки находящийся в воде чтобы поймать баг.

Хотя этот баг проявляется также когда игрок живой. Просто когда любой бот начнёт плавать в воде, появляется мерцающий туман.

**Comment by jeefo** [comment]
а на движке fwgs такое есть?)

**Comment by Vladislav4KZ** [comment]
> а на движке fwgs такое есть?)

На Xash3D FWGS 0.19.3 + CS16Client собранный под Windows, такого бага нет.

На форке Xash3D FWGS 0.20.1 с поддержкой VGUI2 https://github.com/kungfulon/xash3d-fwgs и оригинальным client.dll Counter-Strike 1.6 не удалось поиграть с ботами. Ксаш крашится с ошибкой
```
assert failed at D:\a\xash3d-fwgs\xash3d-fwgs\engine\server\sv_game.c:4176
```

Оригинальный Xash3D FWGS 0.20.1 без поддержки VGUI2 с собранным CS16Client под Windows вообще не запускает Counter-Strike 1.6

**Comment by jeefo** [comment]
это pool_day?

**Comment by Vladislav4KZ** [comment]
> это pool_day?

На скрине fy_poolparty, хотя на fy_pool_day тоже хорошо заметен баг.

**Comment by jeefo** [comment]
На линуксе особо не воспроизводится. А если отключить модуль ботов, то всё ок?

**Comment by Vladislav4KZ** [comment]
> На линуксе особо не воспроизводится. А если отключить модуль ботов, то всё ок?

Без ботов конечно всё норм, если бы был косяк в самой игре, я бы не репорил...

**Comment by Vladislav4KZ** [comment]
> На линуксе особо не воспроизводится.

У меня тоже почему-то баг перестал появляться, даже когда намеренно загонял бота в воду. Хотя сам баг старый, я наблюдал его плюс-минус два года

**Comment by Vladislav4KZ** [comment]
@jeefo В режиме наблюдателя удалось воспроизвести баг

**Comment by jeefo** [comment]
> @jeefo В режиме наблюдателя удалось воспроизвести баг
![fy_poolparty0005](https://user-images.githubusercontent.com/1781346/164188212-7eeab704-583e-4ba0-a127-0987a3d2ed1f.jpg)

**Comment by Vladislav4KZ** [comment]
Выяснил причину, запустил лицензионную Counter-Strike 1.6 со стима, проверил, бага нет.

А на пиратке, билд тот же что и на стим версии, но баг присутствует. Кстати со zBot то же самое происходит. Когда люди плавают в воде, такого не происходило.

Так как этот баг не относится к YaPB я закрываю эту issue.

**Comment by Vladislav4KZ** [comment]
Точнее, дело даже в ReGameDLL, на пиратке он стоял. Без него, бага нет.
