### ISSUE TITLE
Когда стреляешь по тиммейту, он может произносить фразы из Chatter_TeamKill

### ISSUE THREAD

**Issue by Vladislav4KZ** [yapb/yapb#337]
Т.е. когда стреляешь по боту (когда mp_friendlyfire 1) у него реакция как будто игрок убил тиммейта, хотя на самом деле он его только ранил. Фразы из Chatter_TeamKill должны произносится при убийстве союзника а не при его ранении.

А получается так, что бот при ранении произносит фразы как из Chatter_FriendlyFire, так из Chatter_TeamKill.

**Детали окружения:**
 - ОС: Windows 10 Pro x64 21H2
 - Движок: Оригинальный 8684
 - GameDLL: Оригинальный
 - Metamod: нет
 - Версия бота: 4.2.685 (с GitHub Actions)
 - Режим игры: Обычный

**Comment by Vladislav4KZ** [comment]
И по поводу текстового чата. Пока рылся в коде, нашёл не использованную категорию чат сообщений [TEAMATTACK], возможно, это подходило бы для сообщений которые пишет бот при его ранении, а сообщения из [TEAMKILL] при его убийстве.

**Comment by jeefo** [comment]
Teamkill в чаттере нет, и да, фразы оттуда записываются в friendlyfire, отключить?
