### ISSUE TITLE
Не переводится последняя строчка в lang конфиге

### ISSUE THREAD

**Issue by Vladislav4KZ** [yapb/yapb#340]
Раньше был костыль, в виде строчки "EndOfFile" в конце конфига. Сейчас её убрали, и там находится такая последняя строчка
```
[ORIGINAL]
You're launched standalone version of %s. Metamod is not installed or not enabled!

[TRANSLATED]
Вы запустили автономную версию %s. Metamod не установлен или не включён!
```

Когда я ввожу в консоль команду `meta` когда metamod не установлен, появляется эта не переведённая строчка.

Когда в языковой конфиг добавил новую строчку в конец файла, то вышеуказанная строка перевелась.

**Детали окружения:**
 - ОС: Windows 10 Pro x64 21H2
 - Движок: Оригинальный 8684
 - GameDLL: Оригинальный
 - Metamod: нет
 - Версия бота: 4.2.689 (с GitHub Actions)
 - Режим игры: Обычный

**Comment by jeefo** [comment]
добавление лишнего пробела внизу не помогает?

**Comment by Vladislav4KZ** [comment]
> добавление лишнего пробела внизу не помогает?

Там уже была новая пустая строка в конце файла. Попробовал добавить ещё одну, не помогает.

Помогает только способ с созданием новой строки для перевода (можно даже пустой)
```
[ORIGINAL]


[TRANSLATED]

```
