### ISSUE TITLE
How to avoid bot picking up weapons?

### ISSUE THREAD

**Issue by gary00k** [yapb/yapb#342]
Hello,
I got a problem. I have cod mod server and there is blocked picking up weapons from the ground. But bots are trying to pick it up. In effect, they lock themselves over this weapon.
Is there any possibility (maybe some cvar?) to disable bots picking up weapons from the ground?

**Comment by jeefo** [comment]
currently there's no option to disable object pickups.

I will add cvar for this

**Comment by gary00k** [comment]
do you know when?

**Comment by Vladislav4KZ** [comment]
@gary00k can you test this build: https://github.com/yapb/yapb/actions/runs/2369441000 ?

Download and install yapb binary to ``cstrike/addons/yapb/bin``
``yapb.dll`` - for Windows
``yapb.so`` - for Linux (x86)
``yapb.arm64.so`` - for Linux (arm64)
``yapb.dylib`` - for macOS

And set the ``yb_pickup_best`` cvar to ``0``

**Comment by Vladislav4KZ** [comment]
Can you upload the "cod mod" to somewhere?

I tested on vanilla CS 1.6 without any AMXX plugins, and if ``yb_pickup_best`` = ``0``, the bots will ignore any weapon lying on the floor when it have his own weapon.

Bot can pick up a weapon when it is under its feet and it doesn't have his own weapon.

**Comment by gary00k** [comment]
Its QTM Cod MW (https://amxx.pl/topic/36961-call-of-duty-mw-mod-update/)
Bots has only pistol (usp). If you want, I can record it and upload to youtube.

**Comment by Vladislav4KZ** [comment]
> Its QTM Cod MW (https://amxx.pl/topic/36961-call-of-duty-mw-mod-update/) Bots has only pistol (usp). If you want, I can record it and upload to youtube.


I installed this mod and typed the ``yb_pickup_best 0`` cvar into the console, and didn't notice this bug. For me it works perfectly, and nobody gets stuck.

**Comment by gary00k** [comment]
Well, I don't know if we're talking about the same thing. I recorded demo, maybe could you have a look? https://skill-town.eu/bots.dem
They have some weapon (pistol in this case), but stucked on some weapon on the floor. yb_pickup_best is set to 0.

**Comment by Vladislav4KZ** [comment]
> I recorded demo, maybe could you have a look?

Before uploading the demo, you must also attach all the necessary files to play it.

I can't play the demo due to a missing "models/QTM_CodMod/pallet_with_bags2.mdl" model

By the way, I have this CodMod installed that you sent me from the link above

**Comment by gary00k** [comment]
Yes, I uploaded this one from Vladislav's link a few posts ago.

Here is the video: https://www.youtube.com/watch?v=OigTbhd1WIc
Bot stucked at some weapon, he got only pistol. He attacks me when he see my, but cannot move.

**Comment by Vladislav4KZ** [comment]
> Yes, I uploaded this one from Vladislav's link a few posts ago.
> 
> Here is the video: https://www.youtube.com/watch?v=OigTbhd1WIc
> Bot stucked at some weapon, he got only pistol. He attacks me when he see my, but cannot move.

Yes, that's what I was talking about. I don't have this problem with yb_pickup_best 0.

**Comment by Vladislav4KZ** [comment]
@gary00k can you write the details of the environment: what plugins are installed on the server, what OS, what build of the game engine, whether rehlds and regamedll are used?

**Comment by Vladislav4KZ** [comment]
When you type in the console ``yb_jasonmode 1``, do you have the same bug?

**Comment by gary00k** [comment]
I did a test. I started clean test server with just rehlds, yapb and plugin that blocks weapon pickup. Problem presists:
https://www.youtube.com/watch?v=4ypmMQjO6mY

Here's my yapb.cfg:
`yb_debug "0"
yb_debug_goal "-1"
yb_user_follow_percent "40"
yb_user_max_followers "4"
yb_jasonmode "0"
yb_radio_mode "0"
yb_economics_rounds "1"
yb_walking_allowed "1"
yb_camping_allowed "0"
yb_camping_time_min "15.0"
yb_camping_time_max "45.0"
yb_tkpunish "1"
yb_freeze_bots "0"
yb_spraypaints "1"
yb_botbuy "1"
yb_destroy_breakables_around "1"
yb_object_pickup_radius "512.0"
yb_chatter_path "sound/radio/bot"
yb_restricted_weapons ""
yb_attack_monsters "1"
yb_pickup_custom_items "0"
yb_ignore_objectives "0"
yb_random_knife_attacks "1"
yb_chat "0"
yb_chat_percent "25"
yb_shoots_thru_walls "2"
yb_ignore_enemies "0"
yb_check_enemy_rendering "1"
yb_check_enemy_invincibility "0"
yb_stab_close_enemies "1"
yb_bind_menu_key "="
yb_ignore_cvars_on_changelevel "yb_quota,yb_autovacate"
yb_display_menu_text "0"
yb_password "vtf76i7ntbkjhljniibft"
yb_password_key "_ybpw"
yb_csdm_mode "3"
yb_graph_fixcamp "1"
yb_graph_url "yapb.jeefo.net"
yb_autovacate "1"
yb_quota "9"
yb_quota_mode "normal"
yb_quota_match "0"
yb_think_fps "30.0"
yb_autokill_delay "0.0"
yb_join_after_player "0"
yb_join_team "any"
yb_join_delay "10.0"
yb_name_prefix ""
yb_difficulty "3"
yb_difficulty_min "0"
yb_difficulty_max "2"
yb_difficulty_auto "0"
yb_show_avatars "1"
yb_show_latency "2"
yb_save_bots_names "1"
yb_botskin_t "0"
yb_botskin_ct "0"
yb_ping_base_min "11"
yb_ping_base_max "49"
yb_language "en"
yb_whose_your_daddy "0"
yb_path_heuristic_mode "4"
yb_path_danger_factor_min "200"
yb_path_danger_factor_max "400"
yb_display_welcome_text "0"
yb_enable_query_hook "0"
yb_pickup_best 0`

**Comment by gary00k** [comment]
EDIT:
Nevermind, looks like I should type yb_pickup_best "0" instead of yb_pickup_best 0 :D

**Comment by Vladislav4KZ** [comment]
> EDIT:
> Nevermind, looks like I should type yb_pickup_best "0" instead of yb_pickup_best 0 :D

So, now you don't have this problem?

**Comment by gary00k** [comment]
Yes, seems like the problem was no quotes in "0".

**Comment by Vladislav4KZ** [comment]
Good, closing.
