### ISSUE TITLE
Bots try to go through the walls for all eternity.

### ISSUE THREAD

**Issue by XuberAxel** [yapb/yapb#347]
I have a CTF server with reHLDS and have yapb-4.2.637-linux. For some strange reason as time goes on in the game, the bots just try to make their paths through walls anywhere on the map. They can't go through walls but they try and get stuck. The AI is still working fine except for what I explained. I think this has to do with the round being infinite because even if they die, when they respawn they keep trying to go through the walls and this bug does not happens with normal rounds. To fix it I have to kick the stucked bots.

There is another error and that is that the bots do not buy anything but only the first time they appear on the server and even if they die and respawn, they do not buy anything. They should stick around to buy their weapons like they do at the beginning of the map.

These problems should be fixed because it is very annoying that suddenly there is no one on the map and it is because the bots have been bugged on the walls.

**Environment details:**
 - OS: [linux]
 - Engine:
 Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
ReHLDS version: 3.11.0.767-dev
Build date: 03:13:55 Oct 25 2021 (2753)
Build from: https://github.com/dreamstalker/rehlds/commit/471158b

 - GameDLL: [regamedll]
 - Metamod:
 Metamod v1.21p37  2013/05/30 (5:13)
by Will Day
   http://www.metamod.org/
 Patch: Metamod-P (mm-p) v37
 by Jussi Kivilinna
    http://metamod-p.sourceforge.net/
compiled: May 30 2013, 11:41:16 EET (optimized)

 - Bot Version: [4.2.637]
 - Game mode: [reapi_jctf]
 - AMXX Plugins: 
Currently loaded plugins:
       name                    version     author            file             status   
 [  1] Admin Base              1.9.0.5294  AMXX Dev Team     admin.amxx       running  
 [  2] Admin Commands          1.9.0.5294  AMXX Dev Team     admincmd.amxx    running  
 [  3] Admin Help              1.9.0.5294  AMXX Dev Team     adminhelp.amxx   running  
 [  4] Slots Reservation       1.9.0.5294  AMXX Dev Team     adminslots.amxx  running  
 [  5] Multi-Lingual System    1.9.0.5294  AMXX Dev Team     multilingual.am  running  
 [  6] Menus Front-End         1.9.0.5294  AMXX Dev Team     menufront.amxx   running  
 [  7] Commands Menu           1.9.0.5294  AMXX Dev Team     cmdmenu.amxx     running  
 [  8] Players Menu            1.9.0.5294  AMXX Dev Team     plmenu.amxx      running  
 [  9] Teleport Menu           1.9.0.5294  AMXX Dev Team     telemenu.amxx    running  
 [ 10] Maps Menu               1.9.0.5294  AMXX Dev Team     mapsmenu.amxx    running  
 [ 11] Plugin Menu             1.9.0.5294  AMXX Dev Team     pluginmenu.amxx  running  
 [ 12] Admin Chat              1.9.0.5294  AMXX Dev Team     adminchat.amxx   running  
 [ 13] Anti Flood              1.9.0.5294  AMXX Dev Team     antiflood.amxx   running  
 [ 14] Scrolling Message       1.9.0.5294  AMXX Dev Team     scrollmsg.amxx   running
 [ 15] Info. Messages          1.9.0.5294  AMXX Dev Team     imessage.amxx    running  
 [ 16] Admin Votes             1.9.0.5294  AMXX Dev Team     adminvote.amxx   running  
 [ 17] NextMap                 1.9.0.5294  AMXX Dev Team     nextmap.amxx     stopped  
 [ 18] TimeLeft                1.9.0.5294  AMXX Dev Team     timeleft.amxx    running  
 [ 19] Pause Plugins           1.9.0.5294  AMXX Dev Team     pausecfg.amxx    running  
 [ 20] Stats Configuration     1.9.0.5294  AMXX Dev Team     statscfg.amxx    running  
 [ 21] Restrict Weapons        1.9.0.5294  AMXX Dev Team     restmenu.amxx    running  
 [ 22] Autoresponder/Advertis  0.5         MaximusBrood      ad_manager.amxx  running  
 [ 23] Admin Prefixes          4.0         m0skVi4a ;]       AdminPrefixes.a  running  
 [ 24] Advanced Weapon Tracer  1.3.0       ConnorMcLeod      advanced_weapon  running  
 [ 25] GasNades                2.0.0       ConnorMcLeod      amx_gasnades.am  running  
 [ 26] ANTI-SPAM               1.4         Emanuelitop15     anti_spam.amxx   running  
 [ 27] Team Semiclip           2.0.0       schmurgel1983     API-TeamSemicli  running  
 [ 28] Automatic Unstuck       1.5         NL)Ramon(NL       auto_unstuck.am  running  
 [ 29] BIENVENIDA              1.0         Emanuelitop15     Bienvenida_Pres  running
 [ 30] BOTS BUY                1.          Emanuelitop15     bots_buy.amxx    running  
 [ 31] Bullet Damage           2.0         Bboy Grun         bullet_damage.a  running  
 [ 32] Bullet Whizz            1.4         Cheap_Suit        Bullet_Whizz.am  running  
 [ 33] Super Bunny Hopper      1.2         Cheesy Peteza     bunnyhop_super.  running  
 [ 34] TF2: Domination         1.4         Emanuelitop15     ctf_tf2_dominat  running  
 [ 35] Flashbang Dynamic Ligh  0.21        Avalanche         flashbang_dligh  running  
 [ 36] Galileo                 v6.0        Brad Jones/Addon  galileo.amxx     running  
 [ 37] unknown                 unknown     unknown           GHW_connect.amx  bad load 
 [ 38] Grenade Enhancer        1.2         anakin_cstrike    grenade_enhance  running  
 [ 39] Loading Music II        1.2.9       Simon Logic       loading_music2.  running  
 [ 40] Map Spawns Editor       1.0.16      iG_os             Map_Spawns_Edit  running  
 [ 41] mute menu               1.1         Emanuelitop15     mutemenu.amxx    running  
 [ 42] NadeModes               11.2        Nomexous & OT     nademodes.amxx   running  
 [ 43] Ping Faker              1.5a        MeRcyLeZZ         pingfaker.amxx   running  
 [ 44] Xuber CTF               v1.3.6      XuberAxel y Eman  reapi_jctf.amxx  running
 [ 45] ResetScore              1.1         Emanuelitop15     ResetScore.amxx  running  
 [ 46] Ultra Streak Sounds     1.5 fix     Emanuelitop15     Ultra_Streak_So  running  
 [ 47] Sniper Spark / Laser D  1.2         Numb              sniper_spark_la  running  
 [ 48] Speedometer             1.2         AciD              speedometer.amx  running  
 [ 49] Team Grenade Trail      1.2         Numb              team_grenade_tr  running  
 [ 50] Vampire                 1.0c        Shalfey           vampire.amxx     running  
 [ 51] WalkGuard               1.3.2       mogel             walkguard.amxx   running  
 [ 52] Weapon Menu             1.0         Mattcook & xerob  weaponmenu.amxx  running  
 [ 53] CTF Menu                v1.11       LA SOMBRA DEMONI  CTFmenu.amxx     running  
 [ 54] CTF Menu Informativo    v1.1        LA SOMBRA DEMONI  CTFMenuInformat  running  
 [ 55] CTF Informacion Motd    v1.0        totopizza         CTFInformacionM  running  
 [ 56] CTF Reglas Motd         v1.0        totopizza         CTFReglasMotd.a  running  
( 37) Load fails: Plugin uses an unknown function (name "geoip_country") - check your modules.ini.
56 plugins, 54 running

Please help... And if you can, develop a aim error system for the bots please... Thank you.

**Comment by rust2** [comment]
Seems you have to edit waypoints manually

**Comment by XuberAxel** [comment]
> 

I manually edit waypoints of the bots, but they keep getting stuck on the wall. :( I need help!

**Comment by commandcobra7** [comment]
Please take a look at my edit.

https://github.com/yapb/yapb/actions/runs/3281105238

**Comment by Vladislav4KZ** [comment]
Which map?

**Comment by XuberAxel** [comment]
> Which map?

Sorry for the delay. This happens in all maps but I can't test it again because I don't have the server anymore. I still have a Windows version of the bots and I can test them there but it should be better with the server. I can't have a server in these moments for now... Maybe some day...
