### ISSUE TITLE
Настройки для конкретных карт

### ISSUE THREAD

**Issue by willbegithub** [yapb/yapb#348]
Если в папке yapb/conf/maps создать конфиг файл, к примеру de_dust2.cfg с кваром yb_quota "5", то на всех картах будет yb_quota "5"

**Comment by Vladislav4KZ** [comment]
> Если в папке yapb/conf/maps создать конфиг файл, к примеру de_dust2.cfg с кваром yb_quota "5", то на всех картах будет yb_quota "5"

Какая версия бота, плагины, операционка? Есть metamod или нет, используется ли ReGameDLL или нет?

У меня такого бага нет, последняя версия бота для Windows с GitHub Actions: YaPB v4.2.691
Конфиг, который я создал в папке `` yapb/conf/maps`` для карты, выполняется только на той карте, для которой он предназначен.

**Comment by Vladislav4KZ** [comment]
И кстати это нет баг, потому-что по умолчанию квар ``yb_ignore_cvars_on_changelevel`` настроен на ``yb_quota,yb_autovacate``

То есть, после смены карты, значения кваров ``yb_quota`` и ``yb_autovacate`` будут сохранены, и не будут считываться с главного конфига ``yapb.cfg``

**Comment by willbegithub** [comment]
> И кстати это не баг, потому-что по умолчанию квар `yb_ignore_cvars_on_changelevel` настроен на `yb_quota,yb_autovacate` [Ссылка на квар в документации](https://yapb.readthedocs.io/ru/latest/configuring.html#yb-ignore-cvars-on-changelevel)
> 
> То есть, после смены карты, значения кваров `yb_quota` и `yb_autovacate` будут сохранены, и не будут считываться с главного конфига `yapb.cfg`

То есть, нужно указать yb_ignore_cvars_on_changelevel "" - пустым? Чтобы только для определенной карты работал не стандартный yb_quota

**Comment by Vladislav4KZ** [comment]
> То есть, нужно указать yb_ignore_cvars_on_changelevel "" - пустым? Чтобы только для определенной карты работал не стандартный yb_quota

Да

**Comment by Vladislav4KZ** [comment]
Вообщем, закрываю. Решение я уже написал выше, буквально спустя 15 минут после твоего вопроса. А спустя 5 дней так и нет ответа. Хотя, вообще должно работать нормально, если сделал всё как я сказал.

**Comment by willbegithub** [comment]
Всё работает!
