### ISSUE TITLE
Bots see invisible players

### ISSUE THREAD

**Issue by gary00k** [yapb/yapb#349]
Hello,
I found another problem when using bots on my cod mod server. The problem is, bots always see invisible players. I mean full invisibility (player render alpha set to 0).

Could you add a feature: if player alpha render is set to 0, bots always ignore this player, if it's set to eg. 128, bots have 50% "to see" the player, if 191 then 75%, etc.?

**Comment by gary00k** [comment]
Nothing?

**Comment by jeefo** [comment]
https://yapb.readthedocs.io/en/latest/configuring.html#yb-check-enemy-rendering

?

**Comment by gary00k** [comment]
Will try, thakns.
