### ISSUE TITLE
Проблема с Bot Features

### ISSUE THREAD

**Issue by willbegithub** [yapb/yapb#351]
Добрый день, падает сервер в связке ReHLDS, ReGameDLL, ReAPI, YaPB и Bot Features (by Vaqtincha). Возможно вы знаете решение проблемы падений Seg. fault, или есть ли в разработке ваш собственный плагин с тем же функционалом

**Comment by Nord1cWarr1or** [comment]
Скиньте версии всех дополнений и плагина. У меня сервер не падает с этим плагином
