### ISSUE TITLE
VIP Bots keeps trying to pickup weapons.

### ISSUE THREAD

**Issue by PRinceBhai** [yapb/yapb#355]
**Describe the bug**
VIP Bot tries to pickup weapons while he can't because he's not supposed to.

**Expected behavior**
Bot should not bother with picking up a weapon he should prefer running to the Escape Zone.

**Video**
(https://youtu.be/wDJKRc8aIJc)

**Environment details:**
 - OS: [windows 7]
 - Engine: [REHLDS 3.8.0.702]
 - GameDLL: [REGameDLL 5.18.0.479]
 - Metamod: [metamod-p 1.21]
 - Bot Version: [e.g. 4.2.671]
 - Game mode: [e.g. csdm / public / zombie]

List of AMX Mod X plugins:

Loaded plugins:
       id  name                    version     author            url                              file         status   
 [  1] 0   Admin Base              1.10.0.546  AMXX Dev Team                                      admin.amxx   running  
 [  2] 1   Admin Commands          1.10.0.546  AMXX Dev Team                                      admincmd.am  running  
 [  3] 2   Admin Help              1.10.0.546  AMXX Dev Team                                      adminhelp.a  running  
 [  4] 3   Slots Reservation       1.10.0.546  AMXX Dev Team                                      adminslots.  running  
 [  5] 4   Multi-Lingual System    1.10.0.546  AMXX Dev Team                                      multilingua  running  
 [  6] 5   Menus Front-End         1.10.0.546  AMXX Dev Team                                      menufront.a  running  
 [  7] 6   Commands Menu           1.10.0.546  AMXX Dev Team                                      cmdmenu.amx  running  
 [  8] 7   Players Menu            1.10.0.546  AMXX Dev Team                                      plmenu.amxx  running  
 [  9] 8   Teleport Menu           1.10.0.546  AMXX Dev Team                                      telemenu.am  running  
 [ 10] 9   Maps Menu               1.10.0.546  AMXX Dev Team                                      mapsmenu.am  running  
 [ 11] 10  Plugin Menu             1.10.0.546  AMXX Dev Team                                      pluginmenu.  running  
 [ 12] 11  Admin Chat              1.10.0.546  AMXX Dev Team                                      adminchat.a  running  
 [ 13] 12  Anti Flood              1.10.0.546  AMXX Dev Team                                      antiflood.a  running  
 [ 14] 13  Scrolling Message       1.10.0.546  AMXX Dev Team                                      scrollmsg.a  running  
 [ 15] 14  Info. Messages          1.10.0.546  AMXX Dev Team                                      imessage.am  running  
 [ 16] 15  Admin Votes             1.10.0.546  AMXX Dev Team                                      adminvote.a  running  
 [ 17] 16  NextMap                 1.10.0.546  AMXX Dev Team                                      nextmap.amx  running  
 [ 18] 17  Nextmap Chooser         1.10.0.546  AMXX Dev Team                                      mapchooser.  running  
 [ 19] 18  TimeLeft                1.10.0.546  AMXX Dev Team                                      timeleft.am  running  
 [ 20] 19  Pause Plugins           1.10.0.546  AMXX Dev Team                                      pausecfg.am  running  
 [ 21] 20  Stats Configuration     1.10.0.546  AMXX Dev Team                                      statscfg.am  running  
 [ 22] 21  Restrict Weapons        1.10.0.546  AMXX Dev Team                                      restmenu.am  running  
 [ 23] 22  StatsX                  1.10.0.546  AMXX Dev Team                                      statsx.amxx  running  
 [ 24] 23  CS Misc. Stats          1.10.0.546  AMXX Dev Team                                      miscstats.a  running  
 [ 25] 24  CS Stats Logging        1.10.0.546  AMXX Dev Team                                      stats_loggi  running  
 [ 26] 25  4-4 RoF Mod             1.0         hellmonja         unknown                          Customs\44_  running  
 [ 27] 26  Accuracy Fix            3.0         Numb              unknown                          Customs\acc  running  
 [ 28] 27  Achievements            2.3         Pastout!                                           Customs\Ach  debug    
 [ 29] 28  Advanced Chat           5.0.1       tuty              unknown                          Customs\Adv  running  
 [ 30] 29  Advanced Mute           2.1         OciXCrom          unknown                          Customs\crx  running  
 [ 31] 30  Advanced Weapon Tracer  1.3.0       ConnorMcLeod      unknown                          Customs\adv  running  
 [ 32] 31  Anti Silent-run         1.2         Numb              unknown                          Customs\ant  running  
 [ 33] 32  Anti Fast Silencer      0.0.4       ConnorMcLeod      unknown                          Customs\ant  running  
 [ 34] 33  Anti He Bug             1.1         Numb              unknown                          Customs\ant  running  
 [ 35] 34  Reloaded Weapons On Ne  2.1.0       ConnorMcLeod      unknown                          Customs\aut  running  
 [ 36] 35  BackWeapon 3            0.0.6       ConnorMcLeod      unknown                          Customs\bac  running  
 [ 37] 36  Bad Camper              1.4 beta    Brad Jones        unknown                          Customs\bad  running  
 [ 38] 37  Bad Spawns Preventer    1.2         xPaw              unknown                          Customs\Bad  running  
 [ 39] 38  Bot Features            0.9         Vaqtincha                                          Customs\Bot  running  
 [ 40] 39  Best Player MOTD        1.2.1       OciXCrom          unknown                          Customs\crx  running  
 [ 41] 40  Bomb has been defused   1.1         xPaw              unknown                          Customs\Bom  running  
 [ 42] 41  BOMB Ghosting Fix       1.2         Numb              unknown                          Customs\bom  running  
 [ 43] 42  Bomb Scenario           1.0         xPaw              unknown                          Customs\Bom  running  
 [ 44] 43  Bloody Corpses          2.0         se7h/BlackCat     unknown                          Customs\blo  running  
 [ 45] 44  Block Use Sound         1.0         OciXCrom          unknown                          Customs\crx  running  
 [ 46] 45  Bubble Trails           0.0.1       ConnorMcLeod      unknown                          Customs\bub  running  
 [ 47] 46  Buy Icon Fix            1.1         KayDee            unknown                          Customs\buy  running  
 [ 48] 47  C4 Taker                1.10        hellmonja & Haml  unknown                          Customs\c4_  running  
 [ 49] 48  c4 timer                1.1         cheap_suit        unknown                          Customs\c4t  running  
 [ 50] 49  unknown                 unknown     unknown           unknown                          Customs\cli  running  
 [ 51] 50  CS Classes Plus         0.1a        hellmonja         unknown                          Customs\cs_  running  
 [ 52] 51  CSS Flashlight          2.0         schmurgel1983     unknown                          Customs\css  running  
 [ 53] 52  Bomb/Death/CSS Radar    1.2         eDark & Numb                                       Customs\css  running  
 [ 54] 53  FlashBang Color Fix     1.0.1       GlaDiuS | [PRinc  unknown                          Customs\Fla  debug    
 [ 55] 54  Default FOV             0.0.1       ConnorMcLeod      unknown                          Customs\def  running  
 [ 56] 55  Drop Nvg                3.1         tuty              unknown                          Customs\dro  running  
 [ 57] 56  [ER] Escape: Reborn     0.4         mx?!                                               Customs\esc  stopped  
 [ 58] 57  Pushable Object Speed   1.0         Numb              unknown                          Customs\fun  running  
 [ 59] 58  GunGame AMXX            2.13c       Avalanche         unknown                          Customs\Gun  running  
 [ 60] 59  GHW Connect Messages    1.1         GHW_Chronic                                        Customs\GHW  running  
 [ 61] 60  GHW Objective Messages  2.1         GHW_Chronic       unknown                          Customs\GHW  running  
 [ 62] 61  Glock/Famas Anti 4 Bul  0.0.2       ConnorMcLeod      unknown                          Customs\glo  running  
 [ 63] 62  CZ Tutor Messages - En  1.0         Sneaky.amxx | Gl  unknown                          Customs\gms  running  
 [ 64] 63  Pop Grenades            1.0         EFFx/HamletEagle  unknown                          Customs\Gre  running  
 [ 65] 64  Grenade/C4 Fixes & Hud  1.2         Numb              unknown                          Customs\gre  running  
 [ 66] 65  hl_weapon_physics       0.6         Turanga_Leela     unknown                          Customs\hl_  running  
 [ 67] 66  Hostage Icon            1.0         KriegsGeBiet      unknown                          Customs\hos  running  
 [ 68] 67  Kevlar pickup fix       1.0         xPaw              unknown                          Customs\Kev  running  
 [ 69] 68  Loading Music II        1.2.9       Simon Logic       unknown                          Customs\loa  running  
 [ 70] 69  Non-sprite set to glow  1.0         xPaw              unknown                          Customs\Non  running  
 [ 71] 70  Precache Manager        1.0         Sneaky.amxx       unknown                          Customs\Pre  running  
 [ 72] 71  Random Buy              1.1         ConnorMcLeod, he  unknown                          Customs\ran  running  
 [ 73] 72  Ultimate Fire in the H  2.0         OciXCrom          unknown                          Customs\crx  running  
 [ 74] 73  ServerName              0.1         Vaqtincha                                          Customs\Ser  running  
 [ 75] 74  Spawn Protection        1.0.1       OciXCrom          unknown                          Customs\crx  running  
 [ 76] 75  Spray bug fix           1.1         Simo123           unknown                          Customs\spr  running  
 [ 77] 76  [SCM] Entity Editor     1.3.1       schmurgel1983     unknown                          Customs\TSC  running  
 [ 78] 77  [CS] Team Semiclip      3.3.1       schmurgel1983     unknown                          Customs\TSC  running  
 [ 79] 78  Vehicle Knife Sound Fi  1.0         KayDee            unknown                          Customs\veh  running  
 [ 80] 79  Water Fall Damage       0.10        Avalanche         unknown                          Customs\wat  running  
 [ 81] 80  WarmUP Pro              5.6 Beta    ReymonARG         unknown                          Customs\war  running  
 [ 82] 81  Weapon Balance Mod      1.9         Numb              unknown                          Customs\wea  running  
 [ 83] 82  Weapon Lights           0.7.1       HiSS & Arkshine   unknown                          Customs\wea  running  
 [ 84] 83  Molotov Cocktail        0.01a(3.30  DynamicBits, [PR                                   Customs\mol  debug    
 [ 85] 84  CS:GO CZ75              2.4.4       Sneaky.amxx, dia  unknown                          CSWS/csgo_c  debug    
 [ 86] 85  CS:GO MAG-7             1.5.1       Sneaky.amxx, dia  unknown                          CSWS/csgo_m  debug    
 [ 87] 86  CS:GO Negev             1.3.1       Sneaky.amxx, dia  unknown                          CSWS/csgo_n  debug    
 [ 88] 87  CS:GO R8 Revolver       1.2.1       Sneaky.amxx, dia  unknown                          CSWS/csgo_r  debug    
 [ 89] 88  CS:GO Sawed-Off Shotgu  1.6.1       Sneaky.amxx, dia  unknown                          CSWS/csgo_s  debug    
 [ 90] 89  CS:GO Tec-9             2.6.1       Sneaky.amxx, dia  unknown                          CSWS/csgo_t  debug    
 [ 91] 90  CSGO: Death and Money   2.0.1       Digi, ConnorMcle  unknown                          CSWS/csgo_d  debug    
 [ 92] 91  Weapon Price Editor     1.1         ConnorMcLeod, he  unknown                          CSWS/weapon  debug    
 [ 93] 92  CS:GO Inspect Weapon    5.1.5       hellmonja                                          CSWS/csgo_i  debug    
 [ 94] 93  CS:GO Arm Switcher Adv  2.6         Cheap_Suit & hel  unknown                          CSWS/csgo_a  debug    

List of Metamod plugins: 

Loaded plugins:
      description      stat pend  file              vers      src   load  unlod
 [ 1] AMX Mod X        RUN   -    amxmodx_mm.dll    v1.10.0.  ini   Start ANY  
 [ 2] YaPB             RUN   -    yapb.dll          v4.2.671  ini   Chlvl ANY  
 [ 3] okapi            RUN   -    okapi_amxx.dll    v1.0      pl1   ANY   ANY  
 [ 4] Orpheu           RUN   -    orpheu_amxx.dll   v2.6.3    pl1   ANY   ANY  
 [ 5] FakeMeta         RUN   -    fakemeta_amxx.dl  v1.10.0.  pl1   ANY   ANY  
 [ 6] CStrike          RUN   -    cstrike_amxx.dll  v1.10.0.  pl1   ANY   ANY  
 [ 7] Ham Sandwich     RUN   -    hamsandwich_amxx  v1.10.0.  pl1   ANY   ANY  
 [ 8] CSX              RUN   -    csx_amxx.dll      v1.10.0.  pl1   ANY   ANY  
 [ 9] Engine           RUN   -    engine_amxx.dll   v1.10.0.  pl1   ANY   ANY  
 [10] Fun              RUN   -    fun_amxx.dll      v1.10.0.  pl1   ANY   ANY  
 [11] ReAPI            RUN   -    reapi_amxx.dll    v5.21.0.  pl1   ANY   Never
 [12] GeoIP            RUN   -    geoip_amxx.dll    v1.10.0.  pl1   ANY   ANY  

**Additional context**
Note that the player model in the video is not a VIP skin this happens on round 3. And only the bot with this skin has this behavior.

**Suggestion**
Make CT Bots follow or escort any VIP be it a Bot or a real player.

**Comment by jeefo** [comment]
Hello.

Try build frorm https://github.com/yapb/yapb/actions/runs/2777903469 when it's ready.

**Comment by PRinceBhai** [comment]
> Hello.
> Try build from https://github.com/yapb/yapb/actions/runs/2777903469

VIP Bot now doesn't try to pickup weapons, but please try to make normal CT Bots to follow VIP Bot as VIP Bot rushes all by himself and gets himself killed from Camping Terrorists.

Thanks.

**Comment by jeefo** [comment]
I believe second part needs a separate issue / feature request.
