### ISSUE TITLE
make bot aim miss randomly

### ISSUE THREAD

**Issue by ghost** [yapb/yapb#357]
is there a way to make the bot aim more human? they hit too well. the only thing to change is the delay time and HS etc. but no random miss % like in pod bots...

**Comment by Vladislav4KZ** [comment]
Work on this is already in Pull Request https://github.com/yapb/yapb/pull/204

But I don't know when @Hedgefog will finish this.

**Comment by kaktuspo** [comment]
just for anybody, i now lower the damage a bot does in my plugin, and even set HS dmg to 1%

**Comment by kaktuspo** [comment]
i put the dmg by bots to 1%, and now the bots shoot on my players heads perfectly inhumane 5 times headshot in a row, doing almost no damage, but its clear its an aimbot! and i set yapb headshot chance to 1 in difficulty........ man how can this be solved

**Comment by Vladislav4KZ** [comment]
Implemented in the commit: https://github.com/yapb/yapb/commit/1a650c57ce06b9956532a13de9583e881689d03b
