### ISSUE TITLE
If you need a new feature...

### ISSUE THREAD

**Issue by jeefo** [yapb/yapb#364]
Hello

Well, currently due to strange decisions from our (RU) country, i have hard time to find time to do anything with YaPB besides basic bug fixes.

But, there is a fork of SyPB bot (which is itself fork of YaPB) called [CS-EBOT,](https://github.com/EfeDursun125/CS-EBOT) by @EfeDursun125 that is actively (it seems) maintained.

So i believe it's would be good decision to forward global "things" there, especially for custom mods (like zombie) support, and switch to this fork if you need something new, as YaPB is only for classic / csdm modes and not actively updated at this time. I hope author don't mind i have posted this.

Have fun.

**Comment by commandcobra7** [comment]
Hello first of all

I'm sorry that you are in a difficult situation, I hope your problem is solved as soon as possible, you can continue with the project you are left with, solve all the bot problems because too many topics have been opened.

**Comment by MysticDeathProject** [comment]
@jeefo Thank you

**Comment by all85100** [comment]
The shooting method of the robot is too accurate and difficult. Can you modify it? The robot can easily kill the real player
