### ISSUE TITLE
Waiting for a runner to pick up this job...

### ISSUE THREAD

**Issue by gary00k** [yapb/yapb#366]
Why I can't run action on my fork? Compiling arm64 stucks on "Waiting for a runner to pick up this job..." :/

**Comment by Vladislav4KZ** [comment]
arm64 workflow works on jeefo's self-hosted server.

GitHub Actions does not provide the ability to build for arm64.

**Comment by gary00k** [comment]
Ok, so how can I compile it?

**Comment by jeefo** [comment]
why do you need arm64 build?Sent from my Galaxy
-------- Original message --------From: gary00k ***@***.***> Date: 8/29/22  21:50  (GMT+03:00) To: yapb/yapb ***@***.***> Cc: jeefo ***@***.***>, Assign ***@***.***> Subject: Re: [yapb/yapb] Waiting for a runner to pick up this job... (Issue #366) 
Ok, so how can I compile it?

**Comment by gary00k** [comment]
Well, I donno. Do I need it at all?
I would like to make some small changes in this plugin. There are 2 files with .so extension; yapb.so and yabp.arm64.so. Do I need both of them or just yapb.so?

**Comment by Vladislav4KZ** [comment]
> Well, I donno. Do I need it at all?
> I would like to make some small changes in this plugin. There are 2 files with .so extension; yapb.so and yabp.arm64.so. Do I need both of them or just yapb.so?

You need only yapb.so, you can't run yapb.arm64.so on x86 CPU architecture.

If I remember correctly, jeefo was building an arm64 library for an arm64 server running xash3d fwgs.

HLDS or ReHLDS does not support arm64 architecture.

**Comment by jeefo** [comment]
just regular yapb.soSent from my Galaxy
-------- Original message --------From: gary00k ***@***.***> Date: 8/30/22  08:09  (GMT+03:00) To: yapb/yapb ***@***.***> Cc: jeefo ***@***.***>, Assign ***@***.***> Subject: Re: [yapb/yapb] Waiting for a runner to pick up this job... (Issue #366) 
Well, I donno. Do I need it at all?
I would like to make some small changes in this plugin. There are 2 files with .so extension; yapb.so and yabp.arm64.so. Do I need both of them or just yapb.so?

**Comment by gary00k** [comment]
Thank you.
