### ISSUE TITLE
How to batch convert waypoint formats

### ISSUE THREAD

**Issue by Jockey731** [yapb/yapb#382]
How to convert the new waypoint format graph into pwf format online in batch

**Comment by PRinceBhai** [comment]
How do you even convert a .graph into a .pwf?

**Comment by Vladislav4KZ** [comment]
> How do you even convert a .graph into a .pwf?

In game console you need to write ``yb g save old``

I even wrote about this in the documentation for YaPB.

**Comment by Vladislav4KZ** [comment]
@PRinceBhai See third paragraph:
https://yapb.readthedocs.io/en/latest/waypointing.html#using-graph-commands

**Comment by Jockey731** [comment]
I know that in the game, use the yb g save old command to convert the waypoint format to pwf
However, you need to enter the game map to convert, and you must download each map to convert the format. Is there any direct conversion, or later versions support automatic downloading of the pwf format

**Comment by Jockey731** [comment]
Because I want to use waypoints in pwf format in podbot

**Comment by Vladislav4KZ** [comment]
@Jockey731 I have an old archive with waypoints in pwf format on Yandex.Disk in which I saved a whole database of waypoints from https://yapb.jeefo.net/wpdb (now replaced with https://yapb.jeefo.net/graph where graph files are respectively stored)

See yapb_waypoint_pack_5052_working.zip
https://yadi.sk/d/NYOixXW3yZ8KZw

**Comment by Jockey731** [comment]
Thank you very much. I collected some podbot waypoint files before, but I don't know how to share them. Is there any command to upload waypoints

**Comment by Vladislav4KZ** [comment]
> Thank you very much. I collected some podbot waypoint files before, but I don't know how to share them. Is there any command to upload waypoints

YaPB has a ``yb g upload`` command to upload the graph into the database so that it is downloaded automatically for all YaPB users.

Graph file will not be uploaded into the database if:
- It doesn't pass internal validation, e. g.: missing any important nodes, not in a loop (i.e. perhaps somewhere a node is connected by a one-way path in a place where there is not a single node with a connection indicating the return path)
- Graph is already exists in database

PODBot waypoints are installed in the folder ``addons/yapb/data/pwf`` and automatically converted to Graph format.

**Comment by Vladislav4KZ** [comment]
> I uploaded some waypoint files collected in 2004, and the download address
> http://cs15.noip.cn:29010/Waypoint.zip

@Jockey731 Link does not work. It says "This site cannot provide a secure connection"

**Comment by Vladislav4KZ** [comment]
Nevermind, it's Google Chrome issues

**Comment by Jockey731** [comment]
It would be great if online conversion of pwf format could be added in the future. Thank you very much for your patient answer

**Comment by jeefo** [comment]
@Jockey731 

Not online, and for windows x64 only: https://s3.rwsh.ru/share/2023/gtool.exe

@Vladislav4KZ maybe you'll be interested too

**Comment by Jockey731** [comment]
@jeefo I tried several times and didn't see any folders

**Comment by Jockey731** [comment]
Is the method I used incorrect?
![gtool](https://user-images.githubusercontent.com/113936866/229301070-37cdd56c-2114-40bc-95a7-b5b9e63f1e02.jpg)

**Comment by Vladislav4KZ** [comment]
> @jeefo Is the method I used incorrect?
> ![gtool](https://user-images.githubusercontent.com/113936866/229301070-37cdd56c-2114-40bc-95a7-b5b9e63f1e02.jpg)
> 

@Jockey731 you didn't even create a folder. ``any_folder`` is an example name of your folder which contains graphs in it.

**Comment by Jockey731** [comment]
@Vladislav4KZ I have placed the drawing file in the drawing directory
![graph](https://user-images.githubusercontent.com/113936866/229413255-357bd9ed-0a94-4343-bc36-4eb5c5a644af.jpg)

**Comment by jeefo** [comment]
change your current dir to gtool location

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Vladislav4KZ** [comment]
@Jockey731 https://www.youtube.com/watch?v=vfZTp-9yPOU

**Comment by Jockey731** [comment]
@Vladislav4KZ Thank you very much for your video and usage method

**Comment by Jockey731** [comment]
@jeefo After testing, the waypoint exceeds 1024 and cannot be converted to pwf format

**Comment by Vladislav4KZ** [comment]
> After testing, the waypoint exceeds 1024 and cannot be converted to pwf format

@Jockey731 This is a limitation of the PWF format, in this case it will not be possible to convert it from Graph to PWF waypoint format.

You either need to edit the Graph file by deleting the nodes so that their total number does not exceed 1024, or create a waypoint from scratch.
