### ISSUE TITLE
Некорректно работает чат ботов на сервере

### ISSUE THREAD

**Issue by foresl** [yapb/yapb#392]
**Describe the bug**
Некорректно работает чат ботов на сервере.

**Expected behavior**
В консоли сервера видно как боты ведут переписку, однако на самом сервере в чате пустота.
Проверил отображение чата на steam и non_steam клиентах, чат в игре отсутствует по какой-то причине, но виден в консоли управления сервером. Можете подсказать как решить проблему? По началу думал это из-за неверной кодировки ru_chat.cfg, но перекодировка в UTF-8 не помогла решить проблему.  
Команды конфига ботов yb_chat "1" и yb_chat_percent "30".

**Environment details:**
 - OS: [ linux ]
 - Engine: [ ReHLDS version: 3.11.0.767-dev-mpatch ]
 - GameDLL: [ ReGameDLL version: 5.21.0.546-dev ]
 - Metamod: [ Metamod-r v1.3.0.128 ]
 - Bot Version: [ v4.2.671 ]
 - Game mode: [ public ]

**Additionally, please provide list of AMX Mod X plugins: ``amxx plugins`` and list of Metamod plugins: ``meta plugins``.**

meta list
Currently loaded plugins:
      description      stat pend  file                        vers             src  load  unload
 [ 1] Reunion          RUN   -    reunion_mm_i386.so          v0.1.92d         ini  Start Never
 [ 2] SafeNameAndChat  RUN   -    SafeNameAndChat.so          v1.1             ini  ANY   ANY  
 [ 3] ReSRDetector     RUN   -    resrdetector_mm_i386.so     v0.1.0           ini  Chlvl ANY  
 [ 4] ReAuthCheck      RUN   -    reauthcheck_mm_i386.so      v0.1.6           ini  Start Never
 [ 5] VoiceTranscoder  RUN   -    vtc.so                      v2017RC5         ini  ANY   ANY  
 [ 6] ProcessCmds      RUN   -    processcmds_mm_i386.so      v1.2.0           ini  Start Never
 [ 7] WHBlocker        RUN   -    whblocker_mm_i386.so        v1.5.697         ini  Chlvl ANY  
 [ 8] Rechecker        RUN   -    rechecker_mm_i386.so        v2.5             ini  Chlvl ANY  
 [ 9] AMX Mod X        RUN   -    amxmodx_mm_i386.so          v1.9.0.5294      ini  Start ANY  
 [10] ReSemiclip       RUN   -    resemiclip_mm_i386.so       v2.3.9           ini  Chlvl ANY  
 [11] YaPB             RUN   -    yapb.so                     v4.2.671         ini  Chlvl ANY  
 [12] HitBox Fix       RUN   -    hitbox_fix_mm_i386.so       v1.0.11          ini  Start ANY  
 [13] ReAimDetector    RUN   -    reaimdetector_amxx_i386.so  v0.2.2           pl9  ANY   Never
 [14] CStrike          RUN   -    cstrike_amxx_i386.so        v1.9.0.5294      pl9  ANY   ANY  
 [15] Engine           RUN   -    engine_amxx_i386.so         v1.9.0.5294      pl9  ANY   ANY  
 [16] FakeMeta         RUN   -    fakemeta_amxx_i386.so       v1.9.0.5294      pl9  ANY   ANY  
 [17] MySQL            RUN   -    mysql_amxx_i386.so          v1.9.0.5294      pl9  ANY   ANY  
 [18] Ham Sandwich     RUN   -    hamsandwich_amxx_i386.so    v1.9.0.5294      pl9  ANY   ANY  
 [19] Fun              RUN   -    fun_amxx_i386.so            v1.9.0.5294      pl9  ANY   ANY  
 [20] CSX              RUN   -    csx_amxx_i386.so            v1.9.0.5294      pl9  ANY   ANY  
 [21] ReAPI            RUN   -    reapi_amxx_i386.so          v5.21.0.252-dev  pl9  ANY   Never
 [22] hackdetector     RUN   -    hackdetector_amxx_i386.so   v0.15.328.lite   pl9  ANY   ANY  
22 plugins, 22 running

============================================================

amxx plugins
Currently loaded plugins:
       name                    version     author            file             status   
 [  1] ReAimDetector API       0.2.2       ReHLDS Team       reaimdetector.a  running  
 [  2] [190] Map Spawns Edito  20.06.06    SKAJIbnEJIb & iG  MapSpawnsEditor  running  
 [  3] [190] AMXBans RBS       20.06.06    SKAJIbnEJIb & La  amxbans_rbs.amx  running  
 [  4] AWP Restrictions        1.5.1       Radius            awp_restriction  running  
 [  5] [190] AC Spectator ESP  20.06.06    SKAJIbnEJIb & Ko  ac_esp.amxx      running  
 [  6] Gag Me                  2.3.4       Radius            gag_me.amxx      running  
 [  7] [190] Army Ranks Ultim  20.06.06    SKAJIbnEJIb       army_ranks_ulti  running  
 [  8] [190] Skill ELO         20.06.06    SKAJIbnEJIb       skill_elo.amxx   running  
 [  9] [190] AdminCmd RBS      20.06.06    SKAJIbnEJIb & AM  admincmd_rbs.am  running  
 [ 10] [190] CsStats MySQL     20.06.06    SKAJIbnEJIb       csstats_mysql.a  running  
 [ 11] [190] Top Award RBS     20.06.06    SKAJIbnEJIb       topaward_rbs.am  running  
 [ 12] [190] DemoRecorder RBS  20.06.06    SKAJIbnEJIb       demorecorder_rb  running  
 [ 13] [190] Stats Configurat  20.06.06    SKAJIbnEJIb & AM  statscfg_rbs.am  running  
 [ 14] [190] StatsX RBS        21.03.23    SKAJIbnEJIb & AM  statsx_rbs.amxx  running  
 [ 15] [190] Damager RBS       20.06.06    SKAJIbnEJIb       damager_rbs.amx  running  
 [ 16] [190] Screen Player     20.06.06    SKAJIbnEJIb       screen_player.a  running  
 [ 17] [190] Ultimate Weapons  21.03.23    SKAJIbnEJIb       ultimate_weapon  running  
 [ 18] [190] VIP RBS           20.07.20    SKAJIbnEJIb       vip_rbs.amxx     running  
 [ 19] Menus Front-End         20.06.06    SKAJIbnEJIb & AM  amxmodmenu_rbs.  running  
 [ 20] [190] Kill Assist RBS   20.06.06    SKAJIbnEJIb & Di  killassist_rbs.  running  
 [ 21] [190] Warmup RBS        21.03.23    SKAJIbnEJIb       warmup_rbs.amxx  running  
 [ 22] [190] MapsMenu RBS      20.06.06    SKAJIbnEJIb & AM  mapsmenu_rbs.am  running  
 [ 23] AFK Control             1.4.1 [Rnd  neygomon          afk_control.amx  running  
 [ 24] [190] High Ping Kicker  20.06.06    SKAJIbnEJIb       hpk_rbs.amxx     running  
 [ 25] Advanced MapChooser     1.4         neygomon          map_chooser.amx  running  
 [ 26] Auto Team Balance Adva  1.5.1       Radius            auto_team_balan  running  
 [ 27] [190] Parachute RBS     20.06.06    SKAJIbnEJIb & KR  parachute_rbs.a  running  
 [ 28] ReChecker Logging       1.0         custom            rc_logging.amxx  running  
 [ 29] Anti Flood              1.9.0.5294  AMXX Dev Team     antiflood.amxx   running  
 [ 30] Admin Chat              1.9.0.5294  AMXX Dev Team     adminchat.amxx   running  
 [ 31] Pause Plugins           1.9.0.5294  AMXX Dev Team     pausecfg.amxx    running  
 [ 32] Restrict Weapons        1.9.0.5294  AMXX Dev Team     restmenu.amxx    running  
 [ 33] Anti reconnect          3.0         JohnJ             antireconnect.a  running  
 [ 34] finstext                1.5         shad0wgg & MyAre  finstext.amxx    running  
 [ 35] Block grande info       1.0         alliedmods        BlockGrenadeInf  running  
 [ 36] UFPS VoteBan            1.5         UFPS.Team         voteban.amxx     running  
 [ 37] mute menu               1.0         cheap_suit        mutemenu.amxx    running  
 [ 38] [ReAPI] No Team Flash   1.0         ReHLDS Team       noteamflash.amx  running  
 [ 39] ResetScore              0.2.0       aNNakin           resetscore.amxx  running  
 [ 40] HackDetector            0.15.lite   Lev @ AGHL.RU De  hackdetector.am  running  
 [ 41] Bomb Countdown HUD Tim  0.2         SAMURAI           bcd_hudtimer.am  running  
 [ 42] IP                      2.1         Bl0ck             IP.amxx          running  
 [ 43] [190] Chat RBS          20.06.06    SKAJIbnEJIb       chat_rbs.amxx    running  
43 plugins, 43 running

![08-01-2023 18-33-03](https://user-images.githubusercontent.com/122219836/211206540-9ce8851e-c213-4df4-bdda-7bfaf4976a61.png)
![08-01-2023 18-34-04](https://user-images.githubusercontent.com/122219836/211206550-c1f3d59e-9db8-4e77-bb2c-884e45afb977.png)

**Comment by foresl** [comment]
Кажется нашел несовместимый плагин:
 [ 43] [190] Chat RBS          20.06.06    SKAJIbnEJIb       chat_rbs.amxx    running  
 Поковырял его настройки, результата нет. Чтобы чат ботов появился, помогает только его отключение..

**Comment by Vladislav4KZ** [comment]
Это какой-то платный плагин? Может стоит написать его автору пофиксить сам плагин, а не бота?

**Comment by foresl** [comment]
Да, так и сделаю. Пока отключил просто сам плагин. Топик можно закрывать, спасибо)
