### ISSUE TITLE
 A* Search for bot "Deadlynome" has failed. Falling back to shortest-path algorithm. Seems to be graph is broken.

### ISSUE THREAD

**Issue by MysticDeathProject** [yapb/yapb#395]
- YapB v4.2.723
 - Zombie Plague 4.3
 
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 19:53:27 Aug  3 2020 (8684)

Currently loaded plugins:
      description      stat pend  file              vers      src   load  unlod
 [ 1] AMX Mod X        RUN   -    amxmodx_mm.dll    v1.9.0.5  ini   Start ANY  
 [ 2] mmtimer          fail  -    mmtimer.dll       v1.6      ini   ANY   Never
 [ 3] Booster          fail load  booster_686_mm.d  v2.40     ini   Chlvl Pause
 [ 4] Booster          fail load  booster_mm.dll    v2.40     ini   Chlvl Pause
 [ 5] YaPB             RUN   -    yapb.dll          v4.2.723  ini   Chlvl ANY  
 [ 6] Ham Sandwich     RUN   -    hamsandwich_amxx  v1.8.2-d  pl1   ANY   ANY  
 [ 7] CSX              RUN   -    csx_amxx.dll      v1.9.0.5  pl1   ANY   ANY  
 [ 8] CStrike          RUN   -    cstrike_amxx.dll  v1.9.0.5  pl1   ANY   ANY  
 [ 9] FakeMeta         RUN   -    fakemeta_amxx.dl  v1.8.2-d  pl1   ANY   ANY  
 [10] Engine           RUN   -    engine_amxx.dll   v1.8.2-d  pl1   ANY   ANY  
 [11] Fun              RUN   -    fun_amxx.dll      v1.8.2-d  pl1   ANY   ANY  
11 plugins, 8 running

Metamod v1.21p37  2013/05/30 (5:13)
by Will Day
   http://www.metamod.org/
 Patch: Metamod-P (mm-p) v37
 by Jussi Kivilinna
    http://metamod-p.sourceforge.net/
compiled: May 30 2013, 11:41:14 EET (optimized)

не исправляемая ошибка после чего сервер крашится спустя 40 минутной игры на стимовской платформе сервера 8684, кроме того ошибку исправляю уже 5 раз и судя по всему Graph работает не стабильно, на старых версий .pwf waypoint все работает четко и без ошибок

**Comment by MysticDeathProject** [comment]
> карта кто какая?

карта zm_houses она изначально была одной из тех на которой было интересно создавать вейпоинты и на старых версий podbot для этой карты были сделаны вейпоинты, и они работают, но только yapb автоматически их переводит в .graph и у карты выходит ошибка A* Search for bot "Deadlynome" has failed. Falling back to shortest-path algorithm. Seems to be graph is broken. в папке yapb/data/pwf не храняться никаких файлов старых вейпоинтов, я просто давно создаю вейпоинты ошибка кстати не исправляется командой yb g save old если надо могу скинуть сегодняшний проект вот ссылка https://disk.yandex.com/d/5c_u7PN26NDrmA и команды yb_debug 1 не показывает в чем ошибка ничего не могу понять че не пашет то

**Comment by MysticDeathProject** [comment]
> @Vladislav4KZ @Overitab help!!!
> 
> Крэш в любом случае не приемлем, но но надо понять что не так с графом

сервер ложится спустя кол-во этих сообщений походу че-то не то или с моим .graph или же сбой в ботах они словно видят вейпоинты, без путей(желтых и зеленый и белых линий) но спустя где-то 40 мин или 1 часа сервер ложиться вот список плагинов

plugins.ini
; AMX Mod X plugins

; Admin Base - Always one has to be activated
admin.amxx		; admin base (required for any admin-related)
;admin_sql.amxx		; admin base - SQL version (comment admin.amxx)

; Basic
admincmd.amxx		; basic admin console commands
adminhelp.amxx		; help command for admin console commands
adminslots.amxx		; slot reservation
multilingual.amxx	; Multi-Lingual management

; Menus
menufront.amxx		; front-end for admin menus
cmdmenu.amxx		; command menu (speech, settings)
plmenu.amxx		; players menu (kick, ban, client cmds.)
;telemenu.amxx		; teleport menu (Fun Module required!)
mapsmenu.amxx		; maps menu (vote, changelevel)
pluginmenu.amxx		; Menus for commands/cvars organized by plugin

; Chat / Messages
adminchat.amxx		; console chat commands
antiflood.amxx		; prevent clients from chat-flooding the server
scrollmsg.amxx		; displays a scrolling message
imessage.amxx		; displays information messages
adminvote.amxx		; vote commands

; Map related
nextmap.amxx		; displays next map in mapcycle
mapchooser.amxx		; allows to vote for next map
timeleft.amxx		; displays time left on map

; Configuration
pausecfg.amxx		; allows to pause and unpause some plugins
statscfg.amxx		; allows to manage stats plugins via menu and commands

; Counter-Strike
;restmenu.amxx		; restrict weapons menu
statsx.amxx		; stats on death or round end (CSX Module required!)
;miscstats.amxx		; bunch of events announcement for Counter-Strike
;stats_logging.amxx	; weapons stats logging (CSX Module required!)

plugins-zplague.ini
; - Quick tips -
; * Rename this file to disabled-zplague.ini to turn the mod off
; * Rename it back to plugins-zplague.ini to turn it on
; * Put a semi-colon in front of a plugin to disable it
; * Remove a semi-colon to re-enable a plugin
; * Add the word debug after a plugin to place it in debug mode

; Main plugin
zombie_plague40_2022.amxx

; Default zombie classes
zp_zclasses40.amxx
zp_firstzombiecounter.amxx
zmod_weapons.amxx
advanced_fog.amxx
Map_Spawns_Editor.amxx
; Add sub-plugins, custom zombie classes, and extra items here

даже со всеми отключеными плагинами в plugins-zplague.ini на сервере выходят A* Search for bot "Deadlynome" has failed. Falling back to shortest-path algorithm. Seems to be graph is broken. и спустя не знаю сколько 40 минут когда весь консоль забит видимо происходит краш сервера и он попросту вырубается

**Comment by MysticDeathProject** [comment]
Проблема вроде как решена с вейпоинтом, но все равно переодически сервер крашится плагины 
zp_firstzombiecounter.amxx
zmod_weapons.amxx
advanced_fog.amxx
отключены, но спустя несколько смен карт сервер просто ложиться, в логах ничего не написанно, походу ошибка в моих вейпоинтах они видимо слишком тяжелые для ботов потому что боты вроде как выполняют задачи, но подозреваю что дело в вейпоинтах, в любом случае если будет время вы уж там оптимизируйте этих ботов, в ботах по прежнему остались ошибки особенно связанные с зм когда боты стреляют в друг друга, конечно плагином вроде как дело исправилось, но лучше чтобы у ботов была проверка на команду каждые 10 сек хотя бы а так спасибо что максимально быстро ответил, надеюсь fix будет крутой

**Comment by Vladislav4KZ** [comment]
@MysticDeathProject получается, Graph для этой карты делал ты?

Я так полагаю эти ошибки связаны с тем, что какой-то узел не содержит обратного пути. Ты сохранял graph файл без проверки? Если бы сохранил с проверкой, то в консоли должна была бы указаться причина, что не так с графом.

**Comment by Vladislav4KZ** [comment]
@MysticDeathProject перечитал коммент ещё раз.

Если это не твой вэйпоинт, скинь ещё ссылку на оригинальный pwf, который по твоим словам работал.

Может косяки были и в нём, просто PODBot наверно их игнорировал, а YaPB нет.

**Comment by MysticDeathProject** [comment]
@Vladislav4KZ Привет да вейпоинт делал я, старая версию тоже я делал еще в 2015 году где-то https://disk.yandex.com/d/dwWz2Vs9O2fKXA вот ссылка, баг заключается в том что сервер крашится и ошибку с A* Search for bot "Deadlynome" has failed. Falling back to shortest-path algorithm. Seems to be graph is broken. Уже исправил тест был на обычном Zombie Plague и Zombie Biohazard и за 6 часов игры на zp и bh вылетело примерно 1 раз, версия сервера обычная стимовская 8684 и редактировать во время игры на сервере вейпоинты я не могу права не выдает пишет все время ошибку есть же без ошибок версии? Я понять не могу почему именно на этой карте zm_2010 крашится сервер на podbotah последняя версия не помню какое точно названия краш сервера не происходит просто обидно что боты по всей видимости боятся так много прыгать и у них видимо ошибка какая-то выходит на podbotah не крашится сервер

вот настройки yapb
//
// @package: YaPB
// @version: 4.2
// @author: YaPB Project
// @filename: yapb.cfg
// 
// YaPB main configuration file. Can be executed via "exec" command.
//

//
// Enables or disables useful messages about bot states. Not required for end users.
// ---
// Default: "0", Min: "0", Max: "4"
// 
yb_debug "0"

//
// Forces all alive bots to build path and go to the specified here graph node.
// ---
// Default: "-1", Min: "-1", Max: "2048"
// 
yb_debug_goal "-1"

//
// Specifies the percent of bots, that can follow leader on each round start.
// ---
// Default: "20", Min: "0", Max: "100"
// 
yb_user_follow_percent "20"

//
// Specifies how many bots can follow a single user.
// ---
// Default: "1", Min: "0", Max: "8"
// 
yb_user_max_followers "1"

//
// If enabled, all bots will be forced only the knife, skipping weapon buying routines.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_jasonmode "0"

//
// Allows bots to use radio or chattter.
//  Allowed values: '0', '1', '2'.
//  If '0', radio and chatter is disabled.
//  If '1', only radio allowed.
//  If '2' chatter and radio allowed.
// ---
// Default: "2", Min: "0", Max: "2"
// 
yb_radio_mode "2"

//
// Specifies whether bots able to use team economics, like do not buy any weapons for whole team to keep money for better guns.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_economics_rounds "0"

//
// Specifies whether bots able to use 'shift' if they thinks that enemy is near.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_walking_allowed "1"

//
// Allows or disallows bots to camp. Doesn't affects bomb/hostage defending tasks.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_camping_allowed "1"

//
// Lower bound of time from which time for camping is calculated
// ---
// Default: "15.0", Min: "5.0", Max: "90.0"
// 
yb_camping_time_min "60.0"

//
// Upper bound of time until which time for camping is calculated
// ---
// Default: "45.0", Min: "15.0", Max: "120.0"
// 
yb_camping_time_max "120.0"

//
// Allows or disallows bots to take revenge of teamkillers / team attacks.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_tkpunish "1"

//
// If enabled, the bots think function is disabled, so bots will not move anywhere from their spawn spots.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_freeze_bots "0"

//
// Allows or disallows the use of spray paints.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_spraypaints "1"

//
// Allows or disallows bots weapon buying routines.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_botbuy "1"

//
// Allows bots to destroy breakables around him, even without touching with them.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_destroy_breakables_around "0"

//
// The radius on which bot searches world for new objects, items, and weapons.
// ---
// Default: "450.0", Min: "64.0", Max: "1024.0"
// 
yb_object_pickup_radius "1024.0"

//
// Specifies the paths for the bot chatter sound files.
// ---
// Default: "sound/radio/bot"
// 
yb_chatter_path "sound/radio/bot"

//
// Specifies semicolon separated list of weapons that are not allowed to buy / pickup.
// --- not working
// Default: ""
// 
yb_restricted_weapons "shield"

//
// Allows or disallows bots to attack monsters.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_attack_monsters "1"

//
// Allows or disallows bots to pickup custom items.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_pickup_custom_items "1"

//
// Allows or disallows bots to do map objectives, i.e. plant/defuse bombs, and saves hostages.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_ignore_objectives "1"

//
// Allows or disallows the ability for random knife attacks when bot is rushing and no enemy is nearby.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_random_knife_attacks "1"

//
// Enables or disables bots chat functionality.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_chat "1"

//
// Bot chances to send random dead chat when killed.
// ---
// Default: "30", Min: "0", Max: "100"
// 
yb_chat_percent "100"

//
// Specifies whether bots able to fire at enemies behind the wall, if they hearing or suspecting them.
// ---
// Default: "2", Min: "0", Max: "2"
// 
yb_shoots_thru_walls "0"

//
// Enables or disables searching world for enemies.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_ignore_enemies "0"

//
// Enables or disables checking enemy rendering flags. Useful for some mods.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_check_enemy_rendering "1"

//
// Enables or disables checking enemy invincibility. Useful for some mods.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_check_enemy_invincibility "1"

//
// Enables or disables bot ability to stab the enemy with knife if bot is in good condition.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_stab_close_enemies "0"

//
// Binds specified key for opening bots menu.
// ---
// Default: "="
// 
yb_bind_menu_key "="

//
// Specifies comma separated list of bot cvars, that will not be overriten by config on changelevel.
// ---
// Default: "yb_quota,yb_autovacate"
// 
yb_ignore_cvars_on_changelevel "yb_quota,yb_autovacate"

//
// Enables or disables display menu text, when players asks for menu. Useful only for Android.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_display_menu_text "0"

//
// The value (password) for the setinfo key, if user sets correct password, he's gains access to bot commands and menus.
// ---
// Default: ""
// 
yb_password ""

//
// The name of setinfo key used to store password to bot commands and menus.
// ---
// Default: "_ybpw"
// 
yb_password_key "_ybpw"

//
// Enables or disables CSDM / FFA mode for bots.
//  Allowed values: '0', '1', '2', '3'.
//  If '0', CSDM / FFA mode is auto-detected.
//  If '1', CSDM mode is enabled, but FFA is disabled.
//  If '2', CSDM and FFA mode is enabled.
//  If '3', CSDM and FFA mode is disabled.
// ---
// Default: "0", Min: "0", Max: "3"
// 
yb_csdm_mode "0"

//
// Specifies whether bot should not 'fix' camp directions of camp waypoints when loading old PWF format.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_graph_fixcamp "1"

//
// Specifies the URL from bots will be able to download graph in case of missing local one. Set to empty, if no downloads needed.
// ---
// Default: "yapb.jeefo.net"
// 
yb_graph_url "yapb.jeefo.net"

//
// Kick bots to automatically make room for human players.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_autovacate "1"

//
// Specifies the number bots to be added to the game.
// ---
// Default: "9", Min: "0", Max: "32"
// 
yb_quota "32"

//
// Specifies the type of quota.
//  Allowed values: 'normal', 'fill', and 'match'.
//  If 'fill', the server will adjust bots to keep N players in the game, where N is yb_quota.
//  If 'match', the server will maintain a 1:N ratio of humans to bots, where N is yb_quota_match.
// ---
// Default: "normal"
// 
yb_quota_mode "normal"

//
// Number of players to match if yb_quota_mode set to 'match'
// ---
// Default: "0", Min: "0", Max: "32"
// 
yb_quota_match "0"

//
// Specifies how many times per second bot code will run.
// ---
// Default: "26.0", Min: "24.0", Max: "90.0"
// 
yb_think_fps "90.0"

//
// Specifies amount of time in seconds when bots will be killed if no humans left alive.
// ---
// Default: "0.0", Min: "0.0", Max: "90.0"
// 
yb_autokill_delay "0.0"

//
// Specifies whether bots should join server, only when at least one human player in game.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_join_after_player "0"

//
// Forces all bots to join team specified here.
// ---
// Default: "any"
// 
yb_join_team "any"

//
// Specifies after how many seconds bots should start to join the game after the changelevel.
// ---
// Default: "5.0", Min: "0.0", Max: "30.0"
// 
yb_join_delay "30.0"

//
// All the bot names will be prefixed with string specified with this cvar.
// ---
// Default: ""
// 
yb_name_prefix ""

//
// All bots difficulty level. Changing at runtime will affect already created bots.
// ---
// Default: "4", Min: "0", Max: "4"
// 
yb_difficulty "4"

//
// Lower bound of random difficulty on bot creation. Only affects newly created bots. -1 means yb_difficulty only used.
// ---
// Default: "-1", Min: "-1", Max: "4"
// 
yb_difficulty_min "4"

//
// Upper bound of random difficulty on bot creation. Only affects newly created bots. -1 means yb_difficulty only used.
// ---
// Default: "-1", Min: "-1", Max: "4"
// 
yb_difficulty_max "4"

//
// Enables each bot balances own difficulty based kd-ratio of team.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_difficulty_auto "1"

//
// Enables or disables displaying bot avatars in front of their names in scoreboard. Note, that is currently you can see only avatars of your steam friends.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_show_avatars "1"

//
// Enables latency display in scoreboard.
//  Allowed values: '0', '1', '2'.
//  If '0', there is nothing displayed.
//  If '1', there is a 'BOT' is displayed.
//  If '2' fake ping is displayed.
// ---
// Default: "2", Min: "0", Max: "2"
// 
yb_show_latency "2"

//
// Allows to save bot names upon changelevel, so bot names will be the same after a map change
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_save_bots_names "1"

//
// Specifies the bots wanted skin for Terrorist team.
// ---
// Default: "0", Min: "0", Max: "5"
// 
yb_botskin_t "0"

//
// Specifies the bots wanted skin for CT team.
// ---
// Default: "0", Min: "0", Max: "5"
// 
yb_botskin_ct "0"

//
// Lower bound for base bot ping shown in scoreboard upon creation.
// ---
// Default: "7", Min: "0", Max: "100"
// 
yb_ping_base_min "1"

//
// Upper bound for base bot ping shown in scoreboard upon creation.
// ---
// Default: "34", Min: "0", Max: "100"
// 
yb_ping_base_max "100"

//
// Specifies the language for bot messages and menus.
// ---
// Default: "en"
// 
yb_language "en"

//
// Enables or disables extra hard difficulty for bots.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_whose_your_daddy "1"

//
// Selects the heuristic function mode. For debug purposes only.
// ---
// Default: "4", Min: "0", Max: "4"
// 
yb_path_heuristic_mode "4"

//
// Lower bound of danger factor that used to add additional danger to path based on practice.
// ---
// Default: "200", Min: "100", Max: "2400"
// 
yb_path_danger_factor_min "200"

//
// Upper bound of danger factor that used to add additional danger to path based on practice.
// ---
// Default: "400", Min: "200", Max: "4800"
// 
yb_path_danger_factor_max "400"

//
// Enables or disables showing welcome message to host entity on game start.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_display_welcome_text "0"

//
// Enables or disables fake server queries response, that shows bots as real players in server browser.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_enable_query_hook "1"

**Comment by Vladislav4KZ** [comment]
@MysticDeathProject поставил твой старый pwf. YaPB его автоматически сконвертировал в Graph формат, и всё было в порядке. Команда ``yb g check`` также сообщила что ошибок нет.

А вот в новом graph файле, уже были проблемы. Как я и говорил в своём первом сообщении, дело было в односторонних путях между узлами. Это были прыговые пути в одну сторону, которые не имели обратного пути.

Вот, я исправил твой graph, проверяй: 
[zm_houses_fixed.zip](https://github.com/yapb/yapb/files/10471958/zm_houses_fixed.zip)

**Comment by Vladislav4KZ** [comment]
> сорян не знаю как тут спойлер добавить в текст

@MysticDeathProject вот так
```
<details>
  <summary>Спойлер</summary>

Текст

</details>
```

Мог бы загуглить как делать спойлеры в Markdown.

**Comment by MysticDeathProject** [comment]
@Vladislav4KZ Спасибо большое за фикс ща проверю

**Comment by MysticDeathProject** [comment]
@Vladislav4KZ Привет сервер крашился, я провел 4 испытания с тем же зомби плагуе и за 4 часа сервер упал 4 раза т.е сервер даже часа не продержался, я пробовал отключать плагины коих не так много и думал что дело в вейпоинтах, но дело оказалось в чате для ботов когда они мертвые они начинают тупо спамить при отключении чата yb_chat "0" и поставить максимум ботов yb_quota 32 сервер работает норм на той же карте zm_houses с пофикшенем вейпоинтов от тебя @Vladislav4KZ вообщем проблема в чате для ботов они сильно засоряют чат когда мертвы, если вы можете то пофиксите это, и по возможности исправьте баг старый когда боты мочат друг друга при Zombie Swarm и Zombie Escape это очень сильно раздражает не знаю даже что написать долго пришлось мучаться с исправлением ошибки, чат пришлось отключить версия и все что написанно выше это настройки моего локального сервера, я вообще сервер не держу просто из любопытства создаю Graph но мотивация сильно пропадает когда нет возможности поиграть с этими ботами в Zombie Swarm а так спасибо за создания этих ботов надеюсь фиксы будут четкие и нужные буду очень признателен, заранее благодарю

**Comment by MysticDeathProject** [comment]
@jeefo дамп файл сервер не создал при падении были включены логи не знаю может это о чем то говорит, но вот что там было написанно
Mon Sep 27 12:50:14 2021 UTC : BOpenService failed (GLE 1060)
Mon Sep 27 12:50:14 2021 UTC : ServiceStart: failed to start (GLE 131)
Mon Sep 27 12:50:57 2021 UTC : BOpenService failed (GLE 1060)
Mon Sep 27 12:50:57 2021 UTC : ServiceStart: failed to start (GLE 183)
Thu Jan 19 13:07:58 2023 UTC : Failed to load Steam Service (GLE 126)
Thu Jan 19 13:07:58 2023 UTC : BOpenService failed (GLE 1060)
Thu Jan 19 13:07:58 2023 UTC : ServiceStart: failed to start (GLE 183)
Thu Jan 19 13:08:52 2023 UTC : Failed to load Steam Service (GLE 126)
Thu Jan 19 13:08:52 2023 UTC : BOpenService failed (GLE 1060)
Thu Jan 19 13:08:52 2023 UTC : ServiceStart: failed to start (GLE 183)
Thu Jan 19 13:33:57 2023 UTC : Failed to load Steam Service (GLE 126)
Thu Jan 19 13:33:57 2023 UTC : BOpenService failed (GLE 1060)
Thu Jan 19 13:33:57 2023 UTC : ServiceStart: failed to start (GLE 183)
Thu Jan 19 13:45:11 2023 UTC : Failed to load Steam Service (GLE 126)
Thu Jan 19 13:45:11 2023 UTC : BOpenService failed (GLE 1060)
Thu Jan 19 13:45:11 2023 UTC : ServiceStart: failed to start (GLE 183)
Thu Jan 19 15:32:30 2023 UTC : Failed to load Steam Service (GLE 126)
Thu Jan 19 15:32:30 2023 UTC : BOpenService failed (GLE 1060)
Thu Jan 19 15:32:30 2023 UTC : ServiceStart: failed to start (GLE 183)
Thu Jan 19 15:34:12 2023 UTC : Failed to load Steam Service (GLE 126)
Thu Jan 19 15:34:12 2023 UTC : BOpenService failed (GLE 1060)
Thu Jan 19 15:34:12 2023 UTC : ServiceStart: failed to start (GLE 183)
Thu Jan 19 15:39:04 2023 UTC : Failed to load Steam Service (GLE 126)
Thu Jan 19 15:39:04 2023 UTC : BOpenService failed (GLE 1060)
Thu Jan 19 15:39:04 2023 UTC : ServiceStart: failed to start (GLE 183)
Thu Jan 19 15:48:33 2023 UTC : Failed to load Steam Service (GLE 126)
Thu Jan 19 15:48:33 2023 UTC : BOpenService failed (GLE 1060)
Thu Jan 19 15:48:33 2023 UTC : ServiceStart: failed to start (GLE 183)
Thu Jan 19 15:55:48 2023 UTC : Failed to load Steam Service (GLE 126)
Thu Jan 19 15:55:48 2023 UTC : BOpenService failed (GLE 1060)
Thu Jan 19 15:55:48 2023 UTC : ServiceStart: failed to start (GLE 183)
Thu Jan 19 18:37:23 2023 UTC : Failed to load Steam Service (GLE 126)
Thu Jan 19 18:37:23 2023 UTC : BOpenService failed (GLE 1060)
Thu Jan 19 18:37:23 2023 UTC : ServiceStart: failed to start (GLE 183)
Thu Jan 19 22:20:17 2023 UTC : Failed to load Steam Service (GLE 126)
Thu Jan 19 22:20:17 2023 UTC : BOpenService failed (GLE 1060)
Thu Jan 19 22:20:17 2023 UTC : ServiceStart: failed to start (GLE 183)
Sat Jan 21 23:28:58 2023 UTC : Failed to load Steam Service (GLE 126)
Sat Jan 21 23:28:58 2023 UTC : BOpenService failed (GLE 1060)
Sat Jan 21 23:28:58 2023 UTC : ServiceStart: failed to start (GLE 183)
Sun Jan 22 02:28:20 2023 UTC : Failed to load Steam Service (GLE 126)
Sun Jan 22 02:28:20 2023 UTC : BOpenService failed (GLE 1060)
Sun Jan 22 02:28:20 2023 UTC : ServiceStart: failed to start (GLE 183)
Sun Jan 22 02:33:19 2023 UTC : Failed to load Steam Service (GLE 126)
Sun Jan 22 02:33:19 2023 UTC : BOpenService failed (GLE 1060)
Sun Jan 22 02:33:19 2023 UTC : ServiceStart: failed to start (GLE 183)
в amxx логах ничего не написало, я по старой схеме логи записывал командой log on
