### ISSUE TITLE
Csdm/ yb_difficulty_auto

### ISSUE THREAD

**Issue by ClaudiuHKS** [yapb/yapb#400]
Hi, can you make it possible auto adjusting the bot difficulty every 30 or 60 seconds for example? For Csdm?
Because right now, as I see, only at each Round Start the difficulty is auto adjusted if that convar is set to 1.
Thank you!

**Comment by jeefo** [comment]
Hello.

``yb_difficulty_auto_balance_interval`` in latest actions build.
