### ISSUE TITLE
yapb.cfg

### ISSUE THREAD

**Issue by EVOLCORE** [yapb/yapb#404]
yapb.cfg and names of bots are not executing, i changed yb_quota to 6, after restart server, bots were 9 still lol, after i executed yb_quota from console then was all right, and yapb_242342342 names like it

**Comment by Vladislav4KZ** [comment]
It's not a bug, read the docs:
https://yapb.readthedocs.io/en/latest/configuring.html#yb-ignore-cvars-on-changelevel

You need to disable the ``yb_ignore_cvars_on_changelevel`` cvar by setting it to
``yb_ignore_cvars_on_changelevel 0``.

To save the changes in yapb.cfg, you need to enter the ``yb cvars save`` command in console

**Comment by Vladislav4KZ** [comment]
And you can write more about the names of the bots, what language does the bot use (default English? Or other?) and how you add bots.

This bug doesn't reproduce for me.

**Comment by Vladislav4KZ** [comment]
Make sure you have done the full installation of YaPB bot. Perhaps you are missing the ``en_names.cfg`` file.

Download the latest version of YaPB from the Releases section

**Comment by EVOLCORE** [comment]
I have downloaded latest yapb bot from release section, en_names.cfg is there all files are there, but names are still like yp_some numbers

**Comment by Vladislav4KZ** [comment]
> I have downloaded latest yapb bot from release section, en_names.cfg is there all files are there, but names are still like yp_some numbers

@EVOLCORE I reproduced this issue, only when deleted the en_names.cfg file.

When all configs are in place, there is no such issue.

The ``en_names.cfg`` is located in ``addons/yapb/conf/lang`` folder, and not elsewhere?

If so, please describe in more detail about your Counter-Strike setup (game version/engine build, metamod/amxx plugins if any, operating system). This will help identify the problem in your environment.

**Comment by EVOLCORE** [comment]
I have found here issue is it's in installation path, i don't know why is this happening but it's kinda wired if you link yapb.so in this path it's not gonna work
linux addons/metamod/yapb/bin/yapb.so      // not working settings
linux addons/yapb/bin/yapb.so                      // working everything well
after start yapb with linked like this it's self creating folder named yapb/config in addons and some other stuff like settings etc...
