### ISSUE TITLE
Add Zombie Plague mod compatibility.

### ISSUE THREAD

**Issue by commandcobra7** [yapb/yapb#407]
Hi can you add bot compatibility with zombie plague mod because if i play zombie plague mod the bots behave very strangely when the round starts the bots attack themselves when the round starts they prefer to attack closely instead of avoiding zombies so how to make zombie plague mod on this Yapb bot?

**Comment by MysticDeathProject** [comment]
> Hi can you add bot compatibility with zombie plague mod because if i play zombie plague mod the bots behave very strangely when the round starts the bots attack themselves when the round starts they prefer to attack closely instead of avoiding zombies so how to make zombie plague mod on this Yapb bot?

Hi I make a simple fix for YaPB bots 

`
#include < amxmodx >
#include <zombieplague>

new const VERSION[] = "1.3 Mysticpawn";


public plugin_init()
{
register_plugin("[ZM] API YapB", VERSION, "");
register_event("HLTV", "event_round_start", "a", "1=0", "2=0");


}

public zp_round_ended(winteam)
{
// No one won
if (winteam == WIN_NO_ONE)
{
server_cmd("yb_ignore_enemies 1")
}
else if(winteam == WIN_ZOMBIES)
{
server_cmd("yb_ignore_enemies 1")
}
else if(winteam == WIN_HUMANS)
{
server_cmd("yb_ignore_enemies 1")
}
}

public zp_round_started(gamemode)
{
// No one won
if (gamemode == MODE_INFECTION)
{
server_cmd("yb_ignore_enemies 0")
}
else if(gamemode == MODE_NEMESIS)
{
server_cmd("yb_ignore_enemies 0")
}
else if(gamemode == MODE_SURVIVOR)
{
server_cmd("yb_ignore_enemies 0")
}
else if(gamemode == MODE_SWARM)
{
server_cmd("yb_ignore_enemies 0")
}
else if(gamemode == MODE_MULTI)
{
server_cmd("yb_ignore_enemies 0")
}
else if(gamemode == MODE_PLAGUE)
{
server_cmd("yb_ignore_enemies 0")
}
}


public event_round_start()
{
server_cmd("yb_ignore_enemies 1")
}

`
try this this is simple fix for zombie plague about zombie swarm I don't know how to add every second TeamInfo
