### ISSUE TITLE
Bring back the old coloring of camp nodes

### ISSUE THREAD

**Issue by Vladislav4KZ** [yapb/yapb#411]
@commandcobra7 in one of the commits took the coloring of camp nodes from PODBot 3.0 MM.

But I consider it was a bad idea, since the Counter-Terrorists Important Camp node and Terrorists Important Camp node almost no color difference. In the old coloring, it was easy to distinguish the Counter-Terrorist Camp node from the Terrorist Camp node.

**Comment by commandcobra7** [comment]
@Vladislav4KZ check node again check if there is any difference from below solution.

https://github.com/yapb/yapb/actions/runs/4284109687

**Comment by commandcobra7** [comment]
@Vladislav4KZ compile the following commit, is there a color change

https://github.com/yapb/yapb/actions/runs/4414699338

**Comment by Vladislav4KZ** [comment]
> compile the following commit, is there a color change
> 
> https://github.com/yapb/yapb/actions/runs/4414699338

I already looked at it

**Comment by commandcobra7** [comment]
@Vladislav4KZ Is there a difference in colors

**Comment by Vladislav4KZ** [comment]
> Is there a difference in colors

@commandcobra7 Yes, everything is fine. Camp nodes are easy to distinguish. The color difference is visible.

**Comment by Vladislav4KZ** [comment]
I will close this issue after merging your pull request.

Idk, do I need to wait for @jeefo when he is merge this PR? Or merge it yourself...
