### ISSUE TITLE
Боты на he серверах очень редко используют гранату

### ISSUE THREAD

**Issue by wood-grouse** [yapb/yapb#414]
Здравствуйте.
Боты на he серверах очень редко используют гранату (т.е. они водят прицелом по противнику с гранатой в руках) и очень редко могут ее бросить. У меня на сервере стрипается все оружие, кроме гранат.  
Можно добавить в "Приоритет оружия" еще и гранаты? А то к ним есть только настройка "Проценты покупки гранат"

**Comment by jeefo** [comment]
Для броска должен рак на горе свистнуть, там много расчётов. Не уверен, что это меняемо. 

Другими словами, у ботов есть только гранаты ? нет основного и запасного ружия?

**Comment by wood-grouse** [comment]
Да, в руках только гранаты, даже ножа нет.

**Comment by jeefo** [comment]
Как будет возможность, посмотрю, как упростить вариант, когда никакого оружия, кроме гранат.

**Comment by wood-grouse** [comment]
> Как будет возможность, посмотрю, как упростить вариант, когда никакого оружия, кроме гранаты.

Спасибо!

**Comment by Vladislav4KZ** [comment]
@wood-grouse до меня только сейчас дошло, вы же создавали похожую issue 2 года назад: https://github.com/yapb/yapb/issues/243

**Comment by wood-grouse** [comment]
> @wood-grouseдо меня только сейчас дошло, вы же создали похожую проблему 2 года назад: [# 243](https://github.com/yapb/yapb/issues/243)
> 
> Ее я закрываю, и оставляю эту

Да, хорошо :+1:

**Comment by Shkarlatov** [comment]
Исправлено в https://github.com/yapb/yapb/pull/488
Можно закрывать
