### ISSUE TITLE
Bots weakness against flashbombs

### ISSUE THREAD

**Issue by KD4533** [yapb/yapb#417]
**Describe the bug**
Bots have an expected behavior against flash bangs, this makes them vulnerable even at highest difficulty.

Sometimes if I want to play eco, I just keep my pistol and buy two flash bangs, then I can go to an area where CT and T usually collide, wait until I hear footsteps, then throw a flashbang or two, wait for them to finish their weapon cartridge, then I attack and kill them all.

When bots are flashbanged, they either start shooting randomly, this makes players know that there are bots in that area and where they are shooting from. The other scenario is that bots would be spinning around randomly.

This makes bots vulnerable and expected even at highest difficulty, and makes playing with them a little bit boring.

**Expected behavior**
Bots should go hide or take a strategic action when flash bombed rather than randomly shooting or spinning around, or even sneaking towards the enemy blindly.

**Video**
https://dai.ly/k5RY9NLnplebs1ySSQB

**Environment details:**
 - OS: Windows 10
 - Engine: Vanilla (Latest from Steam)
 - GameDLL: Vanilla
 - Metamod: metamod (Vanilla)
 - Bot Version: 4.3.729
 - Game mode: Single player

**Comment by jeefo** [comment]
Agree, but sorry, no timeline.

**Comment by KD4533** [comment]
I have been playing with YapB for some time and I think this is one of the major glitches after bots getting stuck :) so give it priority IMO

**Comment by commandcobra7** [comment]
@KD4533 the problem is fixed now you can close this thread.
