### ISSUE TITLE
Automatic knife duel bug

### ISSUE THREAD

**Issue by gary00k** [yapb/yapb#420]
I found a bug. When using "automatic knife duel" plugin and challenge bot, the plugin blocks using other weapons except knife. Bot still tries to change weapon to something better than knife and traps into some loop, trying to change weapon. In result, he has knife, but don't attacks at all.
I think the solution could be to add some counter; if weapon change failed X times, go ahead with knife.

**Comment by jeefo** [comment]
It's not a bug, Plugin should strip weapons weapons from bots in that case.

Bot knows  that he owns the weapon, and try to use it as usual. Doing changes for every plugin in AMXX - is a bad idea.

**Comment by gary00k** [comment]
I tried to add strip_weapons function, but it still tries to change it. I'll try with this yb_jasonmode cvar.
