### ISSUE TITLE
Bots are using flashlight even impulse 100 command is blocked

### ISSUE THREAD

**Issue by Hedgefog** [yapb/yapb#426]
For some reason, the latest bots using the flashlight even `impulse 100` command blocked on the server side, looks like the bots' flashlight is forcing through the engine. I also didn't find any cvar to disable it.

**Comment by jeefo** [comment]
Hello!

Will add ability to disable darkness check next commit. Nice catch.

**Comment by jeefo** [comment]
``yb_check_darkness`` via this [build](https://github.com/yapb/yapb/actions/runs/4637872475)

**Comment by Hedgefog** [comment]
Works, thanks!
