### ISSUE TITLE
CT bots do not take all hostages at once in the hostage rescue map

### ISSUE THREAD

**Issue by commandcobra7** [yapb/yapb#427]
With the latest edit below, in the CT bots hostage rescue map, the bots ignore the hostages, do not take all the hostages at the same time, and start the hunting mission when there are hostages and if the enemy is in close range, I tested it on every cs_ map, I saw the same behavior in all of them @jeefo I hope you can fix the problem, thanks in advance.

https://github.com/yapb/yapb/actions/runs/4637872475

**Comment by commandcobra7** [comment]
With the latest edit below, in the CT bots hostage rescue map, the bots ignore the hostages, do not take all the hostages at the same time, and start the hunting mission when there are hostages and if the enemy is in close range, I tested it on every cs_ map, I saw the same behavior in all of them @jeefo I hope you can fix the problem, thanks in advance.

https://github.com/yapb/yapb/actions/runs/4637872475

**Comment by jeefo** [comment]
Hello!

It's fixed in uncommitted changes. Thank you, i will commit them in 2-3 days i believe, no time atm.
