### ISSUE TITLE
bots get inaccessible assets

### ISSUE THREAD

**Issue by commandcobra7** [yapb/yapb#431]
In the pictures below, if the bots are close to an asset, they are trying to get it, then it gets stuck, I don't know if it's due to the latest version

![cs_assault_militia0002](https://user-images.githubusercontent.com/91374215/231688608-80162840-6c2f-4847-a6a7-921e7684aa0d.jpg)
![cs_assault_militia0003](https://user-images.githubusercontent.com/91374215/231688615-f749c55d-33c4-43f3-8195-710b656a4187.jpg)
![cs_assault_militia0004](https://user-images.githubusercontent.com/91374215/231688618-8c231fff-5c70-4be6-b861-e909bec7f726.jpg)

**Comment by jeefo** [comment]
Hello! Try the latest actions build

**Comment by commandcobra7** [comment]
thanks @jeefo problem solved
