### ISSUE TITLE
bots go to no access and invisible waypoint

### ISSUE THREAD

**Issue by commandcobra7** [yapb/yapb#432]
First of all hi @jeefo

Bots get stuck picking the closest but invisible waypoints to which they have no access I wonder if this is a remote but visible waypoint, could you add a visibility control that can take the waypoint I trust you will do this thanks in advance.

![de_byfly20000](https://user-images.githubusercontent.com/91374215/231692107-c82ad2de-b4f6-4fc7-9c8d-ed26261ad46d.jpg)
![de_byfly20001](https://user-images.githubusercontent.com/91374215/231692113-fa8aa81c-6bdf-4ec7-ac3a-d5fe025d8255.jpg)
![de_byfly20002](https://user-images.githubusercontent.com/91374215/231692122-816168cf-bfc8-4a96-ad12-941d8d712f90.jpg)

**Comment by jeefo** [comment]
Try latest actions build.

**Comment by jeefo** [comment]
FYI de_byfly2 bugged, for ideal case, there should be graph nodes near every spawn spot. This graph doesn't contains part of nodes on T's spawn.

**Comment by commandcobra7** [comment]
yes the problem is solved thanks @jeefo by the way waypoints are not enough on the de_byfly2 map there are too many distances between them should create a new graph not only on this map but on some maps the waypoints are too few and the target nodes are placed unnecessarily I will take a look at them again thank you for solving the problem
