### ISSUE TITLE
How to change the podbot control plugin to the yapb control plugin

### ISSUE THREAD

**Issue by Jockey731** [yapb/yapb#435]
Please change to yapb control command
[podbot_controler.zip](https://github.com/yapb/yapb/files/11241857/podbot_controler.zip)

**Comment by jeefo** [comment]
What's the purpose of that plugin?

**Comment by Jockey731** [comment]
Control the number of robots. If there are more than 10 real players, all robots will be kicked out. If there are less than 10 players, robots will continue to be added until 30 people. If someone joins the server on the way, 1 robot will be kicked out. If a player exits, 1 robot will be added again

**Comment by jeefo** [comment]
just try

yb_quota_mode fill
yb_quota 10
yb_autovacate 1

in yapb.cfg, it's should do, what u want

**Comment by Jockey731** [comment]
I modified the command and I'm not sure if I can control the robot
[YAPB_control.zip](https://github.com/yapb/yapb/files/11245527/YAPB_control.zip)

**Comment by jeefo** [comment]
Why just not use built-in cvars ?

About autokill in last plugin, take a look at ``yb_autokill_delay``
