### ISSUE TITLE
Bots that move away from the current node and get stuck on the wall

### ISSUE THREAD

**Issue by commandcobra7** [yapb/yapb#436]
Hi @jeefo In the pictures below, while the bots are navigating normally on every map, they move back from the existing node and get stuck on the wall, then even if the new road updates, it moves away from the existing node and still the same, I don't know where this problem comes from, I hope you solve this problem.

![de_dusticed0001](https://user-images.githubusercontent.com/91374215/232319649-01f9690e-d538-45fe-b7ca-44a61975c0b6.jpg)
![de_dusticed0002](https://user-images.githubusercontent.com/91374215/232319655-d5ad5ae9-8d2c-491f-b5f3-15c1010c7147.jpg)
![de_dusticed0003](https://user-images.githubusercontent.com/91374215/232319656-2c74eca4-9713-4c58-85e9-3025ae788ad1.jpg)

**Comment by jeefo** [comment]
Hi. Is that happens on release version?

**Comment by jeefo** [comment]
... and any steps to reproduce?  can't find this behavior

**Comment by commandcobra7** [comment]
@jeefo it can happen when dodging grenades or close to enemy distance or opening it on the next map usually doesn't happen but there is such a problem unfortunately

**Comment by jeefo** [comment]
Can you test latest actions build ?

**Comment by commandcobra7** [comment]
@jeefo I found the problem, the problem is not in the navigation, the problem is that they run back while dodging the grenade, the back keys get stuck and move away from the current node and back to the walls behind it and get stuck. he thinks that the grenade that comes over him is still in the air

**Comment by jeefo** [comment]
Thank you, and now ?

**Comment by commandcobra7** [comment]
Thanks @jeefo yes problem solved
