### ISSUE TITLE
Не работает автоанализ

### ISSUE THREAD

**Issue by Vladislav4KZ** [yapb/yapb#441]
Квар ``yb_graph_analyze_auto_start 1`` включён по умолчанию, но не работает, хотя в консоли пишется что запущен автоанализ карты.
Поставил последний билд бота собранный с master ветки.

**Детали окружения:**
 - ОС: Windows 10 Pro x64 22H2
 - Движок: Оригинальный 8684
 - GameDLL: Оригинальный
 - Metamod: Нет
 - Версия бота: 4.3.811 (с GitHub Actions)
 - Режим игры: Обычный

**Comment by Vladislav4KZ** [comment]
Автоанализ не работает как на первой запущенной карте на сервере с отсутствующим графом для неё, так и после её перезапуска или смены на другую.

**Comment by Vladislav4KZ** [comment]
Автоанализ начинает срабатывать только при попытке вручную загрузить graph файл, например с помощью команды ``yb g load``.

**Comment by jeefo** [comment]
ага

**Comment by commandcobra7** [comment]
@Vladislav4KZ can you see if the problem is solved with the last edit?

https://github.com/yapb/yapb/actions/runs/4902641368

**Comment by Vladislav4KZ** [comment]
> Vladislav4KZ can you see if the problem is solved with the last edit?
> 
> https://github.com/yapb/yapb/actions/runs/4902641368

@commandcobra7 yeah, it's fixed now.

**Comment by Vladislav4KZ** [comment]
@commandcobra7 I mean, it's fixed in the master branch, with commits by jeefo.

I didn't test your fix.
