### ISSUE TITLE
Wrong enemy prediction aim.

### ISSUE THREAD

**Issue by commandcobra7** [yapb/yapb#449]
Hi @jeefo since the last edits the bots are looking at the forward node instead of the close node to the enemy, I want the enemies to look at the nearest node again as before, it would be great if you could edit this.

**Comment by jeefo** [comment]
in what situations?

**Comment by commandcobra7** [comment]
> hello, in what situations?

When taking or guessing the last enemy, they usually need to look forward when there is no enemy, but they still look forward when there is the last enemy in close range.

**Comment by jeefo** [comment]
can you provide video? with yb_debug 1 if bot behavior?  I can't see any issues. also, try to increase yb_max_nodes_for_predict cvar.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by commandcobra7** [comment]
I wrote below which after editing this problem output.

aim: enemy prediction is now done asynchronously by now.
https://github.com/yapb/yapb/commit/a616f25b1a2d6fbb83e40e361b0e4340d0b7a507

**Comment by jeefo** [comment]
is it resolved,,or??

**Comment by commandcobra7** [comment]
> is it resolved,,or??

No, I reopened the issue. yb_max_nodes_for_predict variable didn't work.
@jeefo when can you fix the problem.

**Comment by jeefo** [comment]
is it still an issue with latest commit?
