### ISSUE TITLE
uninstall 

### ISSUE THREAD

**Issue by afterlifedead** [yapb/yapb#454]
How to uninstall yapb

**Comment by jeefo** [comment]
It's depends on how did you install it.

You need to patch liblist.gam in cstrike folder, and change gamedll line 
to "dlls\mp.dl" or remove entry in plugins.ini of metamod.

**Comment by Vladislav4KZ** [comment]
YaPB Installer (for Windows) creates a backup of ``liblist.gam`` named ``liblist.gam.bak``.

So, if you used the installer, you need to delete the ``liblist.gam`` file, and rename the ``liblist.gam.bak`` to ``liblist.gam``.

**Comment by afterlifedead** [comment]
But somehow wheb i start my game it just stuck on starting local server and crash

**Comment by Vladislav4KZ** [comment]
> But somehow wheb i start my game it just stuck on starting local server and crash

Open the ``liblist.gam`` file in a text editor, and paste its contents here.

And if you have metamod installed, also show the contents of the ``plugins.ini`` file, which is located in ``addons/metamod`` directory.

**Comment by afterlifedead** [comment]
I just reinstalled the game
