### ISSUE TITLE
Боты на картах с префиксом ka автоматически используют только нож

### ISSUE THREAD

**Issue by wood-grouse** [yapb/yapb#458]
Добрый день!
Стоят боты на гангейм сервере и почти на всех картах с префиксом ka они используют только нож. На других картах с префиксом gg, fy, aim, dm - все ок

**Comment by jeefo** [comment]
Это нормально, карта то кнайф арена. Но видимо нужен квар, который не будет включать jasonmode в зависимости от префикса карты.

**Comment by jeefo** [comment]
Нужен последняя сборка с GHA:  https://github.com/yapb/yapb/actions/runs/5304805731
Нужно в ``yapb.cfg `` дописать ``yb_ignore_map_prefix_game_mode 1``, после этого "проблема" должна уйти.

**Comment by wood-grouse** [comment]
Спасибо!
