### ISSUE TITLE
Не вызывается функция CSDM

### ISSUE THREAD

**Issue by VerVladislav** [yapb/yapb#459]
https://github.com/yapb/yapb/blob/b38c29af84e2db2875e2e70dadc3c1f2b37bca27/src/botlib.cpp#L3059
Она не должна вызваться?

**Comment by jeefo** [comment]
Должна:
https://github.com/yapb/yapb/blob/b38c29af84e2db2875e2e70dadc3c1f2b37bca27/src/linkage.cpp#L92

**Comment by VerVladislav** [comment]
Неа не вызывается.

**Comment by VerVladislav** [comment]
https://github.com/yapb/yapb/blob/b38c29af84e2db2875e2e70dadc3c1f2b37bca27/src/manager.cpp#L1227
Не знаю правильно ли так делать.
1261: else if (notify->ent () == victim) {
 1262: victimBot = notify.get ();
         ->victimBot->spawned();
 добавил и начало работать)

**Comment by jeefo** [comment]
Ну изначально оно вообще не должно было быть pfnSpawn, не совсем понял, почему оно там оказалось. Если без особых "проблем", то твой вариант правильный. Подготовлю фикс сейчас.

**Comment by jeefo** [comment]
Спасибо!
