### ISSUE TITLE
Some broken apps in bots

### ISSUE THREAD

**Issue by commandcobra7** [yapb/yapb#460]
Hi @jeefo lately I have seen some unnecessary, non-working applications, I wrote below what problems are with bots, I hope you can fix them all, thanks in advance.

1-Bots are looking at the enemy from the wall instead of picking up the node that appears close to the enemy while guessing the enemy.

2-They do not turn on the flashlight in the dark.

3-Instead of holding the current ladder node while climbing the ladder, the bots move to the next normal knot and look straight ahead instead of looking up when climbing the ladder.

**Comment by jeefo** [comment]
Hello!

1) It's a lasting-forever problem in bot :) no ETA
2) yb_check_darkness value ?
3) i haven't touched ladder code, some video would be useful

**Comment by commandcobra7** [comment]
@jeefo they don't turn on flashlight even though yb_check_darkness is 1

**Comment by Vladislav4KZ** [comment]
@commandcobra7 ``mp_flashlight`` is turned on?

**Comment by commandcobra7** [comment]
> @commandcobra7 `mp_flashlight` is turned on?

yes on

**Comment by jeefo** [comment]
map link ?

**Comment by commandcobra7** [comment]
I fixed the flashlight on problem
