### ISSUE TITLE
bots ignoring ladder nodes

### ISSUE THREAD

**Issue by commandcobra7** [yapb/yapb#462]
Hi @jeefo. On maps, instead of holding the current ladder node while climbing the ladder, bots move to the next regular node and look straight ahead instead of looking up when climbing the ladder.

![cs_assault_50530000](https://github.com/yapb/yapb/assets/91374215/c33551b5-7140-4057-9c3f-2403387a49f6)
![cs_assault_50530001](https://github.com/yapb/yapb/assets/91374215/20bce9a6-a467-4263-9b81-6b1faed39c8a)
![cs_assault_50530002](https://github.com/yapb/yapb/assets/91374215/65ba2fc4-9e99-431b-8b5e-0fa4d1a53fb2)
![cs_assault_bungler100000](https://github.com/yapb/yapb/assets/91374215/3aa058e2-13ff-4921-b33c-d803a05a3982)
![cs_assault_bungler100001](https://github.com/yapb/yapb/assets/91374215/c8cfaf0f-67c4-4d94-8aa6-e9e9549624f6)
![cs_assault_bungler100002](https://github.com/yapb/yapb/assets/91374215/d957b193-3ccb-4610-a880-4e5e8eff7041)
![cs_assault_rush20000](https://github.com/yapb/yapb/assets/91374215/d3c196c4-630e-4271-89d8-acdf5e4a402a)
![cs_assault_rush20001](https://github.com/yapb/yapb/assets/91374215/06873abe-cb85-4ecb-a11b-e27b4231fa8d)

**Comment by commandcobra7** [comment]
thx @jeefo

**Comment by jeefo** [comment]
problem solved with last commit?
