### ISSUE TITLE
Danger index does not check visibility

### ISSUE THREAD

**Issue by commandcobra7** [yapb/yapb#465]
Hi @jeefo When I looked at the zm_dust2_city map, I saw that the hazard index on nodes close to the wall was not getting a visibility check. instead of taking it to the visible node, it updates to the invisible side, even if the problem was solved before (https://github.com/yapb/yapb/pull/439/commits/57bb0ac822fe1c5f6a5d511fd8069facf9adfe4d), this problem continues. I hope the problem will be solved soon. thanks in advance

**Comment by jeefo** [comment]
hello, real walls? or wall corners or func_wall, brekables and doors?
