### ISSUE TITLE
Как собрать yapb.so на arm 32bit ?

### ISSUE THREAD

**Issue by melomansky** [yapb/yapb#466]
Я собирал по документации, но там собирается 64бит, а мне надо 32бит, что мне надо сделать, что настроить для сборки 32бит ?

Хочу добавить на сервер на движке Xash3D FWGS 0.21(32BIT), чтобы играть вместе с ними!

**Comment by jeefo** [comment]
Какой выхлоп у meson setup ?

**Comment by jeefo** [comment]
-m32 не добавляется только с -D64bit=true и если CPU aarch64, во всех остальных случаях идёт 32битная сборка.

**Comment by melomansky** [comment]
> Какой выхлоп у meson setup ?

![Screenshot_20230703_002204.jpg](https://github.com/yapb/yapb/assets/94536394/a2a2dd55-09bf-4ce4-bd34-f4b46c57e648)

**Comment by melomansky** [comment]
![Screenshot_20230703_002815.jpg](https://github.com/yapb/yapb/assets/94536394/2114004b-94a8-4a5d-b4e2-fd77f9da4fb2)

Тут я пробую запустить, и мне говорит что этот файл для 64битной системы то есть движок 64бит должен быть, а у меня 32 т.к нормально работает только 32-битнный.

**Comment by jeefo** [comment]
Странно, meson видит железку как aarch64, что за железка такая?)

**Comment by melomansky** [comment]
> Странно, meson видит железку как aarch64, что за железка такая?)

oracle cloud хост, пакеты ставил gcc g++ make cmake без :armhf

**Comment by melomansky** [comment]
такой выхлоп после выполнения команды meson compile -C build

ninja: Entering directory `/home/ubuntu/yapb/build'
[1/22] Compiling C++ object yapb.so.p/src_analyze.cpp.o
FAILED: yapb.so.p/src_analyze.cpp.o 
ccache c++ -Iyapb.so.p -I. -I.. -fvisibility=hidden -flto=auto -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -Werror -std=c++17 -fno-exceptions -fno-rtti -O3 -DVERSION_GENERATED -fno-threadsafe-statics -pthread -mtune=generic -mmmx -msse -msse2 -msse3 -mssse3 -mfpmath=sse -march=x86-64 -funroll-loops -fomit-frame-pointer -fno-stack-protector -fvisibility=hidden -fvisibility-inlines-hidden -fdata-sections -ffunction-sections -fcf-protection=none -fgraphite-identity -floop-nest-optimize -m32 -fPIC -isystem../ext/linkage -isystem../ext/crlib -isystem../ext -isystem../inc -isystem.. -isystem. -MD -MQ yapb.so.p/src_analyze.cpp.o -MF yapb.so.p/src_analyze.cpp.o.d -o yapb.so.p/src_analyze.cpp.o -c ../src/analyze.cpp
c++: error: unrecognized -march target: x86-64
c++: note: valid arguments are: armv4 armv4t armv5t armv5te armv5tej armv6 armv6j armv6k armv6z armv6kz armv6zk armv6t2 armv6-m armv6s-m armv7 armv7-a armv7ve armv7-r armv7-m armv7e-m armv8-a armv8.1-a armv8.2-a armv8.3-a armv8.4-a armv8.5-a armv8.6-a armv8-m.base armv8-m.main armv8-r armv8.1-m.main iwmmxt iwmmxt2 native
c++: error: missing argument to ‘-march=’
c++: error: unrecognized command-line option ‘-mmmx’
c++: error: unrecognized command-line option ‘-msse’
c++: error: unrecognized command-line option ‘-msse2’
c++: error: unrecognized command-line option ‘-msse3’
c++: error: unrecognized command-line option ‘-mssse3’
c++: error: unrecognized command-line option ‘-mfpmath=sse’
c++: error: unrecognized command-line option ‘-m32’; did you mean ‘-mbe32’?
[2/22] Compiling C++ object yapb.so.p/src_config.cpp.o
FAILED: yapb.so.p/src_config.cpp.o 
ccache c++ -Iyapb.so.p -I. -I.. -fvisibility=hidden -flto=auto -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -Werror -std=c++17 -fno-exceptions -fno-rtti -O3 -DVERSION_GENERATED -fno-threadsafe-statics -pthread -mtune=generic -mmmx -msse -msse2 -msse3 -mssse3 -mfpmath=sse -march=x86-64 -funroll-loops -fomit-frame-pointer -fno-stack-protector -fvisibility=hidden -fvisibility-inlines-hidden -fdata-sections -ffunction-sections -fcf-protection=none -fgraphite-identity -floop-nest-optimize -m32 -fPIC -isystem../ext/linkage -isystem../ext/crlib -isystem../ext -isystem../inc -isystem.. -isystem. -MD -MQ yapb.so.p/src_config.cpp.o -MF yapb.so.p/src_config.cpp.o.d -o yapb.so.p/src_config.cpp.o -c ../src/config.cpp
c++: error: unrecognized -march target: x86-64
c++: note: valid arguments are: armv4 armv4t armv5t armv5te armv5tej armv6 armv6j armv6k armv6z armv6kz armv6zk armv6t2 armv6-m armv6s-m armv7 armv7-a armv7ve armv7-r armv7-m armv7e-m armv8-a armv8.1-a armv8.2-a armv8.3-a armv8.4-a armv8.5-a armv8.6-a armv8-m.base armv8-m.main armv8-r armv8.1-m.main iwmmxt iwmmxt2 native
c++: error: missing argument to ‘-march=’
c++: error: unrecognized command-line option ‘-mmmx’
c++: error: unrecognized command-line option ‘-msse’
c++: error: unrecognized command-line option ‘-msse2’
c++: error: unrecognized command-line option ‘-msse3’
c++: error: unrecognized command-line option ‘-mssse3’
c++: error: unrecognized command-line option ‘-mfpmath=sse’
c++: error: unrecognized command-line option ‘-m32’; did you mean ‘-mbe32’?
[3/22] Compiling C++ object yapb.so.p/src_control.cpp.o
FAILED: yapb.so.p/src_control.cpp.o 
ccache c++ -Iyapb.so.p -I. -I.. -fvisibility=hidden -flto=auto -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -Werror -std=c++17 -fno-exceptions -fno-rtti -O3 -DVERSION_GENERATED -fno-threadsafe-statics -pthread -mtune=generic -mmmx -msse -msse2 -msse3 -mssse3 -mfpmath=sse -march=x86-64 -funroll-loops -fomit-frame-pointer -fno-stack-protector -fvisibility=hidden -fvisibility-inlines-hidden -fdata-sections -ffunction-sections -fcf-protection=none -fgraphite-identity -floop-nest-optimize -m32 -fPIC -isystem../ext/linkage -isystem../ext/crlib -isystem../ext -isystem../inc -isystem.. -isystem. -MD -MQ yapb.so.p/src_control.cpp.o -MF yapb.so.p/src_control.cpp.o.d -o yapb.so.p/src_control.cpp.o -c ../src/control.cpp
c++: error: unrecognized -march target: x86-64
c++: note: valid arguments are: armv4 armv4t armv5t armv5te armv5tej armv6 armv6j armv6k armv6z armv6kz armv6zk armv6t2 armv6-m armv6s-m armv7 armv7-a armv7ve armv7-r armv7-m armv7e-m armv8-a armv8.1-a armv8.2-a armv8.3-a armv8.4-a armv8.5-a armv8.6-a armv8-m.base armv8-m.main armv8-r armv8.1-m.main iwmmxt iwmmxt2 native
c++: error: missing argument to ‘-march=’
c++: error: unrecognized command-line option ‘-mmmx’
c++: error: unrecognized command-line option ‘-msse’
c++: error: unrecognized command-line option ‘-msse2’
c++: error: unrecognized command-line option ‘-msse3’
c++: error: unrecognized command-line option ‘-mssse3’
c++: error: unrecognized command-line option ‘-mfpmath=sse’
c++: error: unrecognized command-line option ‘-m32’; did you mean ‘-mbe32’?
[4/22] Compiling C++ object yapb.so.p/src_botlib.cpp.o
FAILED: yapb.so.p/src_botlib.cpp.o 
ccache c++ -Iyapb.so.p -I. -I.. -fvisibility=hidden -flto=auto -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -Werror -std=c++17 -fno-exceptions -fno-rtti -O3 -DVERSION_GENERATED -fno-threadsafe-statics -pthread -mtune=generic -mmmx -msse -msse2 -msse3 -mssse3 -mfpmath=sse -march=x86-64 -funroll-loops -fomit-frame-pointer -fno-stack-protector -fvisibility=hidden -fvisibility-inlines-hidden -fdata-sections -ffunction-sections -fcf-protection=none -fgraphite-identity -floop-nest-optimize -m32 -fPIC -isystem../ext/linkage -isystem../ext/crlib -isystem../ext -isystem../inc -isystem.. -isystem. -MD -MQ yapb.so.p/src_botlib.cpp.o -MF yapb.so.p/src_botlib.cpp.o.d -o yapb.so.p/src_botlib.cpp.o -c ../src/botlib.cpp
c++: error: unrecognized -march target: x86-64
c++: note: valid arguments are: armv4 armv4t armv5t armv5te armv5tej armv6 armv6j armv6k armv6z armv6kz armv6zk armv6t2 armv6-m armv6s-m armv7 armv7-a armv7ve armv7-r armv7-m armv7e-m armv8-a armv8.1-a armv8.2-a armv8.3-a armv8.4-a armv8.5-a armv8.6-a armv8-m.base armv8-m.main armv8-r armv8.1-m.main iwmmxt iwmmxt2 native
c++: error: missing argument to ‘-march=’
c++: error: unrecognized command-line option ‘-mmmx’
c++: error: unrecognized command-line option ‘-msse’
c++: error: unrecognized command-line option ‘-msse2’
c++: error: unrecognized command-line option ‘-msse3’
c++: error: unrecognized command-line option ‘-mssse3’
c++: error: unrecognized command-line option ‘-mfpmath=sse’
c++: error: unrecognized command-line option ‘-m32’; did you mean ‘-mbe32’?
[5/22] Compiling C++ object yapb.so.p/src_combat.cpp.o
FAILED: yapb.so.p/src_combat.cpp.o 
ccache c++ -Iyapb.so.p -I. -I.. -fvisibility=hidden -flto=auto -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -Werror -std=c++17 -fno-exceptions -fno-rtti -O3 -DVERSION_GENERATED -fno-threadsafe-statics -pthread -mtune=generic -mmmx -msse -msse2 -msse3 -mssse3 -mfpmath=sse -march=x86-64 -funroll-loops -fomit-frame-pointer -fno-stack-protector -fvisibility=hidden -fvisibility-inlines-hidden -fdata-sections -ffunction-sections -fcf-protection=none -fgraphite-identity -floop-nest-optimize -m32 -fPIC -isystem../ext/linkage -isystem../ext/crlib -isystem../ext -isystem../inc -isystem.. -isystem. -MD -MQ yapb.so.p/src_combat.cpp.o -MF yapb.so.p/src_combat.cpp.o.d -o yapb.so.p/src_combat.cpp.o -c ../src/combat.cpp
c++: error: unrecognized -march target: x86-64
c++: note: valid arguments are: armv4 armv4t armv5t armv5te armv5tej armv6 armv6j armv6k armv6z armv6kz armv6zk armv6t2 armv6-m armv6s-m armv7 armv7-a armv7ve armv7-r armv7-m armv7e-m armv8-a armv8.1-a armv8.2-a armv8.3-a armv8.4-a armv8.5-a armv8.6-a armv8-m.base armv8-m.main armv8-r armv8.1-m.main iwmmxt iwmmxt2 native
c++: error: missing argument to ‘-march=’
c++: error: unrecognized command-line option ‘-mmmx’
c++: error: unrecognized command-line option ‘-msse’
c++: error: unrecognized command-line option ‘-msse2’
c++: error: unrecognized command-line option ‘-msse3’
c++: error: unrecognized command-line option ‘-mssse3’
c++: error: unrecognized command-line option ‘-mfpmath=sse’
c++: error: unrecognized command-line option ‘-m32’; did you mean ‘-mbe32’?
[6/22] Compiling C++ object yapb.so.p/src_chatlib.cpp.o
FAILED: yapb.so.p/src_chatlib.cpp.o 
ccache c++ -Iyapb.so.p -I. -I.. -fvisibility=hidden -flto=auto -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -Werror -std=c++17 -fno-exceptions -fno-rtti -O3 -DVERSION_GENERATED -fno-threadsafe-statics -pthread -mtune=generic -mmmx -msse -msse2 -msse3 -mssse3 -mfpmath=sse -march=x86-64 -funroll-loops -fomit-frame-pointer -fno-stack-protector -fvisibility=hidden -fvisibility-inlines-hidden -fdata-sections -ffunction-sections -fcf-protection=none -fgraphite-identity -floop-nest-optimize -m32 -fPIC -isystem../ext/linkage -isystem../ext/crlib -isystem../ext -isystem../inc -isystem.. -isystem. -MD -MQ yapb.so.p/src_chatlib.cpp.o -MF yapb.so.p/src_chatlib.cpp.o.d -o yapb.so.p/src_chatlib.cpp.o -c ../src/chatlib.cpp
c++: error: unrecognized -march target: x86-64
c++: note: valid arguments are: armv4 armv4t armv5t armv5te armv5tej armv6 armv6j armv6k armv6z armv6kz armv6zk armv6t2 armv6-m armv6s-m armv7 armv7-a armv7ve armv7-r armv7-m armv7e-m armv8-a armv8.1-a armv8.2-a armv8.3-a armv8.4-a armv8.5-a armv8.6-a armv8-m.base armv8-m.main armv8-r armv8.1-m.main iwmmxt iwmmxt2 native
c++: error: missing argument to ‘-march=’
c++: error: unrecognized command-line option ‘-mmmx’
c++: error: unrecognized command-line option ‘-msse’
c++: error: unrecognized command-line option ‘-msse2’
c++: error: unrecognized command-line option ‘-msse3’
c++: error: unrecognized command-line option ‘-mssse3’
c++: error: unrecognized command-line option ‘-mfpmath=sse’
c++: error: unrecognized command-line option ‘-m32’; did you mean ‘-mbe32’?
ninja: build stopped: subcommand failed.

**Comment by melomansky** [comment]
если есть старый форк, можно его попробовать собрать или готовая либа.

**Comment by jeefo** [comment]
Вообще таргета armv7 небыло в планах посмотрю, что можно сделать.

**Comment by melomansky** [comment]
буду благодарен :)

**Comment by jeefo** [comment]
https://s3.rwsh.ru/share/2023/yapb.so

этот бинарник заведется?

**Comment by melomansky** [comment]
> https://s3.rwsh.ru/share/2023/yapb.so
> 
> этот бинарник заведется?

![Screenshot_20230703_163114.jpg](https://github.com/yapb/yapb/assets/94536394/8a2c852b-e9c7-41ff-85bc-af5be25ba393)

завёлся, но я хотел бы собрать сам ибо новые версии будут, а я так и буду сидеть на старой

**Comment by melomansky** [comment]
![Screenshot_20230703_174945.jpg](https://github.com/yapb/yapb/assets/94536394/30dafb85-5d3c-4338-9feb-b7618b6a1fbb)

сконфигурировал проект

**Comment by melomansky** [comment]
![Screenshot_20230703_175054.jpg](https://github.com/yapb/yapb/assets/94536394/3e308cfb-4aaa-44e3-8e9b-08ef62ab1ea9)

собрал yapb.so

**Comment by melomansky** [comment]
Проверил, всё работает, спасибо вам, ради меня выделили своё время на решение моей проблемы с маленькими изменениями в коде, ещё раз, спасибо!!!
