### ISSUE TITLE
[graph] Recalculate light level for existing waypoints

### ISSUE THREAD

**Issue by Shkarlatov** [yapb/yapb#468]
When I load old waypoints (for example, the `aim_sk_awp` map), the light level at all points is 0. The bots start turning the flashlight on and off.

It would be nice if we could recalculate light level on existing waypoints. But the problem immediately arises of how to update them in the "graph" repository, since the size \ checksum will change.

![image](https://github.com/yapb/yapb/assets/1247023/859a132d-e6ad-4d6e-8956-c136f47bf872)

**Comment by Vladislav4KZ** [comment]
Графы тут не причём, проблема в карте.

Похоже карта была была скомпилирована без расчёта освещения, там однородный свет без теней.

Даже свет от фонарика там не видно, так как карта слишком яркая.

**Comment by Vladislav4KZ** [comment]
It seems that all maps whose pwf waypoints have been converted to a graph are affected by this problem.

**Comment by Shkarlatov** [comment]
Following [this code](https://github.com/yapb/yapb/blob/master/src/graph.cpp#L1334-L1356) , the light level should be calculated each time waypoints are loaded.

**Comment by Vladislav4KZ** [comment]
> Following [this code](https://github.com/yapb/yapb/blob/master/src/graph.cpp#L1334-L1356) , the light level should be calculated each time waypoints are loaded.

Actually, the light calculation is done while saving the graph, not when it's loaded.

idk if @jeefo would be against calculating the light level during each graph load?

**Comment by Shkarlatov** [comment]
Is it possible to make bots react to turning off the light (`cs_mansion`)? The calculation of lighting is made\will be made only 1 time.
You may have to complicate the graph system, 1 calculation of the entire map, then store the changed areas in the same way as in vitable. Or add a new type `computed waypoint` which will be tied to the nearest light source and recalculated when using a trigger

**Comment by Vladislav4KZ** [comment]
The main subject of this issue seems to be solved in this commit: https://github.com/yapb/yapb/commit/9e67232c075e5b6e513bf7080a3c4f83da80df54

Try the latest build from GitHub Actions.
