### ISSUE TITLE
Flashlight

### ISSUE THREAD

**Issue by Borislaw94** [yapb/yapb#469]
Can you add cvar for flashlight off /on i cant stop bots flashlights.Thanks

**Comment by Vladislav4KZ** [comment]
yb_check_darkness 0 in ``addons\yapb\conf\yapb.cfg``

**Comment by Borislaw94** [comment]
not work in zombie server they play with flashlight again.

**Comment by Borislaw94** [comment]
unknown command "yb_graph_analyze_auto_start"
unknown command "yb_graph_analyze_auto_save"
unknown command "yb_graph_analyze_distance"
unknown command "yb_graph_analyze_max_jump_height"
unknown command "yb_graph_analyze_fps"
unknown command "yb_graph_analyze_clean_paths_on_finish"
unknown command "yb_graph_analyze_optimize_nodes_on_finish"
unknown command "yb_graph_analyze_mark_goals_on_finish"
unknown command "yb_economics_disrespect_percent"
unknown command "yb_check_darkness"
unknown command "yb_avoid_grenades"
unknown command "yb_object_destroy_radius"
unknown command "yb_breakable_health_limit"
unknown command "yb_threadpool_workers"
unknown command "yb_graph_url_upload"
unknown command "yb_autovacate_keep_slots"
unknown command "yb_kick_after_player_connect"
unknown command "yb_difficulty_auto_balance_interval"
unknown command "yb_quota_adding_interval"
unknown command "yb_quota_maintain_interval"
unknown command "yb_rotate_bots"
unknown command "yb_rotate_stay_min"
unknown command "yb_rotate_stay_max"
unknown command "yb_path_floyd_memory_limit"
unknown command "yb_path_dijkstra_simple_distance"
unknown command "yb_path_astar_post_smooth"
unknown command "yb_max_nodes_for_predict"

**Comment by Borislaw94** [comment]
i download [yapb-4.3.734-linux.tar.xz](https://github.com/yapb/yapb/releases/download/4.3.734/yapb-4.3.734-linux.tar.xz)

**Comment by Vladislav4KZ** [comment]
@Borislaw94 yapb.cfg which is in the repository, is for the new version of YaPB, which can be downloaded from the GitHub Actions artifacts. You should have edit **your** yapb.cfg, not download it from the repository.
