### ISSUE TITLE
Добавить возможность удаления всех путевых соединений с точки

### ISSUE THREAD

**Issue by Vladislav4KZ** [yapb/yapb#475]
Можно ли сделать, например, аргумент для команды ``yb g path_delete`` который удаляет все путевые соединения с ближайшей точки? Т.е. входящие, исходящие и двусторонние.

Бывают такие моменты, когда ставишь новую точку, когда вокруг находится много других точек, и, следовательно, появляется много путевых соединений у только что созданной точки.

Аргумент для команды ``yb g path_delete`` который удаляет все путевые соединения с ближайшей точки, ускорит процесс создания графа, так как не надо вручную удалять каждое соединение.

Команда ``yb g clean`` не подходит, если надо удалить бесполезные соединения с одной точки. Пару соединений удалятся, а остальные останутся.

А ``yb g clean all`` наоборот может удалить нужные путевые соединения в каких-то точках, про которые я сразу не могу узнать, пока не буду подходить к каждой и проверять наличие путевых соединений.

**Comment by jeefo** [comment]
Привет. Должно работать, но не тестил.

**Comment by Vladislav4KZ** [comment]
Да, работает.
