### ISSUE TITLE
Боты игнорируют ресемиклип (сквозную проходимость)

### ISSUE THREAD

**Issue by wood-grouse** [yapb/yapb#478]
Добрый день!
А есть настройка ботов, чтобы они не реагировали на контакт с союзником при семиклипе? А то на карте есть узкие проходы. Один бот в нем кемперит, а те, что сзади него - стоят на месте, дергаются и ждут, пока тот бот не освободит проход.
Хотя на сервере установлен ReSemiclip.

**Comment by jeefo** [comment]
привет. сделаю

**Comment by jeefo** [comment]
Попробуй yb_has_team_semiclip 1 в yapb.cfg в последнем билде.

**Comment by wood-grouse** [comment]
> Попробуйте yb_has_team_semiclip 1 в yapb.cfg в последней версии.

Спасибо, теперь все ок!
