### ISSUE TITLE
CSDM spawn issues

### ISSUE THREAD

**Issue by jeefo** [yapb/yapb#482]
Добрый ночи уважаемые коллеги! 

Проблема которая возможно каждый сталкивается с этим, но очень серьезная и проблемная. Почти все боты которые спавнятся около стен (Мод CSDM) идут к стене и пока ты не постреляешь по ним 2-3 раза они не очухаются и смотрят туда. Так же есть проблема связанная с тем что по середине спавна боты идут шифтом то есть медленно чтоб их никто не услышал. 

Уважаемые коллеги! Есть ли какой нибудь вариант решения данной проблемы? Кто нибудь может подсказать как решить? Если же проблема связанна с ботами, то пожалуйста прошу у администрации учесть это. Даже в Podbot-ах данная проблема наблюдается. Боты которые спавнятся в режиме presed в csdm так себя ведут. В режиме none тоже самое наблюдал когда бот идет и перед ним выходить стена. Они там стоят и не двигаются. Просьба решить данную проблему.

_Originally posted by @Somon007 in https://github.com/yapb/yapb/discussions/479_

**Comment by Somon007** [comment]
Данная проблема так же наблюдается в Public сервере. Думаю что боты ставят себе путь через стену исправляя Графы, т.к включено исправления графов (автоматом у ботов же есть такая возможность исправлять себе пути). Так вот, даже в Public боты себе строять путь через стену. А в случае с CSDM FFA появляясь около или близко к стенам они просто застревают там. В none режиме (стандартном csdm) тоже застревают на стенах.

**Comment by jeefo** [comment]
На паблике такого не видел

**Comment by jeefo** [comment]
Попробуй: https://github.com/yapb/yapb/actions/runs/6186407420

**Comment by Somon007** [comment]
> Попробуй: https://github.com/yapb/yapb/actions/runs/6186407420

Уже получше ведут себя, но все ровно моментами там где появляются около боксов или в тихих углах пока не увидят другого бота или человека стоят там идут по стене, но уже прогресс есть, ведут себя лучше чем другие + реакция почему-то стала отличаться. Я настраивал конфиг на реакцию, увеличивал а они вовсе быстрее стали, но это хорошо.

**Comment by jeefo** [comment]
какая карта? и можно .spawns к ней?

**Comment by Somon007** [comment]
> какая карта? и можно .spawns к ней?

Завтра скину сюда и спавны. 
В основном на картах
de_kabul_32
de_dust2_2006 
И вовсе в некоторых местах где бот появляется не около стены а около коробок. Они прям туда идут и через них хотят создать себе путь. К стенам вопросов нет. Они уже по лучше ведут себя около стен, а вот там где появляются около коробок - это пздц полный. Они прячутся и застревают там.

**Comment by Somon007** [comment]
> Попробуй: https://github.com/yapb/yapb/actions/runs/6186407420

После того как обновил этот мод на сервере где все по стандартному CSDM (без FFA), где спавн тоже стоит none, в карте de_dust2_sea боты вот таким вот образом появляются друг над другом и стоят на одном и том же месте крутясь. 
Вот ссылка на видео. Раньше в 4.3 версии такой фигни не было. В 4.4 не проверял. Но до загрузки твоей библиотеки которую ты дал такой ошибки 100% не было. 

https://disk.yandex.tj/i/LYNU6wj9qSZbLw

**Comment by Somon007** [comment]
На обычном 4.4 даже эта проблема есть (то есть без того компила который ты мне дал эта проблема есть. Дело не в dll с фиксом для ФФА которую ты мне дал а в 4.4 версии. (В последнем пресс релизе).

**Comment by jeefo** [comment]
у меня проблема не воспроизводится на обычном dust2 со стандартными спавнами

**Comment by jeefo** [comment]
closed as inactive
