### ISSUE TITLE
Не кидаются гранатами

### ISSUE THREAD

**Issue by Somon007** [yapb/yapb#483]
Доброй ночи уважаемые игроки! Не знаю сталкивались ли Вы с такой проблемой или нет, но боты мало пользуются гранатами. К примеру если в PodBot они пользовались ими и отвечали на гранату гранатой то в YaPB я редко вижу чтоб боты пользовались ими. 

А именно HE гранатами. В конфигурациях weapon.cfg стоит:

GrenadePercent = 100,1,1 - то есть шанс использование стоит на 100% и то все ровно боты ими не пользуются. 

P.S Пост отправил для администрации. Возможно они объяснять в чем проблема.

**Comment by Somon007** [comment]
> GrenadePercent - Это процент закупки.
> 
> Должны сойтись звёзды еще.

Понимаю конечно же но даже если идти против них гранатами или прямо кидать на них они тем же не отвечают. Или просто не пользуются гранатами. В целом не знаю как строиться формула использования ботами гранат но они ими редко пользуются что палить ботов)

**Comment by Somon007** [comment]
> Известная проблема, про неё уже писали: #414

Там говорится о HE картах, а тут во всех картах да и везде так. Боты реально мало пользуются гранатами к сожалению.

**Comment by Somon007** [comment]
> GrenadePercent - Это процент закупки.
> 
> Должны сойтись звёзды еще.

Предлагаю тогда сделать в настройках коэффициент использование гранаты ботами.
Так мы хоть сможем настраивать % для их использование ботами, ибо сейчас мои боты за все 20 минут пользуются гранатой 5-7 раз (все боты). А это очень мало для CSDM. Минимум хотя бы 25-30 раз за 20 минут.

**Comment by wood-grouse** [comment]
Надеюсь, [jeefo](https://github.com/jeefo), что-нибудь придумает с гранатами. Podbotы их часто использовали.

**Comment by Shkarlatov** [comment]
@Somon007 я подготовил некоторые изменения, подробнее посмотри в соседней теме #486.  Там же лежит новая dll (пока не от автора, а моя сборка).
