### ISSUE TITLE
Сделать приоритет по гранатам

### ISSUE THREAD

**Issue by wood-grouse** [yapb/yapb#486]
Добрый день.
Ранее поднималась проблема редким использованием гранат ботами.
А можно просто сделать квар, который делает приоритетом гранату и игнорирует другое оружие в арсенале?
У меня гангейм сервер, и на последнем уровне выдается глок+hе граната + иногда смоук и флэш, но боты редко бросают ее.
Вчера проверял на подботах, те почему-то и he бросают часто, и смоук с флэш.

**Comment by Shkarlatov** [comment]
Сделал фикс #488 , теперь боты охотнее используют гранаты.
Если примут изменения то для того чтобы боты чаще бросали гранаты нужно выставить переменную `yb_grenadier_mode =1`
Это меняет условия для броска гранат: они игнорируют минимальную дистанцию броска (могу кинуть себе в ноги), игнорируют союзников рядом, а так же игнорируют свои "чувства" (если слышат или догадываются что враг за стенкой).

Иногда весело за ними наблюдать, а иногда боты руинят всё :(

**Comment by Shkarlatov** [comment]
[yapb.zip](https://github.com/yapb/yapb/files/12775443/yapb.zip)
Скомпилированная версия (дебаг) для тестов.

**Comment by mohikan68** [comment]
when will this update be released for linux

**Comment by mohikan68** [comment]
> you can grab latest pre-release from releases

I am using version 4.3.734 but bots are not using bombs on my gungame server

**Comment by jeefo** [comment]
you need latest 4.4 reelease with yb_grenadier_mode set to 1
