### ISSUE TITLE
Attack monster

### ISSUE THREAD

**Issue by SOUZEGB** [yapb/yapb#489]
I have question about option attack monster in config cvar there is a option to enable this but this doesnt work btw (doesnt hit entity like boss) for what exactly this is ?

**Comment by jeefo** [comment]
what's entity classname, what mod?

**Comment by SOUZEGB** [comment]
Enitity classname is oberon boss, dr.rex or fall titan mixed zm with codmod

**Comment by Vladislav4KZ** [comment]
> Enitity classname is oberon boss, dr.rex or fall titan mixed zm with codmod

You don't seem to understand the question, can you provide links to these mods?

**Comment by SOUZEGB** [comment]
mods is make for personal use i cant provide you any links to these mods but i provide above entity classname and mod on which are using "codmod"

**Comment by jeefo** [comment]
I can't provide support for every third-party mods, especially private ones. Sorry
