### ISSUE TITLE
Should I resubmit a Chinese translation?

### ISSUE THREAD

**Issue by HaoJun0823** [yapb/yapb#491]
Hello,
In 2019, I translated the BOT chat from English to Chinese. [issu](https://github.com/yapb/yapb/issues/88)
When I re-downloaded yapb recently, I found that there was only chs_chat.cfg, and I did not see the relevant Chinese translation in yapb/cfg/addons/yapb/conf/lang/ of the master branch, I guess there must be a reason for this.
I re-translated it, hope it can help you.

[chs_chat_02.cfg.txt](https://github.com/yapb/yapb/files/13185795/chs_chat_02.cfg.txt)

**Comment by jeefo** [comment]
Hello! Yes, sure. It was totally outdated, so was removed, as there was no translators  who can do the work.

**Comment by HaoJun0823** [comment]
> Hello! Yes, sure. It was totally outdated, so was removed, as there was no translators who can do the work.

oh! I'm glad I helped you!
If you have chs (simplified Chinese) and cht (traditional Chinese) needs, you can @HaoJun0823 me next time and I will help you!
