### ISSUE TITLE
Headshot..

### ISSUE THREAD

**Issue by CirovicFG** [yapb/yapb#494]
Bots are doing Waaay to much headshots, i tried everything and they are just headshotting.

![Screenshot_47](https://github.com/yapb/yapb/assets/101999668/7ac1d36b-c112-4bba-8667-f4e8ce8fd14d)
![Screenshot_46](https://github.com/yapb/yapb/assets/101999668/756ff5be-2187-44d1-8b08-3a8046669afa)

**Comment by CirovicFG** [comment]
@jeefo please help with this

**Comment by jeefo** [comment]
try to use latest actions build

**Comment by CirovicFG** [comment]
How to check do i have it already? and where can i get them @jeefo

**Comment by jeefo** [comment]
``yb version`` in console should response with 4.4

https://github.com/yapb/yapb/releases/tag/4.4.913

**Comment by CirovicFG** [comment]
YaPB v4.3.734 (ID 734:84c2794)
   by YaPB Project (yapb@jeefo.net)
   https://yapb.jeefo.net/
compiled: Feb  3 2023 16:17:41 on f67f2e59c27f with gcc 11.1.0

**Comment by CirovicFG** [comment]
So i assume i need to update it.

.so file for linux would be enough to update it or i need to upload other files aswel? @jeefo
