### ISSUE TITLE
Не могу ботам запретить кемперить

### ISSUE THREAD

**Issue by wood-grouse** [yapb/yapb#495]
Здравствуйте.
А как запретить ботам кемперить? У меня мод гангейм.
В кфг стоит:

//Если не на нуле, боты будут пытаться выбирать кемперские точки в качестве своих целей и будут кемперить там некоторое время в зависимости от их личности.
yb_camping_allowed "0"

// Нижняя граница времени от которого расчитывается время для кемпинга.
// Default: "15.0", Min: "5.0", Max: "90.0"
yb_camping_time_min "5.0"

// Верхняя граница времени до которого расчитывается время для кемпинга.
// Default: "45.0", Min: "15.0", Max: "120.0"
yb_camping_time_max "15.0"

**Comment by jeefo** [comment]
они скорее всего уходят в task hide, что не совсем кемеерство.

**Comment by wood-grouse** [comment]
> они скорее всего уходят в task hide, что не совсем кемеерство.

А можно как-то сделать, чтобы они вообще в присядку не сидели в углу, а все время были в движении?

**Comment by jeefo** [comment]
попробуй yb_csdm_mode 1 в конфиге

**Comment by wood-grouse** [comment]
> yb_csdm_mode

Проверил, стоит 1

**Comment by wood-grouse** [comment]
![1](https://github.com/yapb/yapb/assets/47064244/ebeb7d56-574a-4e51-8677-7755a86cd84d)

**Comment by jeefo** [comment]
Ок, посмотрю в ближайшее время. Хайда в CSDM быть не должно.

**Comment by wood-grouse** [comment]
Сидит и в стену уставился))

**Comment by wood-grouse** [comment]
> Ок, посмотрю в ближайшее время. Хайда в CSDM быть не должно.

хорошо, спасибо

**Comment by wood-grouse** [comment]
Если что, айпи сервера [185.5.249.175:27038](steam://connect/185.5.249.175:27038)
Там 10 ботов + 2 бота в спектрах. Если больше 12 игроков, то играют живые люди.

**Comment by jeefo** [comment]
попробуй последий билд с actions

**Comment by wood-grouse** [comment]
Проверил. 
Не кемперят, но боты очень странно себя ведут. 
Пробегают мимо друг друга, словно не видят вблизи, стреляют по дальним целям, а не по ближним.
На самом деле это стало происходить после того, как сделали поддержку семиклипа у ботов. 
Откатился на версию v4.3.734, там все четко, никаких нареканий к игре ботов, кроме игнора семиклипа ну и кемперства.
Могу по возможности показать, в чем именно странность поведения ботов, т.к. словами тяжело объяснить.

**Comment by jeefo** [comment]
Да, если можно видео.

**Comment by wood-grouse** [comment]
На 1-м видео YapBot v4.3.734 с нормальной работой, т.е. боты, как живые игроки стреляют, не бездумно бегают. Только часто кемперят и нет поддержки семиклипа. **https://youtu.be/J82M5_1tPQ8**
На 2-м видео **https://youtu.be/0jbDMJrVA34** Yapbot v4.4.920 странно работают. Боты иногда в упор не видят врага, а стреляют по дальним целям. Бегают рядом друг с другом. Некоторые даже кемперили на открытом пространстве, хотя в v4.3.734 только за укрытием кемперили. Так работать стало после введения поддержки семиклипа.

**Comment by jeefo** [comment]
очень похоже на проблемы с определением команды, какой это мод?

**Comment by wood-grouse** [comment]
> очень похоже на проблемы с определением команды, какой это мод?

gungame by Avalance

**Comment by jeefo** [comment]
Сейчас играю на твоей сборке, не вижу таких проблем на последнем коммите, которые в видео.

**Comment by wood-grouse** [comment]
> Сейчас играю на твоей сборке, не вижу таких проблем на последнем коммите, которые в видео.

так ты последнюю версию ботов поставил? и квар yb_has_team_semiclip 1 стоит?

**Comment by jeefo** [comment]
> > Сейчас играю на твоей сборке, не вижу таких проблем на последнем коммите, которые в видео.
> 
> так ты последнюю версию ботов поставил? и квар yb_has_team_semiclip 1 стоит?

Видео: https://share.s3.rwsh.ru/2024/cs_ePGHPIJHGu.mp4

**Comment by wood-grouse** [comment]
> > > Сейчас играю на твоей сборке, не вижу таких проблем на последнем коммите, которые в видео.
> > 
> > 
> > так ты последнюю версию ботов поставил? и квар yb_has_team_semiclip 1 стоит?
> 
> Видео: https://share.s3.rwsh.ru/2024/cs_ePGHPIJHGu.mp4

Очень странно.
Давай я тебе лучше тогда линукс сборку отправлю на почту

**Comment by wood-grouse** [comment]
> jeefo

Отправил на почту линукс сборку, это точная копия, что на серве, но ток офнуты плагины статистики, что через удаленную бд работают.

**Comment by jeefo** [comment]
окей, завтра проверим

**Comment by jeefo** [comment]
> > > > Сейчас играю на твоей сборке, не вижу таких проблем на последнем коммите, которые в видео.
> > > 
> > > 
> > > так ты последнюю версию ботов поставил? и квар yb_has_team_semiclip 1 стоит?
> > 
> > 
> > Видео: https://share.s3.rwsh.ru/2024/cs_ePGHPIJHGu.mp4
> 
> Очень странно. Давай я тебе лучше тогда линукс сборку отправлю на почту

Ссылка просит подтверждения для скачивания.

**Comment by wood-grouse** [comment]
> > > > > Сейчас играю на твоей сборке, не вижу таких проблем на последнем коммите, которые в видео.
> > > > 
> > > > 
> > > > так ты последнюю версию ботов поставил? и квар yb_has_team_semiclip 1 стоит?
> > > 
> > > 
> > > Видео: https://share.s3.rwsh.ru/2024/cs_ePGHPIJHGu.mp4
> > 
> > 
> > Очень странно. Давай я тебе лучше тогда линукс сборку отправлю на почту
> 
> Ссылка просит подтверждения для скачивания.

Сейчас проверю

**Comment by wood-grouse** [comment]
Извиняюсь, почему-то ограниченный доступ был. Открыл по ссылке. На почту отправлю повторно

**Comment by wood-grouse** [comment]
Отправил на почту на всякий случай. Ссылка та же осталась, если что.

**Comment by jeefo** [comment]
https://share.s3.rwsh.ru/2024/cs_bD9DoC3856.mp4

**Comment by wood-grouse** [comment]
> https://share.s3.rwsh.ru/2024/cs_bD9DoC3856.mp4

На видео я вижу, что кфг ботов другое, т.к. в чате имена ботов отображаются? Какая версия ботов стоит ?
И на видео я вижу, что боты кемперят.
И учет ботами семиклипа квар активирован?

**Comment by MurLemur** [comment]
[wood-grouse](https://github.com/wood-grouse) , по идее если у ботов будет персоналити rusher, то кемперить не будут.
Посмотреть текущие персоналити и сложность ботов можно командой "yb list"

**Comment by jeefo** [comment]
> > https://share.s3.rwsh.ru/2024/cs_bD9DoC3856.mp4
> 
> На видео я вижу, что кфг ботов другое, т.к. в чате имена ботов отображаются? Какая версия ботов стоит ? И на видео я вижу, что боты кемперят. И учет ботами семиклипа квар активирован?

конфиг дефолт, включен только семиклип

**Comment by jeefo** [comment]
Что выдает ``yb list`` на сервере?

**Comment by jeefo** [comment]
Посмотрел еще раз конфиг, yb_difficulty = 0, это нормально? в 4.4 немного переработана сложность. на 0 - они дебилы, которые ничего не видят и не слышат, и ведут себя как идиоты. вохможно стоит попробовать, хотя-бы 1 или 2 ?

**Comment by wood-grouse** [comment]
> yb list

index   name                    personality     team    diff    frag    alive
[2  ]   pika                    normal          T       1       40      yes
[3  ]   L@VELASS                rusher          CT      1       61      yes
[4  ]   [RGG]*e*v*g*e*n*        normal          T       1       55      yes
[5  ]   Злобная         rusher          CT      1       60      yes
[6  ]   OMCK                    normal          T       1       24      yes
[7  ]   wael10004               normal          CT      1       47      yes
[8  ]   FoRman                  rusher          T       1       13      yes
[9  ]   Helpsystem              rusher          CT      1       29      yes
[10 ]   Nino4ka                 normal          T       1       59      yes
[12 ]   gs-m -> adidas          normal          T       1       44      yes
10 bots

**Comment by wood-grouse** [comment]
> Посмотрел еще раз конфиг, yb_difficulty = 0, это нормально? в 4.4 немного переработана сложность. на 0 - они дебилы, которые ничего не видят и не слышат, и ведут себя как идиоты. вохможно стоит попробовать, хотя-бы 1 или 2 ?

сложность от 0 до 1 стоит.
Слишком умные боты не нужны, а то на автоматах тяжело их убить или зарезать.

**Comment by wood-grouse** [comment]
Туплю, а где в кфг сделать, чтобы все боты были rusher?

**Comment by jeefo** [comment]
> Туплю, а где в кфг сделать, чтобы все боты были rusher?

будет, чуть позже, пока никак

**Comment by wood-grouse** [comment]
> > Туплю, а где в кфг сделать, чтобы все боты были rusher?
> 
> будет, чуть позже, пока никак
Спасибо, жду.
Но мне все равно не ясно, почему у меня боты бестолково бегают на последней версии yapb, а у тебя нет, хотя я скинул точь в точь сборку, как у меня на сервере с теми же настройками.
Можно кфг ботов увидеть?

**Comment by jeefo** [comment]
yb_difficulty 0 - проблема)

**Comment by wood-grouse** [comment]
> yb_difficulty 0 - проблема)

Ненене, 100% не в сложности ботов проблема!
Я на выходных проверю еще раз.
Обновлю на последнюю версию ботов + добавлю квары на семиклип и кемперство.

**Comment by jeefo** [comment]
попробуй последний блид отсюда: https://github.com/yapb/yapb/actions/runs/7587798053

**Comment by wood-grouse** [comment]
> попробуй последний блид отсюда: https://github.com/yapb/yapb/actions/runs/7587798053

Проверил, такая же ерунда, боты, словно болванчики бегают, как на видео, что я выше кидал((
Не трогая вообще ничего, а заменяя только yapb.so, такая ерунда происходит.
yb_difficulty 1 и 2 даже поставил, та же история...
понятия не имею, в чем проблема...ну не может быть такого, что на одинаковых сборках у тебя все работает хорошо, а у меня нет.
Откатился снова на версию v4.3.734, там все супер, не считая отсутствия поддержки префиксов карт и семиклипа.
Можешь скинуть мне все, что ты менял в моей сборке?
Полностью папку yapb.

**Comment by jeefo** [comment]
чудеса да, напиши мне в дискорде, хочу воочию увидеть: .jeefo

**Comment by wood-grouse** [comment]
У меня проблема решена, вроде))
Спасибо!
