### ISSUE TITLE
Allow use custom directory for yapb installation

### ISSUE THREAD

**Issue by Shkarlatov** [yapb/yapb#498]
Из дискуссии https://github.com/yapb/yapb/issues/497:

Было бы полезно уметь разгружать конфиги относительно yapb.dll, это даст возможность иметь несколько версий и\или иметь разные конфиги. Да, это немного специфичный кейс, но даже при разработке полезно иметь несколько версий.

Так же при реализации относительных путей станет возможно установить ботов в `cstrike_addon` оставив `cstrike` полностью в оригинальном виде. В `cstrike_addon` устанавливать ботов и там же создавать файл `liblist.game`.

Например старый metamod умеет грузить конфиги только из cstrike, но metamod-r [уже может (meta_init_gamedll)](https://github.com/theAsmodai/metamod-r/blob/master/metamod/src/metamod.cpp) из cstrike_addon.

Причём мы сохраним совместимость со старым способом установки.

**Comment by Shkarlatov** [comment]
Сейчас если установить в `Half-Life\cstrike_addon\addons\yapb` то боты принудительно создают как минимум `D:\Steam\steamapps\common\Half-Life\cstrike\addons\yapb\{conf,data}`

**Comment by jeefo** [comment]
Should work with latest commit.

**Comment by jeefo** [comment]
Bot is almost unusable when in symlinks on linux, needs a better way...

**Comment by jeefo** [comment]
.. and loading configs and other things works just fine ?

**Comment by Vladislav4KZ** [comment]
> .. and loading configs and other things works just fine ?

Нет, я же написал что конфиги тоже не грузятся.

Меню только на английском языке, и в консоли пишется что не удалось загрузить конфиги, используются стандартные захардкоденные значения.

Из-за этого бот вообще не пригоден к игре, ничего толком не работает нормально.

**Comment by Vladislav4KZ** [comment]
Для андроида может надо вернуть загрузку кофигов и графов с папки addons/yapb? Т.к. там саму библиотеку бота всё равно никуда невозможно переставить.

Она может хранится только в одном конкретном месте (различие только в названиях папок под разные архитектуры процессора), в отличие от винды или линукса, где пользователь может сам переименовать папку где находится .dll/.so библиотека бота.

**Comment by Vladislav4KZ** [comment]
И да, я это проверял на своём кастомном билде CS16Client, где я обновил YaPB ботов.

В репозитории от Velaron пока ещё находится CS16Client со старым билдом бота.

**Comment by jeefo** [comment]
да, для андройда realtive-location не подходит.

**Comment by jeefo** [comment]
можешь проверить на последнем коммите ? честно-гвооря не тестировал.

**Comment by Vladislav4KZ** [comment]
> можешь проверить на последнем коммите ? честно-гвооря не тестировал.

Всё работает. Конфиги и графы грузятся успешно, боты присоедняются к игре.
