### ISSUE TITLE
[CS25] Crash while loading cs_coldmansion

### ISSUE THREAD

**Issue by Fixer-007** [yapb/yapb#500]
Running Directly or via metamod. 4.3.734 on latest hl25/cs, win 10.

**Comment by Fixer-007** [comment]
Tried this one: https://github.com/yapb/yapb/suites/18610755014/artifacts/1081746547

CTD right after pressing the "Start" button, latest HL/CS update from yesterday. Same with cs_assault.

**Comment by jeefo** [comment]
yup, my bad, check the latest commit

**Comment by Fixer-007** [comment]
Issue fixed, thanks!
