### ISSUE TITLE
yb_show_latency не работает старых hlds?

### ISSUE THREAD

**Issue by Antom91** [yapb/yapb#503]
`Console initialized.
Protocol version 46
Exe version 3.1.1.1
Exe build: 13:14:23 Dec 22 2003 (2615)
Auth Server
Server IP address 172.17.0.2:27015
`
yapb: [4.3.734](https://github.com/yapb/yapb/releases/tag/4.3.734)
Metamod version 1.21p37
Counter-Strike 1.5

Похоже что yb_show_latency опция вообще не работает, либо я чего то не понимаю. Мне показывает постоянно пинг 0 у всех ботов, так же пробовал yb_show_latency = 1 , аналогично, никаких изменений не увидел 

У podbot все работает, проверял.

это опции установлены в стандартное значение 

`//
// Lower bound for base bot ping shown in scoreboard upon creation.
// ---
// Default: "7", Min: "0", Max: "100"
//
yb_ping_base_min "7"

//
// Upper bound for base bot ping shown in scoreboard upon creation.
// ---
// Default: "34", Min: "0", Max: "100"
//
yb_ping_base_max "34"
`

**Comment by jeefo** [comment]
На старом движке не работает.

**Comment by Antom91** [comment]
> На старом движке не работает.

есть ли в планах пофиксить это ?

**Comment by jeefo** [comment]
> > На старом движке не работает.
> 
> есть ли в планах пофиксить это ?

Это нельзя пофиксить, это клиентская библиотека  старых билдов. Есть есть бит fakeclient, там в любом случае будет 5.
