### ISSUE TITLE
game crashes on server start

### ISSUE THREAD

**Issue by bappp0** [yapb/yapb#504]
i installed the mod through the installer and manually. im using metamod, amxmodx, and csbot enabler (cs bot enabler is strictly for aimbotz, i dont use it for anything else). im not using the beta of cs 1.6 either (aka im on the newest version)

**Comment by jeefo** [comment]
You need latest DLL from here: https://github.com/yapb/yapb/actions/runs/7049913161

to support hl25 anniversary update
