### ISSUE TITLE
YaPB 4.4.XXX боты боятся стрелять

### ISSUE THREAD

**Issue by snaike00** [yapb/yapb#506]
Наблюдаю проблемы с версиями 4.4.XXX - боты толком не стреляют по врагам, а если и стреляют, то по одной пуле и с приличной задержкой.
Поменял бинарник на 4.3.734 с конфигами от 4.4.XXX - боты стали маньяками в хорошем смысле этого слова.
Куда копать?

**Comment by jeefo** [comment]
поэтому 4.4 ещё и не в релизе, будем разбираться

**Comment by jeefo** [comment]
А моды есть какие-нибудь?

**Comment by jeefo** [comment]
Проста вот это, не выглядит как "боятся стрелять":
![image](https://github.com/yapb/yapb/assets/1781346/e95a140a-f0a9-45ee-8a45-3483d4a63a50)

**Comment by jeefo** [comment]
А если совсем дефолтные конфиги взять? вот честно, yb_difficulty 4 - и всё, больше ничего

**Comment by jeefo** [comment]
верно

**Comment by jeefo** [comment]
> Наблюдаю проблемы с версиями 4.4.XXX - боты толком не стреляют по врагам, а если и стреляют, то по одной пуле и с приличной задержкой. Поменял бинарник на 4.3.734 с конфигами от 4.4.XXX - боты стали маньяками в хорошем смысле этого слова. Куда копать?

покажи вывод ``yb list`` демку не посмотреть, либо они блочат РФовские адреса, либо РФ блочит украинские.. :(

Логов не будет, если нет проблем)

**Comment by jeefo** [comment]
попробуй последний блид отсюда: https://github.com/yapb/yapb/actions/runs/7587798053

**Comment by jeefo** [comment]
При старте сервера есть строка

```
YaPB v4.4.937 successfully loaded for game: Counter-Strike v1.6.
        Flags: BotVoice, ReGameDLL, FakePing, Metamod, SIMD: 4.1 & 4.2.
```

Что она показывает ?

**Comment by jeefo** [comment]
Есть вероятность, ч то проблема да, там.

VDS или хостинг?

**Comment by jeefo** [comment]
всё будет.

очень странная железка у тебя)

**Comment by jeefo** [comment]
Должно работать, в последнем билде.

**Comment by jeefo** [comment]
пооверь, чтоб сложность была 4, и стандартный difficulty.cfg от 4.4.

по умолчанию на 4.4 сложность теперь 3.

**Comment by jeefo** [comment]
> > пооверь, чтоб сложность была 4, и стандартный difficulty.cfg от 4.4.
> > по умолчанию на 4.4 сложность теперь 3.
> 
> Все проверено ) Конфиги свежие, с репы. Странно что такие значения для Expert делают только хуже, чем по стандарту. В yapb.cfg
> 
> ```
> yb_difficulty "4"
> yb_difficulty_min "4"
> yb_difficulty_max "4"
> yb_difficulty_auto "0"
> ```
> 
> Кстати, раз уж затронули yapb.cfg `yb_max_nodes_for_predict "25"` Не пойму, его надо уменьшать или увеличивать для "усиления эффекта"

Я их не могу победить на 4 уровне, как и зботы сейчас, но они определённо стали слабее чем в 4.3 (не сильно), но это вроде не баг, т.к. многие жаловались, что ботов не убить вообще.

Касаемо ``yb_max_nodes_for_predict`` допустим бот идёт, услышал кого-то,  Есть точка, куда бот будет смотреть "ожидая" врага оттуда, чем больше указано в переменной, тем больший путь (там составляется именно путь по нодам) может быть от положения бота  до места точки встречи. Если поставить очень много, боты могут начать дуплится в стены частенько)

**Comment by jeefo** [comment]
> Пока они там развлекаются, ситуация выглядит так:
> 
> ![00](https://camo.githubusercontent.com/09bf6b97666cfbc085e3cf8fa84a516c480ac32daff546f60f41841497d1b1b1/68747470733a2f2f692e6962622e636f2f7847334d334c582f30302e6a7067)

Не в чистую, но в целом неплохо)

Возможно, на 4.3 был включен ``yb_whose_your_daddy``. Это был чистейший чит, со стороны ботов, его теперь нет. Если он, конечно, нужен, его можно вернуть назад.

**Comment by jeefo** [comment]
Я думаю, можно в дискуссии переместить, основная проблема решена?)
