### ISSUE TITLE
bot victim always turns angles towards killer on dying animation

### ISSUE THREAD

**Issue by that-is-not-great** [yapb/yapb#510]
The bots turn to the killer on being killed, no matter what position the killer is, or if the bot did not see the killer, the victim bot will turn on dying to the killer. I cannot find the code that causes this behavior, its very annoying and inhumane, do you know what causes this?
I also turned off all bot hearing functions, to test, they still turn angles to the killer

https://github.com/yapb/yapb/assets/132457555/b7f8c813-ca92-4873-9964-2b2ec8027600

**Comment by jeefo** [comment]
It's pretty much logical imho, but not for deathmatch maps ofc.

**Comment by jeefo** [comment]
OK, i have re-read topic on the pc.. and i have misunderstood your question from a start :)

Well, it's game related. Bot's doesn't control dying/dead player in any things besides chat. Angles of player model is not adjusted in any way.

> also why does handleDeath get called before takeDamage on bot death?

they get called by game, from network message handler, so i got no idea, you check out regamedll sources for that.

**Comment by jeefo** [comment]
This happens randomly with all fakeclients, just tested with official cs bots, same result. so probably dirty fix is a good idea.
