### ISSUE TITLE
yb_enable_query_hook not working properly on Internet tab

### ISSUE THREAD

**Issue by christophrus** [yapb/yapb#512]
Servers player count works properly in game browsers favourites tab and in detailed server info window, but does not work on Internet tab. I tried with both release 4.3.734 and current master.

**Comment by jeefo** [comment]
It's normal. Not sure, but probably something has to be changed [here](https://github.com/dreamstalker/rehlds/blob/63fde229c98f7e1bb8f7ea9b8358027414ed26ac/rehlds/engine/sv_steam3.cpp#L540):  to get it working, not on bot side.

but not sure it's a good idea to fake internet servers)
