### ISSUE TITLE
"All bots died..." spam in server console

### ISSUE THREAD

**Issue by di57inct** [yapb/yapb#514]
Is there any way to get rid of this? I have a custom management AMXX plugin that sets them to spectators when there are no active players and this message keeps spamming.

**Comment by jeefo** [comment]
it's executing ``yb killall`` ?

**Comment by di57inct** [comment]
Yes, that was it. Fixed the script and now it's fine. Sorry for the bad report.

**Comment by jeefo** [comment]
anyway i need this too, i will add ability to silence this message with that command
