### ISSUE TITLE
enable_fake_steamids not functional yet?

### ISSUE THREAD

**Issue by siriuzwhite** [yapb/yapb#518]
I found the following undocumented function from commit 1dc1043f7d750f02c8d7767e219f35e7e562e7fd some days ago:
https://github.com/yapb/yapb/blob/d82124e5953117199b5eedddc266f628617b7b11/src/support.cpp#L542-L550

So I added `yb_enable_fake_steamids "1"` to conf/yapb.cfg

But when I run status on the server console all bots still have "BOT" as uniqueid like this:
```
#      name userid uniqueid frag time ping loss adr
# 1 "-=Sh0rTy=-" 1 BOT   0 00:21    0    0
# 2  "Tator" 2 BOT   0 00:21    0    0
# 3 "fury16" 3 BOT   0 00:21    0    0
# 4 "wiggles" 4 BOT   0 00:21    0    0
# 5 "phobos" 5 BOT   0 00:21    0    0
# 6 "Jonny Matrix" 6 BOT   0 00:21    0    0
# 7 "bling bling" 7 BOT   0 00:21    0    0
# 8 "SaVaGe_RuBy" 8 BOT   0 00:21    0    0
8 users
```

**Comment by jeefo** [comment]
Hello.

It's not meant to be fake in ``status`` command, status command provided by engine.

It's was a request for game statistics plugins, when you're unable or won't to track players via Nickname, and bots having always a ``BOT`` steam-id all bots players statistics combined into a single player.
