### ISSUE TITLE
一些功能不生效。。

### ISSUE THREAD

**Issue by all85100** [yapb/yapb#521]
这两个参数的功能不生效
yb_difficulty "0"
yb_autokill_delay "0.1"

**Comment by Vladislav4KZ** [comment]
> yb_autokill_delay "0.1"

This cvar only works with integer values. I tested it in vanilla Counter-Strike 1.6 (without any plugins)

**Comment by Vladislav4KZ** [comment]
> This cvar only works with integer values. I tested it in vanilla Counter-Strike 1.6 (without any plugins)

No, I was wrong. Values less than 1 should not work judging by the following code: https://github.com/yapb/yapb/blob/master/src/manager.cpp#L507

**Comment by all85100** [comment]
The functions of these two parameters are used normally in v4.3
