### ISSUE TITLE
CVars are not updated after read from yapb.cfg

### ISSUE THREAD

**Issue by di57inct** [yapb/yapb#525]
I have saved some settings in server.cfg which executes at map change(after yapb.cfg) so i don't have to re-edit the cfg file after each bot update. For example, yb_enable_query_hook is set to 0 as default in yapb.cfg and 1 in my server.cfg. If I go to the server console and type yb_enable_query_hook it will say it is set to 1, but it behaves like in the yapb.cfg(0). Changing map or making bots rejoin doesn't solve the issue.
Settings saved in my server.cfg:
```
yb_user_follow_percent 0
yb_user_max_followers 0
yb_radio_mode 1
yb_tkpunish 0
yb_freeze_bots 0
yb_attack_monsters 0
yb_pickup_custom_items 1
yb_pickup_ammo_and_kits 1
yb_ignore_objectives 0
yb_chat 0
yb_check_enemy_rendering 1
yb_check_enemy_invincibility 1
yb_ignore_cvars_on_changelevel ""
yb_autovacate 1
yb_autovacate_keep_slots 1
yb_quota 3
yb_autokill_delay 0
yb_join_after_player 0
yb_difficulty 1
yb_show_avatars 1
yb_show_latency 1
yb_save_bots_names 1
yb_rotate_bots 1
yb_rotate_stay_min 450
yb_rotate_stay_max 1800
yb_has_team_semiclip 1
yb_path_astar_post_smooth 1
//yb_display_welcome_text 0
yb_enable_query_hook 1
yb_enable_fake_steamids 1
yb_camping_time_min 5
yb_camping_time_max 15
```

**Comment by jeefo** [comment]
Answer is simple. That settings should not be in a server.cfg.. It's exclusively should be in yapb.cfg. You can skip overwriting yapb.cfg when updates are done.

**Comment by di57inct** [comment]
Okay, sorry but i'm just too lazy sometimes and try to skip things that can be skipped. Please close issue if you think it's not worth it.
