### ISSUE TITLE
[Suggestion] Have yb_enable_query_hook report real time the bot has been on the server instead of random time

### ISSUE THREAD

**Issue by di57inct** [yapb/yapb#526]
New bot joins and server reports 2+ hours activity. Makes it kind of easy to figure it's fake.
EDIT: this should work at least when bot rotation is enabled if not in the other cases.

**Comment by jeefo** [comment]
You have very specific use. Usually bots join game same time, so they'll will have same time even with fake time.

**Comment by di57inct** [comment]
If multiple bots join at the same time, you can add a minute or 2 of fake minutes between them. This would also work good with remember name setting, where they can stay over map change.

**Comment by jeefo** [comment]
Sorry, too much work for very rare request. Closing right now. But will keep it in the mind.

**Comment by di57inct** [comment]
np bro hope you give it a shot sometime
