### ISSUE TITLE
Zombie mode support

### ISSUE THREAD

**Issue by amirwolf5122** [yapb/yapb#527]
Does this robot support zombie mode?

**Comment by di57inct** [comment]
Yes it even works better than cs bot. It has advanced options, just configure it properly in yapb.cfg to suit your needs.

**Comment by amirwolf5122** [comment]
I am testing it
Can I reduce the accuracy of weapons like AWP?
Or block access to a weapon in certain maps?
Can this robot buy items in this mode?

**Comment by di57inct** [comment]
As far as i know, zp forces bots to choose from menus and buy extra items. Accuracy and other difficulty settings can be adjusted in difficulty.cfg
