### ISSUE TITLE
Camping

### ISSUE THREAD

**Issue by SuperCHAOSXXX** [yapb/yapb#528]
I've tested bots on hostage maps, for example like cs_italy2, cs_militia etc. I've noticed that, most of the time, Terrorist bots don't go outside their base range, they'll most of the time protect the hostages, instead of going outside and confronting the CT's. Can it be balanced a little bit towards aggression/confrontation. I've tried setting "yb_camping_allowed" to "0", but it still didn't solve it.

**Comment by SuperCHAOSXXX** [comment]
> **jeefo**, and also try cs_assault_delta for the test camping of t-team

I think i've tried cs_assault yesterday, they rarely go out of their way to attack CT's. Mostly they're circling around inside the base.

**Comment by Vladislav4KZ** [comment]
> EDIT: tried cs_delta_assault, most T's stay inside the base, only 1 or 2 go out.

It's because of the buggy graph.
It got into the database because someone updated YaPB where graph auto-collection is enabled by default, which doesn't check graphs for errors.

**Comment by jeefo** [comment]
Agree with @Vladislav4KZ it's totally bugged graph. If some can, it's would be good to create new one for this famous map.

**Comment by jeefo** [comment]
check the latest build, should be a little better

**Comment by jeefo** [comment]
Unrelated to this issue. And... 

https://github.com/yapb/yapb/assets/1781346/9b1f674f-9e8c-4b1b-9b7b-651a19ff8872

**Comment by jeefo** [comment]
Попробовал с семиклипом, тоже никак, нужно видео, желательно с yb_debug 2

**Comment by jeefo** [comment]
closed as inactive
