### ISSUE TITLE
Yapbots stucked,freeze

### ISSUE THREAD

**Issue by ray913d** [yapb/yapb#529]
https://github.com/yapb/yapb/assets/160438349/789118f5-d2cb-4bc3-8c9e-019fe33b2c27

i find it interesting that Yapbots are superb when it comes at grenade throws, they are humanlike.
however i noticed that yapbots get stucked behind doors (de_dust2)behind walls of some maps . also, Yapbots jump over and over on to dead bodies lying on the ground,nnot really sure if they are "bug?" trying to change weapon or pick item. another issue i noticed is that yapbots do not use their flashlight when navigating dark corner even though modified yapb.config, as compared to podbotmm v3b22 they automatically use  torch during their navigation. finally Yapbot freezes out at flashbang explosion, unlike podbotmm v3b22 they remain steady and shoot at the direction of the launcher.
yapb is good...thanks..i wish these issues will be addressed in the upcoming updates..

**Comment by ray913d** [comment]
https://github.com/yapb/yapb/assets/160438349/f7ce3009-0627-4ee0-a373-016d4f60d53e

**Comment by ray913d** [comment]
here is my friend yapbot spriggan get stucked

https://github.com/yapb/yapb/assets/160438349/1b45e7df-76bc-48de-a8d4-ae45c0a2f519

**Comment by jeefo** [comment]
pleas post your yapb.cfg and plugins in first place.

**Comment by ray913d** [comment]
> pleas post your yapb.cfg and plugins in first place.

//
// @package: YaPB
// @version: 4.4
// @author: YaPB Project
// @filename: yapb.cfg
// 
// YaPB main configuration file. Can be executed via "exec" command.
//

//
// Autostart analyzer if all other cases are failed.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_graph_analyze_auto_start "1"

//
// Auto save results of analysis to graph file. And re-add bots.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_graph_analyze_auto_save "1"

//
// The minimum distance to keep nodes from each other.
// ---
// Default: "64", Min: "42", Max: "128"
// 
yb_graph_analyze_distance "64"

//
// Max jump height to test if next node will be unreachable.
// ---
// Default: "44", Min: "44", Max: "64"
// 
yb_graph_analyze_max_jump_height "44"

//
// The FPS at which analyzer process is running. This keeps game from freezing during analyzing.
// ---
// Default: "30.0", Min: "25.0", Max: "99.0"
// 
yb_graph_analyze_fps "30.0"

//
// Specifies if analyzer should clean the unnecessary paths upon finishing.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_graph_analyze_clean_paths_on_finish "1"

//
// Specifies if analyzer should merge some near-placed nodes with much of connections together.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_graph_analyze_optimize_nodes_on_finish "1"

//
// Specifies if analyzer should mark nodes as map goals automatically upon finish.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_graph_analyze_mark_goals_on_finish "1"

//
// Enables or disables useful messages about bot states. Not required for end users.
// ---
// Default: "0", Min: "0", Max: "4"
// 
yb_debug "0"

//
// Forces all alive bots to build path and go to the specified here graph node.
// ---
// Default: "-1", Min: "-1", Max: "4096"
// 
yb_debug_goal "-1"

//
// Specifies the percent of bots, that can follow leader on each round start.
// ---
// Default: "20", Min: "0", Max: "100"
// 
yb_user_follow_percent "100"

//
// Specifies how many bots can follow a single user.
// ---
// Default: "1", Min: "2", Max: "3"
// 
yb_user_max_followers "2"

//
// If enabled, all bots will be forced only the knife, skipping weapon buying routines.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_jasonmode "0"

//
// Allows bots to use radio or chatter.
//  Allowed values: '0', '1', '2'.
//  If '0', radio and chatter is disabled.
//  If '1', only radio allowed.
//  If '2' chatter and radio allowed.
// ---
// Default: "2", Min: "0", Max: "2"
// 
yb_radio_mode "1"

//
// Specifies whether bots able to use team economics, like do not buy any weapons for whole team to keep money for better guns.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_economics_rounds "0"

//
// Allows bots to ignore economics and buy weapons with disrespect of economics.
// ---
// Default: "25", Min: "0", Max: "100"
// 
yb_economics_disrespect_percent "100"

//
// Allows or disallows bot to check environment for darkness, thus allows or not to use flashlights or NVG.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_check_darkness "1"

//
// Allows bots to partially avoid grenades.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_avoid_grenades "1"

//
// Allows or disallows bots to take revenge of teamkillers / team attacks.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_tkpunish "1"

//
// If enabled, the bots think function is disabled, so bots will not move anywhere from their spawn spots.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_freeze_bots "0"

//
// Allows or disallows the use of spray paints.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_spraypaints "1"

//
// Allows or disallows bots weapon buying routines.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_botbuy "1"

//
// Allows bots to destroy breakables around them, even without touching with them.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_destroy_breakables_around "1"

//
// The radius on which bot searches world for new objects, items, and weapons.
// ---
// Default: "450.0", Min: "64.0", Max: "1024.0"
// 
yb_object_pickup_radius "64,0"

//
// The radius on which bot destroy breakables around it, when not touching with them.
// ---
// Default: "400.0", Min: "64.0", Max: "1024.0"
// 
yb_object_destroy_radius "400.0"

//
// Specifies the paths for the bot chatter sound files.
// ---
// Default: "sound/radio/bot"
// 
yb_chatter_path "sound/radio/bot"

//
// Specifies semicolon separated list of weapons that are not allowed to buy / pickup.
// ---
// Default: ""
// 
yb_restricted_weapons ""

//
// Allows or disallows bots to attack monsters.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_attack_monsters "0"

//
// Allows or disallows bots to pickup custom items.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_pickup_custom_items "0"

//
// Allows bots pickup mod items like ammo, health kits and suits.
// ---
// Default: "0", Min: "0", Max: "0"
// 
yb_pickup_ammo_and_kits "1"

//
// Allows or disallows bots to pickup best weapons.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_pickup_best "1"

//
// Allows or disallows bots to do map objectives, i.e. plant/defuse bombs, and saves hostages.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_ignore_objectives "0"

//
// Enables or disables bots chat functionality.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_chat "1"

//
// Bot chances to send random dead chat when killed.
// ---
// Default: "30", Min: "0", Max: "100"
// 
yb_chat_percent "30"

//SHOTTHRUWALLS
// Specifies whether bots able to fire at enemies behind the wall, if they hearing or suspecting them.
// ---
// Default: "2", Min: "0", Max: "3"
// 
yb_shoots_thru_walls "1"

//ENEMY SEARCH
// Enables or disables searching world for enemies.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_ignore_enemies "0"

//
// Enables or disables checking enemy rendering flags. Useful for some mods.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_check_enemy_rendering "0"

//INVINCIBILITY CHECK
// Enables or disables checking enemy invincibility. Useful for some mods.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_check_enemy_invincibility "0"

//ENEMY STAB
// Enables or disables bot ability to stab the enemy with knife if bot is in good condition.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_stab_close_enemies "1"

//
// Binds specified key for opening bots menu.
// ---
// Default: "="
// 
yb_bind_menu_key "="

//
// Specifies comma separated list of bot cvars, that will not be overwritten by config on changelevel.
// ---
// Default: "yb_quota,yb_autovacate"
// 
yb_ignore_cvars_on_changelevel "yb_quota,yb_autovacate"

//
// Disables logger to write anything to log file. Just spew content to the console.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_logger_disable_logfile "0"

//
// The value (password) for the setinfo key, if user sets correct password, he's gains access to bot commands and menus.
// ---
// Default: ""
// 
yb_password ""

//
// The name of setinfo key used to store password to bot commands and menus.
// ---
// Default: "_ybpw"
// 
yb_password_key "_ybpw"

//
// Enables or disables CSDM / FFA mode for bots.
//  Allowed values: '0', '1', '2', '3'.
//  If '0', CSDM / FFA mode is auto-detected.
//  If '1', CSDM mode is enabled, but FFA is disabled.
//  If '2', CSDM and FFA mode is enabled.
//  If '3', CSDM and FFA mode is disabled.
// ---
// Default: "0", Min: "0", Max: "3"
// 
yb_csdm_mode "0"

//
// If enabled, bots will not apply game modes based on map name prefix (fy_ and ka_ specifically).
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_ignore_map_prefix_game_mode "0"

//
// Maximum number of threads bot will run to process some tasks. -1 means half of CPU cores used.
// ---
// Default: "-1", Min: "-1", Max: "16"
// 
yb_threadpool_workers "-1"

//GRENADIER THROW
// If enabled, bots will not apply throwing condition on grenades.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_grenadier_mode "1"

//
// Specifies whether bot should not 'fix' camp directions of camp waypoints when loading old PWF format.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_graph_fixcamp "0"

//
// Specifies the URL from which bots will be able to download graph in case of missing local one. Set to empty, if no downloads needed.
// ---
// Default: "yapb.jeefo.net"
// 
yb_graph_url "yapb.jeefo.net"

//
// Specifies the URL to which bots will try to upload the graph file to database.
// ---
// Default: "yapb.jeefo.net/upload"
// 
yb_graph_url_upload "yapb.jeefo.net/upload"

//
// Every N graph nodes placed on map, the graph will be saved automatically (without checks).
// ---
// Default: "15", Min: "0", Max: "4096"
// 
yb_graph_auto_save_count "15"

//
// Maximum distance to draw graph nodes from editor viewport.
// ---
// Default: "400", Min: "64", Max: "3072"
// 
yb_graph_draw_distance "400"

//
// Allows bot's to exchange your graph files with graph database automatically.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_graph_auto_collect_db "0"

//
// Kick bots to automatically make room for human players.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_autovacate "1"

//
// How many slots autovacate feature should keep for human players.
// ---
// Default: "1", Min: "1", Max: "8"
// 
yb_autovacate_keep_slots "1"

//
// Kick the bot immediately when a human player joins the server (yb_autovacate must be enabled).
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_kick_after_player_connect "1"

//
// Specifies the number bots to be added to the game.
// ---
// Default: "9", Min: "0", Max: "32"
// 
yb_quota "32"

//
// Specifies the type of quota.
//  Allowed values: 'normal', 'fill', and 'match'.
//  If 'fill', the server will adjust bots to keep N players in the game, where N is yb_quota.
//  If 'match', the server will maintain a 1:N ratio of humans to bots, where N is yb_quota_match.
// ---
// Default: "normal"
// 
yb_quota_mode "fill"

//
// Number of players to match if yb_quota_mode set to 'match'
// ---
// Default: "0", Min: "32", Max: "32"
// 
yb_quota_match "32"

//
// Specifies how many times per second bot code will run.
// ---
// Default: "26.0", Min: "24.0", Max: "90.0"
// 
yb_think_fps "26.0"

//
// Specifies amount of time in seconds when bots will be killed if no humans left alive.
// ---
// Default: "0.0", Min: "0.0", Max: "90.0"
// 
yb_autokill_delay "0.0"

//
// Specifies whether bots should join server, only when at least one human player in game.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_join_after_player "0"

//
// Forces all bots to join team specified here.
// ---
// Default: "any"
// 
yb_join_team "any"

//
// Specifies after how many seconds bots should start to join the game after the changelevel.
// ---
// Default: "5.0", Min: "0.0", Max: "30.0"
// 
yb_join_delay "1.0"

//
// All the bot names will be prefixed with string specified with this cvar.
// ---
// Default: ""
// 
yb_name_prefix ""

//
// All bots difficulty level. Changing at runtime will affect already created bots.
// ---
// Default: "3", Min: "0", Max: "4"
// 
yb_difficulty "3"

//
// Lower bound of random difficulty on bot creation. Only affects newly created bots. -1 means yb_difficulty only used.
// ---
// Default: "-1", Min: "-1", Max: "4"
// 
yb_difficulty_min "2"

//
// Upper bound of random difficulty on bot creation. Only affects newly created bots. -1 means yb_difficulty only used.
// ---
// Default: "-1", Min: "-1", Max: "4"
// 
yb_difficulty_max "3"

//
// Allows each bot to balance their own difficulty based kd-ratio of team.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_difficulty_auto "1"

//
// Interval in which bots will balance their difficulty.
// ---
// Default: "30", Min: "30", Max: "240"
// 
yb_difficulty_auto_balance_interval "50"

//
// Enables or disables displaying bot avatars in front of their names in scoreboard. Note, that is currently you can see only avatars of your steam friends.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_show_avatars "1"

//
// Enables latency display in scoreboard.
//  Allowed values: '0', '1', '2'.
//  If '0', there is nothing displayed.
//  If '1', there is a 'BOT' is displayed.
//  If '2' fake ping is displayed.
// ---
// Default: "2", Min: "0", Max: "2"
// 
yb_show_latency "2"

//
// Allows to save bot names upon changelevel, so bot names will be the same after a map change.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_save_bots_names "0"

//
// Specifies the bots wanted skin for Terrorist team.
// ---
// Default: "0", Min: "0", Max: "5"
// 
yb_botskin_t "0"

//
// Specifies the bots wanted skin for CT team.
// ---
// Default: "0", Min: "0", Max: "5"
// 
yb_botskin_ct "0"

//
// Sets the default personality when creating bots with quota management.
//  Allowed values: 'none', 'normal', 'careful', 'rusher'.
//  If 'none' is specified personality chosen randomly.
// ---
// Default: "none"
// 
yb_preferred_personality "normal"

//
// Lower bound for base bot ping shown in scoreboard upon creation.
// ---
// Default: "7", Min: "0", Max: "100"
// 
yb_ping_base_min "7"

//
// Upper bound for base bot ping shown in scoreboard upon creation.
// ---
// Default: "34", Min: "0", Max: "100"
// 
yb_ping_base_max "34"

//
// Interval in which bots are added to the game.
// ---
// Default: "0.1", Min: "0.1", Max: "1.0"
// 
yb_quota_adding_interval "0.1"

//
// Interval on which overall bot quota are checked.
// ---
// Default: "0.4", Min: "0.4", Max: "2.0"
// 
yb_quota_maintain_interval "0.4"

//
// Specifies the language for bot messages and menus.
// ---
// Default: "en"
// 
yb_language "en"

//
// Randomly disconnect and connect bots, simulating players join/quit.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_rotate_bots "0"

//
// Specifies minimum amount of seconds bot keep connected, if rotation active.
// ---
// Default: "360.0", Min: "120.0", Max: "7200.0"
// 
yb_rotate_stay_min "360.0"

//
// Specifies maximum amount of seconds bot keep connected, if rotation active.
// ---
// Default: "3600.0", Min: "1800.0", Max: "14400.0"
// 
yb_rotate_stay_max "3600.0"

//
// When enabled, bots will not try to avoid teammates on their way. Assuming some of the semiclip plugins are in use.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_has_team_semiclip "0"

//
// Selects the heuristic function mode. For debug purposes only.
// ---
// Default: "0", Min: "0", Max: "4"
// 
yb_path_heuristic_mode "0"

//
// Limit maximum floyd-warshall memory (megabytes). Use Dijkstra if memory exceeds.
// ---
// Default: "6", Min: "0", Max: "32"
// 
yb_path_floyd_memory_limit "6"

//
// Use simple distance path calculation instead of running full Dijkstra path cycle. Used only when Floyd matrices unavailable due to memory limit.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_path_dijkstra_simple_distance "1"

//
// Enables post-smoothing for A*. Reduces zig-zags on paths at cost of some CPU cycles.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_path_astar_post_smooth "0"

//
// Randomize pathfinding on each round start.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_path_randomize_on_round_start "1"

//
// Enables or disables showing welcome message to host entity on game start.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_display_welcome_text "0"

//
// Enables or disables fake server queries response, that shows bots as real players in server browser.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_enable_query_hook "0"

//
// Specifies the maximum health of breakable object, that bot will consider to destroy.
// ---
// Default: "500.0", Min: "1.0", Max: "3000.0"
// 
yb_breakable_health_limit "1.0"

//
// Allows or disallows bots to return fake steam id.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_enable_fake_steamids "0"

//
// Count player pings when calculating average ping for bots. If no, some random ping chosen for bots.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_count_players_for_fakeping "0"

//
// Specifies whether bots able to use 'shift' if they thinks that enemy is near.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_walking_allowed "0"

//
// Allows or disallows bots to camp. Doesn't affects bomb/hostage defending tasks.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_camping_allowed "1"

//
// Lower bound of time from which time for camping is calculated
// ---
// Default: "15.0", Min: "5.0", Max: "90.0"
// 
yb_camping_time_min "10.0"

//
// Upper bound of time until which time for camping is calculated
// ---
// Default: "45.0", Min: "15.0", Max: "120.0"
// 
yb_camping_time_max "15.0"

//
// Allows or disallows the ability for random knife attacks when bot is rushing and no enemy is nearby.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_random_knife_attacks "1"

//
// Maximum number for path length, to predict the enemy.
// ---
// Default: "25", Min: "15", Max: "256"
// 
yb_max_nodes_for_predict "25"

//
// Enables or disables extra hard difficulty for bots.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_whose_your_daddy "0"

**Comment by jeefo** [comment]
Please update to latest build. If problem persists, try settings ``yb_pickup_ammo_and_kits`` to ``0``.

**Comment by ray913d** [comment]
> Please update to latest build. If problem persists, try settings `yb_pickup_ammo_and_kits` to `0`.

still the jumping persist..bot still stucked behind doors

**Comment by jeefo** [comment]
on 4.5.976 ?

what mods do you run ?

**Comment by ray913d** [comment]
> on 4.5.976 ?
> 
> what mods do you run ?

4.4.949

**Comment by jeefo** [comment]
there is no fix in 4.4 tree, you need: https://github.com/yapb/yapb/releases/tag/continuous

**Comment by ray913d** [comment]
> there is no fix in 4.4 tree, you need: https://github.com/yapb/yapb/releases/tag/continuous

Ok. ill let you know if i encounter one in this verson 4.5..thank you for the latest thread

**Comment by ray913d** [comment]
> > there is no fix in 4.4 tree, you need: https://github.com/yapb/yapb/releases/tag/continuous
> 
> Ok. ill let you know if i encounter one in this verson 4.5..thank you for the latest thread

still bots jump and try to pick item....more often observed in CTs

**Comment by jeefo** [comment]
ok then, could you please provide a plugins lists? especially one, than manages items drops. And just in case, on video, the game doesn't seem sto be 1.6, looks like cs 1.5, is it right?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ray913d** [comment]
yes im  playing yapb in cs 1.5...

**Comment by jeefo** [comment]
question about plugin-list is actual

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by di57inct** [comment]
The stuck on door bug is a waypoint issue, the other one i think is a pickup issue.
You should add ignoring non-weapon entity pickup once the bot has walked over it once.

**Comment by ray913d** [comment]
this issue solve when i shifted playing in from cs 1.5 to  cs 1.6...my bad...sory for the trouble. . i hope that in the upcoming yapb updates. yapb has its autonavigation generator for bots. just like preset bot for cs 1.6...thanks
