### ISSUE TITLE
yb_enable_fake_steamids doesn't work

### ISSUE THREAD

**Issue by di57inct** [yapb/yapb#535]
Version: 4.5.989 continuous
> #      name userid uniqueid frag time ping loss adr
> # 1 "_K_O_M_A_D_A_N_T_" 60 BOT   2  1:13:23    0    0
> # 2 "<<.Conec[T]iooN.>>" 61 BOT   1  1:13:23    0    0
> # 3 "RaZvaN" 62 BOT   1  1:13:23    0    0
> # 4 "WonderWoman" 63 BOT   6  1:13:23    0    0
> # 5 "Flamin3 Blaz3" 64 BOT   5  1:13:23    0    0
> # 6 "Player" 47 VALVE_3:0:1958357340   0 25:46   28    0
> # 7 "DenisaG^_^" 65 BOT   5  1:13:23    0    0
> # 8 "DEREGL" 34 VALVE_2:1:810549840   0 31:37   28    0
```
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
ReHLDS version: 3.13.0.788-dev
Build date: 07:36:33 Jul 12 2023 (3378)
Build from: https://github.com/dreamstalker/rehlds/commit/f955b07
Currently loaded plugins:
      description      stat pend  file                      vers          src  load  unload
 [ 1] YaPB             RUN   -    yapb.so                   v4.5.989      ini  Chlvl ANY  
 [ 2] SafeNameAndChat  RUN   -    SafeNameAndChat.so        v1.1          ini  ANY   ANY  
 [ 3] Reunion          RUN   -    reunion_mm_i386.so        v0.1.0.137    ini  Start Never
 [ 4] ReAuthCheck      RUN   -    reauthcheck_mm_i386.so    v0.1.6        ini  Start Never
 [ 5] HitBox Fix       RUN   -    hitbox_fix_mm_i386.so     v1.1.4        ini  Start ANY  
 [ 6] WHBlocker        RUN   -    whblocker_mm_i386.so      v1.5.697      ini  Chlvl ANY  
 [ 7] AMX Mod X        RUN   -    amxmodx_mm_i386.so        v1.10.0.5467  ini  Start ANY  
 [ 8] Engine           RUN   -    engine_amxx_i386.so       v1.10.0.5467  pl7  ANY   ANY  
 [ 9] FakeMeta         RUN   -    fakemeta_amxx_i386.so     v1.10.0.5467  pl7  ANY   ANY  
 [10] CStrike          RUN   -    cstrike_amxx_i386.so      v1.10.0.5467  pl7  ANY   ANY  
 [11] Ham Sandwich     RUN   -    hamsandwich_amxx_i386.so  v1.10.0.5467  pl7  ANY   ANY  
 [12] CSX              RUN   -    csx_amxx_i386.so          v1.10.0.5467  pl7  ANY   ANY  
 [13] GeoIP            RUN   -    geoip_amxx_i386.so        v1.10.0.5467  pl7  ANY   ANY  
 [14] Fun              RUN   -    fun_amxx_i386.so          v1.10.0.5467  pl7  ANY   ANY  
 [15] MySQL            RUN   -    mysql_amxx_i386.so        v1.10.0.5467  pl7  ANY   ANY
```

**Comment by jeefo** [comment]
It's shouldn't it's added solely for a CSstats/gameMe/Hlstats/Pyscohstats etc, to track players via SteamID's, and not via Nick Name.

It's should not modify results of status command. It's not mean't to be used to fake users.

**Comment by di57inct** [comment]
So if i use get_user_authid in amxmodx it will return a unique steamid for every bot?
Can you add so that setting the cvar to a value of 2 for example will print it out via status command too?

**Comment by jeefo** [comment]
Yup, get_user_authid will return fake ID for a bot.

There's nothing to with cvars, i'ts require binary hacking over engine library. It's possible to patch rehlds through.

**Comment by di57inct** [comment]
Ok, ty :)
