### ISSUE TITLE
[Suggestion] Fake pings to client when requested by "ping" command

### ISSUE THREAD

**Issue by di57inct** [yapb/yapb#536]
> ] ping
> Client ping times:
>    0 :olum makinesi
>    0 pR0 bh0peRs^Ana
>    0 Magdalena
>    0 CULCAT
>    0 Flamin3 Blaz3
>    0 _K_O_M_A_D_A_N_T_
>   28 ©S•MASCATII•®0 [1]
>   28 DEREGL

**Comment by jeefo** [comment]
hello, not possible on bot side. it's a SV_CalcPing() function in game engine.
