### ISSUE TITLE
Difficulty climbing ladders sometimes

### ISSUE THREAD

**Issue by di57inct** [yapb/yapb#544]
[yapb3.zip](https://github.com/yapb/yapb/files/14762043/yapb3.zip)

**Comment by Vladislav4KZ** [comment]
Related issue: https://github.com/yapb/yapb/issues/319

**Comment by Vladislav4KZ** [comment]
@di57inct also attach all the necessary map files and the map itself to play the demo.

Or just record a video.

**Comment by di57inct** [comment]
Join server 82.76.20.181:27015 it has all the resources and fast dl. Will be running de_nuke2x2 map for a couple of hours.
Can't record video right now because i'm on a low end laptop.

**Comment by jeefo** [comment]
Try the latest build, i'm unable to see that demos on xash3d engine now... so @Vladislav4KZ right, videos a bit better.

**Comment by di57inct** [comment]
Issue persists with latest continuous build(4.5.1004). ~1/10 climb attempts only is successful.
Unfortunately, I can't provide video until i get home on my pc. For now i can only provide demos from the laptop.
[yapbladder.zip](https://github.com/yapb/yapb/files/14811501/yapbladder.zip)
[yapbladderupsidedowncamera.zip](https://github.com/yapb/yapb/files/14811502/yapbladderupsidedowncamera.zip)

**Comment by jeefo** [comment]
@di57inct someone discord send me videos with that :)

what's the bots difficulty level on this demos ?

**Comment by di57inct** [comment]
"yb_difficulty" is "1"

**Comment by jeefo** [comment]
one more try...

**Comment by di57inct** [comment]
> "yb_version" is "4.5.1007"

Not fixed.
[yapb.zip](https://github.com/yapb/yapb/files/14897815/yapb.zip)

**Comment by jeefo** [comment]
sadly this doesn't happens for me...

**Comment by di57inct** [comment]
Maybe linux issue?
Running HLDS 8684 with ReHLDS 3378(3.13.0.788-dev) on top. No ReGameDLL.

**Comment by jeefo** [comment]
Is this still an issue with latest continuous build ?

**Comment by di57inct** [comment]
will test and let you know.

**Comment by di57inct** [comment]
yup, issue still present. forgot to mention:
> meta version
> Metamod-r v1.3.0.138, API (5:13)
> Metamod-r build: 11:50:32 Nov 28 2023
> Metamod-r from: https://github.com/theAsmodai/metamod-r/commit/5179c25
[yapbladder.zip](https://github.com/yapb/yapb/files/15048790/yapbladder.zip)

**Comment by jeefo** [comment]
It's definitely a graph issue, a fix is placed under the graph repo.

**Comment by di57inct** [comment]
Seems fixed. Thank you. Closing until proven otherwise.
