### ISSUE TITLE
After upgrading to the latest version(4.5.997), killing bots will increase the kill count in csstats

### ISSUE THREAD

**Issue by danteswx** [yapb/yapb#547]
Upgrading from 4.5.970 to 4.5.997 only replaced yapb.so, with no other settings changed. csstats_rankbots 0, 
Killing bots will increase the number of kills for players in csstats, please check!

Another long-standing issue is: If yb_show_latency is set to 2, it will affect player latency and disrupt the game experience. 
If yb_show_latency is set to 0, there is minimal impact, but displaying the ping values of bots requires using a separate plugin. 
Can this be optimized?

thx!

**Comment by di57inct** [comment]
csstats_rankbots 0 will just not rank bots, not the kills you make on them.
As for the fake ping, i highly doubt that it affects player ping. Just disable it and use AMXX ping faker and see if there is any difference.

**Comment by jeefo** [comment]
Try the latest build.

**Comment by danteswx** [comment]
Trying out version 4.5.1000, the issue of bots increasing kill count in csstats has been fixed. 
thx！
