### ISSUE TITLE
Bot chatter, some bugs

### ISSUE THREAD

**Issue by mildly-useful** [yapb/yapb#555]
First of all... I want to say, these bots are amazing. I enjoy playing against them solo greatly! So, this is one reason for why I enabled voice chatter, so they talk like in Condition Zero. There are a few problems I've noticed though (in the continuous release).

The terrorists keep saying "bombsite" after planting and camping near the planted bomb. They usually say it a few times (though I think it's just different bots coming near the bomb). That's it, the terrorists just repeat "bombsite" a few times for no reason if they're near or coming towards the planted bomb. It's a bit annoying.

Second issue is, I heard a CT saying "NEED HELP!" when the entire terrorist team (full of bots) was dead. The CTs were defusing the bomb. No reason to call for help urgently while the Ts are dead, lol. 

Thanks for still working on these bots in 2024, and for having such a huge database of navigation files!

**Comment by mildly-useful** [comment]
Yeah, I think that's likely it, they're just stating that they're camping the bombsite. Problem is, they do it multiple times (and I think the third time they do it with a different pitch, lol). It's amusing, but it doesn't seem like normal behavior.

In my opinion, the bot planting the bomb should not say he's at the bombsite, because naturally he will always stay and camp there after planting. He should say "bombsite" only if he's under fire, so you know the CTs are at the bombsite. After planting, if nothing is going on, he should say nothing. Or he should sometimes say "Where are they?" if no CT is coming and the bomb timer is ticking fast.

The other chatter bugs are amusing, indeed, but it would be nice if they can be fixed sometime, because bot chatter is actually an awesome and very useful feature! I'm glad there's someone else who cares besides me, so no worries about barging in. Thanks for also describing your experience. Awesome to see other people playing solo against the bots!

**Comment by Vladislav4KZ** [comment]
> Second issue is, I heard a CT saying "NEED HELP!" when the entire terrorist team (full of bots) was dead. The CTs were defusing the bomb. No reason to call for help urgently while the Ts are dead, lol.

Fixed. See the Pull Request https://github.com/yapb/yapb/pull/560
The ``chatter.cfg`` included inappropriate phrases for the ``Radio_NeedBackup`` chatter event.

I will merge these commits into a master branch soon, after I finalize and test them.

**Comment by mildly-useful** [comment]
Thank you very much! I will try the newest version soon.

**Comment by jeefo** [comment]
closed as inactive
