### ISSUE TITLE
Бот сообщает о том, что он спасает заложников, когда находится на узле с флагом RESCUE и при этом не ведя за собой заложников.

### ISSUE THREAD

**Issue by Vladislav4KZ** [yapb/yapb#557]
При использовании радиокоманды "Report in, team." когда бот находится на узле с флагом RESCUE, он использует фразу из Chatter_RescuingHostages, т.е. говороит о том, что он спасает заложников даже когда он не ведёт их за собой.

Для проверки можно указать номер узла в кваре ``yb_debug_goal`` который имеет флаг RESCUE, и использовать радиокоманду "Report in, team." ("Доложите обстановку")

В этом участке кода [(взятого с botlib.cpp)](https://github.com/yapb/yapb/blob/3358168fad29a35fc06ec412b2c153c812f04bdd/src/botlib.cpp#L2632-L2634)
```
else if (path.flags & NodeFlag::Rescue) {
   pushChatterMessage (Chatter::RescuingHostages);
}
```

Я пытался заменить условие на:
```
else if (game.mapIs (MapFlags::HostageRescue) && m_team == Team::CT && m_hasHostage) {
   pushChatterMessage (Chatter::RescuingHostages);
}
```

Но при использовании радиокоманды "Report in, team." когда бот контр-террорист ведёт за собой заложников, он молчит.

**Comment by jeefo** [comment]
Я оставил просто условие m_hasHostage без проверки карты и команды, у меня вроде репортят нормально.

**Comment by Vladislav4KZ** [comment]
> Я оставил просто условие m_hasHostage без проверки карты и команды, у меня вроде репортят нормально.

Я изначально сделал так же, но боты не репортили.

Возможно ты спутал это с фразами из Chatter_UseHostage.
Боты когда берут заложников, повторяют эти фразы несколько раз.

**Comment by Vladislav4KZ** [comment]
Нашел причину, см. отрывок по ссылке: https://github.com/yapb/yapb/blob/master/src/botlib.cpp#L2321-L2324


Здесь, в нижеперечисленных условиях для игнорирования радиокоманд есть m_hasHostage.
```
if (getCurrentTaskId () == Task::DefuseBomb || getCurrentTaskId () == Task::PlantBomb || m_hasHostage || m_hasC4) {
      m_radioOrder = 0;
      return;
   }
```

Из-за этого бот не сообщал о том, что спасает заложников.

Также там есть условие m_hasC4 из-за которого также не будет работать данный репорт:
https://github.com/yapb/yapb/blob/master/src/botlib.cpp#L2625-L2627
```
if (game.mapIs (MapFlags::Demolition) && m_team == Team::Terrorist && m_hasC4) {
                  pushChatterMessage (Chatter::GoingToPlantBomb);
               }
```

**Comment by Vladislav4KZ** [comment]
Исправил в этом коммите: https://github.com/yapb/yapb/commit/ffb92ca962b0e628e76b695980bbb81aad95dd58
Боты теперь не должны игнорировать радиокоманду "Report in, team".
Они теперь должны сообщать о том, что они ведут за собой заложников.
