### ISSUE TITLE
Block the flashlight on zombie bots

### ISSUE THREAD

**Issue by stambeto2006** [yapb/yapb#563]
It's about zombie plague 4.3, I put various checks so that bots, when they become zombies, can't spam the flashlight constantly and be banned, as it's done, with real players, so that when they become zombies, they can't turn on the flashlight.
I tried various checks to put in the main plugin of the mod, but they did not fix the effect with the bots.
I saw that there was an option for the flashlight in the bots module to turn it on or off but the effect was the same the bots kept spamming the flashlight when they became zombies.

Is there an option to make it so that when the bots are human they only release the flashlight, and when they become zombies they can't use it?

**Comment by jeefo** [comment]
Hi! There's no special code (well, almost) within the bot to support of ZP. So Would it be any useful or logical to prevent creatures (in bot terminology) to use flashlight at all ? I have added commit for that, you can try out.

**Comment by stambeto2006** [comment]
Well they manage to use the flashlight again when the bots become zombies, they take turns if now one zombie is released until it turns off and is released by another zombie.

I can't understand how with humans it only allows them when they are human to use it and when they become zombies they can't. And with the bots, putting it in the main mod doesn't help?

**Comment by jeefo** [comment]
How the mod prevents usage of flashlight for humans?

**Comment by commandcobra7** [comment]
@jeefo I know where the problem originates from. I think it is due to the creature model. Especially in the zp 4.3 version, there is only one creature model. this file was in the directory ''model/player/''. I don't know how many creature models there are. But I think it is definitely due to the creature model.

**Comment by jeefo** [comment]
what's the models used by zombies? .mdl names

**Comment by di57inct** [comment]
an amxx script done properly should block it for bots too. this is not worth implementing imo.

**Comment by commandcobra7** [comment]
> Is there any solution to this problem or to be done?

For example, I have zp version 5.0.8. I've written down all the zombie models he used below.

blackhand.mdl, CactusMan.mdl, DeimosNewX.mdl, DevilX.mdl, eqs.mdl, fat_zombie.mdl, FlyBurnDemonX.mdl, HeadCrabX.mdl
Husk.mdl, krippinX.mdl, Nemesis2X.mdl, reaper.mdl, SurvivorX.mdl, ubct1.mdl, zombie.mdl, zombie_eye.mdl
zombie_smoker.mdl, zombie_source.mdl

**Comment by commandcobra7** [comment]
> Is there any solution to this problem or to be done?

For example, I have zp version 5.0.8. I've written down all the zombie models he used below.

blackhand.mdl, CactusMan.mdl, DeimosNewX.mdl, DevilX.mdl, eqs.mdl, fat_zombie.mdl, FlyBurnDemonX.mdl, HeadCrabX.mdl
Husk.mdl, krippinX.mdl, Nemesis2X.mdl, reaper.mdl, SurvivorX.mdl, ubct1.mdl, zombie.mdl, zombie_eye.mdl
zombie_smoker.mdl, zombie_source.mdl

For example, this creature can be "customconfig" for models to define.

**Comment by stambeto2006** [comment]
Changing the zombie models is done from the zp_zombieclasses.inl file on zombie plague 4.3
It's just that these models that are made are used by real players and bots, but when the real players become zombies no matter how much they spam the button, the flashlight doesn't work, while the bots allow them to use them almost all the time. If one bot turns on the flashlight and immediately turns it off, the next one turns it on, and so on.

**Comment by commandcobra7** [comment]
> Changing the zombie models is done from the zp_zombieclasses.inl file on zombie plague 4.3 It's just that these models that are made are used by real players and bots, but when the real players become zombies no matter how much they spam the button, the flashlight doesn't work, while the bots allow them to use them almost all the time. If one bot turns on the flashlight and immediately turns it off, the next one turns it on, and so on.

What are the names of the zombie models? Just tell me the .mdl extensions

**Comment by stambeto2006** [comment]
> > Changing the zombie models is done from the zp_zombieclasses.inl file on zombie plague 4.3 It's just that these models that are made are used by real players and bots, but when the real players become zombies no matter how much they spam the button, the flashlight doesn't work, while the bots allow them to use them almost all the time. If one bot turns on the flashlight and immediately turns it off, the next one turns it on, and so on.
> 
> What are the names of the zombie models? Just tell me the .mdl extensions

escom_assassin.mdl , escom_assassin3.mdl , escom_fast.mdl , escom_fat.mdl , escom_headcrab.mdl , escom_hunter.mdl , escom_jump.mdl , escom_neme.mdl , escom_rage.mdl , escom_sucker.mdl , escom_swarm.mdl

**Comment by jeefo** [comment]
[dedbf8a](https://github.com/yapb/yapb/commit/dedbf8ab824817f27cb8e6f0f1bebb9a9c7a7de3) commit should mark bot as infected zombie even with custom models (doesn't have to be zombie.mdl). So, they will not try to control flashlight/nvg themself.

However i haven't tested this. Any feedback would be useful.

**Comment by stambeto2006** [comment]
> [dedbf8a](https://github.com/yapb/yapb/commit/dedbf8ab824817f27cb8e6f0f1bebb9a9c7a7de3) commit should mark bot as infected zombie even with custom models (doesn't have to be zombie.mdl). So, they will not try to control flashlight/nvg themself.
> 
> However i haven't tested this. Any feedback would be useful.

I tested it and so far it looks good, I don't see them using the flashlight on zombies anymore! If I see any problem I will write.
