### ISSUE TITLE
Bots that can hear the enemy but cannot predict the enemy

### ISSUE THREAD

**Issue by commandcobra7** [yapb/yapb#564]
Hello @jeefo, I encountered such a problem with bots. When bots hear the enemy, they guess the enemy as the target. When they approach the enemy from a distance, they stop guessing the enemy. Even if they hear the enemy, they ignore the enemy when they approach. I don't know where the problem comes from. I don't know if it's because they're receiving asynchronous reception or because of the distance.

**Comment by jeefo** [comment]
on what circumstances bot should not forget his enemy ? i still didn't figure out best solution for this...

**Comment by commandcobra7** [comment]
I will look into the problem later
