### ISSUE TITLE
c4 defuse animation for yapb

### ISSUE THREAD

**Issue by ray913d** [yapb/yapb#565]
can anybody please make a amx modx script for this cool c4 defuse animation for all counter strike 1.6 fans. it'd be way cooler to play yapb with this animation.
LINK:https://forums.alliedmods.net/showpost.php?p=2571503&postcount=25

WATCH: https://www.youtube.com/watch?v=vVUAq8Htp2A

**Comment by di57inct** [comment]
what does this have to do with the bots?

**Comment by Vladislav4KZ** [comment]
We are not AMXX scripters, and this has nothing to do with any bots at all.

Closing as this is out of scope.
