### ISSUE TITLE
При вводе команды yb kill_ct, yb kill ct или yb kill 2, умирают террористы а не КТшники

### ISSUE THREAD

**Issue by Vladislav4KZ** [yapb/yapb#566]
Проверял как на билде с master ветки, так и со своей chatter-fixes-and-improvements.

**Comment by Vladislav4KZ** [comment]
С командами yb kick_ct, yb kick ct и yb kick 2 такой проблемы нет. Кикается 1 контр-террорист.

**Comment by jeefo** [comment]
Should be ok.

**Comment by Vladislav4KZ** [comment]
> Should be ok.

Да, теперь всё норм. КТшники теперь убиваются с помощью вышеуказанных команд.
