### ISSUE TITLE
Failure of enemy predictions in some circumstances

### ISSUE THREAD

**Issue by commandcobra7** [yapb/yapb#567]
Hi @jeefo, a fix has been made to ensure that enemies' guesses about bots fail in some cases. I think it would be better for these conditions to go back to normal in order to fix this problem.

      auto isPredictedIndexApplicable = [&] () -> bool {
         if (!vistab.visible (m_currentNodeIndex, predictNode) || !vistab.visible (m_previousNodes[0], predictNode)) {
            predictNode = kInvalidNodeIndex;
            pathLength = kInfiniteDistanceLong;
         }
         return graph.exists (predictNode) && pathLength < cv_max_nodes_for_predict.as <int> ();
      };

**Comment by jeefo** [comment]
Hello, it was against looking-at-the-wall-continuously bug. It's probably should be reworked with some sort of a timer rather than explicitly failing predicted node in that case.

**Comment by commandcobra7** [comment]
> Hello, it was against looking-at-the-wall-continuously bug. It's probably should be reworked with some sort of a timer rather than explicitly failing predicted node in that case.

yes @jeefo timers are broken. They should do this the first time they hear about it.
