### ISSUE TITLE
Ошибка в коде?

### ISSUE THREAD

**Issue by Vladislav4KZ** [yapb/yapb#571]
Я уже писал комментарий в одном из коммитов, но ответа там так и не увидел.

Здесь видимо ошибка, зачем от 0.5 отнимать 7.5?
https://github.com/yapb/yapb/blob/dce340f6bde3824f42dce227ec81e56efc00f501/src/combat.cpp#L646
```
{ 0.5f - 7.5f,  -9.5f }, // zoomrifle
```

Возможно должно быть так:
```
{ 0.5f, -7.5f,  -9.5f }, // zoomrifle
```

**Comment by jeefo** [comment]
привет, да это ошибка)
