### ISSUE TITLE
[Feature request] Прицеливание ботов на модели с кастомным model index

### ISSUE THREAD

**Issue by nikolaygaus** [yapb/yapb#579]
**Это просто полезная фича для Zombie Mode.**

Некоторые зомби классы могут иметь измененное положение хитбоксов (например: хедкраб, половина туловища зомби, деймосы, ревенанты), для этого используется кастомный model index на игрока. Боты же в свою очередь целятся по статичным координатам игрока со смещениями для головы и присевших. Как на счёт добавления допустим опционального квара (для сохранения стандартного метода), который будет исправлять этот нюанс.
Как я знаю, в rehlds/reapi имеется GetBonePosition который должен возвращать положение кости той же головы, возможно с этим можно что-то придумать. При надобности могу прикрепить модели зомби классов для примера.

**Comment by jeefo** [comment]
Привет. Можно попробовать, но есть вероятность, что это плохо отразится на FPS.

**Comment by di57inct** [comment]
if you're using zombie plague mod, have you tried setting model index offset to 1?

> ; If you want your models to have accurate hitboxes, try enabling this.
> ; Note: make sure your models don't have messed up hitboxes, otherwise
> ; this setting might cause your server insane cpu usage and lag!
> SET MODELINDEX OFFSET = 0
>

**Comment by nikolaygaus** [comment]
> Привет. Можно попробовать, но есть вероятность, что это плохо отразится на FPS.

На данный момент я тестирую две идеи которые мне пришли в голову:
1. Вместо магических/константных чисел со смещением голова/сидя, начал учитывать target->mins/maxs. Нюанс в том что нужно допустим тем же плагином устанавливать новый размер для каждого подобного зомби класса.
2. Кэширование значений со смещением для каждой из моделей зомби (голова, туловище, голова сидя, туловище сидя). Больше 4-х смещений по сути для ботов и не нужно. Почему 4-е смещения, вместо 3-х (голова, туловище, сидя) - в зомби модах часто встречаются модели зомби у которых позиция головы в анимациях сидя может находится в другой точке.

Но эти идеи так же имеют и свои минусы:
- Для каждого класса/модели нужно указывать настройки индивидуально самому (хотя, если как-либо закэшировать положение хитбоксов, это можно автоматизировать).
- В кадрах анимаций, допустим голова, может менять свою позицию (конечно же получение позиции именно хитбокса в реал-тайме было бы лучше, но я понимаю что это дорого).

Но всё же, если закрыть глаза на минусы и заставить ботов просто наводиться на врага - это работает 😄

**Comment by nikolaygaus** [comment]
> if you're using zombie plague mod, have you tried setting model index offset to 1?

Именно с этим и появляется проблема.

**Comment by jeefo** [comment]
Добавил в последнем коммите, нужно включить ``yb_use_hitbox_enemy_targeting``.

Не совсем уверен к корректности реализации. Но у меня, на вид, работает.
