### ISSUE TITLE
Bots can't walk up slopes, even small ones have to jump on them.

### ISSUE THREAD

**Issue by han2015** [yapb/yapb#580]
As the title says, the bot always jumps forward on the slope, even if the slope is relatively flat. (e.g. dust2 CT‘ s spawn run on slope to A door)
I think it should have some settings for bot jumping in conf, but I don't find some matching.

**Comment by jeefo** [comment]
I believe you have autogenerated graph ? Probably yes, we should add some slope limit cvar for that situation. For the hand-made graphs i haven't seen such behavior.

**Comment by MysticDeathProject** [comment]
Hi @jeefo in the all old version yapb and sypb if convert pwf to .graph and if create waypoints with old version sypb, yapb, podbot then "jump learned waypoints desired velocity" is removed after convertion in graph and bots yapb can't good jumping and crouch or make a long jump with crouch, check my latest waypoints 
[https://github.com/yapb/graph/commit/b0d70960211bf924dd4ff3572238b721a3721e8e](url)

**Comment by han2015** [comment]
> I believe you have autogenerated graph ? Probably yes, we should add some slope limit cvar for that situation. For the hand-made graphs i haven't seen such behavior.

Right! I autogenerated graphs for all new maps, so they all have the problem. 
Thanks, I will check the slope limit.

**Comment by jeefo** [comment]
> > I believe you have autogenerated graph ? Probably yes, we should add some slope limit cvar for that situation. For the hand-made graphs i haven't seen such behavior.
> 
> Right! I autogenerated graphs for all new maps, so they all have the problem. Thanks, I will check the slope limit.

There's no such cvar exists by now. I will add one in near future.

**Comment by jeefo** [comment]
yb_graph_slope_height should do the thing

**Comment by han2015** [comment]
> yb_graph_slope_height should do the thing

Nice! very very nice! Works great, thanks @jeefo !!
