### ISSUE TITLE
Боты перестают стрелять из снайперок когда враг находится слишком близко

### ISSUE THREAD

**Issue by nikolaygaus** [yapb/yapb#582]
Боты перестают стрелять из снайперок когда враг находится слишком близко. Из наблюдений, заметил баг появляется когда у бота заканчивается обойма в пистолете и он переключается обратно на снайперку. Баг имеется как в версии 4.4 так и в 4.5 (стандартный конфиг с архива).

```
[0 ]    e b l o 0 f f           rusher          CT      4       5       yes     unlimited
```

[Демонстрация была записана на версии 4.4](https://youtu.be/MdIbT3BpzEY)

**Comment by jeefo** [comment]
Можешь проверить пжл, если difficulty < 2 также?

**Comment by nikolaygaus** [comment]
> Можешь проверить пжл, если difficulty < 2 также?

Проверил на difficulty 1, бага нет

**Comment by nikolaygaus** [comment]
Затестил, баг исправлен, проверил на difficulty 1 и 4. Всем спасибо)
