### ISSUE TITLE
Progressive skill levels

### ISSUE THREAD

**Issue by di57inct** [yapb/yapb#585]
My players were always complaining that the bots are either too dumb or too pro when going from a skill level to another, so i rebuilt the skill.cfg file using progressive values.
Hope you find it well done and consider using it, @jeefo :

> Noob = 		1.5, 		2.0, 		15, 		0, 		0, 		40, 		20.0, 	20.0, 	40.0
> Easy = 		1.0, 		1.5, 		20, 		0, 		0, 		35, 		15.0, 	15.0, 	30.0
> Normal = 	0.5, 		1.0, 		25, 		0, 		25, 		30, 		10.0, 	10.0, 	20.0
> Hard = 		0.25, 	0.5, 		50, 		50, 		50, 		25, 		5.0, 		5.0, 		10.0
> Expert = 		0.1, 		0.25, 	75, 		75, 		75, 		20, 		0.0, 		0.0, 		0.0

**Comment by jeefo** [comment]
Applied config changes.
