### ISSUE TITLE
steam id of bots 

### ISSUE THREAD

**Issue by Etrail** [yapb/yapb#586]
steam id of bots when the status command is typed

is it possible to do it?
![Screenshot 2024-06-08 230925](https://github.com/yapb/yapb/assets/33066485/46f9c15d-90f3-4d6f-bd60-1c466f177381)

**Comment by ViBE-HU** [comment]
totally pointless.

**Comment by Etrail** [comment]
It's not meaningless.. A user who has a server puts it in and is ranked on gt.rs and gt.com

It should also be added that the number of players on the server is automatically changed to make it as difficult as possible to break in, that it is fake

**Comment by ViBE-HU** [comment]
@Etrail you want to "fix" two issues with a feature which is not really ypb related. not a good idea and not even fair with maintained and populated servers.

**Comment by jeefo** [comment]
Hello, this stuff isn't possible ob bot side. Requires memory hacking and so on.

Sorry, I can't maintain such things.
