### ISSUE TITLE
there is bug

### ISSUE THREAD

**Issue by all85100** [yapb/yapb#588]
v4.5.1087
yapb.cfg
yb_show_latency "2" has no effect

**Comment by jeefo** [comment]
https://github.com/yapb/yapb/blob/b0da38b2ab1f01ce4881e0773f47d701ed7e96f2/cfg/addons/yapb/conf/custom.cfg#L54

**Comment by all85100** [comment]
This ?  tested no effect
EnableFakeBotFeatures = yes

**Comment by di57inct** [comment]
> This ? tested no effect EnableFakeBotFeatures = yes

did u even brother to read?

> ;
> ; This decides if fake features (like a fake time, fake SID (avatar), fakeping)
> ; should be enabled whitin bot code. By default it's off. To enable it you're 
> ; should provide variable with: "i'm confident for what i'm doing" value.
> ;
> EnableFakeBotFeatures = no

**Comment by all85100** [comment]
The default setting is NO, it has no effect, I changed it to yes and it has no effect,
It was normal before, but there was no fake ping after changing some code last time

**Comment by all85100** [comment]
thinks,It's normal.,But,It's strange.,Why is the value given a sentence?,I didn't understand it before.
