### ISSUE TITLE
Upgrade yapb for zombie mod

### ISSUE THREAD

**Issue by Krtola84** [yapb/yapb#592]
I use yapb on Cs 1.6 Biohazard mod and have few problems.Zombies attack humans only when they are on clear area/ground.For example if I climb leader and stay on the top,zombie bots don't attack me.They just walk around and watch me but never attack.Also if I climb on any object bots don't attack.Waypoint is fine.Also bots have problem with leather climbing.
Waypoints are just fine.

**Comment by MysticDeathProject** [comment]
Hi some wapoints after conversion do not work well after converting from ebot to yapb or from sypb to yapb try installing this version of yapb
[Latest version](https://github.com/yapb/yapb/releases/tag/continuous)

**Comment by Krtola84** [comment]
Hello.
Already try that version and the same problem is present.
I thing we need to force zombie bots to attack humans without thinking,just rush forward and attack with knife.

**Comment by Krtola84** [comment]
I manage to make wp for stairs.But zombies never climb on ladder.

**Comment by MysticDeathProject** [comment]
@Krtola84 Hi check wapoints for errors and if you have a local server I recommend also using sypb bots they are similar to yapb and based on the 2.7.2 yapb source code

**Comment by MysticDeathProject** [comment]
@Krtola84 If you want, you can send me a wp with a bot ladder problem where bots are not climbing

**Comment by Krtola84** [comment]
I use it for my online Linux server,so I can't use sypb.
How to delete all waypoint at once,for example for map de_dust2?

**Comment by Krtola84** [comment]
It happened on every map with ladder.

**Comment by MysticDeathProject** [comment]
@Krtola84 hi you need disable autodownload graph
Leave the yb_graph_url value empty to disable graph file autoloading, and to disable graph autogeneration, change the value of the yb_graph_analyze_auto_start quar to 0 in yapb.cfg

You can enter these quars in the game or server console, then enter the yb cvars save command to save the changes in yapb.cfg. 

This is can help you and after you can delete waypoints

Special thanks to @Vladislav4KZ for helping to disable graph autodownload and disable graph autocreate

**Comment by MysticDeathProject** [comment]
Try to find out the values of the last waypoints id number at the place where the bots don't climb the ladder
Here is an example
map zm_forested waypoint ID 409 bots do not climb the ladder yb_debug_goal 409
Don't forget to writte yb_debug 1 to see whats happened if a one bots try to come 409 wp id

**Comment by Krtola84** [comment]
Thank you.I will try that.Will be back here after testing.

**Comment by Krtola84** [comment]
I fail to debug just don't understand how.
Is it possible to force CT or ts players to go at the specofic place,for example bridge on ce_assault map,and to stay ther

**Comment by MysticDeathProject** [comment]
@Krtola84 Hi yes you can, for this you need to enter first yb_debug_goal ID Waypoint what bots need to go.
After that, you need to enter yb_debug 1 for activate yb_debug_goal with ID number, if bots still not going to ID waypoints try to disable yb_debug 0 and writte yb_debug 1 and after writte yb_debug_goal with ID number then bots will to go on ID number waypoints

**Comment by Krtola84** [comment]
How to know wp I'd number?

**Comment by MysticDeathProject** [comment]
@Krtola84 hi you see
![image](https://github.com/user-attachments/assets/f4532360-821f-4bba-934d-bb528de069e7)
Node 223 if you stay at the waypoint(node) you will see ID number if you writte yb_debug 1 and writte yb_debug_goal 223 then all bots will to going on waypoint 223

**Comment by Krtola84** [comment]
Thank you. That didn't work for me.

**Comment by MysticDeathProject** [comment]
@Krtola84 you mean not work debug and debug_goal is not working for you?

**Comment by Krtola84** [comment]
I did everything you say but bots didn't go where I want them to go

**Comment by MysticDeathProject** [comment]
@Krtola84 Hi try to add a one bot and writte yb_debug 1 after writte yb_debug_goal with ID number waypoint when bot needs to go and if bot lost connection or can't to go on waypoint with number try to writte yb_debug_goal -1 to disable and after that try to found other waypoints around maybe this is can help you.

**Comment by MysticDeathProject** [comment]
I tested the latest version of yapb bots with 30 think fps bots walk normally and attack and climb the ladder on small maps, I think if you created the waypoints with the support and help of auto-generation of waypoints, the waypoint ladder is located incorrectly on the ladder itself, maybe the waypoint is located outside and bots can not climb the ladder.

**Comment by MysticDeathProject** [comment]
@Krtola84 whats the map have a problem with bots and you create waypoints byself I mean manualy without autocreate waypoints?

**Comment by Krtola84** [comment]
Ok I will try that.I use assault for testing,but that happens on every map.But,this happens on zombie mod im not sure for other mods.

**Comment by Krtola84** [comment]
Biohazard mod

**Comment by Krtola84** [comment]
I'm sure the problem is because zombie bots have only knife.And because humans has more powerful weapons than the zombies,zombies bots play defensive and try to avoid enemy.

**Comment by Krtola84** [comment]
I managed to do this but on windows version yapb.On specific node will go only players near that node.Is there a way to force all players to go whatever there distance are?

**Comment by MysticDeathProject** [comment]
@Krtola84 can you test yapb on zombie plague and tell me please bots using ladder? And I also read source code on yapb there have creatures(zombies) and zombie will hunting on humans only if health more 100

**Comment by Krtola84** [comment]
More HP didn't change anything.Just tested.Zombie bots attack only when humans are on the ground and close each other.

**Comment by Krtola84** [comment]
Does in that source code say what bots to do if he have only knife ?

**Comment by MysticDeathProject** [comment]
@Krtola84 Hi I think it's not problem if zombie bots have knifes and also I test the map I try research the problem can you use my waypoints map [zm_tehina.graph](https://github.com/yapb/graph/commit/d38bde7432a730ea7af52934a1b83cbec7c04788) can you test the biggest map there haven't ladder but if you will be on the roof on the church then zombie bots will be not hunting humans if they have big distance, Or can you also add me in discord Mysticpawn#2073 I will try to help you to found mistakes I think the bots if they are zombie and they do not try to climb on any biggest object, I'm sorry I haven't zombie mod biohazard for test it.

**Comment by MysticDeathProject** [comment]
@Krtola84 I tested zm_dust2_final map with zombie plague and humans and zombies are works good zombie hunting to human and humans attack zombies and also yapb bots climb on ladder but I think this is map zm_dust2_final are just ground map without the biggest objects I mean roofs or houses

**Comment by MysticDeathProject** [comment]
@Krtola84 don't forget to download this waypoints [cs_sigma_assault](https://github.com/yapb/graph/commit/77e759a9710561c47322bfb7b2a36c6b3f43aa7c) because older waypoint have bugs and when bots try to climb to ladder there after when bots climb there none connections of any waypoints, bots just stay on the ladder and also I added some jumps and bots can climb to any hidden spot for zombie biohazard. Don't forget to writte me on discord and special thanks for uploading update waypoint by @Vladislav4KZ

**Comment by Krtola84** [comment]
New wp you give me is fine. But now I have new problem.I noticed that bots don't attack when they are on ladder.
https://youtube.com/shorts/dSwZZP76XxQ?si=Cr0HFSKJE27gP3n8

**Comment by MysticDeathProject** [comment]
@Krtola84 maybe this can help you try use this commands yb_stab_close_enemies "1" and yb_has_team_semiclip "1" and yb_random_knife_attacks "1" add on yapb.cfg

**Comment by Krtola84** [comment]
Cvars Is already set like you suggest

**Comment by Krtola84** [comment]
Maybe this is the problem 
// Enables or disables bot ability to stab the enemy with knife if bot is in good condition.
// ---
// Default: "1", Min: "0", Max: "1"
// 
yb_stab_close_enemies "1"
