### ISSUE TITLE
Не работает yb_think_fps_disable

### ISSUE THREAD

**Issue by Vladislav4KZ** [yapb/yapb#593]
В ``yapb.cfg`` уже прописано ``yb_think_fps_disable 1``, но при наблюдении за ботами, видны "подлагивания" движения.

**Детали окружения:**
 - ОС: Windows 10 Pro x64 22H2
 - Движок: Xash3D FWGS v49/0.20 (win32-i386 build 3389) коммит: https://github.com/FWGS/xash3d-fwgs/commit/56ba2325c1035fdb6745ac1a9808ab75b3239aa8 ветка: master
 - GameDLL: ReGameDLL (5.25.0.638-dev)
 - Metamod: нет
 - Версия бота: 4.5.1101 (Continuous build)
 - Режим игры: Обычный

CS16Client:
- Номер сборки: 3118 (CS16Client development build с GitHub)
- Коммит: https://github.com/Velaron/cs16-client/commit/8879e7784a6e6ffcbee670c8acccf6080342614f

**Comment by MysticDeathProject** [comment]
Привет у меня та же проблема yapb последней версии которая в релизе при thinkfps 90 игра крашиться при ботах 20 и спустя 1 час игра вылетает сборка стимовская 2013 года

**Comment by Vladislav4KZ** [comment]
> Привет у меня та же проблема yapb последней версии которая в релизе при thinkfps 90 игра крашиться при ботах 20 и спустя 1 час игра вылетает сборка стимовская 2013 года

Нет, это уже другая проблема.

Я писал про лагающее движение ботов а режиме наблюдателя на движке Xash3D FWGS.

jeefo добавил квар ``yb_think_fps_disable``. При включении этого квара, лаги пропадали.

Но сейчас, что с включенным что с выключенным кваром, в режиме наблюдателя боты двигаются с микролагами.

На оригинальном кс 1.6 (на движке GoldSource) такой проблемы нет.

**Comment by jeefo** [comment]
> i just tested linux gcc with latest https://github.com/yapb/yapb/actions/runs/9881242275 and the bots lag in movement, not sure its related

environment ?

**Comment by jeefo** [comment]
> Привет у меня та же проблема yapb последней версии которая в релизе при thinkfps 90 игра крашиться при ботах 20 и спустя 1 час игра вылетает сборка стимовская 2013 года

краш не нормально, лучше отдельную исусю

**Comment by jeefo** [comment]
@Vladislav4KZ должно быть пофикшено.

**Comment by Vladislav4KZ** [comment]
@jeefo да, проверил, теперь исправлено.
