### ISSUE TITLE
гайд по компиляции 

### ISSUE THREAD

**Issue by deniska21233** [yapb/yapb#597]
Сделай плз гайд по компиляции на centos 
и если можно гайд по компиляции того же rehlds а то не получается не знаю что за ошибка direct GOT relocation R_386_GOT32X against

**Comment by jeefo** [comment]
https://yapb.readthedocs.io/en/latest/building.html ?

**Comment by deniska21233** [comment]
Starting up bot thread worker with 0 threads.
Bots chatter communication disabled.
Loaded Bots Graph data v2 (Memory: 0.29MB).
Loaded Bots Practice data v2 (Memory: 0.31MB).
Loaded Bots Vistable data v4 (Memory: 1.76MB).
Warning: Graph data is probably not for this map. Please check bots behaviour.
L 07/24/2024 - 23:29:55: Started map "cs_office" (CRC "-172878550")
Executing AMX Mod X Configuration File
