### ISSUE TITLE
Zombie don't attack + bots try to reach wp trough walls

### ISSUE THREAD

**Issue by Krtola84** [yapb/yapb#598]
From video you can see that the bots just walk around.Wp for ladder is ok,human bots climb,but when zombies need to attack,if humsns are on hight ground,this happened.
https://youtube.com/shorts/yW3tyKlIZvM?si=wXBkD3BrAddOaFHy

**Comment by Krtola84** [comment]
When enemy meet each other on ladder,attack never happened.Also big issue is that the bots always try to reach waypoint through the walls.
https://youtube.com/shorts/dSwZZP76XxQ?si=5hv104P_bIEKfnsb

**Comment by MysticDeathProject** [comment]
@Krtola84 you tried to add more health zombies? I think zombies afraid hunting to attack humans and zombie plagues work fine zombies climb on ladder

**Comment by Krtola84** [comment]
More health change nothing.

**Comment by jeefo** [comment]
Pls. use single issue.
