### ISSUE TITLE
Bots freeze and jitter when `yb_graph_auto_collect_db` is set to 1 and without Internet connection

### ISSUE THREAD

**Issue by lizhuohua** [yapb/yapb#600]
### Environment
Linux, vanilla CS 1.6 build 8684, yapb-4.5.1102

### Behavior
When connected to a network but **without** Internet access, and `yb_graph_auto_collect_db` is set to 1, the bots freeze and jitter when starting a game for the first time, as shown in the video:

https://github.com/user-attachments/assets/5efbe181-6817-4d44-b799-797ff04dc62c

This freeze lasts for about 2 minutes, after which everything functions normally. It appears that yapb is attempting to download or upload data, but without Internet access, it hangs until a timeout occurs.

Additionally, if I try to close the game or disconnect from the server during the freeze, the game program hangs until the timeout completes.

### Workaround
The issue does not occur when disconnected from any network, or when there is Internet access, or when `yb_graph_auto_collect_db` is set to 0.

### Bugs
If I understand correctly, `yb_graph_auto_collect_db` operates in a separate thread, so even though there is no Internet access, it shouldn't impact the bots. This behavior suggests there might be a bug. Furthermore, when closing the game, the thread should be terminated immediately instead of waiting for the timeout.

**Comment by jeefo** [comment]
Thank you for the report in first place, Don't know when i was checking bots behavior without internet last time.

The problem isn't within bots threading stuff actually.

Bots uses the blocking sockets, so when graph collection is started, process goes into the thread pool which is by default (i believe, in your config) has only one spare thread. When bot's  joins the server, their pathfinding is done in same thread pool which has only one thread which is blocked by sockets ``connect`` call in the pool thread. So we're see that bot jitter/lags until ``connect`` finished. 

The problem with game quit is the same, bots shutdown thread pool by joining pool threads, but ``connect`` isn't finished yet, so game have to wait, terminating threads immediately can cause crash when thread pool hasn't finished his jobs. The same function is used between level changes and game shutdown.

The same problem applies to graph download feature. A long freeze during game startup,. Graph downloading isn't threaded, so this workaround applies to this feature too.

So, the workaround,: On very first game load, we're connect to ``yapb.jeefo.net`` host in a separate thread (not from thread pool), if  it's succeeds bots are able to use graph-http-stuff in future, if not... they can't. Not perfect solution, but a quick-n-dirty fix for a problem. Yes, there can be race-condition  so successful connect to host came later than bots needs to download graph, but i believe it's rate situation.

**Comment by lizhuohua** [comment]
Thank you for your quick response!

I tested the latest build ([c7d02f3](https://github.com/yapb/yapb/commit/c7d02f3f1d240b0949360d8ca472652fabfbf8e2)) and I can confirm that it resolves the issue. Many thanks!
