### ISSUE TITLE
карта 

### ISSUE THREAD

**Issue by deniska21233** [yapb/yapb#601]
L 07/26/2024 - 20:56:12: Server cvars end
L 07/26/2024 - 20:56:12: -------- Mapchange to cs_italy --------
ReGameDLL 
Starting up bot thread worker with 0 threads.
Bots chatter communication disabled.
Loaded Bots Graph data v2 (Memory: 0.14MB).
Loaded Bots Practice data v2 (Memory: 0.24MB).
Loaded Bots Vistable data v4 (Memory: 0.42MB).
Warning: Graph data is probably not for this map. Please check bots behaviour.
L 07/26/2024 - 20:56:13: Started map "cs_italy" (CRC "111715122")
Executing AMX Mod X Configuration File  

Не пойму что ему надо

**Comment by deniska21233** [comment]
не знаю спамит бывает

**Comment by deniska21233** [comment]
и кстати сервер уже 1400 карт сменил за 2 дня и с каждой сменой больше и больше ест оперативки 
подозрение на ботов

**Comment by jeefo** [comment]
нет

**Comment by jeefo** [comment]
это не спам, это информация.
