### ISSUE TITLE
Боты 

### ISSUE THREAD

**Issue by deniska21233** [yapb/yapb#602]
и кстати сервер уже 1400 карт сменил за 2 дня и с каждой сменой больше и больше ест оперативки
подозрение на ботов
При старте сервера ест 285 щас же 463

BUILD 3390 SERVER (0 CRC)
Server # 1463

CPU In Out Uptime Users FPS Players
18.00 4.17 12.05 2902 43914 1028.74 1

и кстати карта как началась новая они уже бегают хотя секунда даже не проходит + сделай что то с картой ассаульт и этой дверью чтобы стреляли через неё или открывали её

**Comment by jeefo** [comment]
ничего не понятно, что ты пишешь, если у тебя проблема оформи нормально. это закрываю.
