### ISSUE TITLE
боты сколько жрут оперативки 

### ISSUE THREAD

**Issue by deniska21233** [yapb/yapb#603]
Привет у меня стоят твои боты при включении сервера , он ест 285 оперативки но чем больше он меняет карты тем жор становиться больше 
щас же он ест 485 мб оперативной памяти
дай свой контакт плз

**Comment by deniska21233** [comment]
и с каждой сменой жор всё больше и больше 
+ боты не учитывают фризтайм когда присоединился на новую карту вместе с ними они уже бегают с пролагом

**Comment by deniska21233** [comment]
и карта ассаульт стоят уткнувшись в дверь и сервер лагает

**Comment by jeefo** [comment]
рекомендую использовать других ботов, к сожалению я не знаю как реагировать на этот сумбур.

**Comment by Vladislav4KZ** [comment]
> и карта ассаульт стоят уткнувшись в дверь

@deniska21233 удали старый граф, я это уже исправил.

Введи в консоль следующую команду для удаления графа:
```
yb g erase iamsure
```

Затем введи эту команду для скачивания нового графа:
```
yb g load
```
