### ISSUE TITLE
[Помощь] Скрыть присутствие игрока от yapb ботов

### ISSUE THREAD

**Issue by rakakarakaka** [yapb/yapb#605]
Как сделать так что бы yapb бот перестал обращать внимание на конкретного игрока в Pawn плагине (игнорировал его присутствие не карте, то есть не атаковал) ? 

Есть ли какая-то возможность это сделать? zbot например игнорируют игрока если у него флаг no_target

**Comment by jeefo** [comment]
Это должно работать, но я не проверял. Боты игнорируют игроков с флагом FL_NOTARGET.

**Comment by UnrealKaraulov** [comment]
Да все верно я недавно такое проверял и флаг FL_NOTARGET в var_flags действительно работает, вот только бот все равно пялится прямо в игрока :) То есть как бы считают его целью но не атакуют.

**Comment by jeefo** [comment]
В последнем билде, по идее, не должны пялится :)

**Comment by UnrealKaraulov** [comment]
@jeefo да теперь боты не обращают внимание на игрока с FL_NOTARGET !
