### ISSUE TITLE
[BUG] yb_autovacate_keep_slots

### ISSUE THREAD

**Issue by han2015** [yapb/yapb#612]
> yb_autovacate 
> If not zero, bots will automatically leave to make room for human players, when they join the server.

> yb_autovacate_keep_slots
> How many slots autovacate feature should keep for human players
> Default: "1", Min: "1", Max: "8"

This's my setting.   _version: 4.5.1 the latest_

```
yb_quota "16"
yb_quota_mode "fill"
yb_autovacate_keep_slots "6"
yb_autovacate "1"
```

My understanding is  that  yapb will always keep at least 16 players.
And when a real player join server, it will kick one bot automatically, until 6 slots all used.  
After that, with more players joining, the total player will increase one by one, until fill the max limit.

But I found that when the num of  real player under 6(maybe), it seems works well.  When people more than 8 or 10, the total number of players is only 12 to 13!!!!  It almost kicked out all bots.

**But the total num of players should be more than 18 for expect!!**

**Comment by jeefo** [comment]
I believe you're misunderstood this option, autovacate keeps free  slots regardless  player counts. 

max players = 30, autovacate = 1, autovacate_keepslots = 5, means means bots can occupy only 25 slots, no matter how many players are playing or quota number.
