### ISSUE TITLE
yapb-4.5.1117 - Crash

### ISSUE THREAD

**Issue by CSLover666** [yapb/yapb#627]
When i kick the bots, sometimes the server is crashing.

yapb-4.5.1117

**Comment by jeefo** [comment]
no information at all.

**Comment by di57inct** [comment]
i have a plugin that automatically manages them, including kicking them often enough and the issue is not present for me as i have uptime of over 2 weeks on the server right now. using the same version.

**Comment by CSLover666** [comment]
[  1] Admin Base              1.9.0.5294  AMXX Dev Team     admin.amxx       running
 [  2] Admin Commands          1.9.0.5294  AMXX Dev Team     admincmd.amxx    running
 [  3] Slots Reservation       1.9.0.5294  AMXX Dev Team     adminslots.amxx  running
 [  4] Menus Front-End         1.8.2       AMXX Dev Team     menufront.amxx   running
 [  5] Commands Menu           1.9.0.5294  AMXX Dev Team     cmdmenu.amxx     running
 [  6] Players Menu            1.9.0.5294  AMXX Dev Team     plmenu.amxx      running
 [  7] Teleport Menu           1.9.0.5294  AMXX Dev Team     telemenu.amxx    running
 [  8] Maps Menu               1.9.0.5294  AMXX Dev Team     mapsmenu.amxx    running
 [  9] Plugin Menu             1.9.0.5294  AMXX Dev Team     pluginmenu.amxx  running
 [ 10] Admin Chat              1.9.0.5294  AMXX Dev Team     adminchat.amxx   running
 [ 11] Anti Flood              1.9.0.5294  AMXX Dev Team     antiflood.amxx   running
 [ 12] Admin Votes             1.8.2       AMXX Dev Team     adminvote.amxx   running
 [ 13] Pause Plugins           1.9.0.5294  AMXX Dev Team     pausecfg.amxx    running
 [ 14] Stats Configuration     1.9.0.5294  AMXX Dev Team     statscfg.amxx    running
 [ 15] Restrict Weapons        1.9.0.5294  AMXX Dev Team     restmenu.amxx    running
 [ 16] StatsX                  1.9.0.5294  AMXX Dev Team     statsx.amxx      running
 [ 17] CS Stats Logging        1.9.0.5294  AMXX Dev Team     stats_logging.a  running
 [ 18] FreshBans               1.4.8b      kanagava          fresh_bans_148-  running
 [ 19] Ultimate Bans           1.9         Souvik            UltimateBans.am  running
 [ 20] Unreal Cheater Cry      1.7         Karaulov          unreal_cheater_  running
 [ 21] ReAimDetector API       0.2.2       ReHLDS Team       reaimdetector.a  running
 [ 22] Chat logs               1.11        thEsp             amx_chatlogs.am  running
 [ 23] AdminListen             2.3x        /dev/ urandom     adminlisten.amx  running
 [ 24] Lite Admin ESP          1.0         neygomon          admin_esp.amxx   running
 [ 25] Stop the Bastards       1.7.0       F@nt0M            stop_the_bastar  running
 [ 26] Advanced Mute           2.1         OciXCrom          crx_advmute.amx  running
 [ 27] Telegram Reports Sende  3.0.1       @pywave & Albert  telegram_report  running
 [ 28] God Seeker              3.7         karaulov          god_seeker.amxx  running
 [ 29] Bypass Guard            1.1.14      mx?!              bypass_guard.am  running
 [ 30] [BG] Provider: IPHub-C  1.3         mx?!              bg_provider_iph  running
 [ 31] HPP_BLOCK               1.2         Karaulov          hpp_blocker.amx  running
 [ 32] [BG] Supervisor         0.6         mx?!              bg_supervisor.a  running
 [ 33] Ping Control            1.2         mx?!              ping_control.am  running
 [ 34] BLOCK FAKE STEAMID      1.5         Karaulov          fake_nosteam_bl  running
 [ 35] Vac Ban Status          0.0.1       Albertio          vac_ban_status.  running
 [ 36] Anti steamid changer    1.0.5       ufame             anti_steamidcha  running
 [ 37] Anti Family Share 2022  1.0         deprale           anti_family_sha  running
 [ 38] Easy KBChecker          2.1.1       bristol           easy_knifebot_c  running
 [ 39] HackDetector            0.15.lite   Lev @ AGHL.RU De  hackdetector.am  running
 [ 40] ReChecker Logging       1.0         custom            rc_logging.amxx  running
 [ 41] Unreal Cheat Detector   1.6         Karaulov          unreal_cheat_de  running
 [ 42] SF Warn Menu            0.1.4g      serfreeman1337    sf_admin_warns.  running
 [ 43] Resetscore System       1.1         OciXCrom          crx_resetscore.  running
 [ 44] OciXCrom's Rank System  3.10        OciXCrom          crx_ranksystem.  running
 [ 45] Save Stuff              1.0         OciXCrom          crx_save_stuff.  running
 [ 46] Advanced Kill Assists   1.5         Xelson            next21_kill_ass  running
 [ 47] Advanced Bullet Damage  1.0         Sn!ff3r           Sebzes_kiiro.am  running
 [ 48] Frags Counter           1.0         CHEL74            frags_counter.a  running
 [ 49] [ReAPI] Info Killer     1.1.0       Jumper            Info_Killer.amx  running
 [ 50] unknown                 unknown     unknown           damage.amxx      running
 [ 51] SF Bets                 0.1.5       serfreeman1337    sf_bets.amxx     running
 [ 52] Hide `/` cmds           1.2         Dev-CS.ru         hide_slash.amxx  running
 [ 53] SpecList                1.2         FatalisDK         speclist.amxx    running
 [ 54] Ultimate Fire in the H  2.1         OciXCrom          crx_fireintheho  running
 [ 55] Deathtype Effects       1.0         anakin_cstrike    deathtype_effec  running
 [ 56] Players Models          1.3.1       ConnorMcLeod      players_models.  running
 [ 57] Back Weapons            1.87        hoboman313/cheap  backweapons.amx  running
 [ 58] Admin Chat Colors       2.0         Arion             admin_chat_colo  running
 [ 59] C4 Crosshair Delete     1.0         Subb98            c4_crosshair_de  running
 [ 60] First Person Death      1.0         Numb              first_person_de  running
 [ 61] GHW Auto Message Displ  2.1         GHW_Chronic       GHW_Message_Dis  running
 [ 62] Spectator Hud Informat  0.0.1       ConnorMcLeod      spec_hud_info.a  running
 [ 63] Weapon Model + Sound R  1.3         GHW_Chronic       GHW_Weapon_Repl  running
 [ 64] Game Messages & Sounds  3.0.2       OciXCrom          crx_gamemessage  running
 [ 65] New Plug-In             1.0         author            show_motd.amxx   running
 [ 66] [ReAPI] Colored Flash   1.0         ReHLDS Team       colored_flash_t  running
 [ 67] Playable Piano          1.1.0       gordon9k          playable_piano.  running
 [ 68] TakeADookie             3.0.2       ConnorMcLeod      SCH-Sicma.amxx   running
 [ 69] MultiJump               1.1         twistedeuphoria   multijump.amxx   running
 [ 70] [190] Parachute RBS     22.11.15    SKAJIbnEJIb & KR  parachute_rbs.a  running
 [ 71] [ReAPI] Pop Grenades    2.5         EFFx & HamletEag  csgo_pop_grenad  running
 [ 72] Guns Menu               1.0         Tornado_SW        Sikoly_Guns.amx  running
 [ 73] [ReAPI] Healthnade      0.0.19f     DEV-CS.RU Commun  reapi_healthnad  running
 [ 74] AMX Slay Losers         1.1         d3n14@yahoo.com   slaylosers.amxx  running
 [ 75] Spawn Protection        7.0         Peli              spawnprotection  running
 [ 76] [HN] SpawnEquip SteamI  1.0         mx?!              hn_spawnequip_s  running
 [ 77] Fake Ping               1.1         MeRcyLeZZ/gyxoBk  FakePing.amxx    running
 [ 78] Knife Duel              1.0         Alka              knife_duel.amxx  running
 [ 79] [GeoIP] Connect Info    1.0.0       Nordic Warrior    geoip_connect_i  running
 [ 80] Connect Announce        0.3b        v3x               connect_announc  running
 [ 81] CS AFK Manager          1.0.6 (amx  Freeman           afk_manager_1-8  running
 [ 82] Map Spawns Editor       1.0.16      iG_os             Map_Spawns_Edit  running
 [ 83] Drop Grenades           1.0.2       fl0wer            drop_grenades.a  running
 [ 84] C4 Taker                1.09        hellmonja & Haml  c4_taker.amxx    running
 [ 85] Nade Semiclip           2.7         JustGo            nade_semiclip.a  running
 [ 86] Bot Control             1.1         SPiNX/EFFEX litt  bot_control_2.a  running
 [ 87] Weapon Remover          1.00        Marky_UK          weapon_remover.  running
 [ 88] Multi FastDL            1.2         JoRoPiTo          multifastdl.amx  running
 [ 89] Map Manager: YaPB Free  1.0                           yb_freeze_bots.  running
 [ 90] Spectator Bot           1.2.2(bata  b0t.              SpectatorBot.am  running
 [ 91] Round End Music         2.3.1       OciXCrom          crx_remusic.amx  running
 [ 92] ReloadSoundFix          1.1         Karaulov          reloadsound_fix  running
 [ 93] ADV. QUAKE SOUNDS (ENA  8.0         HATTRICK (HTTRCK  AQS.amxx         running
 [ 94] AMX Round Money X       1.1         Flaming           amx_round_money  running
 [ 95] FocusOnVotemap          1.2.1       Boec[SpecOPs]     focus_on_votema  running
 [ 96] Map Manager: Advanced   0.1.0-6662  Mistrick          map_manager_adv  running
 [ 97] Map Manager: BlockList  0.0.4-6662  Mistrick          map_manager_blo  running
 [ 98] Map Manager: Core       3.3.1-6662  Mistrick          map_manager_cor  running
 [ 99] Map Manager: Effects    0.1.3-0cb1  Mistrick          map_manager_eff  running
 [100] Map Manager: GUI        0.0.7-6662  Mistrick          map_manager_gui  running
 [101] Map Manager: Informer   0.0.5-6662  Mistrick          map_manager_inf  running
 [102] Map Manager: Nominatio  0.3.6-6662  Mistrick          map_manager_nom  running
 [103] Map Manager: Priority   0.0.2-6662  Mistrick          map_manager_pri  running
 [104] Map Manager: Rtv        0.1.5-6662  Mistrick          map_manager_rtv  running
 [105] Map Manager: Scheduler  0.2.3-6662  Mistrick          map_manager_sch  running
 [106] Map Manager: Sounds     0.0.3-6662  Mistrick          map_manager_sou  running
 [107] Map Manager: Online ch  1.0.4-6662  Sergey Shorokhov  map_manager_onl  running
 [108] Map Manager: Online so  0.0.4-6662  Mistrick          map_manager_onl  running
 [109] Revive Teammates: Core  2.3.15      DEV-CS.RU Commun  rt_core.amxx     running
 [110] Revive Teammates: Plan  2.3.15      DEV-CS.RU Commun  rt_planting.amx  running
 [111] Revive Teammates: Rest  2.3.15      DEV-CS.RU Commun  rt_restrictions  running
 [112] Revive Teammates: Time  2.3.15      DEV-CS.RU Commun  rt_timer.amxx    running
 [113] Revive Teammates: Effe  2.3.15      DEV-CS.RU Commun  rt_effects.amxx  running
 [114] Revive Teammates: Soun  2.3.15      DEV-CS.RU Commun  rt_sounds.amxx   running
 [115] Revive Teammates: Bonu  2.3.15      DEV-CS.RU Commun  rt_bonus.amxx    running
 [116] Revive Teammates: Mode  2.3.15      mx?!              rt_revive_model  running
 [117] Advanced Experience Sy  0.5.9 [REA  serfreeman1337/s  aes_main.amxx    running
117 plugins, 117 running
