### ISSUE TITLE
Shutdown of yapb.jeefo.net for UA users

### ISSUE THREAD

**Issue by jeefo** [yapb/yapb#628]
Hello, due to difficulties paying bills for hosting outside RU zone, and total lock of RU subnets from UA government, i had to say https://yapb.jeefo.net/ will not be available for UA users, as well as graph database download/upload features starting next month due to hosting move to RU segment. Sorry about that, no offense at all here, just a technical difficulties.

**Comment by di57inct** [comment]
back up your files a friend of mine might be able to help

**Comment by MysticDeathProject** [comment]
@jeefo 
Ohh sadly 😭 make backup waypoints please and all files from database and project do not lost project этот проект ни в коем случае нельзя забрасывать это шедевр ❤️

**Comment by di57inct** [comment]
check your discord bro my friend will be able to help you with free hosting

**Comment by jeefo** [comment]
domain transferred to Saint-Petersburg (RU) based hosting provider, if anyone have problems, i'm sorry.
