### ISSUE TITLE
Why crash in the latest version?

### ISSUE THREAD

**Issue by cyxnzb** [yapb/yapb#630]
When I started the server, the server loaded the plugin and started loading the bot, after which the server just crashed.
I upload the mdmp file.

Use:
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
ReHLDS version: 3.13.0.788 (Extended)
Build date: 07:07:50 Jul 21 2023 (3387)
Build from: https://github.com/dreamstalker/rehlds/commit/f955b07

ReGameDLL version: 5.26.0.668-dev
[hlds_3.13.0.788-dev-f955b07_crash_20241020_215946_1.zip](https://github.com/user-attachments/files/17450535/hlds_3.13.0.788-dev-f955b07_crash_20241020_215946_1.zip)

**Comment by jeefo** [comment]
hello, fixed now, sry for that

**Comment by cyxnzb** [comment]
> hello, fixed now, sry for that

it's okay now ^_^
