### ISSUE TITLE
yapb-4.5.1117 - Crash whenk kick bot, or change map.

### ISSUE THREAD

**Issue by CSLover666** [yapb/yapb#631]
When i kick the bots, or change map sometimes the server is crashing.

I uploaded 3 mdmp files please help.

https://file.io/WHd69tuGkbAj

**Comment by jeefo** [comment]
Crash dumps not available

**Comment by CSLover666** [comment]
> Crash dumps not available

https://fileport.io/NCrmuP3ufsqf

**Comment by CSLover666** [comment]
HELP

**Comment by CSLover666** [comment]
Crash again :(

https://drive.google.com/file/d/1-4XBAT9Y0KBPdUL8gkCtLTp6xhEdn3dd/view?usp=drive_link

**Comment by MysticDeathProject** [comment]
> Crash again :(
> 
> https://drive.google.com/file/d/1-4XBAT9Y0KBPdUL8gkCtLTp6xhEdn3dd/view?usp=drive_link

Hi send more information about your server?
need plugins list and metamod list and version your server hlds or rehlds and if you have regamedll send it too whats version you use?

**Comment by CSLover666** [comment]
> > Crash again :(
> > https://drive.google.com/file/d/1-4XBAT9Y0KBPdUL8gkCtLTp6xhEdn3dd/view?usp=drive_link
> 
> Hi send more information about your server? need plugins list and metamod list and version your server hlds or rehlds and if you have regamedll send it too whats version you use?

Sure!

You can read it here:

https://forums.alliedmods.net/showthread.php?t=349421

**Comment by MysticDeathProject** [comment]
@CSLover666 
Can you try to use yapb 4.4.957 version and make backup version

YaPB for Counter-Strike RUN - yapb.dll v4.5.1117 ini Chlvl ANY

but anyway this can fix only @jeefo and can help you, if version 4.4.957 is also will be crashing then problem with plugins or modules you can also update rehlds and regamedll from 2023 to 2024
