### ISSUE TITLE
PODbots 3.0 / YaPB crashes server shortly after launch

### ISSUE THREAD

**Issue by wfllama** [yapb/yapb#634]
Hey guys,

I’ve been having some issues installing a bot plugin for my CS 1.6 server. My server is currently running Metamod 1.2.0 and AMX Mod X 1.8.2. 

I’m trying to make my server run Bailopan CSDM 2.1.1 and a bot plugin. At first, I tried PODbot 3.0, but for unknown reasons the server would crash shortly after I joined it and was stuck in observer mode. The bots appeared on the server, but the server would crash within 30 seconds after being started. 

I then tried YaPB 4.4.957, but experienced the exact same issue, except that bots wouldn’t spawn in at all. 

My plugins.ini folder has these two lines: 

win32 addons\amxmodx\dlls\amxmodx_mm.dll
win32 addons/yapb/bin/yapb.dll

My server is running through Windows, Steam, and the steam_legacy build of CS 1.6.

I’ve triple checked to make sure that all of the plugins and mods are in their proper place, following the installation directions from the YaPB documentation.

Lastly, the server is not being hosted locally, but through PingPerfect server hosting. 

I’ve been stuck on this problem for a few days now, and would greatly appreciate some help.

Thank you!

**Comment by di57inct** [comment]
update your metamod to the latest metamod-r or metamod-p
if you're using rehlds it's recommended that you also use latest amxx 1.10

**Comment by wfllama** [comment]
> update your metamod to the latest metamod-r or metamod-p if you're using rehlds it's recommended that you also use latest amxx 1.10

Thanks for your reply. The server is currently running through HLDS, so I guess I'd have to try the Metamod-p version.

**Comment by di57inct** [comment]
metamod-r is compatible with default hlds too and is the most updated version

**Comment by jeefo** [comment]
Sorry, it's not possible to debug user-specific setups. You should provide full crash dumps or provide link to a full server directory (excluding any sensitive information).

Builds links can be sent to yapb@jeefo.net.

**Comment by wfllama** [comment]
> metamod-r is compatible with default hlds too and is the most updated version

Are you sure about metamod-r? I just looked at https://metamod-r.org/ and it says it's incompatible with standard HLDS. 

I just tried metamod-am and metamod-p, both of which can run PODbots and YaPB without the server crashing as it was doing with standard metamod 1.2.0. 

However, I'm experiencing awful lag spikes despite having a 25 ping connection. 

Thanks for your help, getting bots running is certainly a step in the right direction.

**Comment by di57inct** [comment]
https://github.com/rehlds/metamod-r

**Comment by wfllama** [comment]
> https://github.com/rehlds/metamod-r

Guess I was wrong - Thanks for clarifying that.

I just tried metamod-r on my server along with YaPB 4.4.597, AMX Mod X 1.8.2, and CSDM 2.1.3 KWo. The server runs, but it doesn't perform any differently than when I used metamod-am and metamod-p. I'm still experiencing massive ping fluctuation making for poor gameplay experience. I don't think this has anything to do with metamod or amxx, though. I've contacted PingPerfect support about this and am waiting for their reply.

**Comment by wfllama** [comment]
> Sorry, it's not possible to debug user-specific setups. You should provide full crash dumps or provide link to a full server directory (excluding any sensitive information).
> 
> Builds links can be sent to [yapb@jeefo.net](mailto:yapb@jeefo.net).

Hey, sorry I didn't respond earlier. Running metamod p, r, or am along with YaPB bots solves the crashing issue. PODbots still causes the server to crash after 10 minutes or so, but I'd rather have YaPB anyway. The server is really laggy though.

**Comment by di57inct** [comment]
this is beyond the bots right now as i am also using them and don't have any problems. anyway, try deleting any custom settings that you have in your server's cfg files. if that fails, use rehlds or update your amxx to the latest 1.10 version.
