### ISSUE TITLE
(ERROR): Unable to save Practice file. Empty data.

### ISSUE THREAD

**Issue by CSLover666** [yapb/yapb#638]
How can i fix this error?

2024-11-08 20:37:22 (ERROR): Unable to save Practice file. Empty data. (filename: 'c:\users . . . .  scoutknivez

**Comment by jeefo** [comment]
It's not fatal. Usually that means, the game wasn't run enough time to record some practice data.

**Comment by CSLover666** [comment]
> It's not fatal. Usually that means, the game wasn't run enough time to record some practice data.

Thank you!
