### ISSUE TITLE
4.4.957    CS1.5 服务端运行一直奔溃

### ISSUE THREAD

**Issue by zhouqundao** [yapb/yapb#646]
日志

就是运行不起来 崩溃

L 11/29/2024 - 06:25:10: -------- Mapchange to de_dust2 --------
L 11/29/2024 - 06:25:10: [AMXX] Plugin "givemoneyhpap.amxx" failed to load: Plugin uses an unknown function (name "cs_set_user_money2") - check your modules.ini.
L 11/29/2024 - 06:25:10: [AMXX] Failed to open dictionary file: cstrike\addons\amxmodx\data\lang\server_chime_plugin.txt
L 11/29/2024 - 06:25:11: [csdm_mod.amxx] [CSDM] loaded 40 spawns for de_dust2.
L 11/29/2024 - 06:25:11: [csdm_mod.amxx] [CSDM] loaded 4 weapon blocks.
L 11/29/2024 - 06:25:11: [csdm_mod.amxx] [CSDM] loaded 172 entities for de_dust2.
L 11/29/2024 - 06:25:15: [admin.amxx] Login: "xDL - bjaren<1><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:25:16: [admin.amxx] Login: "xDL - aliendewd1<2><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:25:16: [admin.amxx] Login: "xDL - Ender Wiggin<3><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:25:16: [admin.amxx] Login: "xDL - Hextor<4><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:25:17: [admin.amxx] Login: "xDL - iamblazed<5><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:25:17: [admin.amxx] Login: "xDL - pyr0`<6><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:25:18: [admin.amxx] Login: "xDL - bisTEK<7><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:25:18: [admin.amxx] Login: "xDL - ffmcobalt<8><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:25:18: [admin.amxx] Login: "xDL - Savage|420|<9><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:25:30: -------- Mapchange to de_dust2 --------
L 11/29/2024 - 06:25:30: [AMXX] Plugin "givemoneyhpap.amxx" failed to load: Plugin uses an unknown function (name "cs_set_user_money2") - check your modules.ini.
L 11/29/2024 - 06:25:30: [AMXX] Failed to open dictionary file: cstrike\addons\amxmodx\data\lang\server_chime_plugin.txt
L 11/29/2024 - 06:25:31: [csdm_mod.amxx] [CSDM] loaded 40 spawns for de_dust2.
L 11/29/2024 - 06:25:31: [csdm_mod.amxx] [CSDM] loaded 4 weapon blocks.
L 11/29/2024 - 06:25:31: [csdm_mod.amxx] [CSDM] loaded 172 entities for de_dust2.
L 11/29/2024 - 06:25:35: [admin.amxx] Login: "xDL - bjaren<1><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:25:36: [admin.amxx] Login: "xDL - aliendewd1<2><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:25:36: [admin.amxx] Login: "xDL - Ender Wiggin<3><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:25:36: [admin.amxx] Login: "xDL - Hextor<4><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:25:37: [admin.amxx] Login: "xDL - iamblazed<5><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:25:37: [admin.amxx] Login: "xDL - pyr0`<6><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:25:38: [admin.amxx] Login: "xDL - thesofafox<7><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:25:38: [admin.amxx] Login: "xDL - gixsir1000<8><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:25:38: [admin.amxx] Login: "xDL - Flying Martini<9><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:25:50: -------- Mapchange to de_dust2 --------
L 11/29/2024 - 06:25:50: [AMXX] Plugin "givemoneyhpap.amxx" failed to load: Plugin uses an unknown function (name "cs_set_user_money2") - check your modules.ini.
L 11/29/2024 - 06:25:50: [AMXX] Failed to open dictionary file: cstrike\addons\amxmodx\data\lang\server_chime_plugin.txt
L 11/29/2024 - 06:25:51: [csdm_mod.amxx] [CSDM] loaded 40 spawns for de_dust2.
L 11/29/2024 - 06:25:51: [csdm_mod.amxx] [CSDM] loaded 4 weapon blocks.
L 11/29/2024 - 06:25:51: [csdm_mod.amxx] [CSDM] loaded 172 entities for de_dust2.
L 11/29/2024 - 06:25:55: [admin.amxx] Login: "xDL - bjaren<1><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:25:56: [admin.amxx] Login: "xDL - aliendewd1<2><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:25:56: [admin.amxx] Login: "xDL - Ender Wiggin<3><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:25:56: [admin.amxx] Login: "xDL - Hextor<4><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:25:57: [admin.amxx] Login: "xDL - iamblazed<5><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:25:57: [admin.amxx] Login: "xDL - pyr0`<6><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:25:58: [admin.amxx] Login: "xDL - Savage|420|<7><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:25:58: [admin.amxx] Login: "xDL - Magnus<8><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:25:58: [admin.amxx] Login: "xDL - RAGE OF THE BOY<9><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:26:10: -------- Mapchange to de_dust2 --------
L 11/29/2024 - 06:26:10: [AMXX] Plugin "givemoneyhpap.amxx" failed to load: Plugin uses an unknown function (name "cs_set_user_money2") - check your modules.ini.
L 11/29/2024 - 06:26:10: [AMXX] Failed to open dictionary file: cstrike\addons\amxmodx\data\lang\server_chime_plugin.txt
L 11/29/2024 - 06:26:16: [csdm_mod.amxx] [CSDM] loaded 40 spawns for de_dust2.
L 11/29/2024 - 06:26:16: [csdm_mod.amxx] [CSDM] loaded 4 weapon blocks.
L 11/29/2024 - 06:26:16: [csdm_mod.amxx] [CSDM] loaded 172 entities for de_dust2.
L 11/29/2024 - 06:26:20: [admin.amxx] Login: "xDL - aznfaijai<1><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:26:30: -------- Mapchange to de_dust2 --------
L 11/29/2024 - 06:26:30: [AMXX] Plugin "givemoneyhpap.amxx" failed to load: Plugin uses an unknown function (name "cs_set_user_money2") - check your modules.ini.
L 11/29/2024 - 06:26:30: [AMXX] Failed to open dictionary file: cstrike\addons\amxmodx\data\lang\server_chime_plugin.txt
L 11/29/2024 - 06:26:31: [csdm_mod.amxx] [CSDM] loaded 40 spawns for de_dust2.
L 11/29/2024 - 06:26:31: [csdm_mod.amxx] [CSDM] loaded 4 weapon blocks.
L 11/29/2024 - 06:26:31: [csdm_mod.amxx] [CSDM] loaded 172 entities for de_dust2.
L 11/29/2024 - 06:26:35: [admin.amxx] Login: "xDL - Deadlynome<1><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:26:46: -------- Mapchange to de_dust2 --------
L 11/29/2024 - 06:26:46: [AMXX] Plugin "givemoneyhpap.amxx" failed to load: Plugin uses an unknown function (name "cs_set_user_money2") - check your modules.ini.
L 11/29/2024 - 06:26:46: [AMXX] Failed to open dictionary file: cstrike\addons\amxmodx\data\lang\server_chime_plugin.txt
L 11/29/2024 - 06:26:47: [csdm_mod.amxx] [CSDM] loaded 40 spawns for de_dust2.
L 11/29/2024 - 06:26:47: [csdm_mod.amxx] [CSDM] loaded 4 weapon blocks.
L 11/29/2024 - 06:26:47: [csdm_mod.amxx] [CSDM] loaded 172 entities for de_dust2.
L 11/29/2024 - 06:26:51: [admin.amxx] Login: "xDL - Smok3<1><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:26:52: [admin.amxx] Login: "xDL - RaGe<2><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:26:52: [admin.amxx] Login: "xDL - simslater<3><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:26:53: [admin.amxx] Login: "xDL - Nihility<4><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:26:53: [admin.amxx] Login: "xDL - BorHor<5><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:26:53: [admin.amxx] Login: "xDL - shooterman<6><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:26:54: [admin.amxx] Login: "xDL - {NoV}Fishbulb<7><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:26:54: [admin.amxx] Login: "xDL - Spriggan<8><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:26:55: [admin.amxx] Login: "xDL - bussemann<9><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:27:06: -------- Mapchange to de_dust2 --------
L 11/29/2024 - 06:27:06: [AMXX] Plugin "givemoneyhpap.amxx" failed to load: Plugin uses an unknown function (name "cs_set_user_money2") - check your modules.ini.
L 11/29/2024 - 06:27:06: [AMXX] Failed to open dictionary file: cstrike\addons\amxmodx\data\lang\server_chime_plugin.txt
L 11/29/2024 - 06:27:07: [csdm_mod.amxx] [CSDM] loaded 40 spawns for de_dust2.
L 11/29/2024 - 06:27:07: [csdm_mod.amxx] [CSDM] loaded 4 weapon blocks.
L 11/29/2024 - 06:27:07: [csdm_mod.amxx] [CSDM] loaded 172 entities for de_dust2.
L 11/29/2024 - 06:27:11: [admin.amxx] Login: "xDL - kaosbob<1><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:27:22: -------- Mapchange to de_dust2 --------
L 11/29/2024 - 06:27:22: [AMXX] Plugin "givemoneyhpap.amxx" failed to load: Plugin uses an unknown function (name "cs_set_user_money2") - check your modules.ini.
L 11/29/2024 - 06:27:22: [AMXX] Failed to open dictionary file: cstrike\addons\amxmodx\data\lang\server_chime_plugin.txt
L 11/29/2024 - 06:27:23: [csdm_mod.amxx] [CSDM] loaded 40 spawns for de_dust2.
L 11/29/2024 - 06:27:23: [csdm_mod.amxx] [CSDM] loaded 4 weapon blocks.
L 11/29/2024 - 06:27:23: [csdm_mod.amxx] [CSDM] loaded 172 entities for de_dust2.
L 11/29/2024 - 06:27:27: [admin.amxx] Login: "xDL - Domo<1><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:27:38: -------- Mapchange to de_dust2 --------
L 11/29/2024 - 06:27:38: [AMXX] Plugin "givemoneyhpap.amxx" failed to load: Plugin uses an unknown function (name "cs_set_user_money2") - check your modules.ini.
L 11/29/2024 - 06:27:39: [AMXX] Failed to open dictionary file: cstrike\addons\amxmodx\data\lang\server_chime_plugin.txt
L 11/29/2024 - 06:27:39: [csdm_mod.amxx] [CSDM] loaded 40 spawns for de_dust2.
L 11/29/2024 - 06:27:39: [csdm_mod.amxx] [CSDM] loaded 4 weapon blocks.
L 11/29/2024 - 06:27:39: [csdm_mod.amxx] [CSDM] loaded 172 entities for de_dust2.
L 11/29/2024 - 06:27:44: [admin.amxx] Login: "xDL - thesofafox<1><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:27:44: [admin.amxx] Login: "xDL - Killer apple<2><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:27:44: [admin.amxx] Login: "xDL - Helios<3><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:27:45: [admin.amxx] Login: "xDL - vampiress<4><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:27:45: [admin.amxx] Login: "xDL - Jonny Matrix<5><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:27:46: [admin.amxx] Login: "xDL - Slurr<6><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:27:46: [admin.amxx] Login: "xDL - bling bling<7><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:27:46: [admin.amxx] Login: "xDL - DevilScream<8><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:27:47: [admin.amxx] Login: "xDL - wind<9><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:27:58: -------- Mapchange to de_dust2 --------
L 11/29/2024 - 06:27:58: [AMXX] Plugin "givemoneyhpap.amxx" failed to load: Plugin uses an unknown function (name "cs_set_user_money2") - check your modules.ini.
L 11/29/2024 - 06:27:59: [AMXX] Failed to open dictionary file: cstrike\addons\amxmodx\data\lang\server_chime_plugin.txt
L 11/29/2024 - 06:27:59: [csdm_mod.amxx] [CSDM] loaded 40 spawns for de_dust2.
L 11/29/2024 - 06:27:59: [csdm_mod.amxx] [CSDM] loaded 4 weapon blocks.
L 11/29/2024 - 06:27:59: [csdm_mod.amxx] [CSDM] loaded 172 entities for de_dust2.
L 11/29/2024 - 06:28:04: [admin.amxx] Login: "xDL - aznfaijai<1><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:28:04: [admin.amxx] Login: "xDL - Whatever<2><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:28:04: [admin.amxx] Login: "xDL - Counter123<3><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:28:05: [admin.amxx] Login: "xDL - pimpjuice<4><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:28:05: [admin.amxx] Login: "xDL - Fat Matt<5><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:28:06: [admin.amxx] Login: "xDL - Dk-Unknown<6><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:28:06: [admin.amxx] Login: "xDL - yoshi<7><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:28:06: [admin.amxx] Login: "xDL - dead weight<8><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:28:07: [admin.amxx] Login: "xDL - Brandon<9><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:28:18: -------- Mapchange to de_dust2 --------
L 11/29/2024 - 06:28:18: [AMXX] Plugin "givemoneyhpap.amxx" failed to load: Plugin uses an unknown function (name "cs_set_user_money2") - check your modules.ini.
L 11/29/2024 - 06:28:19: [AMXX] Failed to open dictionary file: cstrike\addons\amxmodx\data\lang\server_chime_plugin.txt
L 11/29/2024 - 06:28:19: [csdm_mod.amxx] [CSDM] loaded 40 spawns for de_dust2.
L 11/29/2024 - 06:28:19: [csdm_mod.amxx] [CSDM] loaded 4 weapon blocks.
L 11/29/2024 - 06:28:19: [csdm_mod.amxx] [CSDM] loaded 172 entities for de_dust2.
L 11/29/2024 - 06:28:24: [admin.amxx] Login: "xDL - xUTxJackFrost<1><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:28:24: [admin.amxx] Login: "xDL - BDM-WhiteViper<2><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:28:25: [admin.amxx] Login: "xDL - HappyKiD<3><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:28:25: [admin.amxx] Login: "xDL - Slayin<4><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:28:25: [admin.amxx] Login: "xDL - Anthology<5><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:28:26: [admin.amxx] Login: "xDL - Hextor<6><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:28:26: [admin.amxx] Login: "xDL - Dori<7><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:28:27: [admin.amxx] Login: "xDL - kingkilla<8><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:28:27: [admin.amxx] Login: "xDL - AttAckA<9><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:28:38: -------- Mapchange to de_dust2 --------
L 11/29/2024 - 06:28:38: [AMXX] Plugin "givemoneyhpap.amxx" failed to load: Plugin uses an unknown function (name "cs_set_user_money2") - check your modules.ini.
L 11/29/2024 - 06:28:39: [AMXX] Failed to open dictionary file: cstrike\addons\amxmodx\data\lang\server_chime_plugin.txt
L 11/29/2024 - 06:28:39: [csdm_mod.amxx] [CSDM] loaded 40 spawns for de_dust2.
L 11/29/2024 - 06:28:39: [csdm_mod.amxx] [CSDM] loaded 4 weapon blocks.
L 11/29/2024 - 06:28:39: [csdm_mod.amxx] [CSDM] loaded 172 entities for de_dust2.
L 11/29/2024 - 06:28:44: -------- Mapchange to de_dust2 --------
L 11/29/2024 - 06:28:44: [AMXX] Plugin "givemoneyhpap.amxx" failed to load: Plugin uses an unknown function (name "cs_set_user_money2") - check your modules.ini.
L 11/29/2024 - 06:28:45: [AMXX] Failed to open dictionary file: cstrike\addons\amxmodx\data\lang\server_chime_plugin.txt
L 11/29/2024 - 06:28:45: [csdm_mod.amxx] [CSDM] loaded 40 spawns for de_dust2.
L 11/29/2024 - 06:28:45: [csdm_mod.amxx] [CSDM] loaded 4 weapon blocks.
L 11/29/2024 - 06:28:45: [csdm_mod.amxx] [CSDM] loaded 172 entities for de_dust2.
L 11/29/2024 - 06:28:50: [admin.amxx] Login: "xDL - Dk-Unknown<1><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:28:50: [admin.amxx] Login: "xDL - RAGE OF THE BOY<2><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:28:50: [admin.amxx] Login: "xDL - Counter123<3><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:28:51: [admin.amxx] Login: "xDL - simslater<4><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:28:51: [admin.amxx] Login: "xDL - thunder<5><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:28:52: [admin.amxx] Login: "xDL - kaosbob<6><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:28:52: [admin.amxx] Login: "xDL - HappyKiD<7><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:28:52: [admin.amxx] Login: "xDL - Fat Matt<8><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:28:53: [admin.amxx] Login: "xDL - Helios<9><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:29:02: -------- Mapchange to de_dust2 --------
L 11/29/2024 - 06:29:02: [AMXX] Plugin "givemoneyhpap.amxx" failed to load: Plugin uses an unknown function (name "cs_set_user_money2") - check your modules.ini.
L 11/29/2024 - 06:29:03: [AMXX] Failed to open dictionary file: cstrike\addons\amxmodx\data\lang\server_chime_plugin.txt
L 11/29/2024 - 06:29:03: [csdm_mod.amxx] [CSDM] loaded 40 spawns for de_dust2.
L 11/29/2024 - 06:29:03: [csdm_mod.amxx] [CSDM] loaded 4 weapon blocks.
L 11/29/2024 - 06:29:03: [csdm_mod.amxx] [CSDM] loaded 172 entities for de_dust2.
L 11/29/2024 - 06:29:08: [admin.amxx] Login: "xDL - Ronin Marmot<1><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:29:08: [admin.amxx] Login: "xDL - Gilroy<2><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:29:09: [admin.amxx] Login: "xDL - aliendewd1<3><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:29:09: [admin.amxx] Login: "xDL - ksqueakj<4><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:29:09: [admin.amxx] Login: "xDL - BHSbballer15<5><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:29:10: [admin.amxx] Login: "xDL - Counter123<6><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:29:10: [admin.amxx] Login: "xDL - xUTxJackFrost<7><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:29:11: [admin.amxx] Login: "xDL - simslater<8><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:29:11: [admin.amxx] Login: "xDL - funk<9><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:29:22: -------- Mapchange to de_dust2 --------
L 11/29/2024 - 06:29:22: [AMXX] Plugin "givemoneyhpap.amxx" failed to load: Plugin uses an unknown function (name "cs_set_user_money2") - check your modules.ini.
L 11/29/2024 - 06:29:23: [AMXX] Failed to open dictionary file: cstrike\addons\amxmodx\data\lang\server_chime_plugin.txt
L 11/29/2024 - 06:29:23: [csdm_mod.amxx] [CSDM] loaded 40 spawns for de_dust2.
L 11/29/2024 - 06:29:23: [csdm_mod.amxx] [CSDM] loaded 4 weapon blocks.
L 11/29/2024 - 06:29:23: [csdm_mod.amxx] [CSDM] loaded 172 entities for de_dust2.
L 11/29/2024 - 06:29:28: [admin.amxx] Login: "xDL - gixsir1000<1><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:29:38: -------- Mapchange to de_dust2 --------
L 11/29/2024 - 06:29:38: [AMXX] Plugin "givemoneyhpap.amxx" failed to load: Plugin uses an unknown function (name "cs_set_user_money2") - check your modules.ini.
L 11/29/2024 - 06:29:39: [AMXX] Failed to open dictionary file: cstrike\addons\amxmodx\data\lang\server_chime_plugin.txt
L 11/29/2024 - 06:29:39: [csdm_mod.amxx] [CSDM] loaded 40 spawns for de_dust2.
L 11/29/2024 - 06:29:39: [csdm_mod.amxx] [CSDM] loaded 4 weapon blocks.
L 11/29/2024 - 06:29:39: [csdm_mod.amxx] [CSDM] loaded 172 entities for de_dust2.
L 11/29/2024 - 06:29:44: [admin.amxx] Login: "xDL - articwolf<1><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:29:54: -------- Mapchange to de_dust2 --------
L 11/29/2024 - 06:29:54: [AMXX] Plugin "givemoneyhpap.amxx" failed to load: Plugin uses an unknown function (name "cs_set_user_money2") - check your modules.ini.
L 11/29/2024 - 06:29:55: [AMXX] Failed to open dictionary file: cstrike\addons\amxmodx\data\lang\server_chime_plugin.txt
L 11/29/2024 - 06:29:56: [csdm_mod.amxx] [CSDM] loaded 40 spawns for de_dust2.
L 11/29/2024 - 06:29:56: [csdm_mod.amxx] [CSDM] loaded 4 weapon blocks.
L 11/29/2024 - 06:29:56: [csdm_mod.amxx] [CSDM] loaded 172 entities for de_dust2.
L 11/29/2024 - 06:30:00: [admin.amxx] Login: "xDL - BHSbballer15<1><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:30:00: [admin.amxx] Login: "xDL - -=Sh0rTy=-<2><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:30:01: [admin.amxx] Login: "xDL - alan_cross2001<3><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:30:01: [admin.amxx] Login: "xDL - Galdalfus<4><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:30:02: [admin.amxx] Login: "xDL - Ender Wiggin<5><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:30:02: [admin.amxx] Login: "xDL - intangible<6><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:30:02: [admin.amxx] Login: "xDL - Slurr<7><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:30:03: [admin.amxx] Login: "xDL - Anthology<8><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:30:03: [admin.amxx] Login: "xDL - -CARDIAC-<9><BOT><>" became an admin (account "xDL - ") (access "bmsyz") (address "127.0.0.1")
L 11/29/2024 - 06:30:15: -------- Mapchange to de_dust2 --------
L 11/29/2024 - 06:30:15: [AMXX] Plugin "givemoneyhpap.amxx" failed to load: Plugin uses an unknown function (name "cs_set_user_money2") - check your modules.ini.
L 11/29/2024 - 06:30:15: [AMXX] Failed to open dictionary file: cstrike\addons\amxmodx\data\lang\server_chime_plugin.txt
L 11/29/2024 - 06:30:16: [csdm_mod.amxx] [CSDM] loaded 40 spawns for de_dust2.
L 11/29/2024 - 06:30:16: [csdm_mod.amxx] [CSDM] loaded 4 weapon blocks.
L 11/29/2024 - 06:30:16: [csdm_mod.amxx] [CSDM] loaded 172 entities for de_dust2.
L 11/29/2024 - 06:31:37: -------- Mapchange to de_dust2 --------
L 11/29/2024 - 06:31:37: [AMXX] Plugin "givemoneyhpap.amxx" failed to load: Plugin uses an unknown function (name "cs_set_user_money2") - check your modules.ini.
L 11/29/2024 - 06:31:38: [AMXX] Failed to open dictionary file: cstrike\addons\amxmodx\data\lang\server_chime_plugin.txt
L 11/29/2024 - 06:31:39: [csdm_mod.amxx] [CSDM] loaded 40 spawns for de_dust2.
L 11/29/2024 - 06:31:39: [csdm_mod.amxx] [CSDM] loaded 4 weapon blocks.
L 11/29/2024 - 06:31:39: [csdm_mod.amxx] [CSDM] loaded 172 entities for de_dust2.

**Comment by MysticDeathProject** [comment]
This is amxx logs not its not mean errors of yapb
🦋日志🦋
