### ISSUE TITLE
yb_smoke_grenade_checks doesn't exist, and therefore bots will just shoot through smokes.

### ISSUE THREAD

**Issue by CalebRCL** [yapb/yapb#651]
The command isn't in yapb.cfg and isn't a recognized command when typed in the in-game console. Without it, obviously smoke grenades are useless.

**Comment by jeefo** [comment]
It's not available in release build, only in dev build. Still, it's yapb.cfg isn't up-to-date in dev-build, but it's not affect the usage, as bot registers this cvar anyway.

**Comment by CalebRCL** [comment]
Ok thanks for the info!
