### ISSUE TITLE
yb_enable_fake_steamids "1"

### ISSUE THREAD

**Issue by ykpon2** [yapb/yapb#652]
Выставляю

// Allows or disallows bots to return fake steam id.
// ---
// Default: "0", Min: "0", Max: "1"
// 
yb_enable_fake_steamids "1"

Но когда пишу в игре команду status в консоль то выдается у ботов BOT вместо SteamID 
Или эта функция отвечает за что то другое ? 
В custom.cfg прописано 
EnableFakeBotFeatures = i'm confident for what i'm doing

**Comment by jeefo** [comment]
That cvar is only applicable to provide fake steam ids in server logs to be sent to stats systems like hlstats. It's not intended to fake "status" or other commands.
